### ISSUE TITLE
Homebrew

### ISSUE THREAD

**Issue by stevenringo** [johnkerl/miller#1]
Hi,

Is there a [homebrew](http://brew.sh/) formula for this by any chance?

Thanks!

**Comment by sammcj** [comment]
+1

**Comment by samuelleach** [comment]
+1

**Comment by zx8** [comment]
Just a quick note. From https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#formula-cookbook, Homebrew requires that formulae:

> [have] a stable, tagged version (i.e. not just a GitHub repository with no versions). See [Interesting-Taps-&-Branches](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Interesting-Taps-&-Branches.md) for where pre-release and head-only versions belong.

**Comment by natelandau** [comment]
+1 for homebrew support

**Comment by trenton42** [comment]
+1

**Comment by johnkerl** [comment]
@zx8 thanks, that's a timesaver for sure!

**Comment by sjackman** [comment]
I'm a Homebrew developer and would be happy to package `miller` for Homebrew if it had a tagged stable release. See #12.

**Comment by p1neapples** [comment]
+1

**Comment by bokmann** [comment]
I just went to create a miller package for homebrew, ran into the lack of a stable release, and discovered this issue.  Consider this my +1.

**Comment by johnkerl** [comment]
OK here we go: https://github.com/johnkerl/miller/releases. Thanks for your offer @sjackman!

**Comment by sjackman** [comment]
@bokmann Go ahead and create the formula now! I'll stand down.

**Comment by bokmann** [comment]
@sjackman are you sure?  You claimed the idea first, I just didn't realize that until I ran into the issue and saw this thread.  I'll gladly yield...

**Comment by bokmann** [comment]
A brew recipe for this is almost trivial... there's only one 'gotcha'.  Right now, there is no way for homebrew to specify the /usr/local/bin directory to install the binary to.  The instructions tell you to hand-edit the make file with your destination.  In order to properly set this up for homebrew, we'll need a resolution for issue #9

**Comment by johnkerl** [comment]
a quick option is in the Makefile
```
INSTALLDIR=$HOME/bin
```
then perhaps have the homebrew formula do
```
make -e INSTALLDIR=/usr/local/bin install
```
?

**Comment by bokmann** [comment]
You gave me an idea with that last comment, and I was able to make it work with some creative temporary wankery manipulating the value of $HOME during the make install.

I have a homebrew pull request just about ready, and the code there will greatly improve if/when issue #9 is resolved.  It is no longer a blocker.

**Comment by johnkerl** [comment]
OK. I'll go ahead and implement my above since there's no reason not to. ;)

https://github.com/johnkerl/miller/issues/9 is (IMO) much less important than https://github.com/johnkerl/miller/issues/4 so I intend to put my near-term effort into the latter.

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/commit/7604d97b88ec63e492a2c0aacc50bc9c67764103

**Comment by johnkerl** [comment]
There is now https://github.com/johnkerl/miller/tree/v2.2.1 with autoconfig support, if that helps.

**Comment by johnkerl** [comment]
This is currently tracked on https://github.com/Homebrew/homebrew/pull/44307

**Comment by DomT4** [comment]
Landed in https://github.com/Homebrew/homebrew/commit/566036b16e043cd2d1fac8d521451dae7fe566da. `brew update && brew install miller`.

**Comment by trenton42** [comment]
Yes!!! :clap:

**Comment by johnkerl** [comment]
https://github.com/Homebrew/homebrew/pull/44307 is resolved! :)
