### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [johnkerl/miller#10]
Would you like to add more error handling for return values from functions like the following?
- [fseek](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html "reposition a file-position indicator") ⇒ [Parse](https://github.com/johnkerl/miller/blob/6c29196cf7f5e29069187fea088105d23b6f3159/c/dsls/lemon.c#L2329)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_create.html "duplicate a string") ⇒ [lrec_put](https://github.com/johnkerl/miller/blob/c641ff36c1c6073b2ba914052b5d30e8fec16c63/c/containers/lrec.c#L91)

**Comment by johnkerl** [comment]
Good calls both. I wrap `malloc` with `mlr_malloc_or_die`; it's quite a facepalm to realize I didn't do the same for `strdup`.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by johnkerl** [comment]
strdup, i wrapped a long time ago

**Comment by elfring** [comment]
Are there [a few update candidates](https://github.com/johnkerl/miller/blob/09ec6447bc70bc742475e8b4b619e35712d3e71c/c/dsls/lemon.c#L2365 "Update candidate: Parse()") left over?
