### ISSUE TITLE
Invalid output of mlr --version

### ISSUE THREAD

**Issue by adrienaury** [johnkerl/miller#1008]
Version : v6.2.0 (https://github.com/johnkerl/miller/releases/tag/v6.2.0)

# Expected

```console
$ mlr --version
mlr 6.2.0
```

# Actual

```console
$ mlr --version
mlr 6.1.0-dev
```

**Comment by johnkerl** [comment]
Thanks @adrienaury -- something is mis-sequenced at https://miller.readthedocs.io/en/latest/how-to-release/ ... :(

**Comment by johnkerl** [comment]
Fixed for https://github.com/johnkerl/miller/releases/tag/v6.3.0
