### ISSUE TITLE
miller-6.2.0-linux-arm64.tar.gz --version 6.1.0-dev, doesn't respond to --help

### ISSUE THREAD

**Issue by drankinatty** [johnkerl/miller#1011]
This may be nothing, but it was unexpected enough to report. Helping a user with a download link on a [StackOverflow Question](https://stackoverflow.com/q/71944985/3422102) for the 5.10.2 release, I downloaded both the older release and the new 6.2 release. 

While the 5.10.2 version responds with the `--version` and `--help` options, the 6.2 version responds to `--version` with `6.1.0-dev` and no longer responds to `--help`.

I haven't gone through all the change-logs for any changes to `--help`, so that may be the desired new behavior (though I'd note, the prior help was quite useful).

The `6.1.0-dev`  version report wasn't expected in a released version (may just be an oversight). Anyway, I tested both the prebuilt binary from /releases and the Archlinux 5.2 package built from source. 

Not a high priority issue, but since I noticed it, I thought I would report it.

**Comment by johnkerl** [comment]
Hi @drankinatty -- is this happening with the 6.3.0 release?

**Comment by drankinatty** [comment]
I'll have to check. I'll go build and test and report back.

**Comment by drankinatty** [comment]
Fixed in:

```none
$ pmq miller
miller 6.3.0-1
```

It properly responds to help now on Arch:

```none
$  mlr --help
Usage: mlr [flags] {verb} [verb-dependent options ...] {zero or more file names}

If zero file names are provided, standard input is read, e.g.
  mlr --csv sort -f shape example.csv

Output of one verb may be chained as input to another using "then", e.g.
  mlr --csv stats1 -a min,mean,max -f quantity then sort -f color example.csv

Please see 'mlr help topics' for more information.
Please also see https://miller.readthedocs.io
```

**Comment by johnkerl** [comment]
awesome, thanks @drankinatty !! :)
