### ISSUE TITLE
Negative exponent elicits 'cannot parse DSL expression' and 'Parse error on token "-"'

### ISSUE THREAD

**Issue by skitt** [johnkerl/miller#1018]
This is forwarded from https://bugs.debian.org/1010046

> Here's a nice, short and sweet one liner that
> demonstrates the problem on bash's command line,
> at least on my computer:
> 
>     $ echo |  mlr put -q 'print 2**-0.5' 
>       mlr: cannot parse DSL expression.
>       Parse error on token "-" at line 1 column 10.
>       Expected one of:
>         { ( field_name $[ braced_field_name $[[ $[[[ full_srec oosvar_name @[ braced_oosvar_name
>         full_oosvar all non_sigil_name float int string_literal regex_case_insensitive
>         int_literal float_literal boolean_literal null_literal inf_literal nan_literal
>         const_M_PI const_M_E panic [ ctx_IPS ctx_IFS ctx_IRS ctx_OPS ctx_OFS ctx_ORS
>         ctx_FLATSEP ctx_NF ctx_NR ctx_FNR ctx_FILENAME ctx_FILENUM env func
> 
> Please note that mlr appears to be unable to parse
> the negative exponent "-0.5".
> 
> I'm happy to report I worked around the problem by
> enclosing the negative exponent in parentheses.
> 
> Here's an example:
> 
>     $ echo |  mlr put -q 'print 2**(-0.5)'
>     0.7071067811865475
> 
> If you decide to mention this issue to the
> upstream author, John Kerl, feel free to let him
> know how impressed I am with his code.

**Comment by johnkerl** [comment]
@skitt the downstream reporter is very welcome! :)

**Comment by johnkerl** [comment]
```
$ echo |  mlr put -q 'print 2**-0.5'
0.7071067811865475
```

Thanks @skitt ! :)
