### ISSUE TITLE
Parse error on token "1e+"

### ISSUE THREAD

**Issue by skitt** [johnkerl/miller#1019]
This is forwarded from https://bugs.debian.org/1010184

> Here are some simple examples that I hope will
> also reveal the bug on your computer:
> 
>     $ echo | mlr put 'print 1e+0'
> 
> On my computer, mlr complains with:
> 
>     mlr: cannot parse DSL expression.
>     Parse error on token "1e+" at line 1 column 7.
>     Please check for missing semicolon.
>     Expected one of:
>       $ ; { > >> | ( field_name $[ braced_field_name $[[ $[[[ full_srec oosvar_name
>       @[ braced_oosvar_name full_oosvar all non_sigil_name float int + - .+ .-
>       ! ~ string_literal regex_case_insensitive int_literal float_literal boolean_literal
>       null_literal inf_literal nan_literal const_M_PI const_M_E panic [ ctx_IPS
>       ctx_IFS ctx_IRS ctx_OPS ctx_OFS ctx_ORS ctx_FLATSEP ctx_NF ctx_NR ctx_FNR
>       ctx_FILENAME ctx_FILENUM env func
> 
> I'm happy to report a workaround is simply
> omitting the positive "+" sign before the exponent
> like this:
> 
>     $ echo | mlr put 'print 1e0'
> 
> At least on my computer, mlr returns
> 
>     1e0
> 
> For what it's worth, here's an analogous example
> with the great grand daddy of csv tools, awk:
> 
>     $ echo | awk '{ print 1e+0 }
> 
> At least on my computer, awk returns
> 
>     1

**Comment by aborruso** [comment]
In the documentation

> Miller has always supported scientific notation in field values, e.g x=1e6. However, it had never supported scientific notation in DSL literals, e.g. mlr put '$y = $x + 1e6.

Running `echo 'a=2' | mlrgo put '$b=$a+(1e0)'`, you have `a=2,b=3`

Always in the doc

> Print statements are for strings (print "hello"), or things which can be made into strings: numbers (print 3, print $a + $b), or concatenations thereof (print "a + b = " . ($a + $b)). Maps (in $*, map-valued out-of-stream or local variables, and map literals) as well as arrays are printed as JSON.

And running `echo 'a=2' | mlrgo put 'print "a + sci = " . ($a + 1e0)'`  you have

```
a + sci = 3
a=2
```

Only to add some notes, I know this message of mine is not a reply.

**Comment by johnkerl** [comment]
```
$ echo | mlr put 'print 1e+0'
1e+0
```

Thanks @skitt ! :)
