### ISSUE TITLE
CSV-quoting must quote fields containing quote

### ISSUE THREAD

**Issue by now** [johnkerl/miller#104]
Hi!

Currently, miller completely ignores the fact that some fields may contain the quoting character.  The quoting character should be doubled whenever it appears in a record, for example, "abc ""def""".

I’ve attached a patch (as .txt, as that’s what GitHub allows me to do).

[csv-quoting.txt](https://github.com/johnkerl/miller/files/327236/csv-quoting.txt)

**Comment by johnkerl** [comment]
Nice! I'll merge this very soon. Thank you!

**Comment by johnkerl** [comment]
Merged in https://github.com/johnkerl/miller/commit/a4ae62216e4d5ed6742f3531adba12a35085a934 -- thank you!
