### ISSUE TITLE
Use '+' as alternative for 'then'?

### ISSUE THREAD

**Issue by zwets** [johnkerl/miller#1041]
Only recently discovered miller and wow does it fill a gap! It's now the monkey wrench in my toolbox, giving well-worn `grep`, `sed`, `cut` and `awk` a rest. Thanks so much for conceiving and developing this!

My suggestion would be to offer `+` as an alternative for `then`. The plus symbol has no meaning for shells, conveys some of the 'pipe' or 'then' meaning, and above all provides a clear visual cue of separating two sides of a pipeline - including suggesting (correctly) that it has lowest binding priority.

I'm well aware that this comes down to personal taste, so feel free to drop the issue.

**Comment by zwets** [comment]
PS: my one peeve with `mlr` is that `-t` isn't the implicit default, though surely this is due to personal trauma. However short it is, having to type it every time reminds of the pain of `awk -F '\t'` 'begin {OFS=FS}'` and of `sort` and `join`'s dreaded "multi-character tab ‘\\t’". Scrapping that compulsory `-t` would bring a disproportionate improvement to my quality of life. :-)

**Comment by johnkerl** [comment]
@zwets have you taken a look at https://miller.readthedocs.io/en/latest/customization/ ?

**Comment by johnkerl** [comment]
@zwets `+` is totally doable! :)

**Comment by zwets** [comment]
> @zwets have you taken a look at https://miller.readthedocs.io/en/latest/customization/ ?

Sure, and I would put it in `~/.mlrrc` if it weren't for portability. My scripts will often be run by others (on our compute cluster) so I'm wary of using dotfile settings or aliases. Great for offhand work, but then you need to always remember to be formal in scripts. If it weren't for this, I'd long had `alias awk='awk -F ...` in my `~/.bash_aliases`. :-)

I could drop a wrapper `tmlr` in the clusterwide `/bin`, just like I've done for `tawk`, `tjoin` and `ttsort` (oww, nameclash with `tsort` in coreutils!), but that's too heavy-handed for just adding that `-t`.

It's just that - at least in bioinformatics - tab-separated has pretty much become the default, and `mlr` looks like just the tool to succeed the golden oldies (awk, grep, sed, ...) for handling it. My thinking was that `mlr` is still young enough to get this default right, without even breaking backward compatibility, but I overlooked that it already has the DKVP default! A somewhat unconventional choice, but I can learn to live with that `-t`.

**Comment by johnkerl** [comment]
@zwets :)

The DKVP default goes WAY back ... to when it was just me. I'd be happy to drop that and use CSV as the default, since (as last year's survey showed) CSV is the format Miller users use most (although all formats get used).

`mlr -t` as default ... I'm sure is the right thing for a very large demographic but it appears the `mlr -c` crowd is bigger still ...

**Comment by johnkerl** [comment]
@zwets apologies on my delay in responding to this (and to everything else Miller-related) -- the last few months I've self-saturated at work on https://github.com/single-cell-data/TileDB-SingleCell/tree/main/apis/python.

#1049 implements `+` as an alias for `then`.
