### ISSUE TITLE
Needing something more than `system`

### ISSUE THREAD

**Issue by forbesmyester** [johnkerl/miller#1043]
I may be missing it, but I'm feeling that just having `system()` for external calls is too limiting.

In Node we have [child_process.spawn(command[, args][, options])](https://nodejs.org/docs/latest-v12.x/api/child_process.html#child_process_child_process_spawn_command_args_options) I know Rust has something similar too.

In GoLang (which I'm not familiar with) I found a struct that looks like a [similar set of options](https://pkg.go.dev/os/exec#Cmd).

Maybe all those options are overkill (particularly things like managing STDIN), but I have a HTML file, with items extracted using [`pup`](https://github.com/ericchiang/pup/) and put into JSON via `jq` so they're still HTML encoded... I have a command line program for decoding HTML entities but I have no sane way to call it because, well perhaps there anything in my data...

Current thinking is a function like `exec("htmlentities", ["decode"] { stdin_value: $the_field_i_want_to_decode })` which has the API `exec(cmd, args, options)`

I might even write it myself if you think it's a good idea and I can get golang going!

**Comment by forbesmyester** [comment]
Notes and rough thoughts for me:

 * `system()` is defined in https://github.com/johnkerl/miller/tree/main/internal/pkg/bifs/system.go
 * `system()` appears to be exposed as a function in https://github.com/johnkerl/miller/blob/24089151604fa1e65891c4678e0136741eaa3ead/internal/pkg/dsl/cst/builtin_function_manager.go#L1920

plan:
 * Create a function called `system_exec()` (name to be agreed) or similar in https://github.com/johnkerl/miller/tree/main/internal/pkg/bifs/system.go
 * Expose in `internal/pkg/dsl/cst/builtin_function_manager.go` as per second bullet point above.
 * Api should be `system_exec(cmd: string, args: string[], { dir?: string, env?: { [k: string]: string }, string_input?: string }. Only `cmd` should be required.
 * No changes to `system()` should be included.
 * Example of variable length function is [`BIF_mapdiff()`](https://github.com/johnkerl/miller/blob/a7226b1633fe0e6861a20f3697ae8ba6d5c85e17/internal/pkg/bifs/collections.go#L303)
 * Example of using Maps is [`BIF_mapselect()`](https://github.com/johnkerl/miller/blob/a7226b1633fe0e6861a20f3697ae8ba6d5c85e17/internal/pkg/bifs/collections.go#L205)
 * Example of using Arrays is [`BIF_concat()`](https://github.com/johnkerl/miller/blob/a7226b1633fe0e6861a20f3697ae8ba6d5c85e17/internal/pkg/bifs/collections.go#L187)
 * Go API for the the method used in `system()` is at https://pkg.go.dev/os/exec#Cmd

I've not put more than 30 mins-ish towards putting this together, but I know zero Go and zero of this codebase, so if someone can validate the following that'd be great:

 * My assumptions
 * The API is sane
 * The modifications are desirable

Thanks :-)

**Comment by johnkerl** [comment]
> I may be missing it, but I'm feeling that just having system() for external calls is too limiting.

I agree, in two different ways.

The good thing about `system` is, of course, that you can interact with external programs.

The main bad thing (from my point of view) is it's single invocation per result. For example, say you have an external program that operates on data a line at a time. Also suppose you have a 1000-line data file. At present in Miller, you'd need to pass that program each field at a time, invoking it 1000 times with a single line each time.

What I would like to see, & have imagined in back-of-envelope sketch, is a sort of _coprogram_, kind of like [coroutines](https://en.wikipedia.org/wiki/Coroutine). You'd invoke it once at the start, maybe pass it a line of data & get the answer back a line at a time.

But this raises issues of line-buffering: lots of external programs only do line-at-a-time when their input is a terminal, & when invoked from other programs -- be it on a pipe in a shell, or `popen`-style from Miller, or what have you -- prefer to 'batch' their reads along 4KB boundaries or some such. It seemed over-fiddly, depending on implementation details of external programs outside Miller's control, to get a true 'handshake'/'baton-pass' kind of environment.

So I have not implemented this. A consolation prize (and a poor one at that) would be multi-part: (a) peel off a column, say, using `mlr cut`; (b) hand that to the external program; (c) stick it back together with `mlr join` or somesuch.

> In Node we have [child_process.spawn(command[, args][, options])](https://nodejs.org/docs/latest-v12.x/api/child_process.html#child_process_child_process_spawn_command_args_options) I know Rust has something similar too.

But I think you're talking about something entirely different -- not a different way to implement handshaking/control, but rather, simply a more flexible way to _launch_ a program.

I think this is a splendid idea.

What `system` has going for it is ease of use, in the sense that you just build up a string like you would keystroke a string while typing at the shell. I agree with you that keeping `system` _as an option_ is a good idea.

Also agreed that something more flexible would be grand.

Your survey of `pkg/bifs` and how Miller handles variadic functions is spot-on.

> My assumptions
> The API is sane
> The modifications are desirable

I think the API `exec(cmd, args, options)` is fine! :)

Apologies on my delay in responding to this (and to everything else Miller-related) -- the last few months I've self-saturated at work on https://github.com/single-cell-data/TileDB-SingleCell/tree/main/apis/python.

**Comment by johnkerl** [comment]
`exec` going out in [6.4.0](https://github.com/johnkerl/miller/releases/tag/v6.4.0)

**Comment by aborruso** [comment]
@johnkerl @forbesmyester this is a great add, thank you very much.

Sometimes, and this is one of the times, I get the feeling that I don't fully understand what the added value of a new feature is, and I wish there was a blog section, or a recipe section in the Miller documentation, with some verbose and "real" use case.

Once again thank you

**Comment by johnkerl** [comment]
ok thanks @aborruso we can/should add some examples :)
