### ISSUE TITLE
csvlite and csv behaves differently with FS within quoted field

### ISSUE THREAD

**Issue by Komosa** [johnkerl/miller#105]
I'm using HEAD.
Example output for both types on linux:

    $ echo -e 'a,b\n"x,y",3' | mlr --icsvlite cat
    mlr: Header-data length mismatch in file (stdin) at line 2.

    $ echo -e 'a,b\n"x,y",3' | mlr --icsv --rs lf cat
    a=x,y,b=3

Expected is common behavior, preferably the working one :)

**Comment by johnkerl** [comment]
This is one of the differences between csv and csvlite:

http://johnkerl.org/miller/doc/file-formats.html#CSV/TSV/etc.
