### ISSUE TITLE
Verb "put" affects subsequent verbs after "then"

### ISSUE THREAD

**Issue by degnbol** [johnkerl/miller#1060]
Given two files, a.csv:
```
A,B
1,2
```

and b.csv:
```
A,B,C
3,4,old
```

If I run:
`mlr --csv --from a.csv put '$C = "new"' then cat b.csv`
I get:
```
A,B,C
1,2,new
3,4,new
```

And if I run:
`mlr --csv --from a.csv put '$C = "new"' | mlr --csv --from /dev/stdin --from b.csv cat`
I get:
```
A,B,C
1,2,new
3,4,old
```

I intend to get the latter result. Is this a bug or am I using miller wrong? I see the same issue with the verb `reorder`. Thanks for any help. 
I'm using version 6.3.0.

**Comment by aborruso** [comment]
@degnbol mlr merges the two inputs before applying `put` verb.

If your goal is to have new where `C` is empty, you could run

```
mlr --csv unsparsify then put 'if(is_empty($C)){$C="new"}' input_01.csv input_02.csv
```

You must use unsparsify, because the two files do not have the same number of fields.

**Comment by degnbol** [comment]
Thanks for the quick reply.

**Comment by aborruso** [comment]
@degnbol for this kind of question, you could start from discussions https://github.com/johnkerl/miller/discussions
