### ISSUE TITLE
[NFR] Verb reorder taking order from first given file

### ISSUE THREAD

**Issue by degnbol** [johnkerl/miller#1061]
I am often concatenating multiple .tsv files that have the same columns, but the columns happen to not be in exactly the same order. `mlr cat` requires the files to have the same column order, otherwise a blankline is inserted between files, so I use commands such as (in zsh)
```
mlr --tsv --from a.tsv --from b.tsv reorder -f `head -n1 a.tsv | tr '\t' ,`
```

Is there already better way, or could a flag be added to either verb `cat` or `reorder` to replicate this? Thanks for any help.

**Comment by aborruso** [comment]
@degnbol try to use [unsparsify](https://miller.readthedocs.io/en/latest/reference-verbs/index.html#unsparsify) and not cat.

And moreover you have the [template](https://miller.readthedocs.io/en/latest/reference-verbs/index.html#template) verb.

**Comment by degnbol** [comment]
Thank you, these verbs are exactly what I need.
