### ISSUE TITLE
Probable serious regression with string handling

### ISSUE THREAD

**Issue by trantor** [johnkerl/miller#1066]
Hello @johnkerl . Today some of my code using miller 5 was run using miller 6 and broke spectacularly XD .
I am gonna give a simple test case which does nothing useful:
```

$ mlr --version
mlr 6.3.0

# Works
$ cat test.sh
echo -e '1\n2\n3' | mlr --nidx put -q '
@m[$1] = "something";
'
$ ./test.sh                                                                                                                                                                                                

# Doesn't
$ cat test.sh
echo -e '1\n2\n3' | mlr --nidx put -q '
@m[$1] = "some
thing";
'
$ ./test.sh
mlr: cannot parse DSL expression.
Parse error on token ""some
" at line 2 column 10.
Expected one of:
  { ( field_name $[ braced_field_name $[[ $[[[ full_srec oosvar_name @[ braced_oosvar_name
  full_oosvar all non_sigil_name float int + - .+ .- ! ~ string_literal regex_case_insensitive
  int_literal float_literal boolean_literal null_literal inf_literal nan_literal
  const_M_PI const_M_E panic [ ctx_IPS ctx_IFS ctx_IRS ctx_OPS ctx_OFS ctx_ORS
  ctx_FLATSEP ctx_NF ctx_NR ctx_FNR ctx_FILENAME ctx_FILENUM env func
```
Apparently multi-line string literals are broken, which is a big problem. Am I missing something?

Bye

**Comment by johnkerl** [comment]
Thanks @trantor !! I had never intentionally supported multi-line string literals (it seems they worked in Miller <= 5 by accident) and wasn't aware of this change.

I'll take a look -- thanks!

**Comment by trantor** [comment]
@johnkerl in my production case I used it to write a multi-line SQL query in a decently readable format, just as an example, so I would much appreciate if you were to introduce formal support for them ;D

**Comment by johnkerl** [comment]
@trantor  totally!!!! :)

**Comment by johnkerl** [comment]
@trantor #1070

Thank you! :)

**Comment by trantor** [comment]
Thanks a lot @johnkerl . I'll compile it and try it as soon as I get a free second ;D.

**Comment by trantor** [comment]
Btw @johnkerl would it make sense to have a minor release with this improvement?

**Comment by johnkerl** [comment]
@trantor sure :)

**Comment by trantor** [comment]
@johnkerl I confirm that the fix works. Could you release a new minor release for this then? Thanks in advance.

**Comment by johnkerl** [comment]
@trantor yes soon :)

Super-busy with day job right now but soon -- hopefully by end of August

**Comment by johnkerl** [comment]
@trantor https://github.com/johnkerl/miller/releases/tag/v6.4.0
