### ISSUE TITLE
mlr head reads entire input file

### ISSUE THREAD

**Issue by bogiebro** [johnkerl/miller#107]
When I try `mlr --csv --rs lf head -n 1000 [large-filename]`, miller continues to read through the file after the first thousand records have been printed. I would have expected this to work like `mlr --csv --rs lf --prepipe 'head -n 1000'  cat` instead. Is there a reason that `mlr head` needs to continue processing input after it has seen the requisite number of lines?

**Comment by johnkerl** [comment]
Yes, when operating keyed (`mlr head -g`) it needs to read the entire input file. When operating non-keyed ... no, it can and should stop. There was a subtle technical reason I didn't implement it at the time: namely, mapper verbs *accept* and *filter* an input stream, but they do not prematurely *close* it. It will take a little refactor but it can certainly be done & it will be worth doing. (Thanks for asking for it & letting me know the latter!)

**Comment by johnkerl** [comment]
The tricky part will be then-chaining: in `mlr something then something else then head then something`, if any of the upstream somethings are record-retainers (like `sort` or `stats1`), then at what point should the input stream be closed.

**Comment by johnkerl** [comment]
Turns out this was totally straightforward (https://github.com/johnkerl/miller/commit/05fc08c5ec921109a9114f2b5b21bc3a604a3510). Sorry I didn't get on it sooner!! `:^/`

This will go out with 4.4.0 (which will be in a month or two, at this rate ... lots of RL recently.)
