### ISSUE TITLE
feature request - add param for filename column when concatenating files with cat

### ISSUE THREAD

**Issue by janxkoci** [johnkerl/miller#1076]
## Problem
Let's say I want to concatenate several CSV files, but I would like to keep an information on which records come from which file. This could be useful for some aggregate statistics based on grouping by file. As an example, different files can represent different samples, countries, etc...

## Proposal
It feels like it should be possible to add a new param to `cat` that would add a new column with either the original filename, or some kind of other identifier. The identifiers could be just integers, possibly with some prefix (as argument to the param?).

### Notes
Now that I'm thinking about it, there probably is some way to do this with `put`, although I'm not entirely sure if it can be done in one step rather than two steps (i.e. just `mlr put '...'` rather than `mlr cat then put '...'`). :thinking: 

If it can be done with `put`, then it would be a very low priority feature request :relaxed:

**Comment by aborruso** [comment]
> If it can be done with `put`, then it would be a very low priority feature request ☺️

You can use `put`

```
mlr --csv put '$name=FILENAME' ./*.csv
```

**Comment by aborruso** [comment]
The doc about it https://miller.readthedocs.io/en/latest/miller-programming-language/#context-variables

**Comment by janxkoci** [comment]
@aborruso Works like a charm, thanks! :wink:

**Comment by johnkerl** [comment]
> Edit: Feel free to close the request if you consider this convenience feature not worth implementing - I can totally use the put solution mentioned above.

It would be very "miller" to have a `mlr cat --filename` and `mlr cat --filenum` as shorthands for what can be done (at more keystroking) in the DSL

**Comment by johnkerl** [comment]
@janxkoci #1080
