### ISSUE TITLE
mlr verb "summary" not found

### ISSUE THREAD

**Issue by janxkoci** [johnkerl/miller#1077]
I wanted to play with the `summary` verb, but I see this:

```bash
$ mlr summary --help
mlr: verb "summary" not found. Please use "mlr --help" for a list.

$ mlr help list-verbs
altkv bar bootstrap cat check clean-whitespace count-distinct count
count-similar cut decimate fill-down fill-empty filter flatten format-values
fraction gap grep group-by group-like having-fields head histogram json-parse
json-stringify join label latin1-to-utf8 utf8-to-latin1 least-frequent
merge-fields most-frequent nest nothing put regularize remove-empty-columns
rename reorder repeat reshape sample sec2gmtdate sec2gmt seqgen shuffle
skip-trivial-records sort sort-within-records split stats1 stats2 step tac
tail tee template top unflatten uniq unsparsify

$ mlr --version
mlr 6.3.0
```

The OS is Linux (several machines and distros, from CentoOS 7 to Ubuntu 20.04) and I installed miller using `conda`, if that makes a difference.

**Comment by aborruso** [comment]
It's not yet in the stable version.

**Comment by johnkerl** [comment]
@janxkoci indeed -- docs (by default) show the latest commit, unless you click 'Release docs'; but when you install the software using most methods, you get the latest release, not the latest commit. This is unfortunate and confusing.

Until the next release (which should be in a week or two 🤞) you might try https://miller.readthedocs.io/en/latest/installing-miller/ to get a latest binary ...
