### ISSUE TITLE
Variable accessing / exec flakiness (I very much don't understand what's going on)

### ISSUE THREAD

**Issue by forbesmyester** [johnkerl/miller#1092]
This

```
printf "%s\n%s\n%s\n%s" number "one" "two two" "three three" | mlr --icsv --omd put '$z=typeof($number) ; $l = exec("echo", ["N: " . $number])'
```

Outputs:

| number | z | l |
| --- | --- | --- |
| one | string | N: one |
| two two | string | N: two two |
| three three | string | N: three three |

Also:

```
printf "%s\n%s\n%s\n%s" number "one" "two two" "three three" | mlr --icsv --omd put '$z=$number ; $l = exec("echo", ["N: " . $number])'
```

Outputs:

| number | z | l |
| --- | --- | --- |
| one | one | N: one |
| two two | two two | N: two two |
| three three | three three | N: three three |

But:

```
printf "%s\n%s\n%s\n%s" number "one" "two two" "three three" | mlr --icsv --omd put '$z=$number ; $l = exec("echo", [$number])'
```

Outputs

`Internal coding error detected at file mlrval_get.go line 104`

This all could be related to my code:

https://github.com/johnkerl/miller/blob/5ffb8a59b38f622b88504bc8ae707966a0468dba/internal/pkg/bifs/system.go#L57 )

Which... erm... means I should maybe submit a PR to fix...

But I (think I) have a string, `typeof` thinks I have a string, but `Mlrval.AcquireStringValue()` doesn't seem to agree and I'm no longer confident I understand anything...

Browsing around I found:

https://github.com/johnkerl/miller/blob/24089151604fa1e65891c4678e0136741eaa3ead/internal/pkg/mlrval/mlrval_get.go#L10

And given I'm clearly out of my depth a bit here I'm wondering if it's related.

Would love to understand what I'm doing wrong (as a user) or having been (as a Miller coder)!

Thanks

**Comment by johnkerl** [comment]
@forbesmyester super-interesting!!! :)

This is something I could make clearer in the Go source:

* `mv.AcquireStringValue()` is for when the mlrval type has already been checked to be `string` or `void` (i.e. `""`)
* `exec` takes all manner of mlrvals, strings or not, so `mv.String()` is the right thing to do as it'll format a number as a string, etc.

**Comment by forbesmyester** [comment]
You're the expert, but your explanation was good and I now understand :-) Thanks for taking the time to explain the problem and the reasons to me.
