### ISSUE TITLE
Go build instructions don't work

### ISSUE THREAD

**Issue by lpar** [johnkerl/miller#1093]
Trying to install using `go install` as mentioned in the README:

```
> go install github.com/johnkerl/miller/cmd/mlr
go: 'go install' requires a version when current directory is not in a module
	Try 'go install github.com/johnkerl/miller/cmd/mlr@latest' to install the latest version
> go install github.com/johnkerl/miller/cmd/mlr@latest
go: github.com/johnkerl/miller/cmd/mlr@latest: module github.com/johnkerl/miller@latest found (v5.10.3+incompatible),
  but does not contain package github.com/johnkerl/miller/cmd/mlr
```

**Comment by johnkerl** [comment]
Hi @lpar !!

Can you tell me a few things so I can try to reproduce the failure? (It does not fail for me.)

* `pwd`
* OS
* `go version`

**Comment by johnkerl** [comment]
I'm super-puzzled about `found v5.10.3` since Miller wasn't ported to Go until Miller 6.0.0; in 5.10.3 it was still written in C. Something, somewhere, is very confused, and I'm unsure what ...

**Comment by lpar** [comment]
`go version go1.19 linux/amd64`

Specifically, Fedora 36.

I go into an empty directory `/home/meta/tmp/mlr`, just to make sure there aren't any files in CWD that might be messing things up, and run `go install github.com/johnkerl/miller/cmd/mlr`

I get:
```
go: 'go install' requires a version when current directory is not in a module  
	Try 'go install github.com/johnkerl/miller/cmd/mlr@latest' to install the latest version
```

So I try that, and get `go: github.com/johnkerl/miller/cmd/mlr@latest: module github.com/johnkerl/miller@latest found (v5.10.3+incompatible), but does not contain package github.com/johnkerl/miller/cmd/mlr`

This is the standard way to build and install a Go program; e.g. `go install github.com/schollz/croc/v9@latest` works fine. So does `go install github.com/lpar/flactools/cmd/flacsum@latest`, so it isn't the `/cmd/mlr` bit that's the problem.

I can't work out what's going wrong here. I've tried various other possible combinations of `v6` and `/cmd/mlr` and none of them seem to work:

```
> go install github.com/johnkerl/miller/v6@latest
go: github.com/johnkerl/miller/v6@latest: module github.com/johnkerl/miller@latest found (v5.10.3+incompatible), but does not contain package github.com/johnkerl/miller/v6
> go install github.com/johnkerl/miller/v6/cmd/mlr@latest
go: github.com/johnkerl/miller/v6/cmd/mlr@latest: module github.com/johnkerl/miller@latest found (v5.10.3+incompatible), but does not contain package github.com/johnkerl/miller/v6/cmd/mlr
> go install github.com/johnkerl/miller/cmd/mlr/v6@latest
go: github.com/johnkerl/miller/cmd/mlr/v6@latest: module github.com/johnkerl/miller@latest found (v5.10.3+incompatible), but does not contain package github.com/johnkerl/miller/cmd/mlr/v6
```

I'm also completely mystified where it's getting the `v5.10.3+incompatible` from, since that's not the version I'm asking for and it still picks it even if I explicitly specify `v6`.

Same behavior on my Mac:

```
go install github.com/johnkerl/miller/cmd/mlr@latest
go: downloading github.com/johnkerl/miller v5.10.3+incompatible
go: github.com/johnkerl/miller/cmd/mlr@latest: module github.com/johnkerl/miller@latest found (v5.10.3+incompatible), but does not contain package github.com/johnkerl/miller/cmd/mlr
```

**Comment by johnkerl** [comment]
oh derp i see what's going on @lpar :( 

I don't have Fedora hardware but I did `docker run --rm -it fedora:latest` and then:

```
# yum install go

# go install github.com/johnkerl/miller/cmd/mlr

# go install github.com/johnkerl/miller/cmd/mlr@latest
go: 'go install' requires a version when current directory is not in a module
    Try 'go install github.com/johnkerl/miller/cmd/mlr@latest' to install the latest version
    [root@f7a01b4b12c5 /]# go install github.com/johnkerl/miller/cmd/mlr@latest
    go: downloading github.com/johnkerl/miller v5.10.3+incompatible
    go: github.com/johnkerl/miller/cmd/mlr@latest: module github.com/johnkerl/miller@latest found (v5.10.3+incompatible), but does not contain package github.com/johnkerl/miller/cmd/mlr
```

The problem is that my notes at https://github.com/johnkerl/miller#building-from-source failed to say the following:

```
$ cd /some/where
$ git clone https://github.com/johnkerl/miller
$ cd miller
$ go install github.com/johnkerl/miller/cmd/mlr
```

i.e. my `go install github.com/johnkerl/miller/cmd/mlr` was within the context of having checked out the repo and `cd`'ed into it, which i failed to make clear

if you're not in a repo then the bad advice from `go install` (which is bizarre) is printed and it tells you to do something that can't work.

in any event i've updated the `README.md`:
https://github.com/johnkerl/miller/commit/f141a0ef4c8bdc731de536aa9a3185a0d1698f92
