### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [johnkerl/miller#11]
[An extra null pointer check is not needed](http://pubs.opengroup.org/onlinepubs/9699919799/functions/free.html "Do I need to check for NULL before free(p)?") in functions like the following.
* [header_keeper_free](https://github.com/johnkerl/miller/blob/6c29196cf7f5e29069187fea088105d23b6f3159/c/containers/header_keeper.c#L13)
* [lrec_remove](https://github.com/johnkerl/miller/blob/c641ff36c1c6073b2ba914052b5d30e8fec16c63/c/containers/lrec.c#L132)

Would you like to apply the following [semantic patch](http://coccinelle.lip6.fr/ "Program transformation with Coccinelle?") to find more update candidates?
```
@Remove_unnecessary_pointer_checks@
expression x;
@@
-if (x)
    free(x);
```

**Comment by johnkerl** [comment]
Nice catch ... I'll sweep through.

**Comment by johnkerl** [comment]
Merged -- thank you!

**Comment by elfring** [comment]
Are there [any update candidates](https://github.com/johnkerl/miller/blob/892e69978ac877949cb2c6c5461c61a72f0ec348/c/containers/dheap.c#L79 "Reconsider implementation of dheap_free()?") left over?

**Comment by johnkerl** [comment]
Did I miss something?

**Comment by elfring** [comment]
Would it make sense to [check the predicate "`pdheap->is_malloced`"](https://github.com/johnkerl/miller/blob/892e69978ac877949cb2c6c5461c61a72f0ec348/c/containers/dheap.c#L79 "Reconsider check order?") without another test for the pointer "`pdheap->elements`"?
