### ISSUE TITLE
`mlr` silently truncating some TSV files since #923

### ISSUE THREAD

**Issue by johnkerl** [johnkerl/miller#1102]
> Since #923 , `mlr` is silently truncating some files. I do not know which files, and cannot share the one file I know is causing the issue because of data security issues. Here's the output:

original file
```
$ wc -l temp.tsv
308170 temp.tsv
```

tsv filetype
```
$ mlr --tsv cat temp.tsv | wc -l
20408
```

csv filetype with tab separator
```
$ mlr --csv --fs "\t" cat temp.tsv | wc -l
308170
```

version 6.0.0
```
$ mlr --tsv cat temp.tsv | wc -l
308170
```

Even if my file is somehow invalid, this probably should throw an error instead of silently truncating the file. Is there something I should be looking for in the file so I can make a reprex for you?

_Originally posted by @BEFH in https://github.com/johnkerl/miller/issues/923#issuecomment-1270486827_

**Comment by BEFH** [comment]
PR is #923, thanks.

**Comment by johnkerl** [comment]
This is fixed for TSV (in my code) but the issue persists for CSV where the bug is in the Go-CSV library -- this needs to be worked around as well ...

**Comment by BEFH** [comment]
Very interesting. For me, using `--csv --fs "\t"` worked previously. I'll
test the fix and get back to you on if it works.

**Comment by johnkerl** [comment]
Concretely:

```
$ cat test.csv
a
1
2

4
5
```

```
$ mlr5 --icsv --ojson cat test.csv
{ "a": 1 }
{ "a": 2 }
{ "a": "" }
{ "a": 4 }
{ "a": 5 }
```

```
$ mlr --icsv --ojson cat test.csv
[
{
  "a": 1
},
{
  "a": 2
},
{
  "a": 4
},
{
  "a": 5
}
]
```

**Comment by johnkerl** [comment]
> This is fixed for TSV (in my code) but the issue persists for CSV where the bug is in the Go-CSV library -- this needs to be worked around as well ...

@skitt has kindly opened #1164 to track the problem for CSV so I'll close this issue out as it solves the problem for TSV.
