### ISSUE TITLE
Doc material on how to duplicate a row by "unnesting" an array in a property

### ISSUE THREAD

**Issue by johnkerl** [johnkerl/miller#1103]
If it can help people, I wanted to duplicate a row by "unnesting" an array in a property.

input.json
```json
[
{"title": "my awesome title", "roles": ["label1","label2"] }
]
```
OR
input.csv
```csv
title,labels
"my awesome title","label1,label2"
```

👇
output.csv
```csv
title, label
"my awesome title","label1"
"my awesome title","label2"
```

I ended up doing

`mlr --ijson --ocsv --from input.json put -q 'for(label in $labels) { emit1 mapsum($*, {"label": label}) }' then cut -x -f labels`

If like me, your input is a comma-separated string instead of an array, you can split the string beforehand like so:

`mlr --icsv --ocsv --from input.csv put '$labels = splita($labels,",")' then put -q 'for(label in $labels) { emit1 mapsum($*, {"label": label}) }' then cut -x -f labels`

_Originally posted by @dotlouis in https://github.com/johnkerl/miller/issues/133#issuecomment-1274981303_

**Comment by aborruso** [comment]
> If like me, your input is a comma-separated string instead of an array, you can split the string beforehand like so:

If it's a CSV, there is also the nest verb

```
mlr --csv nest --evar "," -f labels  input.csv
```
