### ISSUE TITLE
Handling badly delimited lines

### ISSUE THREAD

**Issue by Overdrivr** [johnkerl/miller#1104]
Just recently discovered miller, very impressed by its capabilities!

I'm using it to clean some large CSV files before feeding them into a (non csv tolerant) 3rd party solution, and I recently stumbled on a new case that i'm not sure how to process.

Here is my file

```
col1,col2,col3
123,"Some
Multiline
Badly delimited row\",456
789, "Some properly
delimited row", 123
```

There is a `\`character right before a `"`character and I would like to remove it, fundamentally, the `"`gets escaped which breaks the row delimiting.
Is there a way to do this in miller ?

Thank you for your help!

**Comment by aborruso** [comment]
Hi @Overdrivr ,
it seems to me that the only problem in you example file is in `789, "Some properly`, because you have a space between `789,` and `"Some properly`.

If you correct it

```
col1,col2,col3
123,"Some
Multiline
Badly delimited row\",456
789,"Some properly
delimited row", 123
```

and run in example 

```
mlr --c2j cat input.csv
```

you will have an output in which you can see that `\"` is managed, it's not a problem.

**Comment by Overdrivr** [comment]
Thanks for your answer, not sure I understand it totally, my original message was not entirely clear sorry about that.

I've removed the whitespace in the origin file but I still have the `\"`character in the output file.

This is my input file :
```
col1,col2,col3
123,"Some
Multiline
Badly delimited row\",456
789,"Some properly
delimited row", 123
```

This is the command I use for "cleaning" the file (I've noticed running miller on a csv does a fair amout of cleaning in itself)

`mlr --csv cat input_file.csv > fixed_file.csv`

The output file is identical to the input file, but what I'd like to obtain instead is this :

```
col1,col2,col3
123,"Some
Multiline
Badly delimited row",456
789,"Some properly
delimited row"," 123"
```

Is it possible to pass specific command line arguments to achieve this ?

**Comment by aborruso** [comment]
Hi @Overdrivr , if you run

```
mlr --csv -S put 'for (k in $*) {$[k] = sub($[k], "\\$", "")}' input.csv
```

you will get

```
col1,col2,col3
123,"Some
Multiline
Badly delimited row",456
789,"Some properly
delimited row"," 123"
```

It runs a global search and replace, in all fields, for `\` char at the end of each cell.

**Comment by Overdrivr** [comment]
Wow that is seriously awesome, thanks a lot!
