### ISSUE TITLE
A strange error related to 5 version

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#1108]
Dear @johnkerl ,
I do not know if I can open issues related to 5 version.

I have this input:

```
n1 q1 a1
n2 q2 a2
n3 q3 a3
```

If I run the command below using Miller v5.10.2

```
mlr --nidx label id,sequence,reply then put '$format="{\"type\":\"text\"}"' then reshape -i sequence,reply,format -o k,v input.txt
```

I have

```
free(): invalid pointer
[1]    3918 abort      mlr --nidx label id,sequence,reply then put '$format="{\"type\":\"text\"}"'
```

Using Miller 6 I have

```
n1 sequence q1
n1 reply a1
n1 format {"type":"text"}
n2 sequence q2
n2 reply a2
n2 format {"type":"text"}
n3 sequence q3
n3 reply a3
n3 format {"type":"text"}
```

If it no longer makes sense to open an issue for version 5, I close it.

Thank you

**Comment by johnkerl** [comment]
@aborruso memory corruption is definitely a bug :( 

I can make a branch off of 5.10.3 and put up a fix. Then I can tag a 5.10.4 release. It'll be a "pre-release" and won't be available via any package manager but you'll be able to get a binary executable for it.

**Comment by johnkerl** [comment]
@aborruso https://github.com/johnkerl/miller/releases/tag/v5.10.4

Very sorry about the delay

**Comment by aborruso** [comment]
No problem to compile Miller 5 and it works. Thank you

Note: if I run `./mlr --version` I have still `Miller 5.10.3`

**Comment by johnkerl** [comment]
@aborruso I recreated the tag https://github.com/johnkerl/miller/releases/tag/v5.10.4 with `5.10.4` in `c/mlrvers.h` -- thank you! :)

**Comment by aborruso** [comment]
> @aborruso I recreated the tag https://github.com/johnkerl/miller/releases/tag/v5.10.4 with `5.10.4` in `c/mlrvers.h` -- thank you! :)

thank you
