### ISSUE TITLE
put with -f under windows

### ISSUE THREAD

**Issue by MartinMolhanec** [johnkerl/miller#1111]
Maybe I am stupid, but when I try something very simple as
_mlr --csv --opprint --from test-file.csv put -q -f xx.put_
I got following error:
_Unable t read content of xx.put 
fread: No error                 
mlr: could not fread "xx.put"_
Content of xx.put is so simplest:
_print(2)_
and of course from command line:
_mlr --csv --opprint --from test-file.csv put -q 'print(2)'_
is OK, as well as:
_mlr --csv --opprint --from test-file.csv cat_
Seems to me that problem is with reading of xx.put file, but why?
I am using Windows 11.
Thanks for advice!
Martin Molhanec

**Comment by aborruso** [comment]
Hi @MartinMolhanec ,
I have tried using mlr 6.4.0 for win.

If I run

```
mlr.exe --csv --opprint --from test-file.csv put -q -f xx.put
```

I have no error and I get

```
2
2
```

My input csv is this

```
1,2
a,b
c,d
```

Using mlr6 for Linux, inside win, is the same. I have no error.

**Comment by MartinMolhanec** [comment]
Thank for answer, I finally discover problem, I have been using Miller 5.1.0, but now I am testing with  the version Miller 6.4.0 and all is right. My xx.put is simply:
_print(2);_
The quotes are not needed and semicolon is mandatory. 
I just now started testing Miller and seems to me awesame! :-)

Best regards,
Martin Molhanec

**Comment by aborruso** [comment]
Ok, I think you can close the issue ;)
