### ISSUE TITLE
freebsd failures

### ISSUE THREAD

**Issue by jungle-boogie** [johnkerl/miller#113]
Hi John,

These builds (including head) are failing on freebsd:
651e06f850e534c403ca778255ae156f7db977e8
9c35d04a155361acc3670a499f6597ca6cc43638
2bca3791b416a7fc93ba919bb334409113b1a413
f9fba12f682193fc3ef08bb0bf3acc049786fad2
2f22d5147b830eba9d8e34319ebc621bc5f2d9fe
14f494e572e7a4df57ed0e68e50d18e656e61327
e2729e797bc103a7eb9bed841c848d0419dd5cf7

These pass:
1ce6aee8c268605248a638b93c42eb22581faffb
a100cf34186bae287ea7c91533a6d7a7b7275c12
c5c9a4db304ea8e3f37c199a960f804014966fe6

Failure message is bleak:
```
+ .@@@@@@@@@@@@@@@@@@@@@@@@.@@@@@@@@@@@@@@@@@@@@@@@@.@@@@@@@@@@@@@@@@@@@@@@@@.@@@@@@@@@@@@@@@@@@@@@@@@

  mlr --from ./reg_test/input/abixy put -v
      func f(x) {
          return x**2
      }
*** Error code 1

Stop.
make: stopped in /usr/home/sean/bin/miller/c

```

**Comment by johnkerl** [comment]
Two things:

1. The only thing in `reg_test/run` with `return x**2` in it has a lot of context around it. I'm wondering if you got a file truncated somehow ?

2. While I usually make small, incremental changes to Miller, the last few weeks I've been making cross-cutting changes to the DSL and there are some known memory-management issues I'm actively working on.

**Comment by johnkerl** [comment]
For  #1 if you could pastebin the *entire* build output (including the command you are running to build with) I would appreciate it. Please include the output of `git log | head -n 20` in the paste.

Thanks!

**Comment by jungle-boogie** [comment]
Here's the build log file:
[mlr-fail.txt](https://github.com/johnkerl/miller/files/595217/mlr-fail.txt)

**Comment by johnkerl** [comment]
OK thanks for the diff -- the output is very clear now.

Sorry about this mess. Give me a few days ........

**Comment by jungle-boogie** [comment]
hi @johnkerl,

No problems at all and no worries. I should have been building miller more recently and I would have caught it sooner.

**Comment by jungle-boogie** [comment]
hi @johnkerl,

Something you've done recently corrected it!

```
================================================================
Differences between ./reg_test/expected/out and /usr/home/sean/bin/miller/c/output-regtest/out:
No differences found between ./reg_test/expected/out and /usr/home/sean/bin/miller/c/output-regtest/out
================================================================

ALL REGRESSION TESTS PASSED
Tests completed: 2164  
```

**Comment by johnkerl** [comment]
OK thanks @jungle-boogie! Please let me know if any reoccurrences.

**Comment by johnkerl** [comment]
Thanks for the report!
