### ISSUE TITLE
undefined reference to `.mcount'

### ISSUE THREAD

**Issue by jungle-boogie** [johnkerl/miller#114]
hi @johnkerl,

Any idea what's happening here?

http://thunderx1.nyi.freebsd.org/data/110arm64-default/426002/logs/errors/miller-3.3.2.log

**Comment by johnkerl** [comment]
No idea what `.mcount` is. Given the log output
```
/wrkdirs/usr/ports/textproc/miller/work/miller-3.3.2/c/mlrmain.c:15: undefined reference to `.mcount'
```
can you please post the output of `cat -n /wrkdirs/usr/ports/textproc/miller/work/miller-3.3.2/c/mlrmain.c` ?

Unrelated question: any particular reason to be building 3.3.2 (which is from almost a year ago)? The current release is 4.5.0.

**Comment by jungle-boogie** [comment]
> Unrelated question: any particular reason to be building 3.3.2 (which is from almost a year ago)? The current release is 4.5.0.

Well it comes to me not knowing how to patch miller to work on freebsd 9.x. Your tool needs flex but the versions of flex in 9.x are very old. 

These extra patches were supplied to get it working:
https://svnweb.freebsd.org/ports/head/textproc/miller/files/extra-patch-c_Makefile?view=markup&pathrev=408308
https://svnweb.freebsd.org/ports/head/textproc/miller/files/extra-patch-libtool?view=markup&pathrev=408308

I think I tried to patch it to work on 3.x.x but didn't work out for me. If you have the time and desire, I'll take a patch and open a PR on freebsd's site.

The good news is 9.x is EOL end of the year so I should be able to bump up the version to your current release then since I know it builds on 10.x and 11.x

The build failure above is specific to ARM64, which I don't own. The FreeBSD project builds on different archs and evidently miller fails on this particular arch.

**Comment by johnkerl** [comment]
OK if 9.x is truly EOL at EOY (heh) let's wait. That flex version is truly ancient and I'd rather let it age out.

Let me know if something is hung up past year's end and we can revisit.

**Comment by jungle-boogie** [comment]
> Let me know if something is hung up past year's end and we can revisit.

Thanks for being understanding. I'd rather not mess with patching and have a work around. 

regarding .mcount, we can revisit then, too.

**Comment by johnkerl** [comment]
thanks!

**Comment by terorie** [comment]
Bit of a necropost: I can reproduce it on miller v5.6.2.

Missing `mcount` means it's building on non-GNU libc with profiling enabled.
Profiling in turn depends on gcrt1 (GNU variant of crt1).
BSD libc's (and musl libc's) crt1 does not have the `mcount` symbol, unlike gcrt1.

**Comment by johnkerl** [comment]
@terorie "necropost", TIL. :D
