### ISSUE TITLE
Histogram lo/hi limits

### ISSUE THREAD

**Issue by Poshi** [johnkerl/miller#1146]
There are some issues when using manual limits on the histogram command. When using the automatic range selection, everything seems to go well:
```
$ mlr --pprint --from /tmp/tmp.bNq5vP0GAY histogram --auto --nbins 10 -f count
bin_lo  bin_hi  count_count
1       1766.3  1030
1766.3  3531.6  504
3531.6  5296.9  260
5296.9  7062.2  116
7062.2  8827.5  54
8827.5  10592.8 23
10592.8 12358.1 6
12358.1 14123.4 4
14123.4 15888.7 2
15888.7 17654   2
```
But when using manual range selection, the range (and output) is not the expected:
```
$ mlr --pprint --from /tmp/tmp.bNq5vP0GAY histogram --lo 1 --hi 17654 --nbins 10 -f count
bin_lo  bin_hi  count_count
1765.3  3530.6  1030
3530.6  5295.9  504
5295.9  7061.2  260
7061.2  8826.5  116
8826.5  10591.8 54
10591.8 12357.1 23
12357.1 14122.4 6
14122.4 15887.7 4
15887.7 17653   2
17653   19418.3 2
```

Lowest value for `count` is 1 and highest is 17654, so `--auto` seems to get it right. I used this [test data](https://gist.github.com/Poshi/f848e20ad820144aca14a30768b2d1dd).

Version is 6.5.0:
```
$ mlr --version
mlr 6.5.0
```

**Comment by johnkerl** [comment]
Sadly, this was more of #1089 -- there was a bug (same bug) in the auto and non-auto cases and in #1089 I fixed only one of the two. :(

Also, unit tests for non-auto had `--lo 0` which doesn't surface the bug.

On #1157 I've addressed both issues.

Very sorry about the failures!
