### ISSUE TITLE
JSON output doesn't escape quote and backslahes in strings

### ISSUE THREAD

**Issue by dimfeld** [johnkerl/miller#115]
Using the 4.5.0 release on OSX, installed via homebrew.

Here's a simple script to reproduce:
```
mlr --icsv --ojson --rs lf cat <<EOF
col
"abc ""def"" \ghi"
EOF
```

Output is: `{ "col": "abc "def" \ghi" }`
Whereas I would expect `{ "col": "abc \"def\" \\ghi" }`

**Comment by johnkerl** [comment]
Awesome, thanks!!

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/commit/b3c223c13a624bb74675ece4258e36adc0397b9a and https://github.com/johnkerl/miller/commit/512712beda7dd52a0dbe84891396b49c8cafa477

**Comment by johnkerl** [comment]
Note: this fix is now in head -- but head is (unusually for Miller) a bit flaky right now. Unit tests are passing but there are a few memory-leak issues. This is due to significant DSL churn in support of a 5.0.0 release which is still some weeks away.

Thanks for the bug report!!

**Comment by dimfeld** [comment]
I compiled the latest HEAD and confirmed the fix on my original larger file as well. Thank you!
