### ISSUE TITLE
freesbsd: xxx crash on orderswap

### ISSUE THREAD

**Issue by jungle-boogie** [johnkerl/miller#116]
Hi John,

Sorry to keep you busy tracking down things that may not be an issue lately.

I installed TrueOS <https://www.trueos.org> from their 28th of October snapshot and naturally wanted to test out miller on it.

TrueOS is basically freeBSD with a gui premade. Anything spring to mind?

```
mlr -n put end {
  @a[2][3] = 4;
  b[2][3] = 8;
  emitp (@a, b, {2:{3:12}}); # xxx crash on orderswap
  emit  (@a, b, {2:{3:12}});
  emit {};
  emit  (@a, b, {2:{3:12}}), "t";
  emitp (@a, b, {2:{3:12}}), "t";
  emit {};
  emit  (@a, b, {2:{3:12}}), "t", "u";
  emitp (@a, b, {2:{3:12}}), "t", "u";
}
*** Error code 138
```

Not in the log but reported to stdout is this:
```
Bus error
```
which is immediately above the error code 138 section.

[bus-error.txt](https://github.com/johnkerl/miller/files/605692/bus-error.txt)

**Comment by johnkerl** [comment]
@jungle-boogie please re-check from head.

**Comment by jungle-boogie** [comment]
hi @johnkerl,

Once again you fixed it! What was the problem?

Thanks!

**Comment by johnkerl** [comment]
It was an old uninitialized memory read going back to 4.1.0, dependent on ordering of statements. Randomly, a bit more problematic in FreeBSD.

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/commit/fc2f29ea89a6301b374c24ef811088e1502ac79a was the fix.
