### ISSUE TITLE
Implement `left_pad` and `right_pad` string functions

### ISSUE THREAD

**Issue by johnkerl** [johnkerl/miller#1166]
As requested in #1153

**Comment by derekmahar** [comment]
Do Miller built-in functions follow the "snake_case" or "CamelCase" naming convention?

**Comment by johnkerl** [comment]
@derekmahar snake_case, with some flatcase: https://miller.readthedocs.io/en/latest/reference-dsl-builtin-functions/index.html

**Comment by johnkerl** [comment]
@derekmahar @aborruso https://github.com/johnkerl/miller/pull/1205 is in progress

**Comment by johnkerl** [comment]
Miller 6.7.0 coming soon ... :)
