### ISSUE TITLE
Error during join: output depends on the line order of the right file 

### ISSUE THREAD

**Issue by massyah** [johnkerl/miller#1182]
Hi, 
It seems that the `join` verb is still somewhat sensitive to the row order in the input files. With the example files, the results contains 44 rows as expected. However, if we transpose the two lines in the `campaign-7f48827a-91ba-11ed-89a5-6e3199a441c9-info.csv` file, only 32 rows are generated. 

Full command:
```
mlr --icsv --ocsv join -s -j line_item_uuid -f campaign-7f48827a-91ba-11ed-89a5-6e3199a441c9-info.csv  then cat frames-7f48827a-91ba-11ed-89a5-6e3199a441c9-combined.csv > campaign-7f48827a-91ba-11ed-89a5-6e3199a441c9-all-frames-export.csv
```

Input files : 
[campaign-7f48827a-91ba-11ed-89a5-6e3199a441c9-info.csv](https://github.com/johnkerl/miller/files/10484298/campaign-7f48827a-91ba-11ed-89a5-6e3199a441c9-info.csv)
[frames-7f48827a-91ba-11ed-89a5-6e3199a441c9-combined.csv](https://github.com/johnkerl/miller/files/10484299/frames-7f48827a-91ba-11ed-89a5-6e3199a441c9-combined.csv)

Miller version : mlr 6.6.0
Os : MacOs 12.3; MacBook Pro m1

**Comment by aborruso** [comment]
> It seems that the `join` verb is still somewhat sensitive to the row order in the input files.

It's sensitive, because you are using `-s` parameter. If you use it records must be sorted lexically by their join-field names, else not all records will be paired (the [join documentation](https://miller.readthedocs.io/en/latest/reference-verbs/index.html#join)).  

If you remove it, you can use any column sorting.

**Comment by massyah** [comment]
Thanks @aborruso, I definitely overlooked this.
