### ISSUE TITLE
Is "self join" possible?

### ISSUE THREAD

**Issue by Slebi** [johnkerl/miller#1189]
I want to calculate the difference between 2 consecutive records. I already figured out that I can calculate the in-stream-position with:
`put '$one = 1;  @n += $one; $pos=@n '`

Now I would like to "self-join" with the condition:
`a.$pos = b.$pos -1`

Or is there another (simpler) way to calculate deltas between records? Thanks for your reply!

**Comment by aborruso** [comment]
Hi @Slebi could you add a sample input, and the sample output you want?

**Comment by Slebi** [comment]
Sample Input attached
[230203_mlrTicket.csv](https://github.com/johnkerl/miller/files/10577447/230203_mlrTicket.csv)


I want to filter '$Car == "B" && $Race == 2'. Then I want to know the time difference from TrackPoint A to B; B to C and C to D.

Bonus Question: I have a second file with distances (distance from TrackPoint A to B, ...). I want to know the average speed of the car between trackpoints.

Thank for you reply!

**Comment by Slebi** [comment]
ah I guess the verb `step` is the solution... I will try this soon

**Comment by aborruso** [comment]
> ah I guess the verb `step` is the solution... I will try this soon

Yes it's step. If you run

```
mlr --csv filter '$Car=="B" && $Race==2' then step -a delta -f ElapsedTime 230203_mlrTicket.csv
```

you get

| Car | Race | TrackPoint | ElapsedTime | ElapsedTime_delta |
| --- | --- | --- | --- | --- |
| B | 2 | A | 1 | 0 |
| B | 2 | B | 100 | 99 |
| B | 2 | C | 200 | 100 |
| B | 2 | D | 300 | 100 |

**Comment by aborruso** [comment]
@Slebi Did you evaluate it? Did it work?

If yes, please close the issue
