### ISSUE TITLE
merge-fields to concatenate string columns

### ISSUE THREAD

**Issue by fgvieira** [johnkerl/miller#1195]
I am trying to merge columns, but `merge-fields` seems to only apply to numeric values.
I need to merge two columns with strings, by concating their content or (maybe also) only keeping unique values.

For inspiration, the idea would be similar to what is done here for BED files:
https://bedtools.readthedocs.io/en/latest/content/tools/merge.html

thanks,

**Comment by aborruso** [comment]
Please could you add a sample input and the sample output you want?

**Comment by fgvieira** [comment]
A `uniq` (or `distinct`) command:
```
echo -e "a,b,c\none,two,two\nthree,three,four" | mlr --csv merge-fields -a uniq -f b,c -o bar
```
would give something like:
```
a,bar_uniq
one,two
three,threefour
```

or, if there is some way to specify a delimiter:
```
echo -e "a,b,c\none,two,two\nthree,three,four" | mlr --csv merge-fields -a uniq --del '-' -f b,c -o bar
```
```
a,bar_uniq
one,two
three,three-four
```

A `collapse` command, also specifying a delimiter:
```
echo -e "a,b,c\none,two,two\nthree,three,four" | mlr --csv merge-fields -a collapse --del '-' -f b,c -o bar
```
```
a,bar_collapse
one,two-two
three,three-four
```

**Comment by aborruso** [comment]
> A `collapse` command, also specifying a delimiter:

You could [reshape](https://miller.readthedocs.io/en/latest/reference-verbs/index.html#reshape), cut and [nest](https://miller.readthedocs.io/en/latest/reference-verbs/index.html#nest)

```
echo -e "a,b,c\none,two,two\nthree,three,four"  | mlr --csv reshape -r '(b|c)' -o k,bar_collapse then cut -x -f k then nest --ivar "-" -f bar_collapse
```

to have

```
a,bar_collapse
one,two-two
three, three-four
```

**Comment by fgvieira** [comment]
Thanks @aborruso! Just for future references, you can also get only `uniq` elements.
It is not very readable, but it does the job:

```
$ echo -e "a,b,c\none,two,two\nthree,three,four"  | mlr --csv reshape -r '(b|c)' -o k,bar_collapse then cut -x -f k then uniq -g a,bar_collapse then nest --ivar "-" -f bar_collapse
```
to have:
```
a,bar_collapse
one,two
three,three-four
```
