### ISSUE TITLE
Regex: Cannot escape special characters

### ISSUE THREAD

**Issue by archetyped** [johnkerl/miller#1209]
Some special characters such as `^` and `$` cannot be escaped (to use as a literal character) in regular expressions.

Example:
```bash
echo 'd\n$test\ntest$middle' | mlr --c2p put '$d = sub($d, "^\$", "Dollar")'
```

Output:
```bash
mlr: cannot parse DSL expression.
Parse error on token ""^\$" at line 1 column 14.
Expected one of:
  { ( ) field_name $[ braced_field_name $[[ $[[[ full_srec oosvar_name @[
  braced_oosvar_name full_oosvar all non_sigil_name float int + - .+ .- !
  ~ string_literal regex_case_insensitive int_literal float_literal boolean_literal
  null_literal inf_literal nan_literal const_M_PI const_M_E panic [ ctx_IPS
  ctx_IFS ctx_IRS ctx_OPS ctx_OFS ctx_ORS ctx_FLATSEP ctx_NF ctx_NR ctx_FNR
  ctx_FILENAME ctx_FILENUM env func
```

## Notes

* Miller version: 6.6.0
* Other discussions have referenced using `ssub()`, but that will not work in situations like the above example where the position of the special character is important.
* This is similar to some previous tickets (e.g. #171), but they appear to be related to pre-Go versions of Miller, where regex handling may be different, so it felt best to create a separate ticket.

**Comment by johnkerl** [comment]
@archetyped thank you!! Your example above has been included as a unit-test case in #1212.
