### ISSUE TITLE
No rightpad function

### ISSUE THREAD

**Issue by jonjonw** [johnkerl/miller#1213]
The docs mention a [rightpad function](https://miller.readthedocs.io/en/latest/reference-dsl-builtin-functions/#rightpad) but it doesn't seem to be implemented.

```
$ mlr --version
mlr 6.6.0

$ echo 'a\nb' | mlr -c put '$a=rightpad($a,5,".")'            
mlr: function name not found: rightpad
```

**Comment by johnkerl** [comment]
Hi @jonjonw -- https://miller.readthedocs.io/en/latest/ are for head of the development. Release docs are here:
https://miller.readthedocs.io/en/latest/release-docs/index.html

The `leftpad` and `rightpad` functions are new enough they're not in a release yet.

**Comment by johnkerl** [comment]
That said ... I went ahead and tagged https://github.com/johnkerl/miller/releases/tag/v6.7.0 just now.

I had wanted to get a few more things into the release but they can wait for a 6.8.0, and I think `leftpad`/`rightpad` are popular enough to release right away. :)

**Comment by jonjonw** [comment]
> That said ... I went ahead and tagged https://github.com/johnkerl/miller/releases/tag/v6.7.0 just now.
> 
> I had wanted to get a few more things into the release but they can wait for a 6.8.0, and I think `leftpad`/`rightpad` are popular enough to release right away. :)

Thanks! I'm finding miller to be very useful!

Just a suggestion: you could have /latest point to the most recent release and use /dev for the development/head version docs.
