### ISSUE TITLE
count-distinct: Specify output column name [feature request]

### ISSUE THREAD

**Issue by sjackman** [johnkerl/miller#122]
The output column name of `count-distinct` is named `count`. I'd like to have an output to name the output column. The workaround is to use `then rename count,new_name`. The workaround does not work if a different column is already named `count`.

**Comment by johnkerl** [comment]
Nice! :)

**Comment by johnkerl** [comment]
OK this is done in head:

http://johnkerl.org/miller-releases/miller-head/doc/reference-verbs.html#count-distinct

Thanks for the feature request!!

BTW `histogram`, `least-frequent`, `most-frequent`, and `top` can benefit from the same feature -- which I'll implement  next.

**Comment by sjackman** [comment]
Thanks, John!
