### ISSUE TITLE
DSL: Get substring index (i.e. `strings.Index()`)?

### ISSUE THREAD

**Issue by archetyped** [johnkerl/miller#1225]
Apologies if this is referenced elsewhere, but in Miller's DSL, is there a way to search for a substring within a string and return the substring's position in the string?

Basically something like Go's [`strings.Index()`](https://pkg.go.dev/strings#Index) method:
```go
idx := strings.Index("or", "Ready or Not")
// Returns: 7
```

**Comment by johnkerl** [comment]
@archetyped great idea! :)

**Comment by johnkerl** [comment]
@archetyped Go's `strings.Index` takes the substring as the second arg, not the first.

PR #1247 follows this convention -- but is of course 1-up with its indices since Miller is 1-up.

**Comment by johnkerl** [comment]
https://miller.readthedocs.io/en/main/reference-dsl-builtin-functions/#index

**Comment by archetyped** [comment]
> @archetyped Go's `strings.Index` takes the substring as the second arg, not the first.

Indeed, I got it flipped turned upside down.

Looks great! Thanks 👍
