### ISSUE TITLE
Help with Kaplan-Meier survival function : Running product for the step verb?

### ISSUE THREAD

**Issue by Gavin-Holt** [johnkerl/miller#1227]
Hi,

I am trying to calculate a Kaplan-Meier survival function from csv data describing the fate of artificial knee replacements.

After surgery in the UK, consenting patients have been observed for 20 years in a national audit. Extracts of these data are available for surgeons/departments.

My data has columns for “Endpoint” to describe events, coded as either Blank, Revised, Unrevised, Death.

- I assume Blank entries are lost to follow-up i.e. Censored.
- In this analysis, death means the patient did not need revision (redo) surgery and is the best outcome.
- Unrevised knees are assumed to be functioning adequately when last observed.
- Revision is the outcome of interest and I want the survival function to quantify “knee replacements not revised” at each year after surgery.

These data come with computed “Time to endpoint”, which is blank for censored cases and years to one decimal point for all other events. I have rounded down to create a grouping variable for each year after surgery (i.e. 0–19).

The Wikipedia page for [Kaplan-Meier estimator](https://en.wikipedia.org/wiki/Kaplan%E2%80%93Meier_estimator) states the data requirements for this analysis in the Basic concepts section. But then starts talking in maths hieroglyphics beyond my comprehension.

I am using datamash to cross tabulate “Endpoint” against “Year”. Pre-sorting is required and I have removed “N\A” from the output.

```dos
REM DOS batch file
cat.exe %infile% ^
 | csvtk.exe sort -k Year:n,Endpoint ^
 | datamash.exe  --field-separator=, --header-in crosstab 1,2 count 2 ^
 | sed.exe s/N\/A/0/g ^
 > Test.csv
```
The resulting table looks like this:

```
,,Death,Revised,Unrevised
0,0,96,29,411
1,2,137,30,438
10,6,159,7,361
11,2,141,6,327
12,11,138,3,311
13,8,96,5,340
14,9,83,2,299
15,11,61,0,284
16,33,34,1,204
17,31,12,0,160
18,186,5,0,60
19,298,1,0,3
2,2,167,32,181
3,1,202,28,607
4,7,214,18,677
5,11,222,15,600
6,0,184,16,507
7,28,218,14,460
8,11,211,22,439
9,4,210,7,391
```
Renaming the two blank fields, and sorting by year :
```
Year,Censored,Death,Revised,Unrevised
0,0,96,29,411
1,2,137,30,438
2,2,167,32,181
3,1,202,28,607
4,7,214,18,677
5,11,222,15,600
6,0,184,16,507
7,28,218,14,460
8,11,211,22,439
9,4,210,7,391
10,6,159,7,361
11,2,141,6,327
12,11,138,3,311
13,8,96,5,340
14,9,83,2,299
15,11,61,0,284
16,33,34,1,204
17,31,12,0,160
18,186,5,0,60
19,298,1,0,3
```
In this table the data represent the events happening in each year, for a survival function I think we need the accumulated figures. Searching for running sum is what brought me to mlr!

```
 | mlr.exe --csv step -a rsum -f Censored ^
 | mlr.exe --csv step -a rsum -f Death ^
 | mlr.exe --csv step -a rsum -f Revised ^
 > test.csv && pause
```
Giving :
```
Year,Censored,Death,Revised,Unrevised,Censored_rsum,Death_rsum,Revised_rsum
0,0,96,29,411,0,96,29
1,2,137,30,438,2,233,59
2,2,167,32,181,4,400,91
3,1,202,28,607,5,602,119
4,7,214,18,677,12,816,137
5,11,222,15,600,23,1038,152
6,0,184,16,507,23,1222,168
7,28,218,14,460,51,1440,182
8,11,211,22,439,62,1651,204
9,4,210,7,391,66,1861,211
10,6,159,7,361,72,2020,218
11,2,141,6,327,74,2161,224
12,11,138,3,311,85,2299,227
13,8,96,5,340,93,2395,232
14,9,83,2,299,102,2478,234
15,11,61,0,284,113,2539,234
16,33,34,1,204,146,2573,235
17,31,12,0,160,177,2585,235
18,186,5,0,60,363,2590,235
19,298,1,0,3,661,2591,235
```

Q1. Could anyone here tell me how to make the calculations for Kaplan-Meier estimator so I can plot Year against KM?

- I have the total number of cases in an environment variable !rows!.
- Not sure how to define the cases at risk, perhaps !rows!-($Death_rsum+$Censored_rsum) ?
- Not sure how to define conditional probability, perhaps ($AtRisk-$Revised_rsum)/$AtRisk ?
- I think I may need a running product to multiply the conditional probabilities and generate a cumulative probability i.e. the Kaplan-Meier estimator.

Q2. Should I be using the previous years figures somewhere else in the calculations?

Q3. Could the mlr step verb be extended to generate a running product?

Q4. I can reluctantly use Excel to do running product and generate the following output - is this the correct KM calculation?

NB. !rows!=10547

Year,Censored,Death,Revised,Unrevised,Censored_rsum,Death_rsum,Revised_rsum,AtRisk,KM_cond,KM
0,0,96,29,411,0,96,29,10451,1,1.00
1,2,137,30,438,2,233,59,10312,0.99,0.99
2,2,167,32,181,4,400,91,10143,0.99,0.98
3,1,202,28,607,5,602,119,9940,0.99,0.97
4,7,214,18,677,12,816,137,9719,0.99,0.96
5,11,222,15,600,23,1038,152,9486,0.98,0.94
6,0,184,16,507,23,1222,168,9302,0.98,0.92
7,28,218,14,460,51,1440,182,9056,0.98,0.90
8,11,211,22,439,62,1651,204,8834,0.98,0.89
9,4,210,7,391,66,1861,211,8620,0.98,0.87
10,6,159,7,361,72,2020,218,8455,0.97,0.84
11,2,141,6,327,74,2161,224,8312,0.97,0.82
12,11,138,3,311,85,2299,227,8163,0.97,0.79
13,8,96,5,340,93,2395,232,8059,0.97,0.77
14,9,83,2,299,102,2478,234,7967,0.97,0.75
15,11,61,0,284,113,2539,234,7895,0.97,0.72
16,33,34,1,204,146,2573,235,7828,0.97,0.70
17,31,12,0,160,177,2585,235,7785,0.97,0.68
18,185,5,0,60,362,2590,235,7595,0.97,0.66
19,299,1,0,3,661,2591,235,7295,0.97,0.64

Any advice welcome as long as it doesn’t involve Excel or similar!

Kind Regards Gavin Holt

**Comment by johnkerl** [comment]
Hi @Gavin-Holt and thanks for the very interesting post! Lots to think about here.

First of all the `step -a rprod` will be very easy to implement -- PR coming up. :)

**Comment by johnkerl** [comment]
Sorry I did _not_ mean to mark this as closed yesterday -- #1228 for Q3 was only _one_ item on this issue -- it looks like maybe GitHub autoclosed this issue...

**Comment by johnkerl** [comment]
Same amount of documentation as exists for `rsum` ... perhaps we could say more about both ...

**Comment by aborruso** [comment]
> rprod      Compute running products of field(s) between successive records

Probably I'm stupid and poorly prepared. I know what is a product, I don't know what running product is :)

**Comment by aborruso** [comment]
> Run product is: start with 1. Keep multiplying things keeping trac of the product.

Ok, I'm stupid :)

THank you very much

**Comment by Gavin-Holt** [comment]
Hi,

Many thanks for adding rprod to the step verb. I have downloaded a new binary and this functions flawlessly.

I am seeking expert advice on the calculation of the Kaplan-Meier estimator and will feed back once I have a verified script.

My latest version, with more mlr and less csvtk :)

```batch
REM Change to current directory to the location of this file
cd /D "%~dp0"
cls

REM Set infile
set infile=_DataAll.csv

REM Get Number of Rows
setlocal EnableDelayedExpansion
for /f %%a in ('csvtk.exe nrows %infile%') do set rows=%%a

REM Description
echo. >> Analysis.txt
echo Survival table for !rows! TKR with known Endpoints >> Analysis.txt
echo. >> Analysis.txt

REM KM Calculations all knees with Endpoint
cat.exe %infile% ^
 | mlr.exe --csv put "$Years = floor($ObservedYears)+1" ^
 | mlr.exe --csv filter "$Years < 17" ^
 | mlr.exe --csv cut -o -f Years,Endpoint ^
 | mlr.exe --csv sort -t Years,Endpoint ^
 | datamash.exe  --field-separator=, --header-in crosstab 1,2 count 2 ^
 | sed.exe s/N\/A/0/g ^
 | mlr.exe --csv label Years ^
 | mlr.exe --csv sort -t Years ^
 | tee.exe DataXtabbed.csv ^
 | mlr.exe --csv put "$Total = $Death+$Revised+$Unrevised" ^
 | mlr.exe --csv step -a rsum -f Death ^
 | mlr.exe --csv step -a rsum -f Revised ^
 | mlr.exe --csv step -a rsum -f Unrevised ^
 | mlr.exe --csv step -a rsum -f Total ^
 | mlr.exe --csv put "$AtRisk = !rows!-($Total_rsum-$Total)" ^
 | mlr.exe --csv put "$Survived = $AtRisk-$Revised" ^
 | mlr.exe --csv put "$Survival = $Survived/$AtRisk" ^
 | mlr.exe --csv step -a rprod -f Survival ^
 | mlr.exe --csv format-values -f "%%.3f" ^
 | tee.exe _KM_All.csv ^
 | csvtk.exe pretty -s " | " -r ^
 >> Analysis.txt

REM Add in year zero and plot the curve
echo | set /p dummyname="0,0,0,0,0,0,0,0,0,0,0,0,1" >> _KM_All.csv
cat.exe _KM_All.csv  ^
 | mlr.exe --csv sort -t Years ^
 | csvtk.exe plot line -x Years -y Survival_rprod --title "KM for !rows! TKR with known Endpoints" ^
 -o KM_All.svg

```
For those interested, I have attached DataXtabbed.csv, you can see where it should plug back in to place. Since my first post I have removed all the cases with unknown ```Endpoint``` (these were not _censored_ as we have no idea what happened to them from day one).

Many thanks for miller, it plays perfectly with other UNIX tools, even on Windows! This work-flow is so much better than opening a csv in Excel, having no idea what I am seeing, and gradually degrading the source during dissection.

I think this issue can be closed as you have kindly solved my problem.

Kind Regards Gavin Holt

[DataXtabbed.csv](https://github.com/johnkerl/miller/files/11012250/DataXtabbed.csv)
