### ISSUE TITLE
sort: Clarify what happens when two records compare equal

### ISSUE THREAD

**Issue by sjackman** [johnkerl/miller#123]
When two records compare equal, is `sort` stable, that is, they retain their original order? If so, it would be helpful to mention in the documentation that `sort` is by default a stable sort.

When the input format is `tsvlite`, when two records compare equal, is it possible to optionally fall back to comparing the entire lines lexicographically, to emulate the behaviour of Unix `sort`? e.g.
```
mlr --tsvlite sort -f key -f LINE
```
where `LINE` is the string of the whole line.

**Comment by johnkerl** [comment]
Thanks for the request!

Sorts are definitely stable. I thought I'd said that several times but I may have missed a spot (or more). Where did you expect to find it? Manpage, `mlr sort -h`, http://johnkerl.org/miller/doc/reference-verbs.html ?

Fallback to linesort ... gleah. I get why you'd want that, for sure, but in Miller the sense of 'line' is lost whenever the input format is parsed into a record stream ...

**Comment by sjackman** [comment]
I was reading http://johnkerl.org/miller/doc/reference-verbs.html#sort
It doesn't state that the sort is stable. I'd suggest something like:
```
The sort is stable; records that compare equal will sort together in the order they were encountered.
``

**Comment by johnkerl** [comment]
http://johnkerl.org/miller-releases/miller-head/doc/reference-verbs.html#sort

Thank you!

**Comment by sjackman** [comment]
Thanks, John!
