### ISSUE TITLE
SQL interface?

### ISSUE THREAD

**Issue by avodonosov** [johnkerl/miller#1235]
Consider addind SQL interface.  It may save script authors and readers from learning miller option names and syntax for filtering, jointing, etc.

The "sed, cut, join, and sort" for tabular data just calls for SQL, imho.  Not sure about the awk reference, awk is probably too powerful to be subsumed with SQL.

Prior work exists.  The first google result for "sql in command line for csv" is csvsql:
https://towardsdatascience.com/analyze-csvs-with-sql-in-command-line-233202dc1241

Somebody also said that 
> DuckDB is actually pretty good at this kind of thing.
> Doesn't need to load anything to DB
>
> Can be used in shell
>
> Can read from stdin and write to stdout

**Comment by johnkerl** [comment]
@avodonosov thank you for the suggestion.

SQL occupies a key, cherished, and valuable role in data processing. csvsql is fantastic. Miller is not an SQL tool. There are already tools that do SQL and do it well.  SQL users should use those tools.
