### ISSUE TITLE
concatenate csv files

### ISSUE THREAD

**Issue by jerome-laforge** [johnkerl/miller#1239]
Hello,
I try to concatenate 2 csv files in one csv file like below:

file1:
```csv
a,b,c,d
a1,b1,c1,d1
a2,b2,,d3
```

file2:
```csv
a,c,e
a4,c4,e4
a5,c5,e5
```

expected result:
```csv
a,b,c,d,e
a1,b1,c1,d1,
a2,b2,,d3,
a4,,c4,,e4
a5,,c5,,e5
```

Thanks in advance for your support

**Comment by aborruso** [comment]
Hi, you can use `unsparsify` verb and run `mlr --csv unsparsify file1 file2 >output`

**Comment by jerome-laforge** [comment]
awesome!!
