### ISSUE TITLE
Format-conversion keystroke-saver options don't work?

### ISSUE THREAD

**Issue by sjackman** [johnkerl/miller#124]
The format-conversion keystroke-saver options, such as `--c2t` do not appear to work.
```
❯❯❯ mlr --c2t cat summary.csv
mlr: option "--c2t" not recognized.
Please run "mlr --help" for usage information.
```

From http://johnkerl.org/miller/doc/reference.html
```
Format-conversion keystroke-saver options, for input, output, or both:
As keystroke-savers for format-conversion you may use the following:
  --c2t --c2d --c2n --c2j --c2x --c2p --c2m
```

**Comment by johnkerl** [comment]
The web docs are for head. Probably you have a non-head executable? What is your `mlr --version`?

Note: Miller 5.0.0 is rather a big extension to the DSL & I've been at it for some months now. So, the lag between release & head is extra-big this time around. :^/

**Comment by sjackman** [comment]
Thanks for the explanation. I'm using Miller 4.5.0 from Homebrew. Perhaps the default web site documentation should be for stable rather than HEAD?

**Comment by johnkerl** [comment]
Yeah that's a good idea ...

**Comment by johnkerl** [comment]
OK http://johnkerl.org/miller/doc/index.html points to 4.5.0 and http://johnkerl.org/miller-head/miller/doc/index.html points to head. I've another step to do to make head docs easier to get at, and also I'll remove the doc bits saying that http://johnkerl.org/miller/doc/index.html is head docs.

**Comment by johnkerl** [comment]
OK, all done.

You're not the first to be confused by this -- thanks for the push in the right direction. :)

**Comment by sjackman** [comment]
Thanks again, John! Your responsiveness makes `mlr` all the more useful.

**Comment by johnkerl** [comment]
Glad to hear it @sjackman!!
