### ISSUE TITLE
add column at specific place

### ISSUE THREAD

**Issue by jerome-laforge** [johnkerl/miller#1240]
Hello,
I try to add column in specific place.

file.csv
```csv
a,b,d,e
a1,b1,d1,e1
```

```sh
mlr --csv  --from file.csv put '$c' #add `c` how to add column in specific place
```

expected output
```csv
a,b,c,d,e
a1,b1,,d1,e1
```

Thank in advance for your support.

**Comment by aborruso** [comment]
Add it, and then reorder the fields https://miller.readthedocs.io/en/6.7.0/reference-verbs/index.html#reorder

**Comment by jerome-laforge** [comment]
thanks you very much for this link

The command below works as expected
```
mlr --csv  --from file.csv reorder -f '$c' -b '$d'
```
