### ISSUE TITLE
mlr expects DOS, not unix, newlines by default, for CSV

### ISSUE THREAD

**Issue by dmd** [johnkerl/miller#126]
What am I doing wrong here?

```
dmd@dev ~$ cat test.csv
"foo","bar"
"hello","bye"

dmd@dev ~$ mlr --csv cut -f bar test.csv
mlr: unmatched double quote at line  0.
```

**Comment by dmd** [comment]
Answering my own question -- i needed `--rs lf`

**Comment by johnkerl** [comment]
:) Although that's a very unclear way for me to say 'need --rs lf' ;)

**Comment by dmd** [comment]
I am puzzled, actually, why this is not the default. Consider this very unexpected behavior:

```
$ cat > foo.csv
foo,bar
1,2
$ mlr --csv cut -f foo foo.csv
$
```

No output!  I thought mlr was, first and foremost, unix-native; and yet it expects DOS newlines by default?

**Comment by johnkerl** [comment]
Yes for CSV files. This is part of the CSV spec:

https://github.com/johnkerl/miller/releases/tag/v2.0.0

I was neither happy about defaulting to non-compliant CSV nor to defaulting to compliant CSV.

Autodetect would be a nice feature to implement but it's not clear to me how to do that in a performant way when reading from standard input. Nonetheless it's worth some dev effort on my part, and probably worth a bit of a performance regression for that matter, to have autodetection.

**Comment by johnkerl** [comment]
Also see http://johnkerl.org/miller-releases/miller-4.5.0/doc/faq.html#Number_one_FAQ for the `MLR_CSV_DEFAULT_RS=lf` environment workaround (which may or may not be of some comfort).

**Comment by johnkerl** [comment]
I'm aiming to get autodetect in for the 5.0.0 release (which is underway)

**Comment by johnkerl** [comment]
@dmd I have some unit-test cases to check in, and doc info to write, but the feature is in head if you'd like to pull it and test.

**Comment by johnkerl** [comment]
@sjackman this gets around your prior concern as well, I believe, for TSV -- ?

**Comment by johnkerl** [comment]
This is in head and will go out with 5.0.0 -- @dmd thanks for giving me the push I needed! :)

See also http://johnkerl.org/miller-releases/miller-head/doc/index.html

**Comment by sjackman** [comment]
Nice! Thanks, John.
