### ISSUE TITLE
[question] Handling a CSV file w/ double quotes and a mismatching header

### ISSUE THREAD

**Issue by T145** [johnkerl/miller#1260]
In trying to process the following input, I get a `mlr: unacceptable empty CSV key at file "urls.csv" line 1.`:

```
id;type;url;ip;date;
"1";"pony";"http://www.faridatiannery.com/panel/admin.php";"103.63.2.250";"26-08-2017";
"2";"Zeus fork";"http://hutrnadhi.com/off/www.php?m=login";"119.28.43.178";"26-08-2017";
```

I've gotten this far:
```
mlr --ifs ';' --csv cat urls.csv
```

Obviously I can ignore the first line and pipe the input, but is there a way to handle this all w/in Miller?

**Comment by johnkerl** [comment]
@T145 what's your `mlr version`?

**Comment by T145** [comment]
Miller 5.10.0

**Comment by johnkerl** [comment]
@T145 ok -- what operating system?

**Comment by johnkerl** [comment]
(Miller 6 has been out a while -- currently 6.7.0 -- but I can make a bugfix release on 5.10.)

**Comment by T145** [comment]
I'm using this image: https://github.com/T145/black-mirror/blob/master/Dockerfile

**Comment by T145** [comment]
I also get this error when performing the Go install:

```
root@gotest:/go# go install -v github.com/johnkerl/miller/cmd/mlr@latest
go: downloading github.com/johnkerl/miller v5.10.4+incompatible
go: github.com/johnkerl/miller/cmd/mlr@latest: module github.com/johnkerl/miller@latest found (v5.10.4+incompatible), but does not contain package github.com/johnkerl/miller/cmd/mlr
```

**Comment by T145** [comment]
It works on the latest version! Thanks for the help.
