### ISSUE TITLE
 mlr calculates mean incorrectly when numeric values have a '+' prefix

### ISSUE THREAD

**Issue by arielf** [johnkerl/miller#1267]
### Reproducible example

    % mlr --version
    mlr 6.5.0-dev

    % cat mlrbug.csv
    F1,F2
    a,-1.0
    b,+1.0

    % mlr --icsv stats1 -a mean -f F2 mlrbug.csv
    F2_mean=-1

Actual mean should be 0.
It seems like the number that has the '+' prefix is simply skipped/ignored.

### Expected output

    F2_mean=0

**Comment by aborruso** [comment]
Hi @arielf what is it "[mlr-org/mlr](https://github.com/mlr-org/mlr)"? Is it a R package that uses miller?

I don't think so because I don't see it mentioned in the readme. But maybe I'm wrong

**Comment by arielf** [comment]
@aborruso, I believe you're right. The two are unrelated, and only share the name 'mlr' which is what confused me.
The issue I found is in the (golang) 'mlr' command-line utility (this project) not in the R mlr library. Sorry!

**Comment by johnkerl** [comment]
Thank you @arielf !! :)

**Comment by arielf** [comment]
@johnkerl thanks for fixing [issue 1267](https://github.com/johnkerl/miller/issues/1267) so quickly.

Confirming that the issue is fixed for me now (version: 6.7.0-dev)

Also belated thanks for this amazing tool (which I've starred a while ago).
I've been using it daily and finding it very useful in dealing with my local csv files :-)
