### ISSUE TITLE
Time travel to 1977 or so and make mlr available in all subsequent Unix distributions

### ISSUE THREAD

**Issue by dmd** [johnkerl/miller#127]
Thanks. It would be real helpful. Closing for now; a successful time travel will simply remove this issue from the timeline.

**Comment by johnkerl** [comment]
:)

FWIW it's in a lot of distros but an explicit absence is Centos/RedHat/Fedora. There's more paperwork associated with that than I've had the gumption to deal with. If anyone reading this is an expert in that area ... I'd love to chat. I have an SRPM ready to go. :)

**Comment by dmd** [comment]
Sorry, I didn't really mean 'distributions', I meant I want it in the absolute default minimal unix. E.g., if it (like, say, sed/awk/grep) were missing it would be considered a broken build at best. :D

**Comment by johnkerl** [comment]
Oh got it. Too late then. ;)
