### ISSUE TITLE
Group by and Stats

### ISSUE THREAD

**Issue by nryberg** [johnkerl/miller#1280]
Still getting the hang of things - but want to know if I can do a SQL like:

`SELECT foo, sum(bar) as total_bar from table GROUP BY foo`

I can see`group_by` and `stats` but not sure if I can put the two together.

**Comment by nryberg** [comment]
I found this that works as expected: https://miller.readthedocs.io/en/6.7.0/10min/#sorts-and-stats

`mlr --icsv --opprint sort -f shape -nr index then head -n 1 -g shape example.csv`

**Comment by johnkerl** [comment]
@nryberg perhaps also `mlr stats1 -a sum -f bar -g foo`
