### ISSUE TITLE
Miller Fails To Join Identical Key With `--sorted-input`

### ISSUE THREAD

**Issue by Shooz136** [johnkerl/miller#1287]
I have two very simple CSV datasets.

test-1.csv
```
test_id,test_col
5,AVB2C6
6,AVATHL
18,AVB7IO
```

test-2.csv
```
test_id,join_val
5,JOINVAL1
6,JOINVAL2
18,JOINVAL3
```

If I run the following:
`mlr --csv join --sorted-input -j test_id --ul --ur -f test-1.csv then unsparsify --fill-with ""  test-2.csv` 

I receive the following, where `5` and `6` IDs are joined without issue, but `18` is not joined, and results in two records.

```
test_id,test_col,join_val
5,AVB2C6,JOINVAL1
6,AVATHL,JOINVAL2
18,,JOINVAL3
18,AVB7IO,
```
However, running `mlr --csv join -j test_id --ul --ur -f test-1.csv then unsparsify --fill-with ""  test-2.csv` results in a correctly joined dataset:
```
5,AVB2C6,JOINVAL1
6,AVATHL,JOINVAL2
18,AVB7IO,JOINVAL3
```

Am I misunderstanding how `--sorted-input` works?  I'm working with large datasets, and they *are* sorted, so I'd rather use that option if possible.

**Comment by Shooz136** [comment]
Ah - it's because `--sorted-input` expects lexical sorting, not numeric..   that `18` should be at the top of both files.
I can close this issue shortly, but I'm interested if there's any quick/easy flag or something I could set to allow numerical sorting?

**Comment by aborruso** [comment]
A stupid question @Shooz136 : do you need `--sorted-input`, because you have a left file which is too big to fit into system memory ?

**Comment by Shooz136** [comment]
@aborruso - Yep - both files will be quite large.

**Comment by johnkerl** [comment]
> but I'm interested if there's any quick/easy flag or something I could set to allow numerical sorting?

Sorry @Shooz136 , nothing quick or easy.

**Comment by Shooz136** [comment]
No worries! Appreciate you taking a look! Great utility, by the way!
