### ISSUE TITLE
Cannot access `help` command when alias set

### ISSUE THREAD

**Issue by archetyped** [johnkerl/miller#1290]
Miller's `help` command is no longer accessible when an alias is set for `mlr` to automatically load a library of functions (as [referenced in the docs](https://miller.readthedocs.io/en/latest/reference-dsl-user-defined-functions/#loading-a-library-of-functions)):

```bash
alias mlr='mlr --load ~/my-functions.mlr'
```

After that, it looks like Miller is interpreting `help` as a verb:

```bash
$ mlr help topics
mlr: verb "help" not found. Please use "mlr --help" for a list.
``` 
Any workarounds to keep the auto-loading alias, but also maintain access to Miller's `help` command? Already tried setting a separate alias for `mlr help` (e.g. `mlr-help`), but the `mlr` portion in that alias still appears to be expanded to the auto-loading alias, resulting the in the same error message as above. 😿

**Comment by johnkerl** [comment]
Yikes! :| 

OK, there should be a way to have `help` be found when it's not first on the command line. Maybe when it's the first verb-looking thing on the command line, after the command-line-parse step, but before the set-up-data-stream step. I can do that as a software mod.

Nearer-term, as a workaround, shells will generally accept a leading backslash -- e.g. if `alias rm='rm -i'`, then `\rm` is just the bare command without the `-i` aliases in. Or `/bin/rm`. So you can `\mlr help` or `/usr/local/bin/mlr help` (or wherever `mlr` is installed on your system), for the moment.

**Comment by archetyped** [comment]
Awesome, thanks for the tip 👍 `\mlr help` works!

**Comment by archetyped** [comment]
On a somewhat related note, where do flags such as `--always-color` go when using `mlr help` (e.g. when piping output to `less`)? For example, I see the `--help-color` flag in the docs, which seems like it should be used with `mlr help`, but I get no joy when trying to use flags in different positions:

```bash
$ mlr --always-color help topics
mlr: verb "help" not found. Please use "mlr --help" for a list.

$ mlr help topics --always-color
mlr help topics takes no additional argument.

$ mlr help --always-color topics
--always-color
Instructs Miller to colorize output even when it normally would not. Useful for piping output to `less -r`.
No help found for "topics". Please try 'mlr help find topics' for approximate match.
See also 'mlr help topics'.
```

Perhaps I'm missing something basic?

**Comment by johnkerl** [comment]
@archetyped try `mlr help flags` or `mlr help find --always-color`

There should be an option for `mlr help flags --always-color` -- current `mlr help flags` doesn't let you put anything after

**Comment by johnkerl** [comment]
Ahhh yes. :)

That needs fixing.

**Comment by johnkerl** [comment]
@archetyped as of #1292:

* `mlr --always-color help flags | less -r` produces colorized output
* `mlr --help-color seagreen1 help flags` works
* No need for `\mlr help` if `mlr` is aliased to `mlr --load ~/my-functions.mlr`
* `mlr help flag --always-color` exists

**Comment by archetyped** [comment]
Awesome, thanks!
