### ISSUE TITLE
clang support? / freebsd support?

### ISSUE THREAD

**Issue by jungle-boogie** [johnkerl/miller#13]
Hello,

How would I go about compiling your program with clang?

    clang -v
    FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
    Target: i386-unknown-freebsd10.2
    Thread model: posix
    Selected GCC installation:

Thanks,
Sean

**Comment by johnkerl** [comment]
I just used `make -e CCOMP=clang` in the `c/` subdirectory, on OSX anyway. (Also, notes to this effect at http://johnkerl.org/miller/doc/build.html.) Can you verify?

**Comment by jungle-boogie** [comment]
Hello,

    % make -e CCOMP=clang
    make -C dsls put_dsl_parse.o
    gcc -o lemon lemon.c
    make[1]: exec(gcc) failed (No such file or directory)
    *** Error code 1

    Stop.
    make[1]: stopped in /usr/home/sean/bin/miller/c/dsls
    *** Error code 1

    Stop.
    make: stopped in /usr/home/sean/bin/miller/

Is this too dependent on gcc to work?

**Comment by technion** [comment]
I edited c/Makefile and just changed CCOMP=gcc to CCOMP=clang.

Compiles with clang and runs all regression tests fine here.

**Comment by jungle-boogie** [comment]
Hi @technion,

What's your OS and clang version?

Thanks!

**Comment by jungle-boogie** [comment]
Hello,

If anyone is familiar with vagrant, here's the freebsd page for 10.2-release:
https://atlas.hashicorp.com/freebsd/boxes/FreeBSD-10.2-RELEASE

**Comment by technion** [comment]
I am running Arch Linux with clang version 3.6.2.

**Comment by jungle-boogie** [comment]
Unfortunately I have not made any more progress on installing miller.

**Comment by technion** [comment]
@jungle-boogie have you tried the change I referred to?

The error you pasted suggests your command line simply never passed the variable through (as was the case on my system, hence the edit).

**Comment by technion** [comment]
@jungle-boogie  See the patch I've just submitted. If you can confirm that resolves things for you I'll make a PR.

**Comment by jungle-boogie** [comment]
Hi @technion, @johnkerl,

I got further by first installing and then soft linking gcc from `/usr/local/bin/gcc48` to `/usr/local/bin/gcc`
but still fails:
https://gist.github.com/jungle-boogie/cf75244574102e9661e3

If I run `make -e CCOMP=clang`:
https://gist.github.com/jungle-boogie/334cf40130db8c410a03

Then I can run `./mlr`

Any idea why gcc is still required if I've told it in the Make file to use clang? Is it because of the `lemon.c` file? I'd rather not have to install a second compiler.

Thanks!

**Comment by technion** [comment]
I don't believe make -e is doing what we think it's supposed to do on all platforms. This is why I wrote the patch above. Can you please try it?

**Comment by jungle-boogie** [comment]
Hi @technion,

I tired your patch and the results:

    make -C dsls put_dsl_parse.o
    gcc -o lemon lemon.c
    make[1]: exec(gcc) failed (No such file or directory)
    *** Error code 1

    Stop.
    make[1]: stopped in /home/sean/bin/miller/c/dsls
    *** Error code 1

    Stop.
    make: stopped in /home/sean/bin/miller/c

the patch:

    vagrant@:~/bin/miller/c % head Makefile 
    # ================================================================
    CCOMP ?=gcc
    CFLAGS=-std=gnu99
    IFLAGS=-I.
    WFLAGS=-Wall -Werror
    LFLAGS=-lm

Does your arch system also happen to have any version of gcc installed?

**Comment by johnkerl** [comment]
Sorry, my mistake -- yes, the C compiler needs to be propagated to `c/dsls` as well as `c`, and so when I built with clang to test the mod, it was building in `c/dsls` with gcc and in `c/` with clang. :/

**Comment by jungle-boogie** [comment]
Hi @johnkerl,

So it stands that gcc is definitely a requirement? 

Thanks!

**Comment by johnkerl** [comment]
No, just that you have to spell clang rather than gcc in two different places.

**Comment by johnkerl** [comment]
Namely, `c/Makefile` as well as `c/dsls/Makefile`.

**Comment by jungle-boogie** [comment]
Hi @johnkerl,

You're getting further!

just some warnings when compiling: https://gist.github.com/jungle-boogie/3eac24667253560f344b

**Comment by technion** [comment]
Actually, I noted that c/dsls/Makefile has gcc hardcoded in several places, ignoring the use of the CCOMP variable altogether.

I've just pushed a further patch to my branch, can you try it out @jungle-boogie ?

**Comment by jungle-boogie** [comment]
Hi @technion,

That didn't work.  Your dsls/Makefile doesn't specify the ccompiler. 

See johnkerl's commit here: https://github.com/johnkerl/miller/commit/0b45ff3f5646dc0907efa419b0136e9d2893baea

The only problem now are the 9 warnings generated that I reported above.

**Comment by technion** [comment]
Sounds like a fix then - those warnings aren't related to clang support.

**Comment by johnkerl** [comment]
Created https://github.com/johnkerl/miller/issues/24 for those warnings (previously only a to-do at https://github.com/johnkerl/miller/blob/master/c/todo.txt).

Thanks for the report!

**Comment by jungle-boogie** [comment]
Hello @johnkerl, @technion,

Thank you both for stepping through this problem with me!

Best,
sean
