### ISSUE TITLE
Allow a command to start with then

### ISSUE THREAD

**Issue by sjackman** [johnkerl/miller#130]
I arrange my chained commands like so:
```sh
mlr --tsvlite \
  verb stuff \
  then verb stuff \
  then verb stuff
```
Stylistically it would be nice to write
```sh
mlr --tsvlite \
  then verb stuff \
  then verb stuff \
  then verb stuff
```
Just my two cents. Feel free to ignore if you disagree.

**Comment by johnkerl** [comment]
yeah this is nice. similar concept to allowing
```
y = f(
  abc,
  def,
  ghi,
)

**Comment by johnkerl** [comment]
(which is in 5.0.0)

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/commit/ba1e23dfe1ef193a5e5eb939431831ddab16ea15 will go into 5.0.0 -- thanks @sjackman !!

**Comment by sjackman** [comment]
Thanks!
