### ISSUE TITLE
ship ./configure

### ISSUE THREAD

**Issue by johnkerl** [johnkerl/miller#131]
Currently http://johnkerl.org/miller-releases/miller-5.0.0/doc/build.html#Building_from_source requires

```
autoreconf -fiv
./configure
make
make install
```

The first step can be avoided by shipping the `configure` scripts along with accompanying artifacts. But, the `clean` target also needs to be updated to not clobber them.

**Comment by Jared-Prime** [comment]
+1 I ran into this issue yesterday as the OS I was using at the time ( Fedora ) doesn't have the package available. I was unable to build from source as `autoreconf -fiv` wasn't happy on that particular OS either

**Comment by johnkerl** [comment]
OK. This whole autotools thing confuses me mightily (Miller's `./configure` support was added by the incomparable @0-wiz-0, not myself) but I have been making a habit of running `autoreconf -fiv` more often on commits, in particular on every release.

**Comment by aborruso** [comment]
> but I have been making a habit of running `autoreconf -fiv` more often on commits, in particular on every release.

I do it every time too

**Comment by johnkerl** [comment]
I should clarify, I am running it before commits and pushing it, hopefully so that others don't have to as often.

**Comment by 0-wiz-0** [comment]
So I think the autotools point-of-view is that developers (i.e. people using the git HEAD) can (and should) just run `autoreconf -fiv && ./configure`.
For the others, `make dist` will create a tarball that includes a usable `configure` script already.
(This file will need to be uploaded to the github for each release, github doesn't create such files for us, sadly.)
Does this help?

**Comment by johnkerl** [comment]
@0-wiz-0 it does -- thanks!! :)

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/commit/1349b8c963f9d23d74238ed734565738aa67fc93 clarifies the build-doc wording at http://johnkerl.org/miller-releases/miller-head/doc/build.html.

Thanks everyone for your patience!
