### ISSUE TITLE
Bug when replacing a dot

### ISSUE THREAD

**Issue by badrelmers** [johnkerl/miller#1310]
I have this csv:
```
a,b,c
1,1.2,3
```
when I run this from a batch file
```batch
mlr --csvlite  --from test.csv put '$b=ssub($b,".","0")'
```
I get
```
a,b,c
1,(error),3
```
I should get: `1,102,3`

I read the doc , I searched the old issues and searched google, but I could not find the solution, so maybe this is a bug? or am I doing something wrong? 

this was with the last miller version `miller-6.8.0-windows-386` on `windows 7 x64` using `cmd`

thank you

**Comment by aborruso** [comment]
@badrelmers you could force all to string using `-S`

```
mlr --csvlite -S  --from input.csv put '$b=ssub($b,".","0")'
```

**Comment by badrelmers** [comment]
oh! , the -S or string($b) solve it. miller rocks

thank you very very much @johnkerl @aborruso

**Comment by johnkerl** [comment]
Leaving this open so I can do the third bullet above ☝️
