### ISSUE TITLE
> But if the values is like "**0123456789**" it is presented in JSON output like `{"Key": 0123456789 }`. Which makes invalid JSON produced.

### ISSUE THREAD

**Issue by brandymiller-debug** [johnkerl/miller#1315]
> But if the values is like "**0123456789**" it is presented in JSON output like `{"Key": 0123456789 }`. Which makes invalid JSON produced.

Hi, I have used this sample input

```
fielda,fieldb
a,0123456789
```

and if I run `mlr --c2j cat t.csv` I do not have `{"Key": 0123456789 }`, but `{"Key": "0123456789" }`

```
[
{
  "fielda": "a",
  "fieldb": "0123456789"
}
]
```

I'm using `mlr 6.7.0`

_Originally posted by @aborruso in https://github.com/johnkerl/miller/issues/1293#issuecomment-1551790968_

**Comment by johnkerl** [comment]
spam
