### ISSUE TITLE
mlr nest --nested-fs doesn't work well with multi-character separators

### ISSUE THREAD

**Issue by yutannihilation** [johnkerl/miller#132]
Thanks for this great tool!

In my understanding, except for few cases, separators can be multi-character. But, are there any restriction on the separators for `nest`? I expected the both of these examples below returns 3 fields, but actually, the second one with `nest` returns 4 fields. Is this by design?

I'm sorry if I overlook some documented points. Thanks in advance!

```sh
$ echo 'a; b; c d' | mlr --ifs "; " --oxtab cat
1 a
2 b
3 c d
```

```sh
$ echo '{"value": "a; b; c d"}' | mlr --ijson --oxtab nest \
       --explode --values --across-fields --nested-fs "; " -f value
value_1 a
value_2 b
value_3 c
value_4 d
```

**Comment by johnkerl** [comment]
Yup, that's a bug. Sorry about that!!! I'll get on this quite soon. The fix will go out with the 5.1.0 release.

**Comment by yutannihilation** [comment]
Thanks! Looking forward to v5.1.0 :)

**Comment by johnkerl** [comment]
This is fixed in head. This weekend I'll go ahead and make a 5.0.1 bugfix release.

Thanks for letting me know! :)

**Comment by yutannihilation** [comment]
Sorry for replying late...

I've confirmed the problem is fixed at HEAD. Cool! Thanks for this quick fix 👍 

```sh
$ mlr --version
Miller 5.0.1
$ echo '{"value": "a; b; c d"}' | mlr --ijson --oxtab nest \
>        --explode --values --across-fields --nested-fs "; " -f value
value_1 a
value_2 b
value_3 c d
```

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/releases/tag/v5.0.1

Thanks!
