### ISSUE TITLE
Windows: add miller to winget

### ISSUE THREAD

**Issue by rursprung** [johnkerl/miller#1331]
since a while Microsoft has [a package manager for windows: winget](https://learn.microsoft.com/en-us/windows/package-manager/) and it's possible to add software software to their repository ([documentation](https://learn.microsoft.com/en-us/windows/package-manager/package/repository), [repo](https://github.com/microsoft/winget-pkgs)).

it'd be great if miller could be added there, so that it can be installed on any windows 10 & 11 system using `winget install miller`. this would lower the barrier for a windows installation (and the ability to keep it up to date) significantly (not everyone has choco installed and now that winget exists i don't see the point in using a 3rd party tool anymore which i'd first have to install).

alternatively you could also package it in the MS Store as winget can also install packages from there.

**Comment by aborruso** [comment]
Great idea @rursprung

**Comment by teo-tsirpanis** [comment]
A branch that adds a winget package for Miller is in https://github.com/teo-tsirpanis/winget-pkgs/tree/miller. @johnkerl let me know if you have any comments before I open a PR.

**Comment by johnkerl** [comment]
@teo-tsirpanis wow thank you!!!! This looks great to my eyes -- a PR would be fine -- thanks!

**Comment by aborruso** [comment]
Thank you very much @teo-tsirpanis

**Comment by teo-tsirpanis** [comment]
![image](https://github.com/johnkerl/miller/assets/12659251/49b89788-3195-47a9-a9e4-242243e41ff0)

**Comment by aborruso** [comment]
👏 applause
