### ISSUE TITLE
join: Emit an error if the input is not sorted [feature request]

### ISSUE THREAD

**Issue by sjackman** [johnkerl/miller#134]
`mlr` silently gives the wrong answer if the input is not sorted. An error message would be quite helpful. Alternatively, restart the join as though `mlr join -u` were specified, if it's possible to rewind the inputs (neither are pipes).

**Comment by johnkerl** [comment]
This is by design, to mimic the system `join` command.

Probably best thing to do is make `-u` the default.

**Comment by johnkerl** [comment]
... which I personally would not mind at all. And it wouldn't be backwards incompatible.

**Comment by sjackman** [comment]
I'm fine with making `-u` the default.

**Comment by johnkerl** [comment]
OK this done in head; will go out with next release. Thank you!! :)

**Comment by sjackman** [comment]
Thanks again, John!
