### ISSUE TITLE
`mlr --tsv  --opprint reshape` with multiple dataframes rather than one whole dataframe

### ISSUE THREAD

**Issue by NailouZhang** [johnkerl/miller#1344]
Hi, 
When I use `mlr --tsv  --opprint reshape -s Segment,SeqID  aaa.tsv` to do with my dataframes `aaa.txt`

```
Strain	Segment SeqID
1007	S	KP339095
1008	S	KP339096
1010	S	KP339097
1011	S	KP339098
1033	S	KP339099
1034	S	KP339100
1066	S	KP339101
1074	S	KP339102
10924	S	U43688
1198	S	KP339103
1207	S	KP339104
1210	S	KP339105
124	L	LN823982
1240	S	KP339106
1241	S	KP339107
1242	S	KP339108
1259	S	KP339109
127	L	LN823983
1276	S	KP339110
129	S	KP339050
1310	S	KP339111
132	L	LN823984
132	S	KP339051
139	L	LN823985
148	S	KP339052
1484	S	KP339112
1520	S	KP339113
153	S	KP339053
1549	S	KP339114
1575	S	AF371440
1583	S	AF371441
1586	S	KP339115
1591	S	KP339116
1605	S	KP339117
1606	S	KP339118
1657	S	AF371443
170	S	KP339054
1743	S	AF371444
1747	S	KP339120
1755	S	KP339121
1770	S	KP339122
1786	S	KP339123
1824	S	KP339124
1826	S	KP339125
1840	S	KP339126
185	S	KP339055
1858	S	KP339127
1873	S	KP339128
1878	S	KP339129
1881	S	AF371445
1892	S	KP339130
1895	S	AF371446
1918	S	KP339131
1925	S	KP339132
1946	S	KP339133
200401071	L	OK573224
200401071	S	OK573223
```

but I get something like 

```
Strain    L        S
WFB_Rpear MZ328244 MZ328245
WFS_she   MZ328246 MZ328247
WZ140510  KM051421 KM051423
WZ140512  KM051420 KM051422

Strain     S
Worogui 50 MH028400
Worogui 51 MH028401

Strain L        S
XJ     OK573208 U80009

Strain             S
XJ 44             U70803
XJ (Parodi strain) U70802
XJ44               AF264266
XJCl3              MG189700

Strain L        S
Y      MF276975 DQ118959
```

Could you be nice to help with this, just for convert long text to short text. Thanks forward!

**Comment by aborruso** [comment]
You must add [`unsparsify`](https://miller.readthedocs.io/en/6.8.0/reference-verbs/index.html#unsparsify) verb

```
mlrgo --tsv  reshape -s Segment,SeqID then unsparsify input.tsv
``` 

to get the below result.


| Strain | S | L |
| --- | --- | --- |
| 1007 | KP339095 |  |
| 1008 | KP339096 |  |
| 1010 | KP339097 |  |
| 1011 | KP339098 |  |
| 1033 | KP339099 |  |
| 1034 | KP339100 |  |
| 1066 | KP339101 |  |
| 1074 | KP339102 |  |
| 10924 | U43688 |  |
| 1198 | KP339103 |  |
| 1207 | KP339104 |  |
| 1210 | KP339105 |  |
| 124 |  | LN823982 |
| 1240 | KP339106 |  |
| 1241 | KP339107 |  |
| 1242 | KP339108 |  |
| 1259 | KP339109 |  |
| 127 |  | LN823983 |
| 1276 | KP339110 |  |
| 129 | KP339050 |  |
| 1310 | KP339111 |  |
| 132 | KP339051 | LN823984 |
| 139 |  | LN823985 |
| 148 | KP339052 |  |
| 1484 | KP339112 |  |
| 1520 | KP339113 |  |
| 153 | KP339053 |  |
| 1549 | KP339114 |  |
| 1575 | AF371440 |  |
| 1583 | AF371441 |  |
| 1586 | KP339115 |  |
| 1591 | KP339116 |  |
| 1605 | KP339117 |  |
| 1606 | KP339118 |  |
| 1657 | AF371443 |  |
| 170 | KP339054 |  |
| 1743 | AF371444 |  |
| 1747 | KP339120 |  |
| 1755 | KP339121 |  |
| 1770 | KP339122 |  |
| 1786 | KP339123 |  |
| 1824 | KP339124 |  |
| 1826 | KP339125 |  |
| 1840 | KP339126 |  |
| 185 | KP339055 |  |
| 1858 | KP339127 |  |
| 1873 | KP339128 |  |
| 1878 | KP339129 |  |
| 1881 | AF371445 |  |
| 1892 | KP339130 |  |
| 1895 | AF371446 |  |
| 1918 | KP339131 |  |
| 1925 | KP339132 |  |
| 1946 | KP339133 |  |
| 200401071 | OK573223 | OK573224 |

**Comment by johnkerl** [comment]
@NailouZhang , @aborruso is correct -- I came here to suggest adding `then unsparsify` but @aborruso said the same thing :)

Related: https://github.com/johnkerl/miller/issues/275

**Comment by aborruso** [comment]
> Related: #275

@johnkerl thank you for pointing to this. I'm repetitive, but if the output is tsv or csv, the user who has never used miller and who hasn't read the documentation doesn't expect that output.
Because these are two rectangular formats, they have no other shapes.

**Comment by johnkerl** [comment]
@aborruso agreed. And, `sparsify` is non-streaming which I don't like -- Miller is fine by default with larger-than-RAM files, and adding `unsparsify` by default would break that.

It is a hard trade.

**Comment by NailouZhang** [comment]
Thanks!
