### ISSUE TITLE
JSON output doesn't escape newlines or tabs or control chars in strings

### ISSUE THREAD

**Issue by selassid** [johnkerl/miller#135]
Similar to #115, on v5.0.0:

```
$ mlr --json cat <<< '{"a": "first\tline\nsecond line"}'
{ "a": "first   line
second line" }
```

Would expect:

```
{ "a": "first\tline\nsecond line" }
```

[Looking around](http://stackoverflow.com/questions/3020094/how-should-i-escape-strings-in-json), although I haven't needed it myself, other control chars need to be escaped too to output valid JSON.

Thanks for all your work!

**Comment by johnkerl** [comment]
Awesome thanks!!

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/commit/1a4886f775e774e7d40481a1365b4c12c85b3c36

```
$ mlr --json cat <<< '{"a": "first\tline\nsecond line"}'
{ "a": "first\tline\nsecond line" }
```

Thanks again!!
