### ISSUE TITLE
Small typos in documentation of `mlr nest`

### ISSUE THREAD

**Issue by kusalananda** [johnkerl/miller#1350]
The documentation for the `nest` operation says:
```none
  --evar {string}       Shorthand for --explode --values ---across-records --nested-fs {string}
  --ivar {string}       Shorthand for --implode --values ---across-records --nested-fs {string}
```

Notice the triple dashes in front of `across-records` (these should be double dashes).

Found in output of `mlr help nest` from Miller version `mlr version 6.8.0-dev for openbsd/amd64/go1.20.1`.

**Comment by johnkerl** [comment]
Thank you @kusalananda !
