### ISSUE TITLE
Right join field names do not default to output join field names

### ISSUE THREAD

**Issue by selassid** [johnkerl/miller#136]
The help text for `-r` says it defaults to `-j`, but [the code has it defaulting](https://github.com/johnkerl/miller/blob/e64ef977dcc85b55f33823eb2aca4e73334796aa/c/mapping/mapper_join.c#L265) to `-l`.

This means if you only specify `-j` and `-l`, the right files won't be read using the correct join field.

**Comment by johnkerl** [comment]
crap, my bad. i'll get on it. thanks!!

**Comment by johnkerl** [comment]
I'd thought I'd tested for this case, but to my unpleasant surprise, I had not. In any case, https://github.com/johnkerl/miller/commit/7d6bfcf049890a40fbc78b08aaaa767ff6c6d3c5 fixes the bug as well as testing for it.

Thanks for the heads-up!!!!!!!!!!!!!

**Comment by johnkerl** [comment]
This will go out in 5.1.0 (real soon now).
