### ISSUE TITLE
feature request: add global and regex option to sub, gsub, and ssub verbs

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#1384]
Hi,
it would be great to have `-g` option, to run search and replace in all fields.

And also to have something like `-r` to choose field names by regex.

Thank you

**Comment by johnkerl** [comment]
Or maybe `-a` for `all`

**Comment by johnkerl** [comment]
CC @sloanlance , re your earlier question about issues to help out with, if you're still interested -- this would be a great example.

**Comment by aborruso** [comment]
I have added the regex option to this request.

**Comment by aborruso** [comment]
@johnkerl this is a gem, thank you very much!!
