### ISSUE TITLE
Feature Request: Move functional code outside internal

### ISSUE THREAD

**Issue by mirusky** [johnkerl/miller#1386]
I'd like to use some code that you guys made, instead of copy/paste on my project. 

But since the project uses [internal folder](https://go.dev/doc/go1.4#internalpackages) I can't import things directly in my project, can you guys consider to move the functional code to outside ? 

Maybe it was a decision to reduce user surface but it can open the development of new tools and functionalities.

**Comment by johnkerl** [comment]
@mirusky thanks!

Moving to `internal` was part of my attempt to learn more about current standards in Go packages/modules ... I have a lot more to learn there. :)

One question is what I _should_ call the non-internal directory -- I can look that up on Google.

Another question is what you would find most useful in your project -- i.e. which modules might I move from `internal/` to `newnamegoeshere/`?

**Comment by johnkerl** [comment]
Oh wait! Maybe I already know how to do this :)

I have a little package called `lumin` and it has some code in `internal/pkg/`, and some in just `pkg/`.

And I use this in Miler:

* https://github.com/johnkerl/miller/blob/2b77328b0fa34e0eb0c8e4897988833ee2a14b9e/go.mod#L21
* https://github.com/johnkerl/miller/blob/2b77328b0fa34e0eb0c8e4897988833ee2a14b9e/internal/pkg/colorizer/colorizer.go#L14

So! I guess this just leaves me to ask: what would you find most useful to move from `internal/pkg/` to `pkg/`?

**Comment by mirusky** [comment]
As I know if u have any folder called internal at any level it will be not be public. 

> What I should call the non-internal directory?
I like the `pkg` and `internal` folder structure, the pkg to public code and internal to things that aren't. 

>  What you would find most useful in your project?
transformations, sorts, aggregates are the most useful things that I use.

My project is a analytical tool and dataload (to database or json based APIs). So transformations are the wheels, I wrote some things by myself but there's mature solutions like your's that I would love to use as backbones.

**Comment by johnkerl** [comment]
> So! I guess this just leaves me to ask: what would you find most useful to move from internal/pkg/ to pkg/?

> transformations, sorts, aggregates are the most useful things that I use.

@mirusky #1391 will be merged soon.

I wanted to only move more library-ish things to `pkg` and leave more purely-Miller things like CLI-parsing in `internal/pkg`. But even the record-readers depend on options structs, which are (bad factoring on my part) in the `cli` package, so I just gave up and moved all of `internal/pkg` to `pkg/`.

At https://miller.readthedocs.io/en/main/miller-as-library (which readthedocs should generate in a few minutes) there is an example you can try out ... please let me know how it works ...

This is a brand-new request and I'm happy to comply. There's no reason not to share Miller library code -- do note the no-backward-compatibility-guarantee at the API level in that doc page. And also some things may seem weird -- so do keep in touch and let me know if there are other changes we can make. I'm happy to accommodate reasonable requests, and more developer-level feedback may improve the quality of the API for Miller's own benefit, so I think everybody will win. :)

I think I will make this 6.9.1 which will make your `go get` simpler to articulate.

**Comment by johnkerl** [comment]
> And also some things may seem weird -- so do keep in touch and let me know if there are other changes we can make.

In particular, for the Miller CLI itself I had no need for a simple read-record and transform-record that don't use channels. (And channels were necessary for performance.) But for API use I think it would be natural to want such methods. Coincidentally, the write-record method is simple already. :)

**Comment by johnkerl** [comment]
... nevermind, I think #1392 may suffice. Anyway, please let me know if not.

**Comment by mirusky** [comment]
Hi @johnkerl I was pretty busy these weeks, but I had a look at the code and it's seens good. 

Also nice work with the documentation, the second one looks like what I need. I'll start to using it ASAP and if I have any futher question I'll let you know. 

I think we can close it as you already merged.
