### ISSUE TITLE
Miller 6 and flatten

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#1388]
I have been using miller for some time and for this reason I have installed both versions 5 and 6, because I need to be sure that my old scripts will work.
In my machine version 6 is called "mlrgo" and version 5 is "mlr".

Some problems are related to flatten verb

This is a sample input file

```
{
  "CODICE": [
    "1",
    "3",
    "4"
  ],
  "NUM_PART": [
    "00001/",
    "00003/",
    "00004/"
  ],
  "NODISPLAY": [
    "0",
    "0",
    "0"
  ]
}
```

In Miller 5 if I run `<tmp.json mlr --j2c unsparsify then reshape -r ":" -o item,value` I get

```
item,value
CODICE:0,1
CODICE:1,3
CODICE:2,4
NUM_PART:0,00001/
NUM_PART:1,00003/
NUM_PART:2,00004/
NODISPLAY:0,0
NODISPLAY:1,0
NODISPLAY:2,0
```

In Miller 6 if I run `<tmp.json mlrgo --j2c unsparsify then reshape -r "." -o item,value`, I get

```
item,value.1,value.2,value.3
CODICE,1,3,4
NUM_PART,00001/,00003/,00004/
NODISPLAY,0,0,0
```

I must flatten it, to have the same result of Miller 5 (that is what I need) `<tmp.json mlrgo --j2c unsparsify then flatten then reshape -r "." -o item,value`.

Ok, I must change my old scripts pay attention to `--flatsep` and `flatten` verb and my old scripts will work. 
But one thing that confuses me is the `stdout`: if I run `<tmp.json mlrgo --j2c unsparsify` or if I add `flatten`  `<tmp.json mlrgo --j2c unsparsify then flatten`, I have the same `stdout`.
As if what is passed to `stdout` is different from what is passed to the next verb via `then`.

I think it's intentional, but I wanted to understand a little better if it's correct and why it works in this way.

Thank you

**Comment by johnkerl** [comment]
@aborruso an implicit `then flatten` is added for you unless you specify `--no-auto-flatten`.

Details are here: https://miller.readthedocs.io/en/latest/flatten-unflatten/

This is messy, I know. Miller tries hard to do the most obvious thing, by default, while supporting various file formats -- in particular, when the input, output, both, or neither may be JSON. There is no single best solution; what I did for Miller 6 was very much a compromise; and it's one of the things that resulted in a lot of work to make Miller 6 happen at all. See also https://miller.readthedocs.io/en/latest/new-in-miller-6/#data-processing ...

**Comment by aborruso** [comment]
Thank you
