### ISSUE TITLE
Output encoding problem in Powershell 7.3.6 on Windows 11

### ISSUE THREAD

**Issue by kczyk** [johnkerl/miller#1389]
Given this example CSV file:

```csv
A;B;C
AĄCĆEĘLŁNŃOÓSŚZŻŹ;123456;To jest przykładowy tekst
```

When I run `mlr --no-color --icsv --ifs semicolon --ojsonl cat '.\foo-input.csv'` in Windows Terminal with Powershell 7.3.6, where `foo-input.csv` is our sample file, I get the following correct output:

```
{"A": "AĄCĆEĘLŁNŃOÓSŚZŻŹ", "B": 123456, "C": "To jest przykładowy tekst"}
```

But when I run this command in subshell `(mlr --no-color --icsv --ifs semicolon --ojsonl cat '.\foo-input.csv')` or redirect output to file `... >  file` I get:

```
{"A": "A─äC─ćE─śL┼üN┼âO├ôS┼ÜZ┼╗┼╣", "B": 123456, "C": "To jest przyk┼éadowy tekst"}
```

No problem if I run the same command and redirect to a file in `cmd.exe`.

What could be causing this behavior?

**Comment by johnkerl** [comment]
@kczyk what is your `mlr --version` output?

**Comment by kczyk** [comment]
@johnkerl 

```
> mlr --version
mlr 6.9.0
```

**Comment by kczyk** [comment]
Ok, so I discovered that `mlr` is not to blame here. `jq` has the same problem. This is all because of PowerShell. The solution:

```powershell
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8 # <-- This is required. Normally it's not set to UTF-8.

$output = mlr --no-color --icsv --ifs semicolon --ojsonl cat ".\testfile.csv"
$output # Displays correct, non-malformed output.
```

I recommend this very good SO comment on why: https://stackoverflow.com/a/35980675/1287288

> On receiving data from an external program, PowerShell uses the encoding stored in [Console]::OutputEncoding to decode the data, which in both PowerShell editions defaults to the system's active OEM code page.
