### ISSUE TITLE
Numbering output records after count-distinct

### ISSUE THREAD

**Issue by dusko** [johnkerl/miller#139]
I using `mlr` daily and it helps me a lot, but now I struggling with trivial task. After applying verbs like `stats`, `count-distinct` etc. I would like to numbering output records as 1,2,3...N. Use of built-in variable `NR` doesn't help me here as it contains total number of input records and this behavior is correct.

For example:
```
mlr count-distinct -f a,b then sort -nr count then put '$No = NR' data/medium
a=zee,b=wye,count=455,No=10000
a=pan,b=eks,count=429,No=10000
a=pan,b=pan,count=427,No=10000
a=wye,b=hat,count=426,No=10000
a=hat,b=wye,count=423,No=10000
.....
```
I would like that variable `No` will hold the sequence 1,2,3...N like:
```
a=zee,b=wye,count=455,No=1
a=pan,b=eks,count=429,No=2
a=pan,b=pan,count=427,No=3
a=wye,b=hat,count=426,No=4
a=hat,b=wye,count=423,No=5
....
```
thanks,
Dusan

**Comment by johnkerl** [comment]
`mlr --your-flags ... then cat -n`

**Comment by johnkerl** [comment]
See also

http://johnkerl.org/miller-releases/miller-5.1.0/doc/cookbook.html#Numbering_and_renumbering_records

**Comment by dusko** [comment]
Thank you very much John! That's what I've looking for.
Dusan.

**Comment by johnkerl** [comment]
Happy to help! :)
