### ISSUE TITLE
Median (p_50) for even number of data points

### ISSUE THREAD

**Issue by ve3ied** [johnkerl/miller#14]
Minor issue on a terrific tool btw.  Thanks!

Median is usually defined as the average of two midpoints with an even number of data points.  P_50 isn't working that way at the moment..

**Comment by johnkerl** [comment]
Good call. Yeah, I thought about that ... my personal point of view is I want quantiles to always produce a value taken from somewhere in the input. In particular, all-integer input data should lead to all-integer output data. But this personal preference may not be what most people want. Another issue is, how to handle non-exact quantiles in the general case besides just p50 -- e.g. what would be p99 if there are 23 data points? Anyway, let me think about it a bit & get back to you.

Thanks for the issue!

**Comment by ve3ied** [comment]
I agree with you for the other quantiles.  It would be impractical.  Stats books suggest only median is handled that way.  Best of both worlds would be, keep p_50 the way it is and have a separate median?  I'll see what R does..

**Comment by ve3ied** [comment]
I'm not sure that I agree with what R does, but there you go..

> x <- c(10,20,30,40)
> summary(x)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   10.0    17.5    25.0    25.0    32.5    40.0 
> quantile(x,probs=c(0.5,0.75,0.9))
 50%  75%  90% 
25.0 32.5 37.0 
>

**Comment by johnkerl** [comment]
Marking as wishlist for now, just relative to other things more pressing -- namely, RFC-CSV and packaging. In the medium term, though, this will be a should-do rather than a wishlist item.

What I think we should do is have two modes: one for as now, where all quantile output are data points, and another in which everything is linearly interpolated. Which one is the default, I don't have strong opinions about.

**Comment by johnkerl** [comment]
Interpolated percentiles will be in Miller 4.3.0. Non-interpolated are like R's type=1; interpolated are like R's type=7.

https://github.com/johnkerl/miller/commit/721bd51484abd7d855486f3b22a364104b837e06
