### ISSUE TITLE
Columns with . (dot or period) are not evaluated 

### ISSUE THREAD

**Issue by pshempel** [johnkerl/miller#140]
cat a.csv 
a,b,c,a.os
1,2,2,os-win
1,2,9,os-blah
2,3,4,os-linux

mlr  --csv filter '( $a.os == "os-win" ) || ($a.os == "os-blah")' a.csv

This should produce the output of 

a,b,c,a.os
1,2,2,os-win
1,2,9,os-blah

This is critical to be used via mlr, the lines in the data that we have use full carriage returns within a line, causing a separate line for some rows. The data is actually quoted within the line change.
With grep will give unexpected results, being grep is looking for lines and not data rows, and as such tools like  mlr are born to deal with this form of data.
Not sure if this is a bug or I do not know how to "escape" the period being used in my search

**Comment by johnkerl** [comment]
Try curly braces:

```
$ echo 'x.a=1,y.b=2' | mlr put '${z.c}=${x.a}+${y.b}'
x.a=1,y.b=2,z.c=3
```

**Comment by johnkerl** [comment]
I'll make an FAQ entry for this

**Comment by johnkerl** [comment]
http://johnkerl.org/miller-releases/miller-head/doc/faq.html#How_can_I_handle_field_names_with_special_symbols_in_them?
