### ISSUE TITLE
Contact Conda folks to get 6.9.0 set up

### ISSUE THREAD

**Issue by johnkerl** [johnkerl/miller#1408]
https://github.com/johnkerl/miller/releases/tag/v6.9.0
https://anaconda.org/conda-forge/miller/labels
https://github.com/conda-forge/miller-feedstock/pull/22
https://github.com/BEFH/miller-feedstock

cc @BEFH, may know a good point of contact

**Comment by BEFH** [comment]
I merged the commit, but I see it's not on conda-forge. Maybe the build is failing?

**Comment by BEFH** [comment]
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=772817&view=results

There's an error there that I need to figure out.

**Comment by BEFH** [comment]
https://github.com/conda-forge/conda-smithy/issues/1784

**Comment by johnkerl** [comment]
@mikael-s thanks to some fine people including @BEFH we now have Miller 6.9.0 in Conda:
https://anaconda.org/conda-forge/miller/labels
🎉
