### ISSUE TITLE
Order of columns cut or out of order from the request "cut -f a,d,c"

### ISSUE THREAD

**Issue by pshempel** [johnkerl/miller#141]
cat a.csv
a,b,c,d
1,2,3,4

mlr --csv  cut -f  a,d,c a.csv

output should be columns representing the order given in cut 
but you get the order in the original csv

This is what you get
a,c,d 
1,3,4

I would expect the output to be, as used with the cut 
a,d,c
1,4,3

The tools used at this time do not care about the column names, this is a positional csv that is processed after having been created from mlr.

Not sure, is this an expected way of the output from mlr or a bug?

**Comment by johnkerl** [comment]
Try `cut -o`

http://johnkerl.org/miller-releases/miller-5.1.0/doc/faq.html#Why_doesn%E2%80%99t_mlr_cut_put_fields_in_the_order_I_want?
