### ISSUE TITLE
Add a `--files` option

### ISSUE THREAD

**Issue by johnkerl** [johnkerl/miller#1422]
The user would supply one file name per line like

`cat filenames.txt`
```
file0001.csv
file0002.csv
...
file8956.csv
```

Then they could run `mlr --files filenames.txt ...`

_Originally posted by @derekmahar in https://github.com/johnkerl/miller/discussions/1421_

**Comment by derekmahar** [comment]
Thank you!

**Comment by aborruso** [comment]
Thank you

**Comment by janxkoci** [comment]
Just curious, does it do the same thing as the following code?

```
mlr --mfrom $(cat filenames.txt) --
```

**Comment by johnkerl** [comment]
@janxkoci yes. With the exception that if `filenames.txt` is very long, putting them all on the command line via interpolation can result in an error from the shell saying the argument list is too long. Whereas `mlr --files` will step through `filenames.txt` successfully without hitting that limit.

**Comment by janxkoci** [comment]
I see, cool!
