### ISSUE TITLE
JSONL output does not properly handle keys with quotes

### ISSUE THREAD

**Issue by kusalananda** [johnkerl/miller#1424]
I wanted to convert header-less CSV input into a single JSON object by using the 1st field as the key name and the 2nd field as the value for the corresponding field.

Using JSON output, I get the correct output, but in an array:
```shell
$ echo '"key with ""quote""","value with ""quote"""' | mlr --c2j -N put '$[$1]=$2' then cut -x -f 1,2
[
{
  "key with \"quote\"": "value with \"quote\""
}
]
```

Switching to JSONL output seems to break the quoting of the key, but handles the value correctly:
```shell
$ echo '"key with ""quote""","value with ""quote"""' | mlr --c2l -N put '$[$1]=$2' then cut -x -f 1,2
{"key with "quote"": "value with \"quote\""}
```

I'm using `mlr version 6.9.0 for openbsd/amd64/go1.21.1`.

**Comment by johnkerl** [comment]
@kusalananda thank you for the bug report! :)
