### ISSUE TITLE
Test failure on 32-bit big-endian platforms

### ISSUE THREAD

**Issue by skitt** [johnkerl/miller#143]
Hi John,

On mips and powerpc, we’re getting test failures: in the `SUBSTR` test, `fmtnum(i, "%3d")` is called and ends up interpreting `i` as a `long long` instead of an `int`. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=865317 has the details.

Regards,

Stephen

**Comment by johnkerl** [comment]
Thanks, @skitt. Fixed in https://github.com/johnkerl/miller/commit/b0cf354b34a2c55c4233bf8e2fcc2dacb320874d. However, of course, I had (and have) mixed feeling about exposing `sprintf` format strings in userspace. :^/

Do you need a bugfix release cut?

**Comment by skitt** [comment]
Thanks! No need for a bugfix release, I’ve pulled in the fix for the Debian package.

**Comment by skitt** [comment]
Unfortunately other tests break as a result of this change, see https://buildd.debian.org/status/fetch.php?pkg=miller&arch=mips&ver=5.2.1-2&stamp=1498209124&raw=0

**Comment by johnkerl** [comment]
@skitt my apologies for the incomplete fix: please see https://github.com/johnkerl/miller/commit/13b3de0c0124c7a8427a871861e73e3ee522c785

Also: https://github.com/johnkerl/miller/issues/145

**Comment by skitt** [comment]
Thanks, with both patches applied the tests pass.
