### ISSUE TITLE
Cannot rename field names generated via splita containing the dot character

### ISSUE THREAD

**Issue by NikosAlexandris** [johnkerl/miller#1437]
I cannot rename fields generated after using `splita()`, who indeed contain the `.` character.  Following a _mixed_ example to demonstrate the weirdness : 

``` bash
echo api.1=v5_2/seriescalc | mlr put '$tools = splita(${api.1}, "/")' then rename api.1,API.1,tools.1,Tools.1
```

returns

``` bash
API.1=v5_2/seriescalc,tools.1=v5_2,tools.2=seriescalc
```

Is this some unusual case related to something in my system, or indeed a 'bug' ?

**Comment by johnkerl** [comment]
@NikosAlexandris indeed -- what _comes out at the end_ as `tools.1` and `tools.2` are -- _during processing_ -- a single array-valued attribute named `tools` with indices `[1]` and `[2]`.

I'm glad you got it worked out, but, this surfaces another issue, which is confusing -- as I noted above. See also here:
https://miller.readthedocs.io/en/latest/flatten-unflatten/#manual-control

Miller is trying to do an intuitive thing by default, given file formats with very different semantics, as discussed here:
https://miller.readthedocs.io/en/latest/new-in-miller-6/#improved-json-json-lines-support-and-arrays

Also related: #1062 ...

**Comment by NikosAlexandris** [comment]
I didn't understand that I can also do this with [`flatten`](https://miller.readthedocs.io/en/latest/reference-verbs/#flatten)! The command 
``` bash
echo api.1=v5_2/seriescalc | mlr put '$tools = splita(${api.1}, "/")' then flatten then rename tools.1,Tools_1
```
which gives what I was asking for
```
api.1=v5_2/seriescalc,Tools_1=v5_2,tools.2=seriescalc
```
is more _readable_, I find, albeit it hides away the _real work_ done.

Allow me to mention that what helped _me_ get-going, was actually the following : 

``` bash
echo api.1=v5_2/seriescalc | mlr --ips '/' cat
echo api.1=v5_2/seriescalc | mlr --ips '=' cat
echo api.1=v5_2/seriescalc | mlr --ips '.' cat
```
and their output
```
api.1=v5_2=seriescalc
api.1=v5_2/seriescalc
api=1=v5_2/seriescalc
```

At this point I _realised_ that I did not get all this right in the beginning.  Maybe a link to IPS would help to _connect the dots_ faster ?

I thought about it @johnkerl before, and I was between:
- I should mention that this can be better documented, in particular right there in the description/help.
- I should invest more time to better study the tools and the context

I feel that more _legible_ (as in style, format, appearance) and more examples (as in number of examples) would help.

This

> `splita`  (`class`=conversion #`args`=2) Splits string into [_array_](https://miller.readthedocs.io/en/latest/reference-main-arrays/) with type inference. First argument is _string_ to split; second is the _separator_ to split on.
>
>Examples:
>`splita("3,4,5", ",")` = `[3,4,5]`
>`splita("v5_2/seriescalc", "/")` =` [v5_2,seriescalc]`
>
>Note:
> The default pair separator is `=` -- it separates the key from the value within each key-value pair.
>
>See also:
>- the [Arrays](https://miller.readthedocs.io/en/latest/reference-main-arrays/) page.
>- the [Separators](https://miller.readthedocs.io/en/latest/reference-main-separators/) page.

is maybe better than 

```
splita  (class=conversion #args=2) Splits string into array with type inference. First argument is string to split; second is the separator to split on.
Example:
splita("3,4,5", ",") = [3,4,5]
```
?
