### ISSUE TITLE
`mlr remove-empty-columns` issue with barred PPRINT input and leading spaces

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#1438]
Hi,
I have this no sense input file

```
|Number|Country|Continent|Capital City| 
|1|Portugal|Europe|Lisbon| 
|2|India|Asia|New Delhi|
|3|Egypt|Africa|Cairo|
|4|Canada|America|Ottawa| 
|5|Turkey|Asia&Europe|Ankara|
```

If I run

```
mlr --c2p --barred --ifs "|" remove-empty-columns input.txt
```

I get an empty column in the result

```
+--------+----------+-------------+--------------+---+
| Number | Country  | Continent   | Capital City |   |
+--------+----------+-------------+--------------+---+
| 1      | Portugal | Europe      | Lisbon       |   |
| 2      | India    | Asia        | New Delhi    |   |
| 3      | Egypt    | Africa      | Cairo        |   |
| 4      | Canada   | America     | Ottawa       |   |
| 5      | Turkey   | Asia&Europe | Ankara       |   |
+--------+----------+-------------+--------------+---+
```

**Comment by aborruso** [comment]
@johnkerl what do you think about this? Am I making some errors?

Thank you

**Comment by johnkerl** [comment]
@aborruso sorry for the delay -- I'll update soon.

The issue is there are trailing spaces at the end of some input lines, which Miller should be ignoring.

**Comment by johnkerl** [comment]
@aborruso another issue is that using CSV with `ifs="|"` for barred input is a little weird -- in CSV, the separators are _between_ names, like `a,b,c`, whereas with barred input, they also go _around_ names, like `|a|b|c|`. That results in the _creation_ of empty columns which you need to use `remove-empty-columns` to strip. If there were a better way to read barred input, Miller wouldn't be inserting those empty columns that you need to take right back out again ... 🤔

**Comment by johnkerl** [comment]
Also, `--barred` was a misnomer -- I should have called it `--barred-output` or `--barred-pprint-output` or somesuch to make it clear it only applies to output, and only using the PPRINT output format.

**Comment by aborruso** [comment]
Thank you very much @johnkerl I didn't see those characters at the end of the line.

In fact, this is how it works well

```
mlr --c2p --barred --ifs "|" clean-whitespace then remove-empty-columns input.txt
```

I would be to close the issue and sorry for the confusion

**Comment by johnkerl** [comment]
Nice, `clean-whitespace` to the rescue :)
