### ISSUE TITLE
`mlr join` feature request: if `--lk` is empty keep all left fields

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#1439]
Hi @johnkerl ,
a lot of time I use join only to filter one input file. It could be the left one.
I am not interested in carrying anything from the right file, but just using it as a filter.

In SQL is the classic

```sql
SELECT staff-department.*
FROM staff-department
JOIN staff-info ON staff-department.id = staff-info.id;
```

What about adding it to `join` verb?

It could be the `--lk`: if it is empty keep all left fields.
This way I will not be forced to write down the names of the fields I want to keep.

Thank you

**Comment by johnkerl** [comment]
@aborruso I believe this already exists -- ?

```
$ cat a.csv
N,S,T,U
1,a,b,c
2,d,e,f
3,g,h,i

$ cat b.csv
N,X,Y,Z
1,l,m,n
2,o,p,q
3,r,s,t

$ mlr --csv join -j N -f a.csv b.csv
N,S,T,U,X,Y,Z
1,a,b,c,l,m,n
2,d,e,f,o,p,q
3,g,h,i,r,s,t

$ mlr --csv join -j N --lk N -f a.csv b.csv
N,X,Y,Z
1,l,m,n
2,o,p,q
3,r,s,t

$ mlr --csv join -j N --lk "" -f a.csv b.csv
N,X,Y,Z
1,l,m,n
2,o,p,q
3,r,s,t
```

**Comment by johnkerl** [comment]
@aborruso I'll add a note to the online help for `mlr join`

**Comment by aborruso** [comment]
> @aborruso I'll add a note to the online help for `mlr join`

These last few issues of mine were all wrong, sorry.

But please add it, because I had no idea that if no field indicated, only the left ones would remain. 
I had not even tested it, because I had taken the documentation literally.

Thank you very much
