### ISSUE TITLE
mlr: record has too many input fields named 'y'

### ISSUE THREAD

**Issue by OpenFoam-User** [johnkerl/miller#1462]
Hello,
I am trying to process a file with a large number of columns. Particulary, I have 1100 columns named 'y' but when I pipe the file to miller, I get the error message:

```
mlr: record has too many input fields named 'y'
```

I have checked the source code and found the line. It seems that the limit is hardcoded to be 1000 only. 

https://github.com/johnkerl/miller/blob/e3b98cd62188cd67e93dcaa0925c0876f461daa9/pkg/mlrval/mlrmap_accessors.go#L77-L85

Is there a reason to limit the number to 1000? In future I expect to have files with at least 50k columns with the same name, and I really rely on miller to automatically rename them, `y`, `y_1`, `y_2`, .....

Could you please increase the limit?

Thank you very much

**Comment by johnkerl** [comment]
@OpenFoam-User the break at 1000 was intended to be a fail-safe, circuit-breaker kind of thing, intended to be a buffer far beyond any reasonable behavior. ;)

... however, your behavior is quite reasonable ...

and my caution was overmuch. There is no risk of infinite-looping; the number of fields is naturally bounded by the data in the input files.

I'll remove the limit.

**Comment by OpenFoam-User** [comment]
Dear @johnkerl 
Many thanks for the update :)
