### ISSUE TITLE
system: not able to escape single quote

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#1489]
Hy @johnkerl, 
I want to answer to [this question](https://github.com/johnkerl/miller/discussions/1488), but I'm not able to use properly system function.

I want to replicate this, to start from `1234567` and to get `1,234,567`

```
a=1234567
printf "%'d\n" $a
```

In Miller I would use this

```
echo a=1234567 | mlr --oxtab put '$b=system("printf \"%'d\n\" ".$a)'
```

but I'm not able to escape properly the `'` in `printf`.

I have tried using `'\''`, but it does not work.

Thank you

**Comment by aborruso** [comment]
I think I cannot do it using `fmtnum`, but in any case I'd like to know how to escape my example above.

**Comment by johnkerl** [comment]
@aborruso quoting and escaping with the shell is always tricky.

https://miller.readthedocs.io/en/latest/special-symbols-and-formatting touches on this a bit

In this case I would do:

```
$ cat commas.mlr
$b = system("printf \"%'d\n\" ".$a)
```

```
$ echo a=1234567 | mlr --oxtab put -f commas.mlr
a 1234567
b 1,234,567
```

**Comment by aborruso** [comment]
@johnkerl thank you.

Two things.  

## The first

I have created thsi input file

```
id,a
1,568689
2,28797986
```

and I have

```
cat commas.mlr
$b = system("printf \"%'d\n\" ".$a
```

If I run `mlr --csv put -f commas.mlr input.csv` I have

```
id,a,b
1,568689,(error)
2,28797986,(error)
```

And if I run `echo a=1234567 | mlr --oxtab put -f commas.mlr` I have

```
sh: 1: printf: %': invalid directive
a 1234567
b
```

## The second

Ok, if I created a `.mlr` it is easier. But I think it should a one-liner inconvenient way to do it. In the documentation I have "The pieces are the following, all concatenated together", and then I try to concatenate all:

- `"printf \"%`
- `'\''`
- `d\n\" `

```
echo a=5637875 | mlr --oxtab put '$b=system("printf \"%"."'\''"."d\n\" ".$a)'
```

And I have again 

```
sh: 1: printf: %': invalid directive
a 5637875
b
```

Do I must escape in some way the `%`?

Thank you

**Comment by johnkerl** [comment]
@aborruso I also generally prefer one-liners, all else being equal ...

But escaping all the `'` and `"` at the shell is a perpetual source of confusion (not just for Miller!) and in this case I do recommend use of a `.mlr` file in order to get around the difficult shell-escaping issue.

**Comment by aborruso** [comment]
Thank you John but I'm not able to make it work, in both ways 😕

**Comment by johnkerl** [comment]
```
sh: 1: printf: %': invalid directive
```

sounds like a shell issue

Can you please try this?

```
$ /bin/sh

$ printf "%'d" 123456789
```

?

**Comment by johnkerl** [comment]
Perhaps your WSL's `bash` knows about `printf "%'d" ` but your WSL's `sh` does not? This is my guess ...

**Comment by johnkerl** [comment]
Also: I would _love_ it if I could support `"%'d"` within Miller's `fmtnum` -- however in the implementation of `fmtnum` I leverage the Go library's `fmt.Sprintf` which does _not_ accept `"%'d"` :(

**Comment by aborruso** [comment]
> Can you please try this?

Yes, WSL's `sh` does not know it. 

And I think there is no solution to overcome this :(

![image](https://github.com/johnkerl/miller/assets/30607/47718e93-706f-438c-b589-bd43e2ef4379)

**Comment by aborruso** [comment]
I have this mad way to do it, it works in `/bin/sh`



```
echo 123456789 | awk '{printf "%\47d\n", $1}'
```

**Comment by aborruso** [comment]
I give up, I can't get it to work even with

```
echo 123456789 | awk '{printf "%\47d\n", $1}'
```

My stupid test. I have this:

```
cat commas.mlr
$b = system("echo 123456789 | awk '{printf \"%\47d\n\", $1}'")
```

but when I run `echo a=1234567 | mlr --oxtab put -f commas.mlr` I have

```
awk: cmd. line:1: {printf "%\47d
awk: cmd. line:1:         ^ unterminated string
a 1234567
b
```

**Comment by aborruso** [comment]
In this way it works

```
$b = system("python3 -c \"print(f'{123456789:,}')\"")
```

But I'll stop here, it doesn't seem like a useful way to answer this question: https://github.com/johnkerl/miller/discussions/1488
