### ISSUE TITLE
Is there a way to "sparsify"

### ISSUE THREAD

**Issue by seancarmody** [johnkerl/miller#1497]
Is there any way to do the reverse of `unsparsify` when converting from CSV to JSON? Where there are missing values in for a column in the CSV file, I would like to omit the key completely from that record in the JSON output.  For example, taking as input
```
A,B,C
1,2,3
4,,5
```
the output should be
```
[
{
  "A": 1,
  "B": 2,
  "C": 3
},
{
  "A": 4,
  "C": 5
}
]
```
I can get the desired result by using `mlr --c2j cat` and piping the result through `jq 'map(with_entries(select(.value != "")))'` but it would be nice to be able to do it all in miller.

**Comment by johnkerl** [comment]
Oh wow nice 😎

**Comment by johnkerl** [comment]
@seancarmody what do you think of #1498?

**Comment by seancarmody** [comment]
That works a treat. Thank you for responding to this so quickly.
