### ISSUE TITLE
Use travis-ci

### ISSUE THREAD

**Issue by johnkerl** [johnkerl/miller#15]
Split off from https://github.com/johnkerl/miller/issues/8.

Note: at present I use manual CI [see also http://johnkerl.org/miller/doc/build.html] -- all unit/regression tests run on each build. So this will simply automate that. It looks at present like multi-platform is still beta, but, the more platforms I can get auto-building, the better.

**Comment by johnkerl** [comment]
Marking as wishlist for now, just relative to other things more pressing -- namely, RFC-CSV and packaging. In the medium term, though, this will be a should-do rather than a wishlist item.

**Comment by johnkerl** [comment]
@SikhNerd is working on this

**Comment by SikhNerd** [comment]
Please go to https://travis-ci.org/profile and activate it for this project

**Comment by SikhNerd** [comment]
Thanks, I've created https://github.com/johnkerl/miller/pull/58 now that you've done so :)

**Comment by johnkerl** [comment]
Gorgeous -- thank you!! :)
