### ISSUE TITLE
Investigate spurious `[]` on JSON output in some cases

### ISSUE THREAD

**Issue by johnkerl** [johnkerl/miller#1513]
Originally posted by @johnkerl in https://github.com/johnkerl/miller/discussions/1512#discussioncomment-8652964

In both of the following cases a final `[]` is printed when it should not be:

```
$ cat test.json
{
    "a": [
        {"x":1, "y":2, "z":3},
        {"x":4, "y":5, "z":6},
        {"x":7, "y":8, "z":9}
    ],
    "b":[
        {"i":1, "j":2},
        {"i":3, "j":4},
        {"i":5, "j":6}
    ]
}
```

```
$ mlr -j --from test.json put -q 'print $a'
[
  {
    "x": 1,
    "y": 2,
    "z": 3
  },
  {
    "x": 4,
    "y": 5,
    "z": 6
  },
  {
    "x": 7,
    "y": 8,
    "z": 9
  }
]
[
]
```

Also:

```
$ mlr --json cat nonesuch
[
]
mlr: open nonesuch: no such file or directory.
```

**Comment by johnkerl** [comment]
So @smammy ... it turns out this was intentional on my part.

Here:
https://github.com/johnkerl/miller/blob/6.11.0/pkg/output/record_writer_json.go#L56-L88
the idea is that `mlr --json cat /dev/null` should produce `[]`.

However -- I am questioning that. For example, `jq . /dev/null` produces nothing at all and ostensibly Miller shouldn't either. 🤔

**Comment by johnkerl** [comment]
Also:

```
$ echo '' | jq .

$ echo '[]' | jq .
[]

$ echo '' | mlr --json cat
[
]

$ echo '[]' | mlr --json cat
[
]
```

Miller "forgets" the  outer `[]` even when it's explicitly provided so:

* I don't like empty input leading to `[]` output
* I don't like `[]` input leading to empty output
* I'm not seeing a clean way for the JSON-output writer to know which came in in the first place ...

**Comment by smammy** [comment]
Just thinking out loud here… Miller is pretty forgiving about JSON input. All of these are interpreted as two records:

```sh
# One JSON document, an array of two objects
echo '[{"foo":"bar"},{"foo":"baz"}]' | mlr -j cat
# "JSON Lines" - two JSON documents, one object each
echo -e '{"foo":"bar"}\n{"foo":"baz"}' | mlr -j cat
# Neither, but still accepted
echo '{"foo":"bar"}{"foo":"baz"}' | mlr -j cat
```

The output is normally a single JSON document consisting of an array, but if `--no-jlistwrap` is set, it's a JSON Lines document.

I wonder if the JSON input reader could set `--no-jlistwrap` if it encountered input other than a JSON array?
