### ISSUE TITLE
`flatten` not working on CSV input data

### ISSUE THREAD

**Issue by TobyBrull** [johnkerl/miller#1514]
I would have expected the following commands to give the same output.
```
mlr --c2j --from <( echo $'obj.a,obj.b\n1,2' ) flatten
mlr --c2j --from <( echo $'obj.a,obj.b\n1,2' ) cat then flatten
mlr --c2j --from <( echo $'obj.a,obj.b\n1,2' ) cat | mlr -j flatten
```

The output of the first two commands is:
```
[
{
  "obj": {
    "a": 1,
    "b": 2
  }
}
]
```

The output of the last command is:
```
[
{
  "obj.a": 1,
  "obj.b": 2
}
]
```

I would have expected the latter in all cases. Am I missing something?

**Comment by johnkerl** [comment]
What's going on here:

See also https://miller.readthedocs.io/en/latest/flatten-unflatten/#manual-control.

Output format is JSON so Miller by default (unless `--no-auto-unflatten`) appends an `unflatten` verb at the end of your specified verb chain. So it's as if you typed `mlr --c2j --from <( echo $'obj.a,obj.b\n1,2' ) flatten then unflatten`. 

The workaround for the released version is to do

```
$ mlr --c2j --from <( echo $'obj.a,obj.b\n1,2' ) --no-auto-unflatten flatten
[
{
  "obj.a": 1,
  "obj.b": 2
}
]
```

But the fix should be: keep the logic as at
https://miller.readthedocs.io/en/latest/flatten-unflatten/#manual-control
except that if the final verb is `flatten`, act as if the user had provided `--no-auto-unflatten`.
