### ISSUE TITLE
Skip comments in CSV/TSV files [feature request]

### ISSUE THREAD

**Issue by sjackman** [johnkerl/miller#152]
They're not terribly common, but some CSV/TSV files have comments, typically starting with a `#` character. For example

```
# name: sheet1.tsv
A,B
1,X
2,Y

# name: sheet2.csv
C,D,E
3,4,5
```

It'd be helpful to skip lines that begin with a specified character. I'm thinking
```sh
mlr --tsvlite --comment='#' cat <foo.tsv
```

See for example `readr::read_table` which implements this feature.
https://www.rdocumentation.org/packages/readr/versions/1.1.1/topics/read_table

**Comment by sjackman** [comment]
Perhaps the default value for comment could be `#` if a value is not specified, allowing
```
mlr --tsvlite --comment cat <foo.tsv
```

**Comment by johnkerl** [comment]
OK. Personally I'm happy with `grep -v ^# | ...` but what you suggest would be a good keystroke-reducer over grep pipe mlr, or Miller's prepipe.

**Comment by sjackman** [comment]
Cool. I had forgotten about `prepipe`. Thanks for reminding me about it.

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/blob/master/c/draft-release-notes.md

**Comment by sjackman** [comment]
Woohoo! Thanks, John. And `-t` and `-T`. Yeah!

> the UTF-8 bill-of-materials ("BOM") sequence 0xef 0xbb 0xbf

byte-order mark 😉
https://en.wikipedia.org/wiki/Byte_order_mark

Is there a GitHub issue that I can subscribe to to be notified of release?
e.g. https://github.com/Linuxbrew/brew/issues/1

**Comment by johnkerl** [comment]
Github issue, no, but good call, I can make one.
