### ISSUE TITLE
Add description for "put" verb

### ISSUE THREAD

**Issue by NanXiao** [johnkerl/miller#1525]
Hello, 

For [put](https://miller.readthedocs.io/en/latest/reference-verbs/#put) verb, I think there should be a description between `Usage` and `Options`:
> Usage: mlr put [options] {DSL expression}
Options:
......

Just as other verbs, e.g.:

> Usage: mlr nothing [options]
Drops all input records. Useful for testing, or after tee/print/etc. have
produced other output.
Options:
......

Otherwise users can't get the meaning of `put` verb, thanks!

Best Regards
Nan Xiao

**Comment by johnkerl** [comment]
Oh no @NanXiao this is quite an oversight on my part! Thanks for catching it!! :)
