### ISSUE TITLE
Filter By multiple Partial Entries

### ISSUE THREAD

**Issue by jtotexas** [johnkerl/miller#153]
What function and syntax would I use to filter a column by a partial entry.  For example, I have a column called phone number and I need to filter by numbers that start with 1877, 1888, 1800 and so one.

**Comment by johnkerl** [comment]
Sorry for the delay. How about

```
mlr filter -S '${phone number} =~ "^1800" || ${phone number} =~ "^1877"' ...
```

?

**Comment by johnkerl** [comment]
@jtotexas Please feel free to reopen if this doesn't meet your needs. Thank you!
