### ISSUE TITLE
Automated way of clearing down column data

### ISSUE THREAD

**Issue by karudonaldson** [johnkerl/miller#1539]
Scenario:
We have a good number of columns perhaps 100, there are about 30 that require clearing of their data.

Objective:
When the csv is imported into its destination system, the mentioned cleared down columns will have no data in them.

Solution:
Does miller have the ability to define which column headers should have their data cleared some way?  Or if anyone has any ideas that would be greatly appreciated!

- We recieve the extracted file from a source system that we have no control or access of.  What is exported is what we have to work with.  
- If we can automate a tool to detect when a CSV file is created and automatically provided the above transformation on specific columns, that would be perfect.

**Comment by aborruso** [comment]
Hi @karudonaldson I'm not sure I understand what your goal is.
Looking for a tool that monitors the creation of new files in a folder, and as soon as there is a new one apply a Miller command?

One tool for monitoring a folder is, for example, inotifywait.

**Comment by karudonaldson** [comment]
Thanks for the response @aborruso.

Ideally looking for functionality to:
- clear predefined column data without removing the column 
- above process must retain headers and column order
- require a process to monitor for newly created CSV files in a folder
- if a new file is detected, execute column clearing process

It appears miller can do the column clearing process, but not sure how?

**Comment by aborruso** [comment]
Miller is used to process structured text files. You can write a bash script and have it do what you want.

If you have an example of input and the processing you would like to do, I can give you an example.

**Comment by karudonaldson** [comment]
ok so imagine example.csv looks like this
<img width="303" alt="Screenshot 2024-04-10 at 10 34 16 PM" src="https://github.com/johnkerl/miller/assets/444688/34af43fb-6c83-44bf-ad41-56fdd95c7964">

I need to strip column data in column "two" without affecting the header or column order.  
The result being:
<img width="222" alt="Screenshot 2024-04-10 at 10 35 49 PM" src="https://github.com/johnkerl/miller/assets/444688/94fff8b4-de90-4f21-998c-88afe04e7ef2">

There is roughly 100+ columns, where around 30 need to be cleared.

Does that make more sense?

**Comment by johnkerl** [comment]
@karudonaldson more generally:

```
$ cat example.csv
one,two,three,four,seven,eight,thirty
pan,pan,1,0.347,0.727,0.252,10
eks,pan,2,0.759,0.522,0.396,20
wye,wye,3,0.205,0.338,0.069,30
eks,wye,4,0.381,0.134,0.051,40
wye,pan,5,0.573,0.864,0.495,50
zee,pan,6,0.527,0.493,0.260,60
eks,zee,7,0.612,0.188,0.115,70
zee,wye,8,0.599,0.976,0.584,80
hat,wye,9,0.031,0.750,0.024,90
pan,wye,10,0.503,0.953,0.479,100
```

```
mlr --csv --from example.csv put '
  begin {
    @names = ["two", "seven", "thirty"]
  }
  for (name in @names)  {
   $[name] = ""
  }
'
```

```
one,two,three,four,seven,eight,thirty
pan,,1,0.347,,0.252,
eks,,2,0.759,,0.396,
wye,,3,0.205,,0.069,
eks,,4,0.381,,0.051,
wye,,5,0.573,,0.495,
zee,,6,0.527,,0.260,
eks,,7,0.612,,0.115,
zee,,8,0.599,,0.584,
hat,,9,0.031,,0.024,
pan,,10,0.503,,0.479,
```

**Comment by karudonaldson** [comment]
Thank you both for your help!  I managed to get a preliminary solution tested this morning :)
