### ISSUE TITLE
Miller CSV output issue

### ISSUE THREAD

**Issue by jtotexas** [johnkerl/miller#154]
When I output a CSV from Miller and open that file in excel, data is on a single cell.  I would think that it would output the file the same way that it receives the file.

I'm new to this so bare with me if I'm green.

**Comment by jtotexas** [comment]
The command I'm running is mlr --icsv --opprint cut -o -f orig_callid,domain,orig_id,orig_ip,duration test_cdr.csv > test6_cdr.csv

the output is read by excel as the following in a single cell.

0_1371963526@192.168.10.14                                Gamboaelectric.com                           9155986200               24.242.1.157    1

**Comment by johnkerl** [comment]
Hmm, pretty-print is spaces-delimited while CSV is commas-delimited. Maybe Excel is trying to split on commas?

Also, why not just open the CSV in Excel directly?

**Comment by jtotexas** [comment]
Thank you very much.  I just output straight to CSV with no pretty-print and it formatted correctly.  Thank you again.
