### ISSUE TITLE
Equivalent to Excel function "data load from folder" then "combine and load" multiple CSV's finally "apply transformations"

### ISSUE THREAD

**Issue by karudonaldson** [johnkerl/miller#1544]
#### Edit: split issue into applicable new issues ####

**Scenario:**
I have a folder containing 100 csv FILES

**Current State:**
1. Do a "Combine + Load"
Using Excel, I load data from folder

2. Apply transformations
Filter column C (three) remove all entries containing number "2" leaving only entries containing "1"
$ cat example.csv
```
one,two,three,four,seven,eight,thirty
pan,pan,1,0.347,0.727,0.252,10
eks,pan,2,0.759,0.522,0.396,20
wye,wye,1,0.205,0.338,0.069,30
eks,wye,1,0.381,0.134,0.051,40
wye,pan,2,0.573,0.864,0.495,50
zee,pan,1,0.527,0.493,0.260,60
eks,zee,2,0.612,0.188,0.115,70
zee,wye,2,0.599,0.976,0.584,80
hat,wye,2,0.031,0.750,0.024,90
pan,wye,2,0.503,0.953,0.479,100
```

**After transformation**
$ cat example_clean.csv
```
one,two,three,four,seven,eight,thirty
pan,pan,1,0.347,0.727,0.252,10
wye,wye,1,0.205,0.338,0.069,30
eks,wye,1,0.381,0.134,0.051,40
zee,pan,1,0.527,0.493,0.260,60
```

**Future State**
Using CLI miller

**Comment by johnkerl** [comment]
Hi @karudonaldson ! I believe this is a "how I did it" comment, rather than a "how do I do this?" question -- can you confirm? Thanks!

**Comment by aborruso** [comment]
Hi @karudonaldson you can use the [filter verb](https://miller.readthedocs.io/en/6.12.0/reference-verbs/index.html#filter), and apply it to all the CSV files of a folder.

```
mlr --csv filter '$columnA==1 && $columnB==2' folder/*.csv >./filtered_output_merged.csv
```

**Comment by karudonaldson** [comment]
Hi @johnkerl this is "how I do it" using Excel, however, I'd like to be able to script this in order to automate the procedure using Miller :)

**Comment by johnkerl** [comment]
* https://miller.readthedocs.io/en/latest/reference-dsl-filter-statements/
* https://miller.readthedocs.io/en/latest/reference-dsl-builtin-functions/index.html#ssub

**Comment by karudonaldson** [comment]
Thanks for the direction @johnkerl and @aborruso.

Combining an tranformation of filtering Column name `ColumnX` by string `1` was achieved with:
`mlr --csv filter '$ColumnX == "1"' ../folder/*.csv >./test-filter-output-merged.csv`
