### ISSUE TITLE
Find and remove "string" retaining all other row data

### ISSUE THREAD

**Issue by karudonaldson** [johnkerl/miller#1545]
In ColumnC (three) and ColumnD (four) remove string "TEST", retaining all other row data.  

$ cat example.csv
```
one,two,three,four,five
pan,pan,TEST,TEST,10
wye,wye,TEST,TEST,20
eks,wye,TEST,TEST,30
eks,wye,TEST,TEST,40
```

**After transformation**
$ cat example-clean.csv
```
pan,pan,,,10
wye,wye,,,20
eks,wye,,,30
eks,wye,,,40
```

**Comment by aborruso** [comment]
@karudonaldson please also always write down what test you did, what didn't work for you. Don't just write what you want.

So it will be possible to give you a better answer. Thank you

**Comment by johnkerl** [comment]
@aborruso I think this question is well-posed

**Comment by karudonaldson** [comment]
> @karudonaldson please also always write down what test you did, what didn't work for you. Don't just write what you want.
> 
> So it will be possible to give you a better answer. Thank you

Apologies if this wasn't clear.  I took the liberty to split my original issue into separate issues due to the nature of the individual tasks, and didn't think too much into how they were worded but @johnkerl that's awesome.  I wouldn't' have figured that out!

**Comment by karudonaldson** [comment]
Thanks so much for the response @johnkerl - excellent examples.  I can use this approach as a start point.
