### ISSUE TITLE
File with incompatible license

### ISSUE THREAD

**Issue by luigino** [johnkerl/miller#155]
I've submitted the latest version of miller to openSUSE and legal tells me c/lib/netbsd_strptime.c being licensed under BSD-4-Clause, incompatible with GPL, makes the whole package non distributable.

**Comment by johnkerl** [comment]
crap, ok. what it is specifically that needs to be compatible with GPL? miller itself is BSD.

**Comment by johnkerl** [comment]
and why is this issue now closed?

**Comment by luigino** [comment]
Sorry, I should have left a note. I believe they wanted to tell me to say it's both BSD2 and BSD4 licensed.

The only GPL bits are in the autotools scripts, which I don't believe are a problem.
I've re-submitted it, will update if there's news, but as of now it looks like a blunder of mine.

**Comment by johnkerl** [comment]
@luigino thanks for the help!!! :)

**Comment by luigino** [comment]
Ok, it has been accepted. False alarm:)
