### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by sjackman** [johnkerl/miller#156]
I would've sent a PR, but wasn't sure where this file lived in GitHub.

> Absent (key not present): a field name is not present, e.g. input record is x=1,y=2 and a put or filter expression refers to $z. Or, reading an out-of-stream variable which hasn’t been assigned a value yet, e.g. mlr put -q '@sum += $x'; end{emit @sum}'

There's an errant single quote after `+= $x'`.

**Comment by johnkerl** [comment]
yikes thanks! :)

**Comment by johnkerl** [comment]
file:///Users/kerl/pub_http_internet/miller-releases/miller-head/doc/reference.html updated.

Thanks @sjackman !!
