### ISSUE TITLE
Completely unexpted output of put, then cut, then label

### ISSUE THREAD

**Issue by ghmon** [johnkerl/miller#1564]
[miller 6.12.0]

After searching an error in my statement for two hours, then even asked chatgpt-4 which came out with exactly the same solution i used before i consider this a bug or a profound misunderstanding of miller.

Task: read csv file, add new column, cut part of columns and rearrange, new label (header).

with awk/sed:
echo latitude,longitude,elevation,name; awk -v FS="," '{ print $5 "," $4 ",0," $1}' "$1" | sed 1d

Input (first two data lines only):

Sendername,Block,Blockmittenfrequenz,Geo Länge WGS84,Geo Breite WGS84,Land geographisch,T-DAB-Modus,ERP-MAX horizontal,ERP-MAX vertikal,Polarisation,Antennencharakteristik D/N,HEFF_MAX,Land administrativ,Datum der Veröffentlichung,Datum der Änderung
Aachen,9A,202.928,6.24417,50.7714,D,null,null,30.0,V,D,358,D,28.04.2024,null
Aachen,9A,202.928,6.24361,50.7836,D,null,null,37.5,V,D,355,D,28.04.2024,null

Command (in a bash script):

mlr --csv --from "$1" \\
    put '$elevation = "0"' \\
    then cut -f '{Geo Breite WGS84},{Geo Länge WGS84},elevation,Sendername' \\
    then label latitude,longitude,elevation,name

Output (first two data lines only):

latitude,longitude
Aachen,0
Aachen,0

Expected output:

latitude,longitude,elevation,name
50.7714,6.24417,0,Aachen
50.7836,6.24361,0,Aachen

**Comment by aborruso** [comment]
Hi @ghmon ,
in cut you should use `"` for field names with spaces

```
mlr --csv --from input.csv \
put '$elevation = "0"' \
then cut -f "Geo Breite WGS84","Geo Länge WGS84",elevation,Sendername \
then label latitude,longitude,elevation,name
```

**Comment by aborruso** [comment]
ok @ghmon , if it's ok, please close the issue
