### ISSUE TITLE
Add support for SAM format

### ISSUE THREAD

**Issue by sjackman** [johnkerl/miller#157]
Hi, John. The SAM file format is very common in the field of bioinformatics, used to store alignments of sequencing data to a reference genome. It is hybrid positional and name-type-value file format that looks like this:
```sam
r001	147	ref	37	30	9M	=	7	-39	CAGCGGCAT	*	AS:i:100	NM:i:1	BC:Z:ACGTA
```
equivalent to
```json
{ "qname": "r001", "flag": 147, "rname": "ref", "pos": 37, "mapq": 30, "cigar": "9M",
    "rnext": "=", "pnext": -39, "seq": "CAGCGGCAT", "qual": null,
    "AS": 100, "NM": 1, "BC": "ACGTA" }
```

Would you be open to including support for this file format in Miller? It'd be crazy amazing if you wanted to implement this format yourself. Otherwise I was thinking I'd give my hand at creating a pull request, though it may be a few weeks before I find the time. Before I put the work in though, I wanted to check in that you'd be open to merging the PR. I'd be adding options `--sam --isam --osam`.

The format is described in full here: https://github.com/samtools/hts-specs/blob/master/SAMv1.pdf

**Comment by johnkerl** [comment]
@sjackman sounds like worth the effort! I know a lot of folks use Miller for bioinformatics so this isn't as much a niche request as I thought at first blush.

**Comment by sjackman** [comment]
Great! Any tips or pitfalls before I get to work? I'll start with a first PR to implement `--isam` only.

**Comment by johnkerl** [comment]
No, I'd just start with copypasta. Do be aware there is code duplication between stdio & mmap implementations.

Your example bit looks very straightforward: either positional or named. The full spec in the PDF looks a bit more complicated. Are you thinking of implementing a subset of SAM first?

**Comment by sjackman** [comment]
The container format is pretty simple, as you say. I'm planning on passing the header `@` records through unmodified, details to be determined later. The types of the name fields are…

- `A` Printable character
- `i` Signed integer
- `f` Single-precision floating number
- `Z` Printable string, including space
- `H` Byte array in the Hex format
- `B` Integer or numeric array

I'll implement `i`, `f`, and `Z` to start. I won't implement `H` and `B` at first. I'll have to think a bit about `A`. It's easy to read, but writing might be a bit tricky. I don't think it's very common though.

**Comment by sjackman** [comment]
That's good news. There are no standard optional fields that use `A`. So, I'll support reading `A`, but I won't support writing `A` (for now, anyway).
See https://github.com/samtools/hts-specs/blob/master/SAMtags.pdf

**Comment by sjackman** [comment]
There's only a single standard field that uses `B`, and that's `FS` Flow signal intensities.
Nothing seems to use `H`.

**Comment by johnkerl** [comment]
Oops sorry my comment was based on a misread of the spec. :^/ Looks like we're good to go. :)

**Comment by sjackman** [comment]
The following works surprisingly well for parsing SAM, handling only integer named fields.
```sh
mlr --dkvp --fs tab --ps :i: \
label qname,flag,rname,pos,mapq,cigar,rnext,pnext,tlen,seq,qual
```

Perhaps `ips` could be modified to accept a regex, something like `--ipr` where `r` stands for regex.
```
mlr --dkvp --fs tab --ipr '([A-Za-z0-9][A-Za-z0-9]:[ifZABH]):(.*)' --ops :
```
where the first group matches the key and the second group matches the value.

Is there a way with `--odkvp` to specify that certain fields (in this case the positional fields 1 through 11) should not output the name and pair separator?

**Comment by sjackman** [comment]
Is there currently a way to round-trip the following example?
```
❯❯❯ mlr --dkvp cat <<<'a,b,c,x=d,y=e'
1=a,2=b,3=c,x=d,y=e
```
to output instead
```
a,b,c,x=d,y=e
```

**Comment by sjackman** [comment]
If not, I'm thinking something like this…
+ `--label u,v,w` specify the labels of the first three columns, equivalent to `label u,v,w then …`
+ `--nolabel 1-3` the labels of fields one through three are not output
+ `--nolabel u,v,w` the labels of fields `u`, `v`, and `w` are not output
+ `--ilabel u,v,w` is equivalent to `--label=u,v,w --nolabel=u,v,w`

For my example above…
```
❯❯❯ mlr --dkvp --ilabel u,v,w cat <<<'a,b,c,x=d,y=e'
a,b,c,x=d,y=e
```

A short option `-l` for `--label` would be handy in conjunction with the new `-T`, for example…
```sh
mlr -T -l name,count filter 'count < 10'
```

**Comment by sjackman** [comment]
Here's another possibility to remove labels:
Observed behaviour
```
❯❯❯ mlr --dkvp label ,, <<<'a,b,c,x=d,y=e'
=c,x=d,y=e
```
Desired behaviour
```
❯❯❯ mlr --dkvp label ,, <<<'a,b,c,x=d,y=e'
a,b,c,x=d,y=e
```

**Comment by johnkerl** [comment]
@sjackman I forgot to ask sooner ... clearly the ask here is to support SAM format, but, in addition to that (for context) can we take a step back -- can you tell me what are some of the kinds of *manipulations* on SAM-format data you'd hope to be able to accomplish using Miller that you couldn't otherwise?

**Comment by sjackman** [comment]
Filtering on the unlabeled columns is easy with awk `$5 >= 10` for example to filter on mapping quality in column 5.

Filtering on the labeled columns (such as alignment score `AS:i:1234`) with awk is possible, but not easy and slow. There are tools specifically for SAM to filter SAM Files (like Picard and Sambamba for example `sambamba view -F '[AS] >= 100`.

Miller would be better suited for computing summary metrics of both the positional and labeled columns.

**Comment by sjackman** [comment]
I've started a new job (yeah!), still in bioinformatics, but I don't have an immediate use case for this feature now. Feel free to close it if you like. Thanks for the discussion all the same!

**Comment by johnkerl** [comment]
OK. Let me know if this comes up again. :)

**Comment by janxkoci** [comment]
Just FYI - [bioawk](https://github.com/lh3/bioawk) supports the SAM and a few other formats, so I don't think there is much need for this 😉
