### ISSUE TITLE
Newlines in fields | CSV file: Header/data length mismatch

### ISSUE THREAD

**Issue by oPromessa** [johnkerl/miller#1571]
Excellent tool. Issue I could not find a solution for. Sorry!

I'm possibly missing something ;). Help is very much appreciated.

#### Trying to process a csvlite with IFS pipe and multi-line (\n) fields.
* Using pipe at the end of each line to allow to detect |\n as RS.
* File format:
   * csvlite
   * FS=pipe
   * RS=trying with "|\n" to accommodate for newlines within fields

#### Sample input:
```csv
1-Directory|2-FileName|3-Description|
.|OneFilename.txt|One line only|
.|TwoFilename.txt|Two lines
description|
.|ThreeFilename.txt|One line only again|
```
#### cat -e
```sh
$ cat -e test.txt
1-Directory|2-FileName|3-Description|$
.|OneFilename.txt|One line only|$
.|TwoFilename.txt|Two lines$
description|$
.|ThreeFilename.txt|One line only again|$
```
#### Command and Error
```py
$ mlr --icsvlite --ojson --ifs pipe --irs '|\n' cat test.txt 
[
{
  "1-Directory": ".",
  "2-FileName": "OneFilename.txt",
  "3-Description": "One line only"
}
]
mlr: mlr: CSV header/data length mismatch 3 != 1 at filename test.txt line  3.
.
```
#### Platform:
* Mac swversion
```
ProductName:	macOS
ProductVersion:	12.7.5
BuildVersion:	21H1222
```
* MLR version ` mlr 6.12.0`

**Comment by aborruso** [comment]
For me this is a wrong input file, because you have carriage returns and there is no way to differentiate row ones from cell ones.

So I would first correct the input file and then pass the output to miller:

```
tr -d '\n' < input.txt | sed -E 's/(([^|]*\|){3})/\1\n/g' | mlr --ifs "|" --icsvlite --ojson remove-empty-columns
```

In output

```
[
  {
    "1-Directory": ".",
    "2-FileName": "OneFilename.txt",
    "3-Description": "One line only"
  },
  {
    "1-Directory": ".",
    "2-FileName": "TwoFilename.txt",
    "3-Description": "Two linesdescription"
  },
  {
    "1-Directory": ".",
    "2-FileName": "ThreeFilename.txt",
    "3-Description": "One line only again"
  }
]
```

**Comment by oPromessa** [comment]
> For me this is a wrong input file, because you have carriage returns and there is no way to differentiate row ones from cell ones.

Yup. I was trying with the record separator `--irs "|\n"` to differentiate from a new line in the middle of the exemplified field "Two lines\ndescription". 

I do see your point and will test out your recommendation further. 

Thanks for the prompt reply.

**Comment by aborruso** [comment]
> Yup. I was trying with the record separator `--irs "|\n"` to differentiate from a new line in the middle of the exemplified field "Two lines\ndescription".

And how do you differentiate? In your input file, which you did not attach, are there carriage returns of a different type if it is end-of-line or if it is inside a cell?

If you don`t differentiate it`s all `\n`, and therefore it`s a wrong file.

**Comment by oPromessa** [comment]
@aborruso Thanks for the feedback!

> And how do you differentiate? 
* Via --irs "|\n"
* Far from me to say what's right and wrong: [which-separators-apply-to-which-file-formats](https://miller.readthedocs.io/en/latest/file-formats/#csvtsvasvusvetc) states:
   1. CSV-lite naively splits lines on newline, and fields on comma -- embedded commas and newlines are not escaped in any way. 
      * If "splits lines on newline" means "splits records on newline", then a field can never have a "\n". Case closed ;)
   3. CSV-lite allows changing FS and/or RS to any values, perhaps multi-character.
      * I was hopeful if FS is "|" and RS is "|\n" that it would _consider_ "\n" (given that it is not RS) as part of the field, and only consider a new record when the sequence "|\n" is found. Again, based on the 'axiom' of the previous point **i**, this can never be. Understood!

> In your input file, which you did not attach, 
* Sorry. Attached. [test.txt](https://github.com/user-attachments/files/15523381/test.txt)

> are there carriage returns of a different type if it is end-of-line or if it is inside a cell?
* No.

**Comment by oPromessa** [comment]
> Case closed ;)
So I went back to review my workflow and I guess it's best to stick with standards. So I'm working thru the generating component to produce a pure CSV (which accepts  \n inside a field with quotes) and then handle it.

Thanks again for the support.

**Comment by aborruso** [comment]
> * I was hopeful if FS is "|" and RS is "|\n" that it would _consider_ "\n" (given that it is not RS) as part of the field, and only consider a new record when the sequence "|\n" is found. Again, based on the 'axiom' of the previous point **i**, this can never be. Understood!

Hi, the  "|\n" could be also a cell in which you put a carriage return at the beginning. This is odd but allowable.
You must have a way to differentiate a line return from a cell return.

And for example, one way is to have `CRLF` for rows and only `LF` for cells. But if you produce the file yourself, there is no doubt that the most convenient interoperable solution is not to create a new format, but to use a standard one.
