### ISSUE TITLE
Short option for --nidx --fs tab

### ISSUE THREAD

**Issue by sjackman** [johnkerl/miller#158]
The TSV file format of `cut` and friends is sufficiently common that I feel that `--nidx --fs tab` warrants a short option, similar to `-p`, perhaps `-t`. It's particularly handy when using `mlr` to replace commands from `coreutils`, for example, `mlr -t cut -f 3`. Your thoughts?

I'd also suggest a short option for `--tsvlite`, perhaps `-T`.

**Comment by johnkerl** [comment]
Cool; `mlr put` already uses `-t` and `-T` but `mlr` main uses neither.

**Comment by sjackman** [comment]
Awesome. Do you have a preference which of the two is `-t` and which is `-T`? Which format do you think is more common? I'd say that the more common one should be `-t`.

**Comment by johnkerl** [comment]
@sjackman i don't have a preference. `--tsvlite` = `-T` is fine with me.

**Comment by sjackman** [comment]
I use `--tsvlite` more than I use `--nidx --fs tab`. I'm thinking
`-t` is `--tsvlite` and
`-T` is `--nidx --fs tab`

**Comment by sjackman** [comment]
Woohoo! Thanks, John. New release pending?

**Comment by johnkerl** [comment]
Pretty soon ... I want to get the comment-skipper in there too and it needs a bunch of regression tests, and one more corner-case to implement.

**Comment by sjackman** [comment]
While you're doing the comment-skipper, I have a use case to pass all comments through unmodified to the output. Think that could make it in?

**Comment by johnkerl** [comment]
bler, i don't know how to do that within the miller streaming architecture ...

**Comment by sjackman** [comment]
I was thinking as it's read in from stdin, if it's a comment, immediately write that same line out to stdout.

**Comment by johnkerl** [comment]
gler, that would be ok with line-at-a-time mappers but w sort etc it's not clear to me what would be the right thing to do.

**Comment by sjackman** [comment]
Print the comment lines out in the order that they're observed. In the case of sort, the comment lines would appear before the normal records in the order that they're observed, which would be consistent with a stable sort where a comment line sorts before any other record. That happens to be the behaviour that I need. In my case, the comment lines all appear at the top of the file before the normal records.
