### ISSUE TITLE
Regex match a period

### ISSUE THREAD

**Issue by sjackman** [johnkerl/miller#159]
I'd expect `\\.` to match a period. Neither `\.` nor `\\.` work. `[.]` does work.
```sh
❯❯❯ printf "hi\na.b\nbye\n" | mlr -p filter '$1 =~ "\."'
❯❯❯ printf "hi\na.b\nbye\n" | mlr -p filter '$1 =~ "\\."'
❯❯❯ printf "hi\na.b\nbye\n" | mlr -p filter '$1 =~ "[.]"'
a.b
```

**Comment by johnkerl** [comment]
:( Oddly I ran into this just today. Very weird it's not working. I'm just wrapping the C regex library; maybe I bungled something backslashwise.

**Comment by sjackman** [comment]
🤔

**Comment by sjackman** [comment]
Thanks for the quick fix, John.
