### ISSUE TITLE
Applying multiple filter operations into a single run

### ISSUE THREAD

**Issue by karudonaldson** [johnkerl/miller#1590]
I currently have multiple filters in separate scripts.
`mlr --csv filter '$COLUMN1 == "TEST1"' input.csv > output.csv`

`mlr --csv filter '$COLUMN2 == "TEST2"' input.csv > output.csv`

What is the correct syntax to run these together as a single operation?

I tried using && with no luck
`mlr --csv filter '$COLUMN1 == "TEST1"' && '$COLUMN2 == "TEST2"' input.csv > output.csv`

**Comment by johnkerl** [comment]
@karudonaldson I would suggest

```
mlr --csv filter '$COLUMN1 == "TEST1" && $COLUMN2 == "TEST2"' input.csv > output.csv
```

**Comment by karudonaldson** [comment]
> @karudonaldson I would suggest
> 
> ```
> mlr --csv filter '$COLUMN1 == "TEST1" && $COLUMN2 == "TEST2"' input.csv > output.csv
> ```

Knew it was something simple thanks @johnkerl :)
