### ISSUE TITLE
Simplifying a filter where many strings in column need to be kept

### ISSUE THREAD

**Issue by karudonaldson** [johnkerl/miller#1592]
cat input.csv
```
column1,column2,column3
one,abc,def
two,abc,def
three,abc,def
four,abc,def
five,abc,def
abc,abc,def
six,abc,def
seven,abc,def
eight,abc,def

```
I want to filter (keep) column1 on the following strings:
```
one
two
three
four
five
six
seven
eight
```

output expected is:
```
column1,column2,column3
one,abc,def
two,abc,def
three,abc,def
four,abc,def
five,abc,def
six,abc,def
seven,abc,def
eight,abc,def
```

Typically, I'd use:
mlr --csv filter '$column1 == "one" || $column1 == "two" || $column1 == "three" || $column1 == "four"' input.csv > output.csv

As you can see if I have many string values to filter in the same column, this command will start getting quite long!

How can I define the object $column1 and apply all of the strings I wish to filter (keep) in a shorter method without having to redefine column1?

Then in whole other rule, do the reverse where I filter to keep items that do NOT contain all of the strings?

I have now learnt clearing columns down using something like this @johnkerl :
```
mlr --csv --from test1.csv put '
  begin {
    @names = ["ITEM1", "ITEM2", "ITEM3", "ITEM4", "ITEM5", "ITEM6"]
  }
  for (name in @names)  {
   $[name] = ""
  }
' > test1-clean.csv
```
Presumably I can use this type of statement replace put with filter and moving some things around?

**Comment by aborruso** [comment]
One way is to use regex:

```
mlr --csv filter '$column1=~"^(one|two|three|four|five|six|seven|eight)$"' input.csv
```

Here’s a breakdown:

- `^`: Ensures the match starts at the beginning of the string.
- `(one|two|three|four|five|six|seven|eight)`: Matches any one of the words within the parentheses.
- `$`: Ensures the match ends at the end of the string.

**Comment by johnkerl** [comment]
@aborruso 's answer is a great one using regexes, and probably the best one.

Just to close the loop here's a version using hashmaps following

> Presumably I can use this type of statement replace put with filter and moving some things around?

```
mlr --csv --from input.csv filter '
  begin {
    @map = {
      "one": true,
      "two": true,
      "three": true,
      "four": true,
      "five": true,
      "six": true,
      "seven": true,
      "eight": true,
    }
  }
  @map[$column1]
'
```

```
column1,column2,column3
one,abc,def
two,abc,def
three,abc,def
four,abc,def
five,abc,def
six,abc,def
seven,abc,def
eight,abc,def
```

**Comment by karudonaldson** [comment]
@johnkerl - hashmaps make it clean!

OK so what if I want to map multiple columns with the same mapped items?
e.g.  column1 and column2?

Can I simply do this?
`@map[$column1,$column2]`
or
`@map[$column1 || $column2]`

**Comment by johnkerl** [comment]
`@map[$column1] || @map[$column2]`

**Comment by karudonaldson** [comment]
If setting the mapped item to` "true"` results in the data being kept.  
I thought it would be obvious to use `"false"` to remove the data but that resulted in no output so it's safe to assume, '"false"' simply ignores the filter? 

In that case, what would the syntax look like to remove rows that contain the mapped items?

**Comment by johnkerl** [comment]
`filter -x`

**Comment by karudonaldson** [comment]
Eeek sorry was looking for the solution in the wrong place, my bad!  Thanks so much @johnkerl
