### ISSUE TITLE
prepipe does not work with filenames with spaces combined with file masks

### ISSUE THREAD

**Issue by mkaut** [johnkerl/miller#1600]
I have a set of CSV files in `test/data - part_<N>.csv`, where `<N>` stands for a number.
I want to join them into one file, but this requires removing the first 10 lines, as they contain unquoted comments (metadata).

This works on Ubuntu (on WSL):

```console
mlr --csv cat test/data\ -\ part_*.csv > all_data.csv
mlr --prepipe 'tail -n+11' --csv cat "test/data\ -\ part_0.csv" > part_0_cleaned.csv
```
Note that `--prepipe` needs both quoting (`""`) and escaping (`\ `) to handle the spaces.

Putting it all together does __not__ work:

```console
mlr --prepipe 'tail -n+11' --csv cat "test/data\ -\ part_*.csv" > all_data.csv
```
returns
```console
cannot open test/data - part_*.csv: No such file
```

It looks like the quoting, required by `--prepipe`, breaks the file mask.
Is this a bug?
And is there a way around it (other than renaming the files, or cleaning them before running Miller)?

__Note 1:__ The working syntax is slightly different in Windows terminal (`cmd`), where quoting does __not__ break the file mask:

```console
mlr --csv cat "test\data - part_*.csv" > all_data_w.csv
```
In this case, the `--prepipe` fails even with a single file.

__Note 2:__ If I rename the files to `test/data_part_<N>.csv` (no spaces), then this works fine on both systems:

```console
mlr --prepipe 'tail -n+11' --csv cat test/data_part_*.csv > all_data_clean.csv
```

**Comment by johnkerl** [comment]
Thank you @mkaut !!
