### ISSUE TITLE
Release tracker

### ISSUE THREAD

**Issue by johnkerl** [johnkerl/miller#163]
@sjackman asked for an issue to subscribe to for notifications of new releases. Here it is! P.S. 5.3.0 is coming up real soon now.

**Comment by johnkerl** [comment]
5.3.0 is released

https://github.com/johnkerl/miller/releases/tag/5.3.0

**Comment by johnkerl** [comment]
5.5.0 is released

https://github.com/johnkerl/miller/releases/tag/v5.5.0

**Comment by gromgit** [comment]
Apologies if I missed something, but isn't this what releases-only notifications are for?
![watch-cropped](https://user-images.githubusercontent.com/215702/64075142-17c7ea00-cce7-11e9-8c9b-fc1c0f6bd548.png)

**Comment by johnkerl** [comment]
oops thanks! maybe so! someone else requested this issue. maybe i should have pointed them at that. :^/

**Comment by sjackman** [comment]
The watching `Releases only` is a new GitHub feature since this issue was originally created. This issue can be closed now if you like.

**Comment by johnkerl** [comment]
Thanks!!
