### ISSUE TITLE
sort-within-records and regex: it seems not work

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#1645]
Hi,
I have this input csv

```
a,12,2
z,x,c
4,5,t
```

If I run  `mlr --csv sort-within-records -r "[0-9]+" input.csv` I get

```
12,2,a
x,c,z
5,t,4
mlr: open [0-9]+: no such file or directory.
```

It orders it, but I have in output also an error: "mlr: open [0-9]+: no such file or directory."

I take advantage of this for a feature request: I see that the sorting is done as if all the values were strings. Ideally, it would be great  to add the option to sort by natural sorting and have the fields in the order 2,12,a.

Thank you

**Comment by johnkerl** [comment]
@aborruso the `-r` option to `sort-within-records` isn't a regex match on field names:

```
$ mlr sort-within-records -h
Usage: mlr sort-within-records [options]
Outputs records sorted lexically ascending by keys.
Options:
-r        Recursively sort subobjects/submaps, e.g. for JSON input.
-h|--help Show this message.
```

Regardless, it would be nice to have a regex-match for field-name selection here.

**Comment by aborruso** [comment]
Thank you
