### ISSUE TITLE
Cross-compilation support

### ISSUE THREAD

**Issue by singalen** [johnkerl/miller#165]
I'm building on Linux with

    ./configure --host=arm-some-linux-gnueabi --build=x86_64

but `c/parsing/lemon` is generated for ARM, while it should be for the build platform (right?).

As of now, I'm going to just configure for x86, build and save the binary, then configure for ARM, copy over x86 binary when build fails, and see what happens.

**Comment by johnkerl** [comment]
I believe this is no longer an issue as of the Go port: there is no more Lemon; the code is no longer in C. Please let me know if we need to re-open.
