### ISSUE TITLE
can you keep providing the windows binary when you do release? 

### ISSUE THREAD

**Issue by kundeng** [johnkerl/miller#167]
newer releases don't have windows binary any more.

**Comment by johnkerl** [comment]
Thanks. I don't have a Windows machine anymore ... I need to get binaries produced as part of the AppVeyor build. :(

**Comment by johnkerl** [comment]
Artifacts for head-build are at https://ci.appveyor.com/project/johnkerl/miller/build/artifacts

On future releases I'll attach these to the release.

Thanks for your patience! I've been slow on this point.
