### ISSUE TITLE
About stat function and reading the file path from a variable

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#1677]
Hi,
if I run

```
echo 'file="tmp.txt"' | mlr --oxtab put '$file_info=stat($file)'
```

I get

```
file      "tmp.txt"
file_info (error)
```

If I hard code it

```
echo 'file="tmp.txt"' | mlr --oxtab put '$file_info=stat("tmp.txt")'
```

I get the right result

```
file              "tmp.txt"
file_info.name    tmp.txt
file_info.size    6
file_info.mode    0644
file_info.modtime 1728150479
file_info.isdir   false
```

The input of `stat` must be `class=system`, and I have a string.  Is there any way to convert the value of a string variable to `system`?

Thank you

**Comment by johnkerl** [comment]
The `system` bit is only a documentation category, not a runtime type ... no conversion issue.

Something else is up -- I'll look.

**Comment by johnkerl** [comment]
@aborruso two things: one is that `"` isn't part of the filename; the other is that `stat` returns a map not a single value.

```
$ echo 'file=tmp.txt' | mlr --ojson put '$file_info=stat($file)'
[
{
  "file": "tmp.txt",
  "file_info": {
    "name": "tmp.txt",
    "size": 0,
    "mode": 0644,
    "modtime": 1728225438,
    "isdir": false
  }
}
]
```

**Comment by aborruso** [comment]
> returns a map not a single value.

I know it, thank you. My stupid error is related to default mlr format: I thought it was necessary to put a string in double quotes.

Thank you

**Comment by johnkerl** [comment]
All good @aborruso ! It would be nice if someday DKVP could take quotes just as CSV does -- #266
