### ISSUE TITLE
Distinct rows

### ISSUE THREAD

**Issue by sjackman** [johnkerl/miller#168]
Is there a way to get the distinct lines without naming all of the columns to `uniq -f`? The output need not be sorted. It'd be nice if the output were in the same order as the input.

**Comment by sjackman** [comment]
I do have a key column that I know to be unique, but `mlr uniq -f key` also has the side effect of `mlr cut -f key`.

**Comment by johnkerl** [comment]
@sjackman can you provide some sample input along with desired output?

**Comment by sjackman** [comment]
Here's an example using Awk. In R the function is called `uniq`:
https://stat.ethz.ch/R-manual/R-devel/library/base/html/unique.html

```
❯❯❯ cat foo
2
5
1
2
2
1
3
1
1
6
7
2
1
1
4
8
1
3
2
1
2
```sh
❯❯❯ awk '!x[$0] { print } { x[$0] = 1 }' foo
2
5
1
3
6
7
4
8
```

**Comment by sjackman** [comment]
Here's a better reference: `dplyr::distinct` http://dplyr.tidyverse.org/reference/distinct.html

> Retain only unique/distinct rows from an input tbl. … If there are multiple rows for a given combination of inputs, only the first row will be preserved. If omitted, will use all variables.

If you were to add a `distinct` verb to `mlr`, then `mlr distinct then sort` would produce the same result as `mlr sort then uniq`, and `mlr distinct` would produce the same set of distinct elements, but in the same order as the original data.

**Comment by johnkerl** [comment]
@sjackman thanks, this is easy :)

**Comment by johnkerl** [comment]
@sjackman: https://github.com/johnkerl/miller/commit/6942f6334221d1efd87f8bff77086e0c41025b93 creates `mlr uniq -a`

**Comment by sjackman** [comment]
Thanks, John! It needn't be incompatible with `uniq -g` though. It is possible to specify a set of key column(s), and keep the first record for which those columns are distinct.

> If there are multiple rows for a given combination of inputs, only the first row will be preserved. If omitted, will use all variables.

**Comment by johnkerl** [comment]
OK, that didn't make sense to me at first but of course you're right.

Also I think `uniq -a -c` would make sense.

**Comment by sjackman** [comment]
> Also I think uniq -a -c would make sense.

Ah, yeah, that would be useful. `dplyr::count` in R's Tidyverse: http://dplyr.tidyverse.org/reference/tally.html

**Comment by johnkerl** [comment]
@sjackman re "It is reasonable to specify a set of key columns, and keep the first record for which those columns are distinct": `mlr head -n 1 -g a,b,c`

**Comment by johnkerl** [comment]
http://johnkerl.org/miller-releases/miller-head/doc/reference-verbs.html#uniq

http://johnkerl.org/miller-releases/miller-head/doc/cookbook.html#Options_for_dealing_with_duplicate_rows

Will go out with the next release.

Thanks @sjackman !!

**Comment by sjackman** [comment]
> `mlr head -n 1 -g a,b,c`

Nice hack! That hadn't occurred to me. Thanks again, John!
