### ISSUE TITLE
DSL splita and splitax return indexes instead of the splitted parts

### ISSUE THREAD

**Issue by VesaKoppa** [johnkerl/miller#1693]
With DSL, when using splita or splitax on a text field, to split it on a character, the returned array contains only indexes of the parts.
If you do `splita("a/b", "/")`, the result is `[1,2]`. Expected result is `["a","b"]`.
Miller version 6.13.0 on Windows.

**Comment by aborruso** [comment]
Hi @VesaKoppa, I'm using mlr 6.13 on linux.

If I run 

```
echo 'field=lorem' | mlr --opprint --barred put '$split=splitax("a/b","/")'
```

I get

```
+-------+---------+---------+
| field | split.1 | split.2 |
+-------+---------+---------+
| lorem | a       | b       |
+-------+---------+---------+
```

**Comment by VesaKoppa** [comment]
Hi @aborruso,

I am trying like this (mlr 6.13, windows).

input.csv:
```
ID;Location;Town
1;Fin;Tampere
2;Fin/Swe;ALL
```

mlr_script.txt:
```
Locations = splitax($Location, "/");
$LocNew = joink(Locations, "|");
```

run with:
`mlr --csv --fs semicolon put -f mlr_script.txt input.csv > output.csv`

output.csv:
```
ID;Location;Town;LocNew
1;Fin;Tampere;1
2;Fin/Swe;ALL;1|2
```

I would expect to see `Fin` and `Fin|Swe` in column LocNew. Is it supposed to work like this or am I holding it wrong?

**Comment by aborruso** [comment]
hi @VesaKoppa `joink` is to join the keys. If you use `joinv`

```
mlr --csv --ifs ";" put '$LocNew=joinv(splitax($Location, "/"),"|")' input.csv
```

you get

```
+----+----------+---------+---------+
| ID | Location | Town    | LocNew  |
+----+----------+---------+---------+
| 1  | Fin      | Tampere | Fin     |
| 2  | Fin/Swe  | ALL     | Fin|Swe |
+----+----------+---------+---------+
```

**Comment by VesaKoppa** [comment]
Hi @aborruso and thanks! So I was just using the wrong function...
