### ISSUE TITLE
Join docs wrong link

### ISSUE THREAD

**Issue by jxu** [johnkerl/miller#1694]
The docs for join linked in the man page are not available https://miller.readthedocs.io/en/latest/reference-verbs.html#join

Should be https://miller.readthedocs.io/en/latest/reference-verbs/#join which was not easy to find on google!
I also like https://github.com/johnkerl/miller/discussions/760 as a reference for common joins like inner, outer, left SQL-style joins

**Comment by aborruso** [comment]
> The docs for join linked in the man page are not available [miller.readthedocs.io/en/latest/reference-verbs.html#join](https://miller.readthedocs.io/en/latest/reference-verbs.html#join)

On what page did you find this link? So we correct it
