### ISSUE TITLE
Builing for Conda

### ISSUE THREAD

**Issue by zachcp** [johnkerl/miller#172]
Hi @johnkerl,

Thank you for your wonderful library. 

I am attempting to package Miller for the [conda-forge](https://conda-forge.org/) ecosystem which provides pre-compiled cross-platform binaries.  I am running into a linking error (see below) and I wonder if you have any pointers/suggestions on how to solve it.  

The recipe builds on OSX but runs into an issue building on linux. Have you encountered this issue before?  A few similar issues on Google seems to suggest its an x86 vs x86_64 linking problem.  (I believe Conda-forge only uses x86_64 for builds but would need to check)

Thanks,
zach cp

```
... [from the build report; link below]
...
...
/opt/rh/devtoolset-2/root/usr/bin/ld: cannot find gcrt1.o: No such file or directory
collect2: error: ld returned 1 exit status

```
For Reference:

Link to conda [build script](https://github.com/conda-forge/staged-recipes/pull/5599/files)

Automated Build Error report [here](https://circleci.com/gh/conda-forge/staged-recipes/25761?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

PR triggering the build [here](https://github.com/conda-forge/staged-recipes/pull/5599)

**Comment by johnkerl** [comment]
BTW https://github.com/johnkerl/miller/issues/165 may be related.

**Comment by zachcp** [comment]
Thanks @johnkerl . I've built a number of python libraries and some c/c++ for conda. I usually have to fiddle a bit to get the compilers to work on one or more platforms but once they are done,  they typically are easy to rebuild following updates.  I'll check out #165 and give the package build another go later this week.

**Comment by zachcp** [comment]
Now built for conda
