### ISSUE TITLE
Make resetting of data structure members before memory release configurable

### ISSUE THREAD

**Issue by elfring** [johnkerl/miller#18]
I have noticed that a few function implementations reset members of specific data structures directly before corresponding memory is released.
* [dheap_free](https://github.com/johnkerl/miller/blob/892e69978ac877949cb2c6c5461c61a72f0ec348/c/containers/dheap.c#L79 "Update candidate: dheap_free")
* [hss_free](https://github.com/johnkerl/miller/blob/db2d1ade6a9e97c042a87247550dbf17bfb1d609/c/containers/hss.c#L59 "Update candidate: hss_free")

The following [semantic patch](http://coccinelle.lip6.fr/ "Program transformation with Coccinelle?") can point more update candidates out.
```
@show_modification_before_memory_release@
expression value;
identifier element, var;
@@
 <+...
*var->element = value;
 ...+>
 free(var);
```

I suggest to avoid such extra data modification by default.
How do you think about to make it configurable if you really need to turn this functionality on again?

**Comment by johnkerl** [comment]
I prefer to invalidate about-to-be-freed memory in the off chance it gets reused (which it should not).
