### ISSUE TITLE
--pprint --csv argument-parsing oddity [was: double quote handling appears to be broken again]

### ISSUE THREAD

**Issue by masukomi** [johnkerl/miller#180]
possible re-emergence of issue #4   ( or... a regression in the support for double quotes?)

The following file (foo.csv)
```
id,name,state
5755,"foo,bar",AL
```

produces the following error
```
$ mlr --pprint --csv cat foo.csv 
mlr: syntax error: unwrapped double quote at line 1.
```
version
```
$ mlr --version                                                                                 
Miller 5.3.0
```
on macOS installed via homebrew.

**Comment by johnkerl** [comment]
try `mlr --csv cat foo.csv`, or maybe `mlr --icsv --opprint cat foo.csv`

**Comment by johnkerl** [comment]
i.e. these two should do the same thing:

```
$ mlr --pprint --csv cat foo.csv
mlr: syntax error: unwrapped double quote at line 1.

$ mlr --csv cat foo.csv
id,name,state
5755,"foo,bar",AL
```

**Comment by johnkerl** [comment]
looking at the code, it makes less sense to have `--oneformat` clobber all effects of `--otherformat`. it's important to let people do `--ifs tab --csv` vs. `--csv --ifs tab` and what I proposed earlier would break that. :^/
