### ISSUE TITLE
Is there a way to do regex extract with mlr?

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#183]
Hi,
I know there is gsub, but it would be very  useful to have something to extract only the strings that match a regex.

Thank you

**Comment by johnkerl** [comment]
can you give an example with expected input and expected output?

**Comment by aborruso** [comment]
I have made some corrections to the original text

**Comment by johnkerl** [comment]
this should be pretty quick to code up -- thanks for the request!! :)

**Comment by aborruso** [comment]
@johnkerl then probably it will be in a future release??  :) :) :)

**Comment by aborruso** [comment]
@johnkerl wow, really great!!!

I agree with `regex_extract_or_else`, good idea.

Do you will create a new [release](https://github.com/johnkerl/miller/releases) with this new feature?

Thank you

**Comment by johnkerl** [comment]
OK now we have:

```
$ echo x=abcdef | mlr put '$y=regextract($x, "[cde]+")'
x=abcdef,y=cde

$ echo x=stuvwx | mlr put '$y=regextract($x, "[cde]+")'
x=stuvwx

$ echo x=abcdef | mlr put '$y=regextract_or_else($x, "[cde]+", "")'
x=abcdef,y=cde

$ echo x=stuvwx | mlr put '$y=regextract_or_else($x, "[cde]+", "")'
x=stuvwx,y=
```

which I like quite a bit. @aborruso  what do you think?

**Comment by aborruso** [comment]
@johnkerl really great!

What happens with

    $ echo x=abcdeftorcde | mlr put '$y=regextract($x, "cde")'

I think I will have (and it's ok for me) only the first and than always `x=abcdeftorcde ,y=cde`

Thank you

**Comment by johnkerl** [comment]
awesome. yes, i can emphasize it's first-found.

**Comment by aborruso** [comment]
@johnkerl do you will publish a binary release in github? 

I'm asking it because I'm not sure to be able to compile it

**Comment by johnkerl** [comment]
no worries, i'll make one

**Comment by johnkerl** [comment]
@aborruso what platform do you use btw?

**Comment by aborruso** [comment]
@johnkerl Ubuntu 16.04.3 LTS and sometime Windows 10

**Comment by johnkerl** [comment]
ok. windows is my weak spot; i need to do some more work with appveyor. linuxes, mac, etc. no problem. :)

**Comment by aborruso** [comment]
Linux is perfect!!

**Comment by aborruso** [comment]
I have solved my `make` problem.

I had always `aclocal-1.13' is missing on your system`.

Than I found this solution: run `autoreconf -vfi`.

And now I built mlr in my system and tested the great `regextract` function.

Thank you, thank you, thank you :)

**Comment by johnkerl** [comment]
you're welcome! :)

**Comment by aborruso** [comment]
Please @johnkerl when you have the time please compile a binary release for Linux.
I'm not able to compile it in my production server.

Thank you

**Comment by johnkerl** [comment]
ok @aborruso  please paste me the error you have; i'd like to understand failures to build from source when they arise.

also i can built a static executable on 64-bit centos; should work for you -- ?

**Comment by johnkerl** [comment]
@aborruso :
[mlr.static.x86_64.gz](https://github.com/johnkerl/miller/files/2322125/mlr.static.x86_64.gz)

**Comment by aborruso** [comment]
@johnkerl thank you your file works.

Tonight I have tried again and I have solved also there with `autoreconf -vfi`
