### ISSUE TITLE
too old version in distros

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#186]
Hi John,
the distro versions are very old (in example in ubuntu and debian it's 3.4.0-1).

![image](https://user-images.githubusercontent.com/30607/45021761-b1a47a80-b032-11e8-9d33-c879580ea9ae.png)

I think that it's important to have the latest version in distros repos. I'm not able to help you, it's only a feature request.

Thank you

**Comment by johnkerl** [comment]
thanks, i'll see who i can ping.

**Comment by janfri** [comment]
@aborruso Maybe you can contact the package managers yourself?

**Comment by skitt** [comment]
> the distro versions are very old (in example in ubuntu and debian it's 3.4.0-1).

I’m not sure what versions of Debian and Ubuntu you were looking at, but all their releases have the latest version of Miller at the time they were frozen. So Debian 9 has Miller 4.5.0, Debian 10 will have Miller 5.4.0, Ubuntu 16.04 has 3.4.0, 18.04 and 18.10 have 5.3.0, 19.04 will have 5.4.0.

The update policies of these distributions mean that newer versions aren’t candidates for updates. What I can do is provide newer versions of Miller in Debian’s backports repositories, which would help Debian users at least.

**Comment by aborruso** [comment]
A lot of user click on these buttons, you have in the home of repo. 

![image](https://user-images.githubusercontent.com/30607/55958197-5f7ea400-5c68-11e9-82ba-34e92a34abf0.png)

I think that you Debian idea is very useful. Thank you. And than we could close the issue

**Comment by skitt** [comment]
> I think that you Debian idea is very useful. Thank you. And than we could close the issue

The package is now queued for Stretch backports: https://ftp-master.debian.org/new/miller_5.4.0-1~bpo9+1.html

**Comment by aborruso** [comment]
thank you very much!
