### ISSUE TITLE
Overwrite one of the input file

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#187]
Hi,
is it a way to overwrite one of the input file of a process like `mlr  --csv join -j url -f input1.csv input2.csv` without producing an intermediate file?

Thank you

**Comment by johnkerl** [comment]
Hi @aborruso -- check out `mlr -I` (capital 'i')

**Comment by aborruso** [comment]
@johnkerl and which file is overwritten? input1.csv or input2.csv

Thank you

**Comment by johnkerl** [comment]
`input2.csv`

**Comment by johnkerl** [comment]
`-f` is a flag to `join` and all filenames at the end of the command-line can be overwritten by `mlr -I`. so i guess `-I` info from `man mlr` might have done it -- ? :)
