### ISSUE TITLE
How to work with special chars in field names?

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#188]
Hi,
I need to use something like

    mlr --csv filter '$Prov. == "AG"' input.csv

But the field name contains a dot and it does not work. I have tried with `$Prov\.` and `"$Prov."`, but it's the same.

Thank you

**Comment by johnkerl** [comment]
try `${Prov.}`

**Comment by johnkerl** [comment]
I'll update the FAQ to surface this a bit higher.

**Comment by aborruso** [comment]
Great @johnkerl , thank you

**Comment by johnkerl** [comment]
oops, it's already in the FAQ ;)

http://johnkerl.org/miller/doc/faq.html#How_can_I_handle_field_names_with_special_symbols_in_them?
