### ISSUE TITLE
feature request: add fill down by column

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#189]
Hi,
I love mlr and for this reason I would like to use it for a lot of tasks.

It would be great to have in it something that transform this

|A|B|
|---|---|
|1|6|
|2||
|3||
|4|8|
|5||

in

|A|B|
|---|---|
|1|6|
|2|6|
|3|6|
|4|8|
|5|8|

Using a command in which it's possible to specify which columns you want to fill down.

Thank you

**Comment by johnkerl** [comment]
hmm ok this should be pretty easy with the DSL. and also there could be a fill-from-last-non-null built-in verb so you don't need to write DSL expressions.

**Comment by aborruso** [comment]
hi john, thank you!

I do not find in the documentation anything about `fill-from-last-non-null` verb. Where can I find it?

**Comment by johnkerl** [comment]
no i mean it would be new ;)

**Comment by johnkerl** [comment]
http://johnkerl.org/miller-releases/miller-head/doc/reference-verbs.html#fill-down

Going out in the next release. Thanks @aborruso for the feature request! :)

**Comment by johnkerl** [comment]
@aborruso yes you can compile the new version now if you like.

**Comment by aborruso** [comment]
@johnkerl I have read [this](http://johnkerl.org/miller-releases/miller-head/doc/reference-verbs.html#fill-down) but I do not understand the `-a` option.

Moreover if I use your example input

```
a,b,c
1,,3
4,5,6
7,5,9
```

the output is always the same with or without `-a`.

Thank you

**Comment by johnkerl** [comment]
sorry, the example input is

```
a,b,c
1,,3
4,5,6
7,,9
```

I'll update the doc.

**Comment by johnkerl** [comment]
(This option is less useful for CSV where every record must have the same field-list. It's more useful for DKVP, JSON, etc. wherein a field could be absent on one record and present on another.)

**Comment by aborruso** [comment]
> (This option is less useful for CSV where every record must have the same field-list. It's more useful for DKVP, JSON, etc. wherein a field could be absent on one record and present on another.)

I have it

Hi @johnkerl using

`echo '[{ "a": 2, "b": 3 },{ "a": 1}]' | mlr --json fill-down -a -f b`

or

`echo '[{ "a": 2, "b": 3 },{ "a": 1}]' | mlr --json fill-down -f b`

I have always

```
{ "a": 2, "b": 3 }
{ "a": 1, "b": 3 }
```

Instead if `b` is not absent with `echo '[{ "a": 2, "b": 3 },{ "a": 1,"b":""}]' | mlr --json fill-down -f b` I have

```
{ "a": 2, "b": 3 }
{ "a": 1, "b": 3 }
```

With `-a` using `echo '[{ "a": 2, "b": 3 },{ "a": 1,"b":""}]' | mlr --json fill-down -a -f b` I have

```
{ "a": 2, "b": 3 }
{ "a": 1, "b": "" }
```
