### ISSUE TITLE
CRLF support for file formats other than CSV

### ISSUE THREAD

**Issue by Komosa** [johnkerl/miller#19]
Currently parsing files with CRLF line ending is not supported. (I used simplest possible DKVP file `cat`'ed to `mlr put`)
I know, that now you are working on CSV-RFC4180 support (which explicitly says that CRLF is vaild (and required - :( ).

For now, I can suggest following:
0. at least log warning if CRLF is encountered.
1. silently drop CRLFs

Later of course _proper_ support for line endings should be added :)

BTW. really great tool!

**Comment by johnkerl** [comment]
thanks! yes, rfc-csv currently #1. minimally, adding an option to do CRLF rather than LF is feasible. as an aside, depending on how the technical details work out i may replace my current pointer-walking file parsers with a lemon parser (currently i only use a lemon parser for DSLs, not file data) in which case we could get double-quoting in other formats besides CSV.

**Comment by ve3ied** [comment]
Or, stick tr out front for now.

tr -d '\015' | mlr ...

**Comment by johnkerl** [comment]
Marking as wishlist for now, just relative to other things more pressing -- namely, RFC-CSV and packaging. In the medium term, though, this will be a should-do rather than a wishlist item.

**Comment by johnkerl** [comment]
Dup'ing to https://github.com/johnkerl/miller/issues/50

**Comment by johnkerl** [comment]
Change of plans ... multi-character-separator options for CSV is separately implemented on https://github.com/johnkerl/miller/issues/50. Meanwhile doing that for other formats -- and doing it performantly (RFC-CSV I/O is already slow, and I don't want to make the other formats also slow) -- is a separate, still-open coding task.

**Comment by johnkerl** [comment]
So, I'm re-opening this issue.

**Comment by johnkerl** [comment]
Support exists for DKVP, e.g. `mlr --rs crlf cut -f a,x,y myfile.dkvp`, or `mlr --ifs ': ' --ofs =`, etc.

I'll leave this issue open until other formats also have multi-character support.

**Comment by johnkerl** [comment]
Multi-char-separator CSV-lite done

**Comment by johnkerl** [comment]
Resolved by https://github.com/johnkerl/miller/releases/tag/v2.2.0
