### ISSUE TITLE
Feature proposal: add clean-whitespaces verb

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#190]
Hi,
the more I understand how it works miller, the more ideas (very simple) come to me.

For some cleaning tasks I use the great OpenRefine, or python pandas inside a jupyter notebook.
But these tools sometime are too much and to use mlr for task as the two below is very convenient and quick.

![image](https://user-images.githubusercontent.com/30607/45751155-c6c40080-bc11-11e8-9d1b-38ddc4d30fbc.png).

The generic DSL to do this could be:

```bash
mlr -I --csv --from input.csv put -S '
  for (key, value in $*) {
  $[key] = gsub($[key], "  *"," ");
  $[key] = gsub($[key], "^ ","");
  $[key] = gsub($[key], " $","");
  }
' 
```

A lot of tables require this whitespaces cleaning and I think it would be great to have a verb like `clean-whitespaces`.

Thank you

**Comment by johnkerl** [comment]
awesome idea! :)

**Comment by johnkerl** [comment]
Code on https://github.com/johnkerl/miller/commit/dbef8bb0f8a658eccbd78345f5c0dc30c29f806e

Test output (& therefore examples) on https://github.com/johnkerl/miller/commit/cdfee0cda8fac9645b2d4fcae2323378fbcb8bb9

Docs http://johnkerl.org/miller-releases/miller-head/doc/reference-verbs.html#clean-whitespace

**Comment by johnkerl** [comment]
@aborruso please let me know what you think

**Comment by aborruso** [comment]
Wow, wow, wow, you are great and once again I'm very proud.

It seems exactly my goal!

Thank you

**Comment by johnkerl** [comment]
Happy to help out! :)

**Comment by aborruso** [comment]
@johnkerl if I compile now I will have already this new verb and functions?

Thank you

**Comment by johnkerl** [comment]
@aborruso yes. Also, https://github.com/johnkerl/miller/releases/tag/5.4.0
