### ISSUE TITLE
Implicit Header option for TSV

### ISSUE THREAD

**Issue by techdragon** [johnkerl/miller#191]
While we have the `--implicit-csv-header` option for CSV, it does not appear to have an equivalent when working with TSV files. I tried to use `--implicit-csv-header` and it does nothing for TSV files.

**Comment by johnkerl** [comment]
that's weird, the TSV & CSV code is the same code, only the delimiter is different.

Can you please include some sample data & a repro command?

**Comment by johnkerl** [comment]
```
$ cat foo.csv
a,b,c
d,e,f
$ cat foo.tsv
a	b	c
d	e	f
```

```
$ mlr --icsv --oxtab cat foo.csv
a d
b e
c f
$ mlr --itsv --oxtab cat foo.tsv
a d
b e
c f
```

```
$ mlr --icsv --oxtab --implicit-csv-header cat foo.csv
1 a
2 b
3 c

1 d
2 e
3 f
$ mlr --itsv --oxtab --implicit-csv-header cat foo.tsv
1 a
2 b
3 c

1 d
2 e
3 f
```

I can't reproduce this. Please send me a reproducible scenario; if something's confusing I'm happy to fix that.

**Comment by johnkerl** [comment]
@techdragon please let me know if you have a repro -- thanks!!
