### ISSUE TITLE
About join and unpaired records 

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#193]
Hi,
I have these two files

```
id,color
3,y
2,g
4,r
```

```
idc,colorn
4,red
2,green
```

If I run `mlr --csv join -u -j id -r idc -f ./tmp1.csv ./tmp2.csv` I obtain

```
id,color,colorn
4,r,red
2,g,green
```

If I add `--ul`, then `mlr --csv join --ul -u -j id -r idc -f ./tmp1.csv ./tmp2.csv`, I have

```
id,color,colorn
4,r,red
2,g,green

id,color
3,y
```

Ho to merge all and obtain after this left join something like

id,color,colorn
4,r,red
2,g,green
3,y,
```

Thank you

**Comment by aborruso** [comment]
Is it right with this?

    mlr --csv join --ul --ur -u -j id -r idc -f ./tmp1.csv then unsparsify --fill-with "" ./tmp2.csv

**Comment by johnkerl** [comment]
looks good to me! :) i'll update the FAQ, since this is a very nice tip.

**Comment by johnkerl** [comment]
Commit https://github.com/johnkerl/miller/commit/5f87da809d8d64373090efc8920377a7508ad366 and the next two after.

http://johnkerl.org/miller-releases/miller-head/doc/faq.html#How_to_rectangularize_after_joins_with_unpaired?

Thanks again! :)

**Comment by aborruso** [comment]
I'm very very proud to be in the FAQ of this great project!!!

**Comment by johnkerl** [comment]
:)
