### ISSUE TITLE
documentation bug (in the "unsparsify" section)

### ISSUE THREAD

**Issue by tst2005** [johnkerl/miller#194]
Hello,
[This line](https://github.com/johnkerl/miller/blob/master/doc/mlr.1#L1671) is lost during the documentation generation.
The end of the sentence is missing.

See in the [manpage.txt](https://github.com/johnkerl/miller/blob/master/doc/manpage.txt#L1277-L1278) or in the [manpage.html](https://github.com/johnkerl/miller/blob/master/doc/manpage.html#L1471-L1472)

**Comment by johnkerl** [comment]
@tst2005 thanks!

**Comment by johnkerl** [comment]
great catch!!
