### ISSUE TITLE
Pattern escaping in 'rename' verb

### ISSUE THREAD

**Issue by susanin-ivan** [johnkerl/miller#196]
Hi,

Is it possible to somehow escape "special symbols" in regexp match for rename verb?

For example:

$ jo aa^bb=1 bb^cc=2 cc^dd=3 | mlr --ijson --odkvp --ops $'="' --ors $'"\n' --ofs $'"\n' cat

aa^bb="1"
bb^cc="2"
cc^dd="3"

Here ^ is interpreted exactly as needed (in regexp POV), but not what I wanted:
$ jo aa^bb=1 bb^cc=2 cc^dd=3 | mlr --ijson --odkvp --ops $'="' --ors $'"\n' --ofs $'"\n' rename -r '^,.'

.aa^bb="1"
.bb^cc="2"
.cc^dd="3"

I thought something like this should work (as in  sed 's/\\^/./g'), but not:
$ jo aa^bb=1 bb^cc=2 cc^dd=3 | mlr --ijson --odkvp --ops $'="' --ors $'"\n' --ofs $'"\n' rename -r '\\^,.'

aa^bb="1"
bb^cc="2"
cc^dd="3"

And this one newer ends:
$ jo aa^bb=1 bb^cc=2 cc^dd=3 | mlr --ijson --odkvp --ops $'="' --ors $'"\n' --ofs $'"\n' rename -r -g '^,.'

Current solution for me is to use sed:

$ jo aa^bb=1 bb^cc=2 cc^dd=3 | mlr --ijson --odkvp --ops $'="' --ors $'"\n' --ofs $'"\n' cat | sed 's/\\^/./g'

aa.bb="1"
bb.cc="2"
cc.dd="3"

Thank you!

PS: Miller 5.3.0

**Comment by johnkerl** [comment]
Hi @susanin-ivan -- I should probably make a regex-free version, like the difference between `sub` and `ssub`.

**Comment by johnkerl** [comment]
@susanin-ivan how about:

```
 jo aa^bb=1 bb^cc=2 cc^dd=3 | mlr --ijson --odkvp --ops $'="' --ors $'"\n' --ofs $'"\n' rename -r '[\^],.'
aa.bb="1"
bb.cc="2"
cc.dd="3"
```

**Comment by susanin-ivan** [comment]
@johnkerl 

You are magician :)

Thanks a lot!
