### ISSUE TITLE
new verb proposal: remove completely empty "records"

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#197]
Hi,
I think it could be useful to have a verb that allows you to transform this 

```
field1,field2
a,b
,
a,z
```

to

```
field1,field2
a,b
a,z
```

Sometime, especially with CSV files, there are these ugliness.

Thank you

**Comment by johnkerl** [comment]
http://johnkerl.org/miller-releases/miller-head/doc/reference-verbs.html#skip-trivial-records

**Comment by aborruso** [comment]
wow, thank you!!

I'm sorry, I had no idea

**Comment by johnkerl** [comment]
no no it's brand-new! :)

**Comment by johnkerl** [comment]
so thank you!!

**Comment by aborruso** [comment]
Wow, now - with the third verb proposed and accepted - I feel myself a little little little little little little bit a mlr author :D :D :D

**Comment by aborruso** [comment]
In the doc there is not the typical "Flags" section. Here is only for `-h`

**Comment by johnkerl** [comment]
yes, since there are no options :)
