### ISSUE TITLE
Is there a way to create pivot table?

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#198]
Hi,
is there something to pass from

id | pasta | city | calories
-- | -- | -- | --
1 | Spaghetti | Palermo | 450
2 | Spaghetti | Roma | 500
3 | Lasagna | Roma | 600
4 | Lasagna | Roma | 600
5 | Spaghetti | Roma | 300

to 

pasta | Palermo | Roma
-- | -- | --
Lasagna |   | 2
Spaghetti | 1 | 2

This is a classic example with count of items, but it could be mean calculation of calories

pasta | Palermo | Roma
-- | -- | --
Lasagna |   | 600
Spaghetti | 450 | 400

Thank you very much

**Comment by johnkerl** [comment]
Hmm, `mlr reshape` is close but not quite:

```
$ cat foo.csv
id,pasta,city,calories
1,Spaghetti,Palermo,450
2,Spaghetti,Roma,500
3,Lasagna,Roma,600
4,Lasagna,Roma,600
5,Spaghetti,Roma,300

$ mlr --c2p reshape -s pasta,city then unsparsify foo.csv
id calories Spaghetti Lasagna
1  450      Palermo   -
2  500      Roma      -
3  600      -         Roma
4  600      -         Roma
5  300      Roma      -

$ mlr --c2p reshape -s city,pasta then unsparsify foo.csv
id calories Palermo   Roma
1  450      Spaghetti -
2  500      -         Spaghetti
3  600      -         Lasagna
4  600      -         Lasagna
5  300      -         Spaghetti
```

**Comment by aborruso** [comment]
Thanks

**Comment by xkcd386at** [comment]
almost there :)

start with a stats1-mean, then the rest:

    mlr < in --t2p stats1 -a mean -g city,pasta -f calories then reshape -s city,calories_mean then unsparsify
    pasta     Palermo Roma
    Spaghetti 450     400
    Lasagna   -       600
