### ISSUE TITLE
About specifying input and output format

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#199]
Hi,
I'm a basic user of mlr and I'm becoming mad for stupid thing: specifying input and (especially) output format.

If I run 

    echo '[{"name":"tom","age":22},{"name":"bianca","age":34}]' | mlr --json --csv cat

I have an error, because I must write `--ocsv` for output. I lost (I'm stupid :) ) a lot of minutes to figure out how to correct the above command, for two reasons:

- it's not mandatory to specify `i` and than `--ijson` for input (it works in both ways). Than for me it had to be the same also for output and I was looking for syntax errors only in the input file and not in the command. For me `--csv` had to be ok;
- I think that - I could be wrong - that there is not in documentation a sentence like "to specify the output format prepend `--o` to the format name (i.e. --ocsv, --ojson, etc.) and optionally prepend `--i` for input one". I think it would be good to have it

Probably the right way is to add dedicated section in the documentation, because mlr option for input and output are many:

- `mlr --ijson cat input.json`, to set the input as json and to have the default output;
- `mlr --json cat input.json`, to set the input and output as json;
- `mlr --ijson --ocsv cat input.json`, to set the input as json and to have csv output;
- `mlr --json --ocsv cat input.json`, to set the input as json and to have csv output;
- `mlr --j2c cat input.json`, to set the input  as json and to have csv output;
- `echo "name=tom,age=22\nname=bianca,age=34" | mlr --ocsv cat`, to set csv as output and use the default input format;

Thank you

**Comment by johnkerl** [comment]
Thanks, I will definitely write this up as an FAQ!

Additionally:
* `--ijson --ocsv` is what I would recommend
* `--json` is shorthand for `--ijson --ojson`
* `--foo --obar` isn't quite the same as `--ifoo --obar` in all cases (https://github.com/johnkerl/miller/issues/180).

**Comment by johnkerl** [comment]
http://johnkerl.org/miller-releases/miller-head/doc/reference.html#Formats

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/commit/fbef04e893255932502d2bef048b3f6b042e978f

https://github.com/johnkerl/miller/commit/831cdd7c9b1d1c89aa39640a8cdea8edf409eeec

**Comment by aborruso** [comment]
thank you
