### ISSUE TITLE
Avoiding timegm improves portability

### ISSUE THREAD

**Issue by tkob** [johnkerl/miller#20]
I tried compiling miller on AIX and found that timegm function, which is GNU extension, is missing from AIX libc.
If I replace timegm function, the build completes, although some unit tests still fail (probably another problem).

The timegm man page provides the way to write portable timegm replacement and avoiding timegm would improve portability. How do you think?

**Comment by johnkerl** [comment]
sure if we can have code without #ifdef that passes UTs on one more platform, that's a definite win!

**Comment by johnkerl** [comment]
Merged -- thank you! :)
