### ISSUE TITLE
Strange behavior when changing output format

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#200]
Hi,
I have this input {"name":"tom, aa","age":22},{"name":"bianca","age":34}`.

If I do some format transformation, with the final one again as json I have an output different from input.

In example with

    echo '{"name":"tom, aa","age":22},{"name":"bianca","age":34}' | mlr --j2c cat | mlr --icsv --odkvp cat | mlr --idkvp --ojson cat

I have

```
{ "name": "tom", "2": " aa", "age": 22 }
{ "name": "bianca", "age": 34 }
```

The problem is in the comma in `"name":"tom, aa"` I have in the input. How to prevent this and to have at the end the same structure of the input?

Thank you

**Comment by johnkerl** [comment]
CSV has the feature wherein you can use double-quotes to protect against use of commas within fields. DKVP doesn't, and I've often thought about the idea of adding CSV-style double-quoting support to DKVP format.

An option is to use a different delimiter than comma -- a pipe character, or maybe a tab.

## Before:

```
$ echo '{"name":"tom, aa","age":22},{"name":"bianca","age":34}'
{"name":"tom, aa","age":22},{"name":"bianca","age":34}
```

```
$ echo '{"name":"tom, aa","age":22},{"name":"bianca","age":34}' | mlr --j2c cat
name,age
"tom, aa",22
bianca,34

$ echo '{"name":"tom, aa","age":22},{"name":"bianca","age":34}' | mlr --j2c cat | mlr --icsv --odkvp cat
name=tom, aa,age=22 <------ Here is the problem: no support for quoted-comma use within DKVP
name=bianca,age=34

$ echo '{"name":"tom, aa","age":22},{"name":"bianca","age":34}' | mlr --j2c cat | mlr --icsv --odkvp cat | mlr --idkvp --ojson cat
{ "name": "tom", "2": " aa", "age": 22 }
{ "name": "bianca", "age": 34 }
```

## After:

```
$ echo '{"name":"tom, aa","age":22},{"name":"bianca","age":34}'
{"name":"tom, aa","age":22},{"name":"bianca","age":34}
```

```
$ echo '{"name":"tom, aa","age":22},{"name":"bianca","age":34}' | mlr --j2c cat
name,age
"tom, aa",22
bianca,34
```

```
$ echo '{"name":"tom, aa","age":22},{"name":"bianca","age":34}' | mlr --j2c cat | mlr --icsv --odkvp --ofs pipe cat
name=tom, aa|age=22
name=bianca|age=34
```

```
$ echo '{"name":"tom, aa","age":22},{"name":"bianca","age":34}' | mlr --j2c cat | mlr --icsv --odkvp --ofs pipe cat | mlr --idkvp --ifs pipe --ojson cat
{ "name": "tom, aa", "age": 22 }
{ "name": "bianca", "age": 34 }
```

**Comment by aborruso** [comment]
Thank you very much, as usual very clear and didactic

**Comment by johnkerl** [comment]
http://johnkerl.org/miller-releases/miller-head/doc/faq.html#How_can_I_handle_commas-as-data_in_various_formats?
