### ISSUE TITLE
How to escape "?" in regex?

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#203]
Hi,
if I run

    mlr --j2t put -S '$IMPORTO = gsub($IMPORTO, "(€|\?)","")' input.csv

I have

    mlr: could not compile regex "(€|?)" : Invalid preceding regular expression

How to escape `?` char?

Thank you

**Comment by aborruso** [comment]
Hi,
it seems that I must use `\\\\?`. Am I right?

If yes it's different in example from `$` and `.`.

**Comment by aborruso** [comment]
> it seems that I must use \\\\?. Am I right?

No, it does not work

**Comment by aborruso** [comment]
@johnkerl probably the right way is

    mlr --j2t put -S '$IMPORTO = gsub($IMPORTO, "(€|[?])","")' input.csv

**Comment by johnkerl** [comment]
http://johnkerl.org/miller-releases/miller-head/doc/faq.html#How_to_escape_'?'_in_regexes?

**Comment by aborruso** [comment]
Thank you very much!
