### ISSUE TITLE
Is there a way to do a global search and replace?

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#204]
Hi,
using put and gsub I can do ''$name=gsub($name, "old", "new")''.

Is there a way to do it for all data fields?

Thank you

**Comment by johnkerl** [comment]
@aborruso using the DSL you can do:

```
$ cat foo.csv
a,b,c
the quick,brown fox,jumped
over,the,lazy dogs
```

```
$ cat foo.sh
mlr --csv put '
  for (k in $*) {
    $[k] = gsub($[k], "e", "X");
  }
' foo.csv
```

```
$ sh foo.sh
a,b,c
thX quick,brown fox,jumpXd
ovXr,thX,lazy dogs
```

**Comment by johnkerl** [comment]
I can put this in the Miller FAQ.

**Comment by aborruso** [comment]
@johnkerl to meet you and miller was like opening a gift

**Comment by johnkerl** [comment]
will faq this

**Comment by johnkerl** [comment]
http://johnkerl.org/miller-releases/miller-head/doc/cookbook.html#Search-and-replace_over_all_fields

**Comment by aborruso** [comment]
Thank you @johnkerl
