### ISSUE TITLE
Is it possible to use comments in multiline bash script?

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#205]
Hi,
I would like to insert some comments between lines as in the code below. I think it's very useful for long "then" chains.
But in my code there is the wrong way to do it.

How to do it properly?

Thank you

```bash
#!/bin/bash

mlr --csv filter -S '$Regista =~ ".+"' \
# apply fill-down to "Anno" field
then fill-down -f Anno \
# apply search and replace to "Nazione" field
then put '$Nazione=gsub($Nazione,"/ +","|")' ./input.csv >./output.csv
```

**Comment by johnkerl** [comment]
no and this is a fact of life with bash. comments are to end of "line" and backslashes make one long line. one would need some left-right comment syntax like `/* ... */`
