### ISSUE TITLE
feature request: skip-trivial-fields verb

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#206]
Hi,
I think it could be very useful to have skip-trivial-fields, to delete those fields/columns completely empty for every items/rows.

Thank you

**Comment by johnkerl** [comment]
warning, this will be non-streaming (like `tac`) -- it will need to ingest all rows before emitting any.

**Comment by johnkerl** [comment]
(super-easy to code up though! ;) )

**Comment by johnkerl** [comment]
http://johnkerl.org/miller-releases/miller-head/doc/reference-verbs.html#remove-empty-columns

**Comment by aborruso** [comment]
The couple skip-trivial-fields and remove-empty-columns is for me a big presente and I think it's the same for all people that work with messy data.

mlr is really great. I'm working to do a small course on data, based upon bash and cli, and miller will be the main tool.

**Comment by aborruso** [comment]
@johnkerl it would be great to have a new stable release with remove-empty-columns and skip-trivial-records :)

I have just compiled and these verbs are GREAT
