### ISSUE TITLE
Another item for the FAQ? Filter by date

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#208]
Hi,
starting from

```
date,field
2018-02-03,a
2018-03-07,a
2018-02-03,b
```

apply 

    mlr --csv filter 'strptime($date, "%Y-%m-%d") > strptime("2018-03-03", "%Y-%m-%d")' input.csv

And obtain

```
date,field
2018-03-07,a
```

The FAQ could be "How to filter by date?"

The text could be: It's necessary to parse with [`strptime`](http://johnkerl.org/miller/doc/reference-dsl.html#strptime) the field that contains date info and than apply the filter. In example ...

**Comment by johnkerl** [comment]
http://johnkerl.org/miller-releases/miller-head/doc/faq.html#How_can_I_filter_by_date?

**Comment by aborruso** [comment]
Thank you

**Comment by TechIsCool** [comment]
http://johnkerl.org/miller-releases/miller-5.5.0/doc/faq.html#How_can_I_filter_by_date?
