### ISSUE TITLE
A regex problem: is it possible to use non-greedy matching?

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#210]
Hi,
I have this weird data

```
IMPORTO
.1316,88
.1011552,07 Giugno 2018)
.1011552,07 (Luglio 2018)
. 18721,20
. 30171,36
.20895,70
.24480,25
.42686,27
.35875,00
. 9360,60
. 11716,30
```

I need to transform it in

```
IMPORTO
1316,88
1011552,07 Giugno 2018)
1011552,07 (Luglio 2018)
18721,20
30171,36
20895,70
24480,25
42686,27
35875,00
9360,60
11716,30
```

But I use `mlr --csv put -S '$IMPORTO=gsub($IMPORTO,"^(.*?)([0-9].*)$","\2")' input.csv` and obtain the output below. My regex [seems correct](https://regex101.com/r/A7j82U/1).

What am I doing wrong?

Thank you

```
IMPORTO
8
8)
8)
0
6
0
5
7
0
0
0
```

**Comment by aborruso** [comment]
>
>
> What platform is this on? Using MacOS I get
>
> $ mlr --csv put -S '$IMPORTO=gsub($IMPORTO,"^(.*?)([0-9].*)$","\2")' input.csv
> mlr: could not compile regex "^(.*?)([0-9].*)$" : repetition-operator operand invalid
>
>
With my debian 9 (WSL in Windows10) and Miller v5.4.0-dev I do not have any
error, I have the above output.

Ok, than it's not possible to use repetition-operator in miller (probably
for the regex rules of C). Am I wrong?

Thank you

-- 
___________________

Andrea Borruso
website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E, EPSG:4326
___________________

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino

**Comment by aborruso** [comment]
Hi John

On Sun, 23 Dec 2018 at 18:23, John Kerl <notifications@github.com> wrote:

> But I do have
>
> $ mlr --tsv put -S '$IMPORTO=gsub($IMPORTO,"^(\. *)([0-9].*)$","\2")' input.csv
> IMPORTO
> 1316,88
> 1011552,07 Giugno 2018)
> 1011552,07 (Luglio 2018)
> 18721,20
> 30171,36
> 20895,70
> 24480,25
> 42686,27
> 35875,00
> 9360,60
> 11716,30
>
> thank you.
But this table is really bad, and sometime this field stats with "a",
sometime with "-", etc. than the best solution for me would have been to
use non-greedy regex and `?`

**Comment by johnkerl** [comment]
Miller uses `regcomp` and `regexec` from the `regex` C library from the target system it is compiled for.

**Comment by aborruso** [comment]
Ok, I'm closing the issue, thank you very much

**Comment by aborruso** [comment]
@johnkerl is useful to open an issue related to the problem that I do not have "repetition-operator operand invalid" error?

**Comment by aborruso** [comment]
Dear @johnkerl another great thing that I think it will possible in the GO version of Miller, it will to be able to use non-greedy matching regex.
I do not know if you want to add it in your go README.

**Comment by johnkerl** [comment]
We'll see! :)

**Comment by aborruso** [comment]
Now it's possible to use it `echo 'a=363 2021' | mlr put '$b=sub($a,"^.+?2","")'`

I'm closing it
