### ISSUE TITLE
To have both null values and count

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#213]
Hi,
every time I start to work with a data table I try to print something like

| column | nulls | distinct | mode | min | max | median | mean | stdev |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| county | 0 | 6 |  |  |  |  |  |  |
| tiv_2011 | 0 | 8 |  | 22890.55 | 2850980.31 | 603915.005 | 880033.26 | 1045889.70 |
| tiv_2012 | 0 | 8 |  | 19757.91 | 2785551.63 | 561682.02 | 1061531.46 | 1217782.49 |
| line | 0 | 2 | Residential |  |  |  |  |  |

I know that in miller I could have something similar with stats1 

    mlr --c2x stats1 -a count --fr '^.' flins.csv

```
county_count   8
tiv_2011_count 8
tiv_2012_count 8
line_count     8
```

And I know that I have `FNR` variable and I could use for each record something like `$null=(count-NFR)`, but I'm able to build only verbose script, but I imagine there is a clean way.

However to have in Miller something like pandas `df.describe(include='all')`, that gives as output something like the above table, could be a great thing.

It could be a special option of stats1 verb that uses `--fr '^.'` , that does calculations (sum, mean, interpolated percentiles, etc) for numeric fields and not for text fields (it calculate only count, p,  ecc.).

Thank you

**Comment by aborruso** [comment]
Hi @johnkerl 
after years I have build my [first version of a script](https://github.com/aborruso/millerstat) that starting from 

| id | city | value |
| --- | --- | --- |
| 1 | Palermo | 5 |
| 2 | Palermo | 55 |
| 3 | Milano | 6 |
| 4 |  | 2 |
| 5 | Torino | 2 |

creates this output

| field | fiedlType | min | max | mode | mean | unique | null |
| --- | --- | --- | --- | --- | --- | --- | --- |
| city | string |  |  |  |  | 4 | 1 |
| id | int | 1 | 5 | 1 | 3 | 5 | 0 |
| value | int | 2 | 55 | 2 | 14 | 4 | 0 |

This kind of output is very useful for exploratory data analysis.

**Comment by aborruso** [comment]
@johnkerl  my script is horrible, but I will improve it over time.

My feature request is to add 2 options, to stats1:

- `unique` to have unique values count by field;
- `null`  to have null values count by field.

These are two very useful explorative stats.

**Comment by johnkerl** [comment]
@aborruso as of #1056 we have `null_count` and `distinct_count` accumulators for `mlr summary` as well as `mlr stats1`:

https://miller.readthedocs.io/en/latest/reference-verbs/index.html#stats1

```
$ cat test.csv
a,b,c
1,2,3
,4,5
2,7,9
1,3,2
```

```
$ mlr --c2x stats1 -a null_count,distinct_count -f a,b,c test.csv
a_null_count     1
a_distinct_count 2
b_null_count     0
b_distinct_count 4
c_null_count     0
c_distinct_count 4
```

**Comment by aborruso** [comment]
What a great thing. can't wait for there to be the new release and use it
