### ISSUE TITLE
How to paste two files?

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#216]
Hi,
I would like to paste

```
a,b,c
1,2,3
4,5,6
```

and

```
d
7
8
```

And obtain 

```
a,b,c,d
1,2,3,7
4,5,6,8
```

What's the analogue of `paste` command in Miller?

Thank you

**Comment by aborruso** [comment]
Probably the right way is to use simply paste, there is no a mlr horizontal stack

**Comment by johnkerl** [comment]
agreed -- sorry for the delay. also `mlr cat -n` and `mlr join -j n` perhaps.

**Comment by aborruso** [comment]
> agreed -- sorry for the delay. also mlr cat -n and mlr join -j n perhaps.

Is there an elegant way? I'm able to do with a bash for loop to create the two new output files with cat, and then use join. Is there a better way (I think yes).

Thank you
