### ISSUE TITLE
Not able to calculate min and max with string-cast on integerable fields (needs mlr stats1 -S)

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#219]
Hi,
I have this input

```
0164318,001449,001452,001922  
0164318,001456,001457,001922  
0842179,002115,002118,001485  
0846354,001512,001513,001590  
0841422,001221,001224,001860  
0841422,001227,001228,001860
```

If I run `mlr --opprint --inidx --ifs , stats1 -g 1 -a max -f 3 input` I have 

```
1       3_max
0164318 815
0842179 2118.000000
0846354 843
0841422 1228.000000
```

But the max for `3` for `0164318` is not "815", it's "001457". It seems that it's necessary to apply something like `-S`, but I do not know how to do it with `stats1`. 

Thank you

**Comment by aborruso** [comment]
The way that works is

`mlr --ocsv --quote-all --inidx --ifs , cat imput | mlr --opprint --icsvlite stats1 -g '"1"' -a max -f '"3"'`

It seems to me not very elegant

**Comment by johnkerl** [comment]
agreed. `stats1` should have a `-S`.

**Comment by johnkerl** [comment]
BTW 815 in decimal is 1457 in octal -- inferred due to the leading 0

**Comment by johnkerl** [comment]
@aborruso I believe this is resolved by https://github.com/johnkerl/miller/pull/788 / https://github.com/johnkerl/miller/issues/756 along with `mlr -S` (https://miller.readthedocs.io/en/latest/reference-main-flag-list/index.html#miscellaneous-flags). If I'm mistaken please let me know and we can re-open ...
