### ISSUE TITLE
JSON output doesn't escape quote and backslahes when using --jvquoteall

### ISSUE THREAD

**Issue by rgiordani** [johnkerl/miller#222]
Issue #115 i fixed, but not when using --jvquoteall

$ mlr --icsv --ojson --rs lf cat <<EOF
col
"abc ""def"" \ghi"
EOF

{ "col": "abc \"def\" \\ghi" }

$ mlr --icsv --ojson --jvquoteall --rs lf cat <<EOF
col
"abc ""def"" \ghi"
EOF

{ "col": "abc "def" \ghi" }

Using the 5.4.0 release on Ubuntu.

**Comment by johnkerl** [comment]
Fixed by https://github.com/johnkerl/miller/commit/1d4d41d87cc6b66c47e6594a807e451fd82cb659 -- thank you!! :)
