### ISSUE TITLE
how to mix mlr command with other utilities output

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#223]
Hi,
if I run (using `echo` inside a mlr command)

```
echo "field1=a,field2=b" | mlr --ocsv put '$field3="'$(echo "ca")'"'
```

I have

```
field1,field2,field3
a,b,ca
```

If I add a space, `$(echo "c a")`, I have this error

    mlr put: syntax error on DSL parse of '$field3="c'

It seems that I need to escape the space. But why and how to do it?

Thank you

**Comment by aborruso** [comment]
My goal was to reply to this question in stack exchange https://unix.stackexchange.com/q/497375/195582

**Comment by aborruso** [comment]
Hi @johnkerl I add a use case.

I have a column with italian short month name. In example I have "05-LUG-2019", where LUG is the short for july.

To "normalize" date values usually it I use a great cli utility, [dateutils](https://github.com/hroptatyr/dateutils), and in example with

    dconv --from-locale it_IT -i "%d-%b-%Y" "05-LUG-2019"

I have `2019-07-05`.

My date values are in a field where I must apply `regextract` to have it -  `put '$data=regextract($2,"[0-9]{1,}-[a-zA-Z]{1,}-[0-9]{1,}")'` - and it works great. But I need also to edit it with dateutils.

But how to apply dconv  to regextract output in a bash script?

Thank you

**Comment by splintax** [comment]
Hi @aborruso. That was my question on Stack Exchange, thanks for looking at it! I just added an answer to my own question after a building up a few weeks of experience with Miller. Thank you @johnkerl for this fantastic tool!

Getting input in and out of Miller is usually pretty easy considering that CSV-like data has been native to unix for ages (using `IFS=,` and `read`). But you often need to use `--implicit-csv-header foo,bar` and `--headerless-csv-output` in a pipeline, and these flags are pretty verbose! Could we perhaps get a one-letter flag for these options, and a single option like `--header foo,bar` to shorten `--implicit-csv-header label foo,bar`?

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/commit/4befcff604bcf05bfd1df6a21c4024d55d9fc29f makes `-N` a keystroke-saver for `--implicit-csv-header --headerless-csv-output`

**Comment by johnkerl** [comment]
@aborruso let me know if we should re-open this -- thanks!
