### ISSUE TITLE
Is it possible to sort per row by value using DSL

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#227]
Hi,
I have this kind of data

```
field1=a,field2=o,field3=e
field1=c,field2=a,field3=b
```

How is it possible to order every row by value and have

```
field1=a,field3=e,field2=o
field2=a,field3=b,field1=c
```

I do not see order function in DSL.

Thank you

**Comment by johnkerl** [comment]
That would be easy enough to code up in C. :)

**Comment by aborruso** [comment]
I'm adding a new verb feature request: sort by field name.

From 

    field3=a,field2=o,field1=e

to

    field1=e,field2=o,field3=a

Thank you

**Comment by aborruso** [comment]
A tool to sort by field name is datamash (the input is a TSV)

    datamash transpose  -H <file_in.csv | sort -V | datamash transpose -H >file_out.csv

**Comment by johnkerl** [comment]
Note: this will implement sort-by-name (https://github.com/johnkerl/miller/issues/258) as well as sort-by-value.

**Comment by johnkerl** [comment]
Closing out this old issue:

There is the `sort-within-records` verbs, and as of Miller 6 (soon to be released) a `sort` DSL function. Example:

```
$ echo field3=a,field2=o,field1=e | mlr sort-within-records
field1=e,field2=o,field3=a

$ echo field3=a,field2=o,field1=e | mlr put '$* = sort($*)'
field1=e,field2=o,field3=a

# Sort by key (which is the default anyway):
$ echo field3=a,field2=o,field1=e | mlr put '$* = sort($*, func(ka,va,kb,vb) { return ka <=> kb})'
field1=e,field2=o,field3=a

# Sort by value:
$ echo field3=a,field2=o,field1=e | mlr put '$* = sort($*, func(ka,va,kb,vb) { return va <=> vb})'
field3=a,field1=e,field2=o
```

See also https://miller.readthedocs.io/en/latest/sorting/
