### ISSUE TITLE
strptime doesn't work

### ISSUE THREAD

**Issue by kundeng** [johnkerl/miller#228]
The time looks like:
Mon Feb 04 00:08:48 EST 2019

The format string is pi_timeformat = "%a %b %d %H:%M:%S %Z %Y";

epoc= strptime($LastSeen, pi_timeformat); print "epoc=" . epoc; 

gave error.   This string works fine with original python code.

**Comment by kundeng** [comment]
If you use glibc,  you should be able to include timezone info in the input. 

https://linux.die.net/man/3/strptime

**Comment by johnkerl** [comment]
@kundeng sorry for the long delay on this.

Miller has been re-written in Go (see also https://github.com/johnkerl/miller/issues/372) and one of several reasons (https://github.com/johnkerl/miller/blob/main/README-go-port.md) was to get access to some better library functions including date-time things.

In Miller 6 we now have this:

```
$ cat foo.dat
x=Mon Feb 04 00:08:48 EST 2019

$ mlr --from foo.dat put 'epoc= strptime($x, "%a %b %d %H:%M:%S %Z %Y"); print "epoc=" . epoc'
epoc=1549238928
x=Mon Feb 04 00:08:48 EST 2019
```

which I believe resolves this issue.

Please let me know if I've misunderstood and we need to re-open -- thanks!
