### ISSUE TITLE
'nest' verb behaves differently for tab-delimited vs. JSON output formats

### ISSUE THREAD

**Issue by ernstki** [johnkerl/miller#232]
I have a related [Unix & Linux Stack Exchange question](https://unix.stackexchange.com/q/504891/278323) about this—which is _super_-verbose right now, but I'll edit it later, once I figure out what the root of the problem is.

Here's the gist: the `nest` verb seems to have different behavior depending on whether the output format is JSON or tab-separated values. At this point, I'm not sure if it's just because I'm not used to thinking like Miller, I don't understand what the `nest` verb is supposed to do, or the appropriate context where it's supposed to be used, or if I've found a bug.

(I was similarly unsuccessful with using DSL functions like `splitnv` to accomplish my goal, which is simply to reverse `LastName, Firstname` into `Firstname LastName` in the output... but that's not what this issue is about.)

Given an input record with one column called `last_first` and the value `LastName, Firstname`, here's what I get when using the `-T` option (tab-delimited for input and output):

```bash
echo -e "last_first\nLastName, Firstname" \
  | mlr -T nest --explode --values --across-fields --nested-fs , -f last_first

# result (no delimiter here, just one field, confirmed w/ 'cat -A')
# last_first
# LastName, Firstname

# expected:
# last_first_1<tab>last_first_2
# LastName,<tab> Firstname
```

Here is the same result (as expected), using JSON as the output format:

```bash
echo -e "last_first\nLastName, Firstname" \
  | mlr --t2j nest --explode --values --across-fields --nested-fs , -f last_first

# result (as expected)
# { "last_first_1": "LastName", "last_first_2": " Firstname" }
```

I am using Miller 5.4.0, built from source.

**Comment by aborruso** [comment]
Hi,
if I run 

```bash
echo -e "last_first\nLastName, Firstname" | \
mlr --tsv nest --explode --values --across-fields --nested-fs "," -f last_first \
then clean-whitespace
```

I have (tab is the separator)

```
last_first_1    last_first_2
LastName        Firstname
```

I'm using Miller 5.4.0-dev

**Comment by ernstki** [comment]
Apologies, all. This was user error.

The `-T` option is a shorthand for `--nidx --fs tab` (as _clearly_ stated in the manual), and what I was giving Miller was _clearly_ not a numerically-indexed file, as it had a header row.
