### ISSUE TITLE
mlr cut csv: empty output when referencing columns by name (differences in behaviour between script and CLI)

### ISSUE THREAD

**Issue by quinncomendant** [johnkerl/miller#234]
I am unable to use `mlr cut` referencing columns by name using Miller 5.4.0 on macOS. Referencing columns numerically, I get the output I expect. 

I'm trying to get a couple fields out of the CSV produced by an IMDB watchlist ([download the csv here](https://www.imdb.com/list/ls009272523/export)):

    Position,Const,Created,Modified,Description,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors
    1,tt0072443,2012-07-10,2012-07-10,,Zerkalo,https://www.imdb.com/title/tt0072443/,movie,8.1,107,1975,"Biography, Drama",31268,1975-07-31,Andrei Tarkovsky
    2,tt0050634,2012-07-10,2012-07-10,,Letyat zhuravli,https://www.imdb.com/title/tt0050634/,movie,8.3,95,1957,"Drama, Romance, War",12689,1957-10-12,Mikhail Kalatozov
    3,tt0057358,2012-07-10,2012-07-10,,Nattvardsgästerna,https://www.imdb.com/title/tt0057358/,movie,8.1,81,1963,Drama,18322,1963-02-09,Ingmar Bergman

The output of `file imdb-watchlist.csv` is:

    imdb-watchlist.csv: ISO-8859 text

 I want the get the `Title` and `URL` fields, so I'm doing this:

    mlr --csv cut -f 'Title,URL' imdb-watchlist.csv

The resulting output is 78 blank lines.

I also tried:

    mlr --csv --fs comma --rs lf cut -f 'Title,URL' imdb-watchlist.csv
    mlr --csvlite --fs comma --rs lf cut -f 'Title,URL' imdb-watchlist.csv

And other variations. Always empty output.

If I reference columns numerically, I _do_ get the output I expect.

    mlr --csv cut -f '6,7' imdb-watchlist.csv

I found the FAQ entry _[No output at all](https://johnkerl.org/miller/doc/faq.html#No_output_at_all)_ which suggests checking for non-printing characters. The output from `cat -ev imdb-watchlist.csv` does not show any non-printing characters.

Is my usage wrong? Is the file from IMDB corrupt?

**Comment by quinncomendant** [comment]
Plot twist: when using `mlr` inside a shell script, even referencing columns numerically fails. 

    #!/bin/bash
    mlr --csv cut -f 1 ~/imdb-watchlist.csv

Executing the above script outputs 78 blank lines. Running `mlr --csv cut -f 1 ~/imdb-watchlist.csv` alone in the terminal prints the contents of the first column. 🤷‍♂️

**Comment by aborruso** [comment]
Hi @quinncomendant ,
I'm using mlr 5.4.0 on Debian.

When I run

    curl -s https://www.imdb.com/list/ls009272523/export | mlr --csv cut -f 'Title,URL' | head

I have no problem

![image](https://user-images.githubusercontent.com/30607/54142377-d5081200-4427-11e9-8e99-d095a7671833.png)

To have empty rows is ok when you use `curl -s https://www.imdb.com/list/ls009272523/export | mlr --csv cut -f 6 | head -3` because in the csv there is no field called "6".

If you want to use numeric reference you could use this command

    curl -s https://www.imdb.com/list/ls009272523/export | tail -n +2 | mlr --csv --implicit-csv-header --headerless-csv-output cut -f 6 | head

to have

```
Zerkalo
Letyat zhuravli
Nattvardsgsterna
Partido Alto
Nelson Cavaquinho
Orfeu Negro
Karamazovi
Sans soleil
Dor
Aparajito
```

**Comment by quinncomendant** [comment]
Solved it:

The difference between a command running in a shell script vs. on the command line directly is that a shell running a script is always a non-interactive shell. In my environment, I was loading some environment variables, functions, and aliases only if the shell is interactive, using this:

    # If shell is not really interactive, don't process further.
    [[ $- == *i* ]] || return;
    
    # … further down …
    
    alias mlr="mlr --some-options-that-bit-me-in-the-ass";

The alias for `mlr` I had defined for interactive sessions caused the strange behaviour I experienced earlier.

@aborruso Thanks for the tip on using numeric references. Obvious in hindsight. :D
