### ISSUE TITLE
how to rename the nth field? and, make a capitalize function

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#236]
Hi,
I have this input file.

```
one,two,THREE,four
3,4,6,1
4,4,5,2
```

If I want to rename the third field, transforming it in lowecase, I can run:

    mlr --nidx --fs "," put -S 'if (NR == 1) {counter=1; for (key in $*) { if (counter == 3) { $[key]=tolower($[key]); } counter += 1; }}' input.txt

Is there not any way to use something simpler? Is there something like to awk and work directly on $3?

And is there a simpler way to have for the third field only the first letter in uppercase?

    mlr --nidx --fs "," put -S 'if (NR == 1) {counter=1; for (key in $*) { if (counter == 3) { $[key]=toupper(gsub($[key],"^(.)(.+)$","\1")).tolower(gsub($[key],"^(.)(.+)$","\2")); } counter += 1; }}' input.txt

Thank you

**Comment by johnkerl** [comment]
I was rather strident about making Miller name-indexed rather than position-indexed -- this (along with support for multiple file formats) being Miller's entire reason for existing.

That said, some way to access fields by position simpler than the (very nice) DSL bit you wrote would be useful.

Secondly, for the uppercase-first-letter, we can definitely make a `capitalize` function.

**Comment by aborruso** [comment]
@johnkerl what do you think of this issue? Do I close it and open a new one with capitalize function feature request?

**Comment by johnkerl** [comment]
The `capitalize` function is on https://github.com/johnkerl/miller/commit/acc529e9f408c99bad3547c3437aee20a29193a2

**Comment by johnkerl** [comment]
For the position-indexing I think the easiest would be a DSL function `nth_field($*, 3)` ... but that would only work on right-hand sides not left-hand sides ..... maybe even better some `$[[3]]` syntax .......

**Comment by aborruso** [comment]
Hi @johnkerl as usual thank you.

For the position-indexing I do not understand the hand sides fact. But you don't need to explain it to me, I'm sure you'll choose a good implementation

**Comment by johnkerl** [comment]
Idea is `$[[3]]` would get you the name of the 3rd field.

Then `$[ $[[3]] ]` would be the value at the 3rd field which can be shorthanded to `$[[[3]]]`.

Examples:
```
................................................................
mlr --c2p cat input.txt
one two three four
a   b   c     d
e   f   g     h
```

```
................................................................
mlr --c2p put '$[[3]] = capitalize($[[3]])' input.txt
one two Three four
a   b   c     d
e   f   g     h

................................................................
mlr --c2p put '$[[[3]]] = capitalize($[[[3]]])' input.txt
one two three four
a   b   C     d
e   f   G     h
```

```
................................................................
mlr --c2p put '$foo = capitalize($[[3]])' input.txt
one two three four foo
a   b   c     d    Three
e   f   g     h    Three

................................................................
mlr --c2p put '$foo = capitalize($[[[3]]])' input.txt
one two three four foo
a   b   c     d    C
e   f   g     h    G
```

```
................................................................
mlr --c2p put '$[[3]] = "NEW"' input.txt
one two NEW four
a   b   c   d
e   f   g   h

................................................................
mlr --c2p put '$[[[3]]] = "NEW"' input.txt
one two three four
a   b   NEW   d
e   f   NEW   h
```

**Comment by aborruso** [comment]
@johnkerl WOWWWW!

Is it only a demo or do you have it in your PC and testing it??

**Comment by johnkerl** [comment]
the latter, should be able to push later this week

**Comment by johnkerl** [comment]
@aborruso https://github.com/johnkerl/miller/commit/136d0244c028c6b2505e02810267f03721bac1ee contains the raw feature (as noted above) but there will be a couple more commits, one with regression-testing and another with documentation updates.

Also I'll soon make a Miller 5.5.0; this is worth it. :D

**Comment by johnkerl** [comment]
@aborruso OK the reg-test and doc commits are in head along with the feature commit.

As for 5.4.0 ... it's definitely time (almost a year since 5.3.0!!) but I need to hold off a bit as there is one incomplete feature (`sort-within-records`) needing finishing, or temporarily reverting out of 5.4.0 & putting back in incomplete for 5.4.0-dev.

**Comment by aborruso** [comment]
Wow, this is really a great project and you are a special man!

Then I can compile mlr and test the positional-indexing feature. Am I right?

What's `sort-within-records` feature?

Thank you very very much

**Comment by johnkerl** [comment]
yes correct!

`sort-within-records` is for https://github.com/johnkerl/miller/issues/258

**Comment by aborruso** [comment]
> `sort-within-records` is for #258

Thank you again, very useful!

**Comment by aborruso** [comment]
A last question: is sort-within-records already available in the current code? I understood not, but I would like to be sure

**Comment by aborruso** [comment]
mmm, I think yes, wow, I must try it!!

![image](https://user-images.githubusercontent.com/30607/64061294-2627e000-cbd9-11e9-9a9c-a750012ea393.png)

**Comment by johnkerl** [comment]
`sort-within-records` exists by name but is a skeleton. I'll mask it out for the 5.5.0 release since it doesn't actually do anything and will only confuse people.

**Comment by johnkerl** [comment]
I'm making 5.5.0 now.

Thanks again for the great feature requests!! :)

**Comment by aborruso** [comment]
> `sort-within-records` exists by name but is a skeleton. I'll mask it out for the 5.5.0 release since it doesn't actually do anything and will only confuse people.

I hope to see it in the next months in a 5.5 dev, because for me is a great new feature.

As usual thank you very very much
