### ISSUE TITLE
Clean up warnings in Lemon and Lemon-generated code

### ISSUE THREAD

**Issue by johnkerl** [johnkerl/miller#24]
I don't think anything here is problematic per se, but a nice clean `-Werror` build in `c/dsls/` (as we currently already have in the Miller-per-se code in `c/`) would be a nice-to-have.

**Comment by SikhNerd** [comment]
Why not include lemon as a precompiled header since it will likely not be updated much?

**Comment by johnkerl** [comment]
`-Wall` won't be in the offing due to some unused static functions defined by `flex`. But, the warnings are gone, which was the main goal here.

**Comment by johnkerl** [comment]
@sikhnerd re precompiled: good thought. But, if there are actionable warnings, I want to deal with them whenever the lemon output is generated (no matter how infrequently).
