### ISSUE TITLE
"nan" being interpreted as floating point in JSON output

### ISSUE THREAD

**Issue by joatca** [johnkerl/miller#241]
I'm using `mlr --idkvp --irs $'\n\n' --ifs $'\n' --ips ': ' --ojson cat` to convert from LDIF (from LDAP) to JSON. This mostly works fine but with this particular piece of (sample) data:

```
dn: uid=foo,ou=People,dc=example,dc=com
uid: fannan
sn: fan
givenName: nan
mail: nani@example.com
uidNumber: 1234
gidNumber: 1234
homeDirectory: /home/fannan
o: ExampleU
preferredLanguage: en
cn: nan fan
```

...this is the output:

```
{ "dn": "uid=foo,ou=People,dc=example,dc=com", "uid": "fannan", "sn": "fan", "givenName": nan, "mail": "nani@example.com", "uidNumber": 1234, "gidNumber": 1234, "homeDirectory": "/home/fannan", "o": "ExampleU", "preferredLanguage": "en", "cn": "nan fan", "12": "" }
```

`jq` chokes on that because `givenName` isn't a string and appears to have been interpreted as a float. Adding `--jquoteall` fixes it but obviously also quotes the uid and gid numbers.

Could be fixed with a heuristic... if a field in many records is a string then always interpret it as a string even when it looks like a number, but that suffers from obvious problems if the first record looks like a number. Maybe also an option to force-quote certain fields like `--jquotefield=givenName` ?

**Comment by johnkerl** [comment]
@joatca thanks. This is definitely a problem. As you point out there are several ways to handle it. Another one might be an option to not scan `inf` and `nan` in otherwise-numeric fields -- this would be a stateless solution. Force-quoting by field is also stateless. The stateful heuristic I also like in principle (although it would take a bit more coding).

**Comment by johnkerl** [comment]
This is addressed in Miller 6 -- https://johnkerl.org/miller6/reference-main-data-types/#type-inference-for-literal-and-record-data

**Comment by johnkerl** [comment]
Fixed in Miller 6.
