### ISSUE TITLE
DSL keyless map constructor (Lua-style)

### ISSUE THREAD

**Issue by divtiply** [johnkerl/miller#242]
Allow [Lua-style](https://www.lua.org/pil/3.6.html) map constructors without specifying keys.
```
days = {"Sunday", "Monday", "Tuesday", "Wednesday",
        "Thursday", "Friday", "Saturday"}
```
will initialize `days[1]` with the string "Sunday" (the first element has always index 1, not 0), `days[2]` with "Monday", and so on; in other words, shorthand equivalent of
```
days = {1: "Sunday", 2: "Monday", 3: "Tuesday", 4: "Wednesday",
        5: "Thursday", 6: "Friday", 7: "Saturday"}
```

**Comment by johnkerl** [comment]
nice!!

**Comment by johnkerl** [comment]
In the Go port (https://github.com/johnkerl/miller/issues/372) there are arrays per se ...

An option here is JavaScript-style `{x, y}` which is the same as `{x:x, y:y}` ...

**Comment by johnkerl** [comment]
Fixed in Miller 6.
