### ISSUE TITLE
How to create n random floating values between x and y?

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#243]
Hi,
I'm sure there is a very simple way to do it, combining math and some Miller verbs.

Starting from n=10, x=13.565, y=17.859, I need to create n random floating values between x and y.

Is this a right way?

    mlr -n --opprint seqgen --stop 10 then put '$value=urand()*4.294+13.565'

Thank you for ideas and time

**Comment by johnkerl** [comment]
Looks good to me!! :)

You could use some min/max oosvars if you like:

```
mlr -n --nidx seqgen --stop 10 then put 'begin {@min = 13.565; @max_diff = 4.294} $value=@min+@max_diff*urand()'

mlr -n --nidx seqgen --stop 10 then put 'begin {@min = 13.565; @max = 17.859} $value=@min+(@max-@min)*urand()'
```

**Comment by aborruso** [comment]
Thank you very much

**Comment by aborruso** [comment]
@johnkerl what's the meaning of oosvars?

Thank you

**Comment by johnkerl** [comment]
Sorry, out-of-stream variables -- prefixed with `@` -- they persist across records.

https://johnkerl.org/miller/doc/reference-dsl.html#Out-of-stream_variables

I'll reopen this as a to-do to make an FAQ entry.

**Comment by aborruso** [comment]
As usual thank you very much @johnkerl !

Using out-of-stream variables is it more elegant? Is it more efficient? Or both? 
I mean for this task about random values generation

**Comment by johnkerl** [comment]
It's a bit more elegant since the min and max are named and it makes the code easier to reuse. Also there should be a `randrange(a, b)` which is uniformly distributed on the interval `[a, b)`.

**Comment by johnkerl** [comment]
Please leave open -- I want to make an FAQ entry, and `randrange(a,b)` is definitely worth doing.

**Comment by johnkerl** [comment]
There is a new `urandrange` as of https://github.com/johnkerl/miller/commit/f85f84b1dd2dfc7fbedc20aeed9a279b42e4cb4b

**Comment by johnkerl** [comment]
No FAQ entry needed since there's a function now :)

**Comment by aborruso** [comment]
Wow, thank you very much @johnkerl

**Comment by johnkerl** [comment]
`urandrange` is in https://github.com/johnkerl/miller/releases/tag/v5.5.0

**Comment by aborruso** [comment]
@johnkerl it's a great release ;)
