### ISSUE TITLE
mlr, curl and CSV with empty cell at the end

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#251]
Hi,
id I run

```bash
curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vTnnMlAs8-3WniJYJH4H11opWzI2tOk-mz4afBleN95qpulZ4RreffYNH1sVmKGmQRgUkKEtZTYeJn3/pub?gid=0&single=true&output=csv" >tmp.cvs
mlr --csv cat tmp.csv
```

I have

```
nome,età
Andy,45
John,
```

But if I pass to mlr via pipe

    curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vTnnMlAs8-3WniJYJH4H11opWzI2tOk-mz4afBleN95qpulZ4RreffYNH1sVmKGmQRgUkKEtZTYeJn3/pub?gid=0&single=true&output=csv" | mlr --csv cat

I have

```
nome,età
Andy,45
mlr: syntax error: record-ending field separator at line 2.
```

because there is not  `\n`.

And a solution is to use

    curl -w "\n" -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vTnnMlAs8-3WniJYJH4H11opWzI2tOk-mz4afBleN95qpulZ4RreffYNH1sVmKGmQRgUkKEtZTYeJn3/pub?gid=0&single=true&output=csv" | mlr --csv cat

Probably mlr does properly its job, but curl is for a lot of people an everyday tool, and when I have this error, in the first minutes  I can't understand the cause.

If it makes sense, this is a request to make it natively compatible with curl output (also with CSV with empty cell at the end).

Thank you

**Comment by johnkerl** [comment]
It isn't curl's fault ... it's because Miller uses `mmap` by default (for ~20% performance increase) when it can, except that reading input off a pipe it cannot. There are two readers for every file format: one using `mmap` and one using `stdio`. This case reveals that there is a long-standing bug in the stdio-based CSV reader.

```
$ cat tmp.cvs
nome,età
Andy,45 <---- no EOL here
```

```
$ mlr --c2x --mmap cat tmp.cvs
nome Andy
età  45

nome John
età
```

```
$ mlr --c2x --no-mmap cat tmp.cvs
nome Andy
età  45
mlr: syntax error: record-ending field separator at line 2.
```

**Comment by johnkerl** [comment]
In particular the bug is only when there is no EOL *and* the last field is empty.

**Comment by aborruso** [comment]
Grazie @johnkerl

**Comment by johnkerl** [comment]
Prego!
