### ISSUE TITLE
label verb misbehaves when a 'new' name is same as an 'old' name

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#253]
Hi,
I have this input file

```
codiceComune,REGIONE,COMUNE_1
066001,ABRUZZO,ACCIANO
066002,ABRUZZO,AIELLI
066003,ABRUZZO,ALFEDENA
066004,ABRUZZO,ANVERSA DEGLI ABRUZZI
```

If I run

    mlr --csv label codiceComune,nomeRegione,nomeComune input.csv

I have only two fields in output

```
nomeRegione,nomeComune
ABRUZZO,ACCIANO
ABRUZZO,AIELLI
ABRUZZO,ALFEDENA
ABRUZZO,ANVERSA DEGLI ABRUZZI
```

If I change it in `label codicecomune,nomeRegione,nomeComune` I have all the fields.

Is it normal? It seems that it skips field name that already exists.

Thank you

**Comment by johnkerl** [comment]
Yes and this is an easy fix. As a pleasant side-effect it will also make `rename` run faster. :)

**Comment by johnkerl** [comment]
```
$ cat input.csv
codiceComune,REGIONE,COMUNE_1
066001,ABRUZZO,ACCIANO
066002,ABRUZZO,AIELLI
066003,ABRUZZO,ALFEDENA
066004,ABRUZZO,ANVERSA DEGLI ABRUZZI
```

```
$ mlr --csv label codiceComune,nomeRegione,nomeComune input.csv
codiceComune,nomeRegione,nomeComune
066001,ABRUZZO,ACCIANO
066002,ABRUZZO,AIELLI
066003,ABRUZZO,ALFEDENA
066004,ABRUZZO,ANVERSA DEGLI ABRUZZI
```

**Comment by johnkerl** [comment]
The code is pushed to head. This will go into 5.6.0.

Thanks!!! :)

**Comment by aborruso** [comment]
@johnkerl thank you very much
