### ISSUE TITLE
toupper does not work with accented chars

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#254]
Hi,
if I run `echo 'name="Andreà"' | mlr put '$upper=toupper($name)'` I have back `name="Andreà",upper="ANDREà"` and not `name="Andreà",upper="ANDREÀ"`.

The à char is the same after toupper.

Thank you

**Comment by johnkerl** [comment]
oops, thanks!

**Comment by johnkerl** [comment]
So ... Miller handles UTF-8 mostly by accident. Normally it operates on sequences of bytes and the only time it really pays attention to the encoding is in the `strlen` DSL function.

https://github.com/johnkerl/miller/blob/master/c/lib/mlrutil.c#L324-L335

Even regexes work by accident -- the old and new multi-byte sequences are strings of bytes and the particular location of 'letter' boundaries is something Miller can remain blissfully ignorant of:

```
$ mlr put '$a=sub($a, "e", "é")' \
  then put '$new=$a' \
  then put '$new = gsub($new, "é", "açoît")' \
  ../data/small
a=pan,b=pan,i=1,x=0.3467901443380824,y=0.7268028627434533,new=pan
a=éks,b=pan,i=2,x=0.7586799647899636,y=0.5221511083334797,new=açoîtks
a=wyé,b=wye,i=3,x=0.20460330576630303,y=0.33831852551664776,new=wyaçoît
a=éks,b=wye,i=4,x=0.38139939387114097,y=0.13418874328430463,new=açoîtks
a=wyé,b=pan,i=5,x=0.5732889198020006,y=0.8636244699032729,new=wyaçoît
```

The `toupper`, `tolower`, and `capitalize` functions are places Miller will need to look at the multi-byte letters and do meaningful things with them. Either by taking a new dependency on a UTF-8 library, or by hand-coding some one-off logic (as in `strlen`, above).

**Comment by johnkerl** [comment]
Wow, I found https://github.com/sheredom/utf8.h -- very nice!

```
$ cat reg_test/input/utf8-1.csv
langue,nom,jour
français,françois,vendredi
```

```
$ mlr --csv put '$langue=toupper($langue)' reg_test/input/utf8-1.csv
langue,nom,jour
FRANÇAIS,françois,vendredi
```

```
$ mlr --csv put '$nom=toupper($nom)' reg_test/input/utf8-1.csv
langue,nom,jour
français,FRANÇOIS,vendredi
```

**Comment by aborruso** [comment]
@johnkerl you are a magic box!

Andreà :D

**Comment by johnkerl** [comment]
OK this was quick and nice! :) This is all committed to head now (code, test, docs) and will go out with 5.6.0.
