### ISSUE TITLE
High memory usage with thousand files on input.

### ISSUE THREAD

**Issue by Fuco1** [johnkerl/miller#256]
Hey, I seem to be having similar issues to #160.  This `mmap` thing bit me in the butt today, I've spent a lot of time fiddling around with buffering (using `stdbuf`, `script` etc.) thinking that's where the problem is.  After adding `--no-mmap` everything is awesome, memory usage is at 30 MB streaming gigabytes of data.

My situation is a bit different though since I have thousands of files so I'm not sure how miller can know the size of the input... but then why should the memory keep growing?  Wouldn't it drop the file handles as soon as they are processed?

I'm not sure what's going on but after using the flag things work.

This is the command I'm using: 

```
mlr --no-mmap --itsv --otsv --nr-progress-mod 50000 \
        put '$date = strftime(strptime($date, "%Y-%m-%dT%H:%M:%SZ"), "%Y-%m-%d")' \
        'then' cut -f sku_id,outlook,date,quantity_cumulative,confidence,type \
        output-*.tsv | tee output-combined.tsv
```

**Comment by johnkerl** [comment]
OK thank you.

Well ... all along I tried to default to mmap since it's fractionally faster than using stdio/malloc. However ... as you find out, mmap stresses memory for large files (#160) or large number of not-large files (here).

Maybe ....... I should simply default to using stdio. :(

Or, maybe switch to no-mmap automatically if the number of files is 'big'.

Also, I agree there should be munmap after each file is processed so I will debug that.

**Comment by johnkerl** [comment]
OK I am (rather, *was*) tempted to just jettison `mmap` entirely. Avoiding this problem, cutting the lines-of-code count for the record-readers in half, etc.

But it's worth keeping by default. For data I took 100 concatenations of https://github.com/johnkerl/miller/blob/master/data/medium into `foo.dat`.

```
$ head foo.dat
a=pan,b=pan,i=1,x=0.3467901443380824,y=0.7268028627434533
a=eks,b=pan,i=2,x=0.7586799647899636,y=0.5221511083334797
a=wye,b=wye,i=3,x=0.20460330576630303,y=0.33831852551664776
a=eks,b=wye,i=4,x=0.38139939387114097,y=0.13418874328430463
a=wye,b=pan,i=5,x=0.5732889198020006,y=0.8636244699032729
a=zee,b=pan,i=6,x=0.5271261600918548,y=0.49322128674835697
a=eks,b=zee,i=7,x=0.6117840605678454,y=0.1878849191181694
a=zee,b=wye,i=8,x=0.5985540091064224,y=0.976181385699006
a=hat,b=wye,i=9,x=0.03144187646093577,y=0.7495507603507059
a=pan,b=wye,i=10,x=0.5026260055412137,y=0.9526183602969864

$ wc -l foo.dat
 1000000 foo.dat
```

The timings are pretty clear:

```
$ repeat 20 justtime mlr --mmap check foo.dat
TIME IN SECONDS 1.104 -- mlr --mmap check foo.dat
TIME IN SECONDS 1.096 -- mlr --mmap check foo.dat
TIME IN SECONDS 1.102 -- mlr --mmap check foo.dat
TIME IN SECONDS 1.099 -- mlr --mmap check foo.dat
TIME IN SECONDS 1.099 -- mlr --mmap check foo.dat
TIME IN SECONDS 1.091 -- mlr --mmap check foo.dat
TIME IN SECONDS 1.290 -- mlr --mmap check foo.dat
TIME IN SECONDS 1.123 -- mlr --mmap check foo.dat
TIME IN SECONDS 1.114 -- mlr --mmap check foo.dat
TIME IN SECONDS 1.106 -- mlr --mmap check foo.dat
TIME IN SECONDS 1.104 -- mlr --mmap check foo.dat
TIME IN SECONDS 1.093 -- mlr --mmap check foo.dat
TIME IN SECONDS 1.092 -- mlr --mmap check foo.dat
TIME IN SECONDS 1.090 -- mlr --mmap check foo.dat
TIME IN SECONDS 1.090 -- mlr --mmap check foo.dat
TIME IN SECONDS 1.099 -- mlr --mmap check foo.dat
TIME IN SECONDS 1.092 -- mlr --mmap check foo.dat
TIME IN SECONDS 1.095 -- mlr --mmap check foo.dat
TIME IN SECONDS 1.090 -- mlr --mmap check foo.dat
TIME IN SECONDS 1.092 -- mlr --mmap check foo.dat

$ repeat 20 justtime mlr --no-mmap check foo.dat
TIME IN SECONDS 1.341 -- mlr --no-mmap check foo.dat
TIME IN SECONDS 1.344 -- mlr --no-mmap check foo.dat
TIME IN SECONDS 1.347 -- mlr --no-mmap check foo.dat
TIME IN SECONDS 1.356 -- mlr --no-mmap check foo.dat
TIME IN SECONDS 1.349 -- mlr --no-mmap check foo.dat
TIME IN SECONDS 1.348 -- mlr --no-mmap check foo.dat
TIME IN SECONDS 1.353 -- mlr --no-mmap check foo.dat
TIME IN SECONDS 1.327 -- mlr --no-mmap check foo.dat
TIME IN SECONDS 1.363 -- mlr --no-mmap check foo.dat
TIME IN SECONDS 1.362 -- mlr --no-mmap check foo.dat
TIME IN SECONDS 1.355 -- mlr --no-mmap check foo.dat
TIME IN SECONDS 1.345 -- mlr --no-mmap check foo.dat
TIME IN SECONDS 1.367 -- mlr --no-mmap check foo.dat
TIME IN SECONDS 1.364 -- mlr --no-mmap check foo.dat
TIME IN SECONDS 1.347 -- mlr --no-mmap check foo.dat
TIME IN SECONDS 1.356 -- mlr --no-mmap check foo.dat
TIME IN SECONDS 1.358 -- mlr --no-mmap check foo.dat
TIME IN SECONDS 1.350 -- mlr --no-mmap check foo.dat
TIME IN SECONDS 1.346 -- mlr --no-mmap check foo.dat
TIME IN SECONDS 1.308 -- mlr --no-mmap check foo.dat
```

Means are 1.108 and 1.349 seconds; `mmap` 22% faster than `stdio`.

So, I'll keep both, and will keep `mmap` as default, and will augment https://github.com/johnkerl/miller/issues/160 by flipping to `stdio` if the number of files is over some number (10 or 20 maybe).

**Comment by johnkerl** [comment]
Addressed by https://github.com/johnkerl/miller/commit/5cc470d83a603a1f5d924b367f4458db43bfeb4d

Sorry @Fuco1 for the delay! :^/

**Comment by Fuco1** [comment]
No worries and thanks for working on this! In the meantime the `--no-mmap` option served me well.  My workload was batch jobs so the speed wasn't *that* critical (we parallelize in the cloud on 500+ CPUs).  Miller still saved me hours of boring python csv transformations, so <3 !

**Comment by johnkerl** [comment]
Happy to hear it!! :)
