### ISSUE TITLE
Number format uncontrollably changing per record with cat and JSON output?

### ISSUE THREAD

**Issue by trantor** [johnkerl/miller#257]
Hello.
I am processing a CSV file with numeric columns having a fixed format of 11 decimal digits.
If I do `mlr --icsv --ojson cat FILE` and the input is
```
"0.0069233556"
"0.0000055129"
"0.0000007876"
```
what I get as output (extracted from the JSON structure) is
```
0.0069233556
5.5129e-06
7.876e-07
```
I've also tried `put` and `filter` to avoid type conversion, but the result is the same.
If I use a different output, such as dkvp or csv that does not take place and the number is left in the original format.
Is there a way to avoid type conversion or at least to specify a consistent numeric format?

Btw, thanks a lot for the fantastic tool

**Comment by aborruso** [comment]
Hi,
using as input

```
value
0.0069233556
0.0000055129
0.0000007876
```

and running `mlr --icsv --ojson cat input.txt` I have 

```
{ "value": 0.0069233556 }
{ "value": 0.0000055129 }
{ "value": 0.0000007876 }
```

Which version of Miller are you using??

**Comment by trantor** [comment]
Thanks @aborruso . The anwer would be 5.4.0, which is made irrelevant by the fact that I've reported a non-existing problem.
The conversion was made by jq downstream and for some reason (read occasional idiocy on my part) I didn't look at the raw output of mlr (since there were tens of columns in the original CSV file), utterly missing the actual culprit.
Sorry for wasting your time, and shame on me for forgoing my usual meticulousness this time when I was troubleshooting and reporting the problem.
I am therefore closing the issue.
