### ISSUE TITLE
Feature request: add sort by field name option in sort verb

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#258]
It would be great to have something like `mlr sort --field-name input.txt`

From 

    field3=a,field2=o,field1=e

to

    field1=e,field2=o,field3=a

Thank you

**Comment by johnkerl** [comment]
I'll duplicate this to https://github.com/johnkerl/miller/issues/227 -- one issue is about sort-by-key, the other about sort-by-value.

**Comment by aborruso** [comment]
Ok @johnkerl I will wait this new great new feature.

Thank you very much

**Comment by aborruso** [comment]
A related Stack Exchange question https://unix.stackexchange.com/questions/546910/merge-csv-files-based-on-id-even-when-unmatched-ids-and-indefinite-number-of-col/547056#547056
