### ISSUE TITLE
Implicitly coerce to string left operand of =~ and !=~ operators

### ISSUE THREAD

**Issue by divtiply** [johnkerl/miller#259]
To prevent (IMO very non-descriptive) error for expressions like this
```
$ echo x=123 | mlr filter '$x =~ "^[0-9]+$"'
Expression does not evaluate to boolean: got MT_ERROR.
```
I know I can coerce explicitly, but I see no reason for this
```
$ echo x=123 | mlr filter 'string($x) =~ "^[0-9]+$"'
x=123
```

**Comment by divtiply** [comment]
Found this

**Comment by johnkerl** [comment]
In the spirit of https://github.com/johnkerl/miller/issues/151 this will be handled better in the future, without need for `-S`.

**Comment by aborruso** [comment]
thank you very much @johnkerl
