### ISSUE TITLE
test/run reports error on open

### ISSUE THREAD

**Issue by jungle-boogie** [johnkerl/miller#26]
Hello,

Tail end of `sh test/run`:
`open: No such file or directory`
`test/../mlr: could not open "test/input/{a,b,c,d,e,f,g}.csv"`

I can run `mlr --icsv --odkvp cat test/input/{a,b,c,d,e,f,g}.csv` just fine:

    a=1,b=2,c=3
    a=4,b=5,c=6
    d=5,e=6,f=7
    a=1,b=2,c=3
    a=4,b=5,c=6
    a=7,b=8,c=9
    h=3,i=4,j=5
    m=8,n=9,o=10
    a=1,b=2,c=3
    a=4,b=5,c=6

**Comment by johnkerl** [comment]
perhaps sh vs. bash on your system. in any case the curly braces are a keystroke-saver and can be manually expanded. i'll fix along with the bash -> sh.

**Comment by jungle-boogie** [comment]
Hello,

I think you're right, sh doesn't know what to do with the curly braces.

Thanks,
sean

**Comment by johnkerl** [comment]
Also this explains the "no such file" on `test/run` on your earlier report ... "file" being "not found" being not `test/run` but rather `/bin/bash` from the shebang line. I'll rework `test/run` to not use bash. This is worth doing.

**Comment by johnkerl** [comment]
Please repull: given https://github.com/johnkerl/miller/commit/f17dc5639a115a1fa619c5eb80a18969810626b3

(On my system sh==bash so I'm not 100% sure, without your help. Although I don't see any bashisms remaining ...)

**Comment by jungle-boogie** [comment]
Hello,

Output of `sh test/run`:
https://gist.github.com/jungle-boogie/504189cc1c6c5ef13383

Did it used to report test results?

**Comment by johnkerl** [comment]
those diffs are a regression-test fail. issue is "./test" vs. "test". if you "sh test/run" then it will do this. If you do "make tests" then it won't -- because that invokes "sh ./test/run". I should make a note of this somewhere because it's confused me before.

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/commit/dc78c38a1977cbad41dd0277984f27df81bfcaf7

Please let me know if `make tests` succeeds for you & if so I'll close this.

**Comment by jungle-boogie** [comment]
Hi,

I see, I had to remove the previously installed `/usr/local/bin/mlr` file and do the make and make install again.

I did notice this: 
`ALL REGRESSION TESTS PASSED`
`Tests completed: $[num_passed+1]`

While installing and running `make tests`

**Comment by johnkerl** [comment]
Gah; another bash-ism. Thanks.

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/commit/a07feddee903c714108213870cc1d070a84a4236 fixes that

**Comment by johnkerl** [comment]
oops i meant https://github.com/johnkerl/miller/commit/409b1b2912a025c17198e31853ee0e762cd53d3e

**Comment by jungle-boogie** [comment]
Hi,

Yep, great job!

Thanks

**Comment by johnkerl** [comment]
awesome! after the HN release announcement, the #1 ask was RFC-compliant CSV and the #2 was portability. thanks for lots of help on #2. :)

**Comment by jungle-boogie** [comment]
No problem at all. Thank you for writing mlr!
