### ISSUE TITLE
New "-N option" in documentation

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#265]
Hi,
in the best Miller release ever made, the 5.5 🤣, there is "a new -N option for mlr which is a keystroke-saver for --implicit-csv-header --headerless-csv-output".

This issue only to indicate that it is not yet documented on the documentation page.

Thank you

**Comment by johnkerl** [comment]
whaaaat! thanks!

**Comment by aborruso** [comment]
Ok, it's in http://johnkerl.org/miller-releases/miller-5.5.0/doc/reference.html

Thank you
