### ISSUE TITLE
segmentation fault: I'm not able to understand why

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#271]
Hi,
I have a lot of tsv files in this [zip files](https://github.com/johnkerl/miller/files/3632470/file.zip).

I want to merge them and I run

    mlr --itsv  put '$name=FILENAME' then unsparsify tmp_*.tsv

But I have `[1]    18163 segmentation fault (core dumped)`.

If I remove `unsparsify ` I know that the error is when mlr reads `tmp_438.tsv` file.

But If I run `mlr --itsv  put '$name=FILENAME' tmp_437.tsv tmp_438.tsv tmp_439.tsv`, I have no error.

Is there something wrong in my files or in the procedure?

I'm using Miller 5.5.0-dev.

Thank you

**Comment by johnkerl** [comment]
It absolutely should not SEGV. Sorry about this.

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/commit/5f009edf484abbc7fdaab53bfdd6e22ad796e034 fixed this. I'll make a 5.6.2 soon along with https://github.com/johnkerl/miller/issues/270 once I fix that.

Thank you for reporting this bug!

**Comment by aborruso** [comment]
It works!!!

Thank you
