### ISSUE TITLE
Compilation error on macOS w/ latest XCode

### ISSUE THREAD

**Issue by herbygillot** [johnkerl/miller#272]
```
/bin/sh ../libtool  --tag=CC   --mode=link gcc -g -pg -Wall -std=gnu99 -g -O2 -static  -o mlrp mlrp-mlrmain.o cli/libcli.la containers/libcontainers.la stream/libstream.la input/libinput.la dsl/libdsl.la mapping/libmapping.la output/liboutput.la lib/libmlr.la parsing/libdsl.la auxents/libauxents.la -lm
libtool: link: gcc -g -pg -Wall -std=gnu99 -g -O2 -o mlrp mlrp-mlrmain.o  cli/.libs/libcli.a containers/.libs/libcontainers.a stream/.libs/libstream.a input/.libs/libinput.a dsl/.libs/libdsl.a mapping/.libs/libmapping.a output/.libs/liboutput.a lib/.libs/libmlr.a parsing/.libs/libdsl.a auxents/.libs/libauxents.a -lm
clang: error: the clang compiler does not support -pg option on versions of OS X 10.9 and later
make[3]: *** [mlrp] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

Using:

```
$ /usr/bin/xcodebuild -version
Xcode 11.0
Build version 11A420a
```

macOS 10.14.6 18G95

**Comment by johnkerl** [comment]
Do we know why we are building `mlrp`? The profiler build should be getting invoked only for manual analysis when someone has something to profile ...

**Comment by herbygillot** [comment]
No idea; a simple `./configure` and `make` seems to be building `mlrp` as part of the build process by default.  Is there a way to specifically instruct the build process _not_ to build `mlrp`?

**Comment by johnkerl** [comment]
gurk. ok, i never intended that to happen ... thanks for the heads-up. :(

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/commit/9f4a60227dbee241e434167ca739470cf3999326

**Comment by johnkerl** [comment]
Can you try head now? I believe this will do it.

**Comment by herbygillot** [comment]
Yes, that fixed the issue, looks good now - thank you.

**Comment by johnkerl** [comment]
Awesome, thanks! And sorry about the delay.

**Comment by herbygillot** [comment]
No worries - thank you

**Comment by herbygillot** [comment]
Hello @johnkerl, any idea when the next version of `miller` will be released incorporating this fix?

**Comment by johnkerl** [comment]
good call, i'll stamp one soon -- thanks!

**Comment by herbygillot** [comment]
Thanks for cutting release 5.7.0 @johnkerl. It looks like it builds successfully across macOS versions: https://ports.macports.org/port/miller/summary

Closing this one, and thanks again.

**Comment by johnkerl** [comment]
@herbygillot Great! And sorry for the delay.
