### ISSUE TITLE
remove-empty-columns and skip-trivial-records verbs

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#274]
Dear @johnkerl ,
these precious verbs I think are ready for some week, and we have had some new releases in these weeks.

What do you think to put them in the next mlr release?

Thank you

**Comment by johnkerl** [comment]
They are there ...

```
$ echo x=3,y= | mlr remove-empty-columns
x=3
$ echo x=3,y= | mlr skip-trivial-records
x=3,y=
```

```
$ echo x=,y= | mlr skip-trivial-records
```

```
$ mlr --version
Miller v5.6.2
```

What version are you using?

**Comment by aborruso** [comment]
I didn't see them in the documentation, and I use version the last dev version.

But I think it is necessary for me to buy a pair of glasses :/

I'm sorry

**Comment by johnkerl** [comment]
No worries! Please let me know if I indeed missed something in the documentation. :)
