### ISSUE TITLE
How to index return value of a function

### ISSUE THREAD

**Issue by Fuco1** [johnkerl/miller#276]
I'm trying to use a result of a function producing a map:

```
> printf "a\nfoo,bar" | mlr --tsv put '$x = splitnvx($a, ",")[1]'
mlr DSL: syntax error at "["
mlr put: syntax error on DSL parse of '$x = splitnvx($a, ",")[1]'
```

I came up with this workaround

```
> printf "a\nfoo,bar" | mlr --tsv put 'func f(x) { return x[1]; } $x = f(splitnvx($a, ","))'
a       x
foo,bar foo
```

How can I do this in a more natural way?

**Comment by johnkerl** [comment]
I can't believe I didn't put that into the DSL grammar :^/

**Comment by Fuco1** [comment]
Heh, surprisingly many languages don't support this, most notable one being PHP where this was only added in version 5.4 after 18 years of its life!

So I take it this is not currently possible.  I'll stick with the `func` workaround for the meanwhile.  Thanks for working on miller!

**Comment by johnkerl** [comment]
@Fuco1 in the Go port (https://github.com/johnkerl/miller/issues/372) this is handled quite nicely:

```
$ mlr --opprint --from myfile.dat put '
  func f(n) {
    return [n-1,n,n+1]
  }
  $z=f($i)[3]
'
a   b   i  x                    y                   z
pan pan 1  0.3467901443380824   0.7268028627434533  2
eks pan 2  -0.7586799647899636  0.5221511083334797  3
wye wye 3  0.20460330576630303  0.33831852551664776 4
eks wye 4  -0.38139939387114097 0.13418874328430463 5
wye pan 5  0.5732889198020006   0.8636244699032729  6
zee pan 6  0.5271261600918548   0.49322128674835697 7
eks zee 7  0.6117840605678454   0.1878849191181694  8
zee wye 8  -0.5985540091064224  0.976181385699006   9
hat wye 9  0.03144187646093577  0.7495507603507059  10
pan wye 10 0.5026260055412137   0.9526183602969864  11
```

**Comment by Fuco1** [comment]
Oh my god yes for Go port!  I'm happy to wait until v6.  

Love your work, thanks!  I guess we can close this as no solve.

**Comment by johnkerl** [comment]
Thanks! For tracking I prefer to leave these open until the Go port is released. (Since that is non-trivial and non-immediate ;) )

**Comment by johnkerl** [comment]
Fixed in Miller 6.

(And, I've re-thought the above _For tracking I prefer to leave these open until the Go port is released. (Since that is non-trivial and non-immediate_ ... I don't see a need to keep these open.)
