### ISSUE TITLE
 Better documentation on regexp syntax #279 

### ISSUE THREAD

**Issue by johnkerl** [johnkerl/miller#281]
Wishlist # 1: Full documentation of regex syntax and semantics accepted by miller.  In particular, what "non standard" regex abbreviations are supported?  E.G., is the gawk extension "\s" abbreviation for [[:space:]] accepted?  Are PCRE abbreviations (\w, etc.) accepted?  Are POSIX character classes like [[:digit:]] accepted?  Current documentation is very sparse on this subject.

_Originally posted by @pjfarleyiii in https://github.com/johnkerl/miller/issues/77#issuecomment-538553828_

**Comment by johnkerl** [comment]
I believe https://miller.readthedocs.io/en/latest/reference-main-regular-expressions resolves this.

**Comment by aborruso** [comment]
> I believe https://miller.readthedocs.io/en/latest/reference-main-regular-expressions resolves this.

Thank you
