### ISSUE TITLE
More concise DSL-function information

### ISSUE THREAD

**Issue by johnkerl** [johnkerl/miller#282]
Wishlist # 2: Much more concise table of DSL functions and operators plus summary tables "by type" (e.g., arithmetic, statistical, string functions and operators, etc).  The current web format is very, very long and provides no summary by type for quick reference.

_Originally posted by @pjfarleyiii in https://github.com/johnkerl/miller/issues/77#issuecomment-538553828_

**Comment by johnkerl** [comment]
@pjfarleyiii how is this?

http://johnkerl.org/miller-releases/miller-head/doc/reference-dsl.html#Built-in_functions_for_filter_and_put,_summary

**Comment by pjfarleyiii** [comment]
Much better, thank you.  Can it be multiple columns perhaps?  Arithmetic through string in column 1, math and time in column 2, typing through maps in column 3?  Not sure if that works out in terms of total page length, but it's a start.

It's OK if multiple columns are not practical or desirable from your point of view.  I can live without them.  The shorter summary section is an excellent addition.

Slight typo in the summary: The triple "? :" in the Boolean section needs the ":" moved into in the first sub-column, "boolean" in the second and "3" in the third.

Thank you for the addition to the docs.  It will be helpful.

Peter

**Comment by johnkerl** [comment]
@pjfarleyiii good catch on `? :`. Regarding multi-column ... this table is auto-genned and I prefer not to deal with the additional complexity there.

Thank you though!! :)
