### ISSUE TITLE
Unlashed counts for uniq

### ISSUE THREAD

**Issue by vapniks** [johnkerl/miller#289]
Often when I am doing an initial reconnaissance of a dataset I want to know how many uniq values there are for each individual field. 
The mlr "uniq" verb allows me to do this one field at a time, but if I have many fields this is tedious. I could write a bash/zsh "for" loop to loop over the fields, but it would be much nicer if there was an extra option for the uniq verb like the "-u" option for count-distinct (with an extra column showing the field name).
Also it would be nice to have an option for specifying all fields without having to type them all out (which can get very messy).

**Comment by johnkerl** [comment]
Nice request!! :)

**Comment by aborruso** [comment]
Dear @johnkerl ,
a great feature, that I use a lot in xsv, visidata, csvkit, is to have a general view of the input table.

An example output is the one below.

To have a sort of "info" verb, would be great

```
field       type     sum                 min       max         min_length  max_length  mean                stddev              median              mode  cardinality
id          Integer  5050                1         100         1           3           50.5                28.86607004772212   50.5                N/A   100
first_name  Unicode                      Annabal   Willabella  3           11                                                                      N/A   98
last_name   Unicode                      Albinson  Zaniolini   3           13                                                                      N/A   100
f           Float    2063.2419999999984  0.2656    51.1245     4           7           20.632419999999996  12.603955889545158  17.930799999999998  N/A   100
```

**Comment by johnkerl** [comment]
Also nice request!! :)

**Comment by janxkoci** [comment]
Isn't this what the `summary` verb does? Also one can easily use `stats1 -a distinct_count` to get the info for many columns (it even supports regex to select columns). And there is also the `count-distinct` verb, although you need to list all columns yourself.
