### ISSUE TITLE
Miller 5.6.2 is not a static binary

### ISSUE THREAD

**Issue by deftdawg** [johnkerl/miller#292]
Looks like miller 5.60 is a static binary
```
$ ldd mlr.linux.x86_64.5.60 
        not a dynamic executable
```

Miller 5.6.0 core dumps
```
$ ./mlr.linux.x86_64.5.60
FATAL: kernel too old
Aborted (core dumped)
```

However Miller 5.0.1 seems to be okay 😄

**Comment by deftdawg** [comment]
> * Not unlike jq (http://stedolan.github.io/jq/) for JSON, Miller is written in portable, modern C, with zero runtime dependencies. You can download or compile a single binary, scp it to a faraway machine, and expect it to work.

Hmm, maybe it's supposed to be statically compiled, but the latest wasn't for some reason, I will check previous releases.

**Comment by johnkerl** [comment]
My apologies, I probably mistyped. Will fix this evening!

**Comment by johnkerl** [comment]
@deftdawg sorry for the long delay!!! I updated the `mlr.linux_x86_64` binary to be static at https://github.com/johnkerl/miller/releases/tag/v5.6.2.
