### ISSUE TITLE
Not able to use max and out-of-stream variables

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#295]
Hi,
if I run

```
echo -e 'a=2,b=3\na=4,b=1' | mlr filter '@max=max(@max,$b);$b==@max'
```

I have `a=2,b=3` and it's right.

If I start from this inputFile

```
score=1
score=1
score=1
score=1
score=1
score=1
score=1
score=7.1
score=1
```

and run

```
mlr filter '@max=max(@max,$score);$score==@max' inputFile
```

I have nearby all items back

```
score=1
score=1
score=1
score=1
score=1
score=1
score=1
score=7.1
```

Why do I not have only `score=7.1`?

Thank you

**Comment by aborruso** [comment]
If I add sort before the filter it works:

```
mlr sort -nr score then filter '@max=max(@max,$score);$score==@max' tmp.mlr
```

But why it does not work without sorting since it is out of stream variable?

**Comment by johnkerl** [comment]
There are three kinds of expressions for `filter` and `put`. Those inside a `begin { ... }` block run before any records are read; those inside an `end { ... }` block run after all records are read; those inside neither a `begin` or `end` run once for every record.

Your `@max=max(@max,$score);$score==@max` looks like it wants to do two things: the `@max = max(@max, $score)` looks like it wants to run on every record and track the largest value. Your `$score==@max` looks like it wants to run at the end but it's not.

So the filter expression `$score == @max` is testing the current record's `$score` against the maximum value encountered *so far*. For example, on the first record, `$score` is `1` and `@max` is the largest value seen so far which is also `1` which is why `score=1` is emitted for the first record.

(As a side note, please be careful about making exact comparisons such as `$score == @max` when you are using floating-point data. This is not a Miller-specific issue -- it's a general concern.)

If what you want to do is find the entire record with the largest `score` value then what I think you want is

```
mlr top -n 1 -a -f score inputFile
```

Examples:

```
$ mlr --opprint cat ../data/small
a   b   i  x                   y
pan pan 1  0.3467901443380824  0.7268028627434533
eks pan 2  0.7586799647899636  0.5221511083334797
wye wye 3  0.20460330576630303 0.33831852551664776
eks wye 4  0.38139939387114097 0.13418874328430463
wye pan 5  0.5732889198020006  0.8636244699032729
zee pan 6  0.5271261600918548  0.49322128674835697
eks zee 7  0.6117840605678454  0.1878849191181694
zee wye 8  0.5985540091064224  0.976181385699006
hat wye 9  0.03144187646093577 0.7495507603507059
pan wye 10 0.5026260055412137  0.9526183602969864

$ mlr --opprint top -a -n 1 -f i ../data/small
a   b   i  x                  y
pan wye 10 0.5026260055412137 0.9526183602969864

$ mlr --opprint top -a -n 1 -f x ../data/small
a   b   i x                  y
eks pan 2 0.7586799647899636 0.5221511083334797

$ mlr --opprint top -a -n 1 -f y ../data/small
a   b   i x                  y
zee wye 8 0.5985540091064224 0.976181385699006
```

**Comment by aborruso** [comment]
@johnkerl thank you. My goal is to write it in DSL.

Because I'm able to use miller especially using verbs (it's a really great tool), but I must still understand a lot of DSL. After this reply, I'm trying to use begin and end.

I will write my results here

**Comment by johnkerl** [comment]
OK, great! You will need to retain all input records, and then loop over them in the `end` statement ...

**Comment by aborruso** [comment]
I'm closing it, because your reply as usual is great.

I hope to be able to write it in DSL soon.

Thank you

**Comment by johnkerl** [comment]
OK, thanks! :)

**Comment by johnkerl** [comment]
Let me know what you find out! :)

**Comment by aborruso** [comment]
Hi @johnkerl ,
this is my awful DSL and it seems to work

```
mlr put -q 'begin { @highest = 0 };
for (key, value in $*){
if (@highest < value) {
        @highest = value
}
};end { emit @highest }' input
```


My input is

```
score=1
score=1
score=1
score=1
score=1
score=7.1
score=1
score=1
```

Is there a way to do write something like the code below and to do a for loop only for the values of `score` field (in a multi field input source)?


```
mlr put -q 'begin { @highest = 0 };
for (value in $score){
if (@highest < value) {
        @highest = value
}
};end { emit @highest }' input
```

**Comment by aborruso** [comment]
But I would like to write a filter DSL.

If I write

```
mlr filter 'begin { @highest = 0 };
for (key, value in $*){
if (@highest < value) {
        @highest = value
}
};end { emit @highest };$score==@highest' input
```

I have 

```
score=1
score=18
highest=18
```

How to apply the filter after I have had highest `score` value?

Thank you and be patient :)

**Comment by johnkerl** [comment]
You're almost there!

Input data:

```
$ cat foo
score=0.3467901443380824,other=0.7268028627434533
score=0.7586799647899636,other=0.5221511083334797
score=0.20460330576630303,other=0.33831852551664776
score=0.38139939387114097,other=0.13418874328430463
score=0.5732889198020006,other=0.8636244699032729
score=0.5271261600918548,other=0.49322128674835697
score=0.6117840605678454,other=0.1878849191181694
score=0.5985540091064224,other=0.976181385699006
score=0.03144187646093577,other=0.7495507603507059
score=0.5026260055412137,other=0.9526183602969864
```

Extract highest score only:
```
$ cat g4
mlr put -q '
  begin { @highest = 0 };
  if (@highest < $score) {
    @highest = $score
  }
  end { emit @highest }
' foo

$ sh g4
highest=0.758680
```

Extract highest score and the full record it was found in:
```
$ cat g5
mlr put -q '
  begin {
    @highest_value = 0;
    @highest_value_record = {};
  };
  if (@highest_value < $score) {
    @highest_value = $score;
    @highest_value_record = $*;
  }
  end { emit @highest_value_record }
' foo

$ sh g5
score=0.7586799647899636,other=0.5221511083334797
```

**Comment by johnkerl** [comment]
Oops just saw your most recent comment after I replied to the previous. Reading ...

**Comment by johnkerl** [comment]
... OK I think the above will get you what you were trying to do with the final `filter`.

**Comment by aborruso** [comment]
Thank you very much.

It's great

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il dom 5 gen 2020, 19:57 John Kerl <notifications@github.com> ha scritto:

**Comment by aborruso** [comment]
@johnkerl I have tried and if I run

```
mlr filter '
  begin { @highest = 0 };
  if (@highest < $score) {
    @highest = $score
  }
  end { emit @highest }; $score==@highest' input
```

I have

```
score=1
score=18
highest=18
```

and not `score=18`. If I remove `end { emit @highest }` (but I think I do not must remove it) I have

```
score=1
score=18
```

What's wrong.

Thank you

**Comment by aborruso** [comment]
I'm reopening to understand why [DSL filter](https://github.com/johnkerl/miller/issues/295#issuecomment-571051349) does not work

**Comment by aborruso** [comment]
Dear @johnkerl,
as soon as you can, could you tell me why the filter is not working? What am I doing wrong?

Thank you

**Comment by johnkerl** [comment]
Sorry! Lost track.

More later. Meanwhile the final statement of the filter is operating on a per-record basis, not at the very end (after end of stream).

**Comment by aborruso** [comment]
@johnkerl then, if I understand correctly it's not possible to use filter verb, but I must use something like your code below.

I'm closing it

```
mlr put -q '
  begin {
    @highest_value = 0;
    @highest_value_record = {};
  };
  if (@highest_value < $score) {
    @highest_value = $score;
    @highest_value_record = $*;
  }
  end { emit @highest_value_record }
' foo
```

**Comment by johnkerl** [comment]
OK thanks for your patience! :)
