### ISSUE TITLE
"Too many open files" error

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#299]
Hi,
when I run 

```
mlr --csv --from tmp_a.csv put -q 'tee > $comune.".csv", $*'
```

using [this csv](https://gist.github.com/88819d3cef49f4ad00da4457e1361b9b), I have this error: `fopen: Too many open files`.

I'm using `Miller 5.6.1-dev`.

What's wrong on my command?

Thank you

**Comment by johnkerl** [comment]
Your command isn't wrong.

```
$ mlr --c2p uniq -n -f comune tmp_a.csv
count
7552
```

So there are 7,552 distinct values of `$comune` and so `tee` is needing to keep open 7,552 file descriptors.

If you can increase the limit on the number of open files for your platform, this symptom should go away.

A nicer user experience (but would require a code change) would be for Miller to keep its own LRU cache of open file descriptors, and managing re-opening closed ones as it processes data.

**Comment by aborruso** [comment]
Hi John,
thank you.

I will write a classic bash for loop

**Comment by aborruso** [comment]
> If you can increase the limit on the number of open files for your platform, this symptom should go away.

Yes, the way is `ulimit -n 9000` (9000 is an example)

**Comment by johnkerl** [comment]
I will make a FAQ entry.
