### ISSUE TITLE
header data mismatch

### ISSUE THREAD

**Issue by jungle-boogie** [johnkerl/miller#30]
Hello,

Obtained this file: http://catalog.data.gov/dataset/fdic-failed-bank-list
Edited header to have it resemble this:
`BankName,City,ST,CERT,AcquiringInstitution,ClosingDate,UpdatedDate`

And I want to `cat listbank.csv| mlr --icsv --opprint count-distinct -f ST,ClosingDate`
But I get error: `Header-data length mismatch!`

The original file did contain ctrl-M characters that you can observe with `cat -e banklist.csv` but even after removing those characters, I get the same mismatch message. 

Any idea how I can get around the mismatch and what it means?

Thanks!

**Comment by jungle-boogie** [comment]
I also see header data mismatch with this file:
http://catalog.data.gov/dataset/consumer-complaint-database

`% cat Consumer_Complaints.csv| mlr --icsv --opprint count-distinct -f 7 | head`
`Header-data length mismatch!`

Header looks like:
`ComplaintID,Product,Sub-product,Issue,Sub-issue,State,ZIPcode,Submittedvia,Datereceived,Datesenttocompany,Company,Companyresponse,Timelyresponse?,Consumerdisputed?`

**Comment by johnkerl** [comment]
I'll check it out but I suspect it's a double-quoting issue. Also the error message could give better info about line number & file.

**Comment by johnkerl** [comment]
So this is a dup of
https://github.com/johnkerl/miller/issues/4
https://github.com/johnkerl/miller/issues/31

**Comment by jungle-boogie** [comment]
Hi,

Thanks for checking it out.

**Comment by jungle-boogie** [comment]
FYI...
I removed all commas from the original file (fdic-failed-bank-list):
`% ack -c '"' banklist.csv`
`% 0`

And tried the same count-distinct:
`% cat banklist.csv | mlr --icsv --opprint count-distinct -f ST,ClosingDate`
`Header-data length mismatch!`

`% file banklist.csv `
`banklist.csv: ASCII text, with CRLF line terminators`

`% cat banklist.csv > file.csv`

I removed the ^M:
`% file file.csv`                     
`file.csv: ASCII text`

Ran same query above:
`% cat file.csv |  mlr --icsv --opprint count-distinct -f ST,ClosingDate`
`Header-data length mismatch!`

I'm sure it's related to #4 & #31 but just wanted to update the issue for another data point to test later.
