### ISSUE TITLE
FILENAME and FILENUM not preserved?

### ISSUE THREAD

**Issue by trantor** [johnkerl/miller#303]
Hello.
I've come across what (to me) seems to be a problem with the FILENAME and FILENUM variables.
```
# mlr --version
Miller v5.6.2

# cat /tmp/csv1
A,B,C
_2GB,255,2
_4GB,120,4
_6GB,50,6
_10GB,10,10

# cat /tmp/csv2
FIRST,SECOND,THIRD,FOURTH
1,2,3,4
5,6,7,8
9,10,11,12
13,14,15,16

# mlr --icsv cat then put 'print FILENAME'   /tmp/csv1 /tmp/csv2
/tmp/csv1
A=_2GB,B=255,C=2
/tmp/csv1
A=_4GB,B=120,C=4
/tmp/csv1
A=_6GB,B=50,C=6
/tmp/csv1
A=_10GB,B=10,C=10
/tmp/csv2
FIRST=1,SECOND=2,THIRD=3,FOURTH=4
/tmp/csv2
FIRST=5,SECOND=6,THIRD=7,FOURTH=8
/tmp/csv2
FIRST=9,SECOND=10,THIRD=11,FOURTH=12
/tmp/csv2
FIRST=13,SECOND=14,THIRD=15,FOURTH=16

# mlr --icsv cat then sort -f A then put 'print FILENAME'   /tmp/csv1 /tmp/csv2
/tmp/csv2
/tmp/csv2
/tmp/csv2
/tmp/csv2
/tmp/csv2
/tmp/csv2
/tmp/csv2
/tmp/csv2
A=_10GB,B=10,C=10
A=_2GB,B=255,C=2
A=_4GB,B=120,C=4
A=_6GB,B=50,C=6
FIRST=1,SECOND=2,THIRD=3,FOURTH=4
FIRST=5,SECOND=6,THIRD=7,FOURTH=8
FIRST=9,SECOND=10,THIRD=11,FOURTH=12
FIRST=13,SECOND=14,THIRD=15,FOURTH=16
```
Pretty much the same goes for FILENUM.
Is the information about which line belonged to which input file preserved at all after some processing? Is it related to the record heterogeneity?
I hope I am not wasting anybody's time and it wasn't something mentioned in the documentation that I couldn't find.

Thanks in advance.

**Comment by aborruso** [comment]
Hi @trantor , starting from your input files, what's your goal?

**Comment by trantor** [comment]
@aborruso well... something pretty convoluted I was beginning to sketch and cannot quite explain at this point. I wanted to reference the lines coming from two different files mapping them by `FILENAME` or `FILENUM` in a `put` script, mostly in order to get around the fact that I can't easily have two inputs, except by using `system()` to load one of the files.
The input files in the previous post are just a random example, unrelated to what I intend to do.

**Comment by aborruso** [comment]
@trantor I do not if it's your goal, but if I run

```
mlr --icsv put '$fn=FILENAME' then sort -f A csv1 csv2 | sed -r 's/(,)(fn)=(.+)$/\n\3/g'
```

I have 

```
A=_10GB,B=10,C=10
csv2
A=_2GB,B=255,C=2
csv2
A=_4GB,B=120,C=4
csv2
A=_6GB,B=50,C=6
csv2
FIRST=1,SECOND=2,THIRD=3,FOURTH=4
csv1
FIRST=5,SECOND=6,THIRD=7,FOURTH=8
csv1
FIRST=9,SECOND=10,THIRD=11,FOURTH=12
csv1
FIRST=13,SECOND=14,THIRD=15,FOURTH=16
csv1
```

**Comment by johnkerl** [comment]
@trantor this is interesting. I'll make an FAQ entry.

There's a subtle thing going on here which is intentional on my part but perhaps over-subtle from the end-user point of view.

* If the then-chaining is all record-by-record processing, like `put` or `filter` or `cut` or what have you then the `FILENAME`/`FILENUM` context will still be in place as desired.
* But some verbs require consuming all input before producing any -- this includes `sort` and `tac`. For these, the `FILENAME`/`FILENUM` context is 'gone' everywhere in the then-chain after the `sort`/`tac`/whatever.

So @aborruso's suggestion is a good one which is to explicitly stash the filename/filenum in the records via `put $FILENAME=FILENAME` etc.

Things I can do:

* First of all document this more clearly. Definitely to do.
* Second of all, I'm not certain whether to implement, and it would be a bit of a coding project, is to put the filename/filenum/etc context not just as a single data instance but rather as data copied into each record so it would 'stick' with each record throughout the then-chain. Something to think about.

Anyway I'll write this up at very least.

**Comment by trantor** [comment]
Thanks @johnkerl for the clarification and @aborruso for the suggestion. It reminds of the old decorate-sort-undecorate trick. The only annoyance is that I was thinking of using miller as part of a tool which could be as agnostic as possible when it comes to field names, so I was hoping for an internal variable which could no conflict with any possible field name. I'll try to come up with a pretty unique name for the ancillary field to avoid collisions with existing fields.

Just to give you an idea, I was sort of abusing miller to load an external map in a put script from a csv file which I would use as a reference data structure processing the CSV file containing my actual data. I sort of got around it by calling `system()` inside the `put` script and then splitting manually by line and field to create a map variable, since, as far as I can tell, you can dump a map variable but not load it from an external source. Since I wanted to process both CSV files as CSVs with miller I sort of thought of using support for record heterogeneity and the FILENAME/FILENUM variables to have both files as arguments to miller and then create two map variables for the records using the filename as key. I didn't think further than that stumbling upon this issue so I don't know yet what I would do after that step. It's slighty past the point where I would give up and write a trusty Perl script instead but I enjoy both miller as a standalone tool and pushing the envelope to see what it can achieve, so I am still going to stretch it until something comes out ;-)

**Comment by trantor** [comment]
@johnkerl Regardless of the variable behaviour, shouldn't FILENAME and/or FILENUM be emptied instead of referring to the last file for the lines coming from all the input files after using sort/tac/etc. ?

**Comment by johnkerl** [comment]
> @johnkerl Regardless of the variable behaviour, shouldn't FILENAME and/or FILENUM be emptied instead of referring to the last file for the lines coming from all the input files after using sort/tac/etc. ?

Good call!! :) And quick to code up. :)

**Comment by johnkerl** [comment]
@trantor @aborruso in Miller 6 `FILENAME` and `FILENUM` now travel with records so I believe this is resolved. Please feel free to re-open if I'm incorrect -- thank you! :)

**Comment by aborruso** [comment]
> @trantor @aborruso in Miller 6 `FILENAME` and `FILENUM` now travel with records so I believe this is resolved. Please feel free to re-open if I'm incorrect -- thank you! :)

Thank you
