### ISSUE TITLE
Question: split on any whitespace

### ISSUE THREAD

**Issue by leahneukirchen** [johnkerl/miller#304]
Perhaps I just missed this in the manual, but is there a mode that splits columns on any whitespace (i.e. at least space *and* tab)?

**Comment by aborruso** [comment]
@leahneukirchen please insert an example input file and the output you want.

To set field separator you have `--fs --ifs --ofs`. TSV is a default input output format.

**Comment by leahneukirchen** [comment]
```
% printf 'one\ttwo three' | mlr --inidx --fs ' ' cat
1=one	two 2=three
% printf 'one\ttwo three' | mlr --inidx --fs '\t' cat
1=one	2=two three
```

I want `1=one 2=two 3=three`.

**Comment by aborruso** [comment]
It seems to me that you are mixing separators

In the first you `one\ttwo three`. The separator is a tab or a space?

In example if you run 

    printf 'one\ttwo\tthree' | mlr --inidx --ifs '\t' --ofs ' ' cat

you have

    1=one 2=two 3=three

**Comment by leahneukirchen** [comment]
I want the equivalent of 

```
% printf 'one\ttwo three' | awk '{print "1="$1, "2="$2, "3="$3}'
1=one 2=two 3=three
```

awk(1):
> In the special case that FS is a single space, fields are separated by runs of spaces and/or tabs and/or newlines.

**Comment by trantor** [comment]
Well from what I understand miller doesn't have magic behaviour on splitting like awk or perl where character classes (or regexes even) can be employed, such as "split on whitespace".

The separator is one character, period.
You could work around it, even though is quite the hack, with something similar to this
```
printf 'one\ttwo three' | mlr --prepipe 'sed -r s/[[:blank:]]+/\\t/g' --ifs '\t' cat
```
(You've got also `--repifs` if the separator happens to be the same character occasionally repeated multiple times.)
It's ugly and of course you might as well use something else in a pipeline ahead of `mlr`.
Personally I would like some more flexibility when it comes to separators, but I guess that's pretty much it for now, even though I would quite enjoy being wrong here.

**Comment by johnkerl** [comment]
> The separator is one character, period.

Close -- it can be multiple characters but it needs to be a fixed character *sequence*. E.g. you can split on `:=` if you wanted.

But yes it does not support splitting by regex and `--repifs` is a sad consolation for the lack of splitting by regex.

And yes the prepipe would work, as well as some `sed ... | mlr ...` of course.

**Comment by trantor** [comment]
@johnkerl sorry you're right of course. You explicitly mentioned sequences such as `\r\n` in the documentation for record separators. But maybe the documentation and or the usage information might mention that a sequence is allowed a bit more explicitly for field separators, since they are mentioned for OPS/OFS but for instance the only examples of sequences are for record separators.

**Comment by trantor** [comment]
@johnkerl Slight OT but since I am at it you've got Record-Hetrogeneity with a missing "e" in many places on the documentation web site. I looked for a repository for the web site to open an issue but I guess there isn't one.

**Comment by johnkerl** [comment]
> @johnkerl Slight OT but since I am at it you've got Record-Hetrogeneity with a missing "e" in many places on the documentation web site. I looked for a repository for the web site to open an issue but I guess there isn't one.

Thanks, good catch!!!

And, website issues are tracked here. I'll fix. :)

**Comment by johnkerl** [comment]
@trantor I'll also try to make it a little more obvious that GitHub issues are the right place to submit issues regarding the website. Thanks for the tip! :)

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/commit/45af20694f797d11bb55aae7260b9573c442d175 fixes the `hetrogeneity` -> `heterogenity` issue

**Comment by johnkerl** [comment]
@trantor http://johnkerl.org/miller/doc/contact.html now suggests GitHub issues for the docsite ...

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/issues/301 gives me now a single code-path for each file-format reader (stdio only) instead of stdio & mmap which will make it quicker to implement this feature request.

**Comment by johnkerl** [comment]
> But yes it does not support splitting by regex and `--repifs` is a sad consolation for the lack of splitting by regex.

In Miller 6 `IFS` and `IPS` will be regexes.

* I'll still support `--repifs` for compatibility/familiarity.
* You'll be able to use `--ifs space` as a synonym for`--ifs ' '` or `--ifs spaces` as a synonym for `--ifs '( )+'` or `--ifs whitespace` as a synonym for `--ifs '([ \t])+'`, and so on.

**Comment by johnkerl** [comment]
Fixed in Miller 6.

https://johnkerl.org/miller6/reference-main-separators/#multi-character-and-regular-expression-separators
