### ISSUE TITLE
trivial compiler error when compiling with clang on termux

### ISSUE THREAD

**Issue by zettelmuseum** [johnkerl/miller#307]
Hello,
i get the following error when compiling with clang9 on termux using
make -f makefile.no-autoconf

cli/mlrcli.c:1148:49: error: implicit conversion from 'long long' to 'ssize_t'
      (aka 'int') changes value from 4294967296 to 0
      [-Werror,-Wconstant-conversion]                                           ...= DEFAULT_MAX_FILE_SIZE_FOR_MMAP;                                             ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                         cli/mlrcli.c:36:58: note: expanded from macro 'DEFAULT_MAX_FILE_SIZE_FOR_MMAP'
#define DEFAULT_MAX_FILE_SIZE_FOR_MMAP (4LL*1024LL*1024LL*1024LL)                                                     ~~~~~~~~~~~~~~~~~^~~~~~~

I fixed it by just removing the value from the following line
fprintf(o, "                                  files less than %lld bytes in size.\n", DEFAULT_MAX_FILE_SIZE_FOR_MMAP);

But I'm sure there's a proper and very trivial fix.
(my  C knowledge is almost nonexisting)

Regards

**Comment by johnkerl** [comment]
Thanks!!!

**Comment by zettelmuseum** [comment]
one more -very low priority- termux thing
in mlr_test_util, there's a hard coded directory which i had to change
char* path = mlr_strdup_or_die("/tmp/mlr.ut.XXXXXXXX")
for maximum portability one might check TMPDIR first

**Comment by johnkerl** [comment]
@zettelmuseum the long-long thing is gone away now as of https://github.com/johnkerl/miller/commit/2632ddc71669129192b70a7c28db6a60a0164d8a

I'll get on the `TMPDIR` fix though -- good call, and thank you! :)

**Comment by johnkerl** [comment]
@zettelmuseum can you please try now? https://github.com/johnkerl/miller/commit/bfc9cc523ef84b5e55b439c92a06e8c0c0765aa4 is in HEAD.

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/releases/tag/v5.7.0
