### ISSUE TITLE
Miller 5.x on Ubuntu 16.x

### ISSUE THREAD

**Issue by mrjcleaver** [johnkerl/miller#309]
I note from https://github.com/johnkerl/miller/issues/186 that Miller was backported to Debian (Stretch).

I need to run it on Ubuntu 16.x

Will it compile from source? Should I attempt to cross install that backport like https://www.alibabacloud.com/blog/how-to-install-newer-software-in-debian-or-ubuntu_594454 ?

Thanks,
   Martin.

**Comment by johnkerl** [comment]
Hi @mrjcleaver! Regarding the second option -- I don't know but I don't see why not ...

Regarding the first option -- yes compile from source should work -- I do this regularly.

http://johnkerl.org/miller/doc/build.html#Building_from_source

If you install from source, please let me know of any issues that arise -- I'm always eager to document various things that come up on various platforms.

**Comment by mrjcleaver** [comment]
John: thank you so much for the prompt reply - we'll try the compile from source. Seeing as it has few dependencies I'm hoping it'll be straightforward.

I'll comment & close when done!

**Comment by aborruso** [comment]
Thank you very much @mrjcleaver !

**Comment by mrjcleaver** [comment]
Following up! This is for Ubuntu 16.04:

> Hesam  9:45 AM 😄 
> Miller 5.6.2 installed on staging

All good 🥇
