### ISSUE TITLE
How to escape single quote [ ' ] ?

### ISSUE THREAD

**Issue by luckman212** [johnkerl/miller#311]
I'm trying to parse a TSV file that contains some characters that are messing up a `system()` call. Long story short I am trying to `gsub()` or `ssub()` them out, but running into trouble with the single quote `'`

E.g.
```
$ echo "a=that's all folks" | mlr put '$a = ssub($a, "\'", " _singlequote_ ")'
>
(unterminated line)
```
I also tried some quackery like
```
$ q="'"
$ echo "a=that's all folks" | mlr put '$a = ssub($a, '$q', " _singlequote_ ")'
mlr put: syntax error on DSL parse of '$a = ssub($a, ', " _singlequote_ ")'
```
or
```
echo "a=that's all folks" | mlr put "\$a = ssub(\$a, $q, ' _singlequote_ ')"
mlr put: syntax error on DSL parse of '$a = ssub($a, ', ' _singlequote_ ')'
```
Those don't work either 😞

Is there a way to do this all inside `mlr` without piping thru `sed` first?

_**edit:** forgot to say a hearty "thanks" for Miller! amazing tool!_

**Comment by aborruso** [comment]
Hi,
in this way

```
echo "a=that's all folks" | mlr put '$a = ssub($a, "'\''", " _singlequote_ ")'
```

It's in the FAQ http://johnkerl.org/miller/doc/faq.html#How_can_I_put_single-quotes_into_strings?

**Comment by luckman212** [comment]
Thanks @aborruso ! That worked indeed. Not sure how I missed it in the FAQ but it was a late night so `¯\_(ツ)_/¯`

**Comment by aborruso** [comment]
@luckman212 you are welcome. Than please close the issue
