### ISSUE TITLE
Problem when list of fields has a stray CR LF

### ISSUE THREAD

**Issue by spmundi** [johnkerl/miller#313]
Difficult to describe in words, but the attached output should explain it better.
I was trying to do "mlr --csv cut -f _selection_
where _selection_  was taken from a file with dos terminations. E.g.
mlr --csv cut -f $(head -1 dos_terminated_filename) ....

The effect is that the last field specified by the list of fields following -f is omitted.
See the attached output
[output.txt](https://github.com/johnkerl/miller/files/4234166/output.txt)

**Comment by aborruso** [comment]
The same for me. It works if you convert line termination to unix:

```
mlr --csv cut -f $(<selectionFile head -1 | tr -d '\r') input
```

**Comment by johnkerl** [comment]
OK this is a bug. I worked hard on auto-detect of LF vs. CR/LF files but it looks like I missed a spot.

**Comment by johnkerl** [comment]
Sorry for the delay.

I see what you are doing. The field names *on the command line itself* have embedded line-terminators. I never thought of anyone doing that.

Easy enough to deal with though. Thanks for letting me know!

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/commit/0290ceff9de235e70a73e4ae7c6d59fd0e80fda1
