### ISSUE TITLE
Set a value in a put from the shell/environment

### ISSUE THREAD

**Issue by spmundi** [johnkerl/miller#315]
A typical put clause is surrounded by single quotes, both to protect the dollar sumbol on variables, and to make it appear to mlr as a single variable.
Is it thus impossible to  write a put clause which references a shell variable?

Specifically I am trying to create a new column (field). I would like to do something like this:
mlr...put '$newfield=some_date_value" .... some_file_name
where some_date_value depends upon some_file_name (eg the file name might be events_from_20200305)

Awk has a mechanism whereby you can set a variable from the command line and then use it in the awk script:
awk .. -smy_variable=value ... { can refer to $my_variable in this script }'

Thanks
PS> And thanks for a fantastic program. This has saved me hours of labor using what would be cumbersome work-arounds

**Comment by aborruso** [comment]
Hi,
you can use [`system`](http://johnkerl.org/miller/doc/data-sharing.html#Running_shell_commands) function:

```bash
example="Hello"

echo 'example=ciao' | mlr put '$fieldName=system("echo '"$example"'")'
```

and you will have

```
example=ciao,fieldName=Hello
```

**Comment by spmundi** [comment]
Andrea
Thanks. I guess that works but it looks horribly inefficient: doesn't that spawn a new process for every line in the input file?  But I guess I can wrap that in an if(NR==1) statement or such. It does, though, require an environment variable, and not just a shell local variable.

Perhaps I could make a formal request for parameters to be set on the command line in the same was as awk?

**Comment by aborruso** [comment]
@spmundi the file name is the one of your mlr input file?

**Comment by johnkerl** [comment]
`mlr -s my_variable=my_value` is awesome! And not too hard to code up.

Only caveat, these would come in as out-of-stream variables:

```
$ echo 'a=cheese,b=cabbage' | mlr -s foo=bar put '$new=@foo.$a'
a=cheese,b=cabbage,new=barcheese
```

would do the same as

```
$ echo 'a=cheese,b=cabbage' | mlr put 'begin{@foo="bar"} $new=@foo.$a'
a=cheese,b=cabbage,new=barcheese
```

**Comment by johnkerl** [comment]
Correction, that would be

```
$ echo 'a=cheese,b=cabbage' | mlr put -s foo=bar '$new=@foo.$a'
a=cheese,b=cabbage,new=barcheese
```

**Comment by johnkerl** [comment]
@spmundi the commit https://github.com/johnkerl/miller/commit/8d63f17f1ac5b39a286dc51fbf10e47dd2947c54 has the essential feature -- unit-tests and documentation to follow on subsequent commits.

```
mlr --opprint put -s foo=bar -s baz=quux '$new=@foo.$a.@baz' ../data/small
a   b   i  x                   y                   new
pan pan 1  0.3467901443380824  0.7268028627434533  barpanquux
eks pan 2  0.7586799647899636  0.5221511083334797  bareksquux
wye wye 3  0.20460330576630303 0.33831852551664776 barwyequux
eks wye 4  0.38139939387114097 0.13418874328430463 bareksquux
wye pan 5  0.5732889198020006  0.8636244699032729  barwyequux
zee pan 6  0.5271261600918548  0.49322128674835697 barzeequux
eks zee 7  0.6117840605678454  0.1878849191181694  bareksquux
zee wye 8  0.5985540091064224  0.976181385699006   barzeequux
hat wye 9  0.03144187646093577 0.7495507603507059  barhatquux
pan wye 10 0.5026260055412137  0.9526183602969864  barpanquux
```

**Comment by johnkerl** [comment]
Commit https://github.com/johnkerl/miller/commit/b5a5c14904c5fa8b4dc7e03ec897deaaa62593d9 has online help and manpage.

**Comment by spmundi** [comment]
Wow, John. You move fast!
Thanks

**Comment by johnkerl** [comment]
@spmundi fast *sometimes*. Very slow others. ;)

Thanks for the great feature request! :)
