### ISSUE TITLE
(Undocumented ?) exit codes

### ISSUE THREAD

**Issue by afranke** [johnkerl/miller#316]
Maybe I missed something but I was unable to find anything in the docs regarding exit codes. I have a set of scripts that do miscellaneous operations on TSV files with miller and other tools. One of them in the middle of the pipeline was failing but still producing a file, and it took me a while to figure out that something was wrong and what it was. In the end, I noticed a suspiciously small file compared to the original, because miller was choking on a malformed line and stopped on that record so I had only the beginning of the input in the output up to that line. Then I saw that mlr was actually returning 1 which would have been helpful to know earlier.

I would expect at the very list the documentation to tell me that mlr will return 1 when something goes wrong. It would be even better if I could get something more precise that tells me what happened so I know where to look for the source of the issue.

**Comment by johnkerl** [comment]
Thanks. I can write this up but the short of it is 0 for normal exit and 1 for not-normal exit. I don't use any others than 0 or 1.

If you can send me some sample TSV where Miller is choking on a malformed line but still exiting with 0 that would be great -- that is definitely a bug I want to fix.

**Comment by johnkerl** [comment]
@afranke I put a write-up at https://miller.readthedocs.io/en/latest/reference-main-overview/#exit-codes -- please let me know if we need to re-open this issue -- thanks!

**Comment by afranke** [comment]
Sorry I didn’t get back to you earlier. I think the write-up is great, thank you.

Unfortunately I don’t work on that project where I had the issue anymore, so I can’t provide any more context on choking on TSV. Thanks again for your tool, it has been **very** useful.
