### ISSUE TITLE
Regex as conditional in put

### ISSUE THREAD

**Issue by spmundi** [johnkerl/miller#317]
I fear I will wear out my welcome mat if I keep up this rate of posting. Apologies.

I am trying to do the following :
if ($var =~ "some_regexp") {
     another_var = value;
} elif ($var =~ "some_other_regexp") {
    another_var = some_other_value;
}

This doesn't work. I get this message:
"Expression does not evaluate to boolean: got MT_ERROR"

On close reading of John's documentation it would appear that this is not supported. I guess because a statement like
x =~ "someregexp"
does not evaluate to a boolean result. Is that so?

But how can one then do one thing if a regexp matches, and another thing if it doesn't?
**THIS COMMENT IS NOT TRUE: SEE NEXT POSTING**

**Comment by spmundi** [comment]
**Correction**. The problem was elsewhere. I was trying to do this conditional within the regexp match:
if( ((a % 2) == (b %2)) {
}
that is what didn't work. I am still not sure why.

**Comment by spmundi** [comment]
There is something very strange at work here. I have distilled my code (ie lines in a file refeerenced by put -f) to bare essentials:

**if( $address =~ "^([1-9][0-9]*)") {
    $nsw_lonum  = "\1";
    $nsw_hinum  = 2;
    $lparity = $nsw_lonum % 2;
    if($lparity == 1) {
        $nsw_parity = $lparity;
    }
}**

Gives the aforementioned error and no output.
If I change statement #4 to:

**$lparity = $nsw_hinum % 2;**

then everything is ok.

**Comment by spmundi** [comment]
I think I have found the problem.
The line **$nsw_lonum = "\1"**  seemed to extract an integer (it is a street address in fact) but mlr is treating it as a real. Then taking a modulo 2 returns an error. Then the if statement fails.
If I code instead **$lparity = int($nsw_lonum) %2** works OK.
But why don't I have to cast $nsw_hinum in the same fashion??

**Comment by johnkerl** [comment]
@spmundi re "I fear I will wear out my welcome mat if I keep up this rate of posting. Apologies." -- haha!! :) No, keep it coming! I really appreciate the dialog. :)

**Comment by johnkerl** [comment]
Real mod int is supported:

```
$ echo x=1 | mlr put '$x=$x%2'
x=1
$ echo x=1.0 | mlr put '$x=$x%2'
x=1.000000
$ echo x=1.1 | mlr put '$x=$x%2'
x=1.100000
```

But `$nsw_lonum` is definitely a string & hence the error trying to reduce it mod 2.

```
$ cat x.csv
address
20 foo
21 foo
22 foo
23 foo
```

```
$ cat nsw.mlr
if( $address =~ "^([1-9][0-9]*)") {
    $nsw_lonum  = "\1";
    $nsw_hinum  = 2;

    $lparity = $nsw_lonum % 2;
    $typeof_nsw_lonum = typeof($nsw_lonum);
    $typeof_lparity = typeof($lparity);

    $lparity = int($nsw_lonum) % 2;
    $typeof_nsw_lonum = typeof($nsw_lonum);
    $typeof_lparity = typeof($lparity);

    if($lparity == 1) {
        $nsw_parity = $lparity;
    } else {
        $nsw_parity = ""
    }
}
```

```
$ mlr --c2p put -f nsw.mlr x.csv
address nsw_lonum nsw_hinum lparity typeof_nsw_lonum typeof_lparity nsw_parity
20 foo  20        2         0       string           int            -
21 foo  21        2         1       string           int            1
22 foo  22        2         0       string           int            -
23 foo  23        2         1       string           int            1
```

So I think you want your line 2 to be

```
    $nsw_lonum  = int("\1");
```

**Comment by johnkerl** [comment]
@spmundi I believe this is resolved -- ?

If I'm mistaken please feel free to re-open -- thanks!
