### ISSUE TITLE
regex: how to replace first char at the beginning of a cell

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#322]
Hi,
if I run 

```
echo a=309090 | mlr put -S '$b=gsub($a,"^.","")'
```

I have `a=309090,b=` and not `a=309090,b=09090`. Am I doing something wrong? How to map the generic first char of a cell?

Thank you

**Comment by johnkerl** [comment]
I think you want `sub` not `gsub` ?

**Comment by aborruso** [comment]
I'm really stupid :(

Thank you
