### ISSUE TITLE
Bug with uniq

### ISSUE THREAD

**Issue by mfernandez-turnto** [johnkerl/miller#323]
First I want to say tanks for miller, it is a tool I use daily as part of my workflow, it is an excelent tool, that said, I was extracting a list of unique items in a column by:

`mlr --icsv --onidx cut -f column then uniq -a then sort filename.csv`

And I noticed some of the lines were repeated, I did some steps to try to fix it with no sucess. This is what I tried:

```
mlr --icsv --onidx cut -f column then uniq -f column then sort filename.csv
mlr --icsv --onidx cut -f column then sort then uniq -f column filename.csv
mlr --icsv --onidx cut -f column then put '$column = strip($column)' then sort then uniq -f column filename.csv
```

I also tried:

`mlr --icsv --onidx cut -f column then uniq -f column then sort -f column filename.csv |mlr lecat`

But I saw no difference between the repeated lines, of course piping to regular unix uniq eliminates the extra copies, but I thought I should report this. Unfortunately I cannot share the file that is giving me this problem.

Another thing I noticed while experimenting is that:

`mlr --icsv --onidx count-distinct -f column then sort -f column filename.csv`

Gives me the same number of lines, but the first appearance has a count and the second doesn't.

PS: I looked in the issues I found nothing similare so I decided to report.

**Comment by aborruso** [comment]
Hi, I have tested with a file of mine and I have no error.
A note, when you use sort I think you should set also the field name. Then something like:

```
mlr --icsv --onidx cut -f column then uniq -a then sort -f column input.csv
```

I'm using `Miller v5.7.0`

**Comment by mfernandez-turnto** [comment]
I did one more experiment and found what was wrong, it was not miller's fault but me not realizing that I had values that expanded 2 lines. When I did --ocsv instead of --onidx I got.

"aaa", 3
"aaa
additional text", 1

Sorry about the confusion, and thanks for the prompt help.
