### ISSUE TITLE
Pass CSV data that is already stored in a variable

### ISSUE THREAD

**Issue by wattry** [johnkerl/miller#328]
For argument's sake, I have a variable that stores CSV data in a file that needs some simple manipulation before I use miller to access the values.

How would I pass that variable into a miller command?

Please let me know if you need a snippet of code or if you will be able to assist. Thanks.

**Comment by johnkerl** [comment]
Looking ...

**Comment by johnkerl** [comment]
@09wattry your snippet of code would be handy indeed, thanks! :)

**Comment by Anth0nyME** [comment]
echo "$variable" | mlr
No?

**Comment by johnkerl** [comment]
> echo "$variable" | mlr
> No?

I had a hard time getting the carriage returns to be respected by echo ...

**Comment by johnkerl** [comment]
```
$ data='a,b,c
> 1,2,3
> 4,5,6'
$
$ echo $data
a,b,c 1,2,3 4,5,6
```

**Comment by Anth0nyME** [comment]
> 
> 
> ```
> $ data='a,b,c
> > 1,2,3
> > 4,5,6'
> $
> $ echo $data
> a,b,c 1,2,3 4,5,6
> ```

Quotation is a trick :)
$ echo "$data"

**Comment by Anth0nyME** [comment]
My own situation: remote command execution (expect\ssh in batch script) is return to me data in csv format. I don't want to store it in "middle" file and parse it later and i keep all returned data at system variable:

query

object_array=`expect -c 'log_user 0; set timeout -1; spawn ssh -o StrictHostKeyChecking=no '$ls_login'@'$ls_addr'; ...  ;expect {'$ls_cli':'$ls_login'>} {log_user 1; send "'$ls_target' -bytes -delim , \r"}; ...`

**echo "$object_array"** | mlr --csv cut -f 'id,enclosure_id,slot_id,mdisk_name,use,capacity,status,tech_type' | mlr --c2j --jlistwrap cat

raw csv input data:

id,status,error_sequence_number,use,tech_type,capacity,mdisk_id,mdisk_name,member_id,enclosure_id,slot_id,node_id,node_name,auto_manage,drive_class_id
0,online,,member,tier_enterprise,837.9GB,0,mdisk0,8,1,10,,,inactive,0
1,online,,member,tier_enterprise,837.9GB,0,mdisk0,9,1,4,,,inactive,0
2,online,,member,tier_enterprise,837.9GB,0,mdisk0,7,1,3,,,inactive,0
3,online,,member,tier_enterprise,837.9GB,0,mdisk0,11,1,7,,,inactive,0
4,offline,1242,failed,tier_enterprise,837.9GB,,,,1,2,,,inactive,

output json data:

[
{ "id": 0, "status": "online", "use": "member", "tech_type": "tier_enterprise", "capacity": 899647799296, "mdisk_name": "mdisk0", "enclosure_id": 1, "slot_id": 10 }
,{ "id": 1, "status": "online", "use": "member", "tech_type": "tier_enterprise", "capacity": 899647799296, "mdisk_name": "mdisk0", "enclosure_id": 1, "slot_id": 4 }
,{ "id": 2, "status": "online", "use": "member", "tech_type": "tier_enterprise", "capacity": 899647799296, "mdisk_name": "mdisk0", "enclosure_id": 1, "slot_id": 3 }
,{ "id": 3, "status": "online", "use": "member", "tech_type": "tier_enterprise", "capacity": 899647799296, "mdisk_name": "mdisk0", "enclosure_id": 1, "slot_id": 7 }
,{ "id": 4, "status": "offline", "use": "failed", "tech_type": "tier_enterprise", "capacity": 899647799296, "mdisk_name": "", "enclosure_id": 1, "slot_id": 2 }
]

So, it works as expected!
=)

**Comment by johnkerl** [comment]
@wattry I think we can close this out -- ? Please let me know if I'm mistaken & we can re-open. :)

**Comment by wattry** [comment]
@johnkerl shew, I completely forgot about this. You can close it
