### ISSUE TITLE
another old URL reference

### ISSUE THREAD

**Issue by tieguy** [johnkerl/miller#329]
https://github.com/johnkerl/miller/blob/b5a5c14904c5fa8b4dc7e03ec897deaaa62593d9/c/mapping/mapper_put_or_filter.c#L148

Contains "http://johnkerl.org/miller/doc/reference.html" and then a broken anchor.

Looks like a handful of these in --help throughout the codebase.

**Comment by johnkerl** [comment]
Fixed in https://github.com/johnkerl/miller/commit/09aab8f21656accd83749484f6cfbf6a4d343ab3 -- thanks for finding this! :)
