### ISSUE TITLE
seg fault from format-values

### ISSUE THREAD

**Issue by diekhans** [johnkerl/miller#330]
Miller 5.7.0 on both Mac and Linux:

The command:
`mlr --tsv format-values -f "%0.3f" galGal4-hg38.stats.join.tsv`

generates a segfault on the uncompressed version of the attached file.

[galGal4-hg38.stats.join.tsv.gz](https://github.com/johnkerl/miller/files/4641202/galGal4-hg38.stats.join.tsv.gz)

**Comment by johnkerl** [comment]
You definitely need `%0.3lf` not `%0.3f`, & I don't have a good way to enforce against float formats for doubles (or int formats for longs), as a general principle in Miller ... however, there's something else broken here ... debugging now ...

**Comment by johnkerl** [comment]
Well that was embarrasing :^/

https://github.com/johnkerl/miller/commit/ef6557537dcbadb7a44cb43904c259d3546e0d32

**Comment by johnkerl** [comment]
I'll publish a 5.7.1 bugfix release tout suite -- thanks for reporting this!!! :D

**Comment by diekhans** [comment]
> I'll publish a 5.7.1 bugfix release tout suite -- thanks for reporting this!!! :D

thanks for the fast response and for the great software

**Comment by johnkerl** [comment]
thanks @diekhans ! :)
