### ISSUE TITLE
Miller for windows: problem using filter

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#333]
Hi,
using the latest mlr for win this input file

```
year
2019-01
2018-11
```

if I run `mlr.exe --csv filter '$year>"2018-12"' input.csv` I have this error

```
mlr DSL: syntax error at "input"
mlr filter: syntax error on DSL parse of '$year input.csv'
```

I have no problem using the same command using mlr for Linux.

Thank you

**Comment by aborruso** [comment]
Solved, I must use double quotes in windows way

```
mlr.exe --csv filter "$year>""2018-11""" input.csv
```

**Comment by johnkerl** [comment]
worth an faq entry! :)

**Comment by johnkerl** [comment]
Options are at https://miller.readthedocs.io/en/latest/miller-on-windows/#differences

**Comment by aborruso** [comment]
> Options are at https://miller.readthedocs.io/en/latest/miller-on-windows/#differences

thank you
