### ISSUE TITLE
About mlr unhex (probably off-topic)

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#337]
Hi,
in this [covid19 map](https://giscovid.sdp.csi.it/tiles/), one of the source file it this one https://giscovid.sdp.csi.it/tiles/data/in.dat?rnd=0.3911148384866574https://giscovid.sdp.csi.it/tiles/data/in.dat?rnd=0.3911148384866574

It's a binary file.

Then I thought to run something like `hexdump -v inputfile | mlr unhex` to read it, but I do not have a readable result. Probably because in some way I must set a proper way to decode the binary file via hexdump (or other tools).
Or is there some simple and almost direct way to read it?

Thank you

**Comment by johnkerl** [comment]
Hi there -- `mlr unhex` takes only raw nybbles.

```
$ cat foo.txt
buongiorno!

$ hexdump -v foo.txt
0000000 62 75 6f 6e 67 69 6f 72 6e 6f 21 0a
000000c

$ mlr hex foo.txt
00000000: 62 75 6f 6e  67 69 6f 72  6e 6f 21 0a              |buongiorno!.|

$ mlr hex -r foo.txt
62 75 6f 6e  67 69 6f 72  6e 6f 21 0a

$ mlr hex -r foo.txt | mlr unhex
buongiorno!
```

**Comment by aborruso** [comment]
@johnkerl thank you.

Do you have some tips on where to start on how to decode those nibbles that are not raw. Reply to me only if it's a very fast reply.

As usual thank you

**Comment by aborruso** [comment]
> Hex-dumping that `in.dat` it looks like binary data in some format; I don't see strings. Do you know anything about the format of this file, e.g. from any author documentation?

I have seen this [code hack](https://github.com/lombax85/covidpiemonteparser/blob/master/csipiemonte.js) that decode the arraybuffer , but I do not understand ho to use it outside js, how to use via some cli/bash code.

**Comment by johnkerl** [comment]
@aborruso I don't think there are open action items here other than what we've already got written down in this issue -- please let me know if I'm mistaken & we can re-open -- thank you!
