### ISSUE TITLE
.mlrrc for defaults

### ISSUE THREAD

**Issue by awildturtok** [johnkerl/miller#339]
The data I work with is always in semicolon separated gzip compressed format. I've set up an alias to handle that but would it be possible to establish a .mlrrc or a default_args environment variable for Miller?

**Comment by aborruso** [comment]
Great idea

**Comment by johnkerl** [comment]
The feature is now in HEAD and will go out with 5.9.0.

Please see http://johnkerl.org/miller-releases/miller-head/doc/customization.html and let me know if/how this works for you!!

**Comment by awildturtok** [comment]
John this is actually really cool! Thanks for taking the time to implement and properly document this feature! I was very close to commenting on this thread again to propose profiles or similar, but this is much simpler and thus more elegant. Am 19.08.2020 17:27 schrieb John Kerl <notifications@github.com>:
The feature is now in HEAD and will go out with 5.9.0.
Please see http://johnkerl.org/miller-releases/miller-head/doc/customization.html and let me know if/how this works for you!!

**Comment by johnkerl** [comment]
@awildturtok thanks! What do you mean by "profiles" BTW?

**Comment by aborruso** [comment]
@johnkerl as usual very very cool: you and Miller are great.
It works very well

And this @awildturtok idea is a great idea.

**Comment by awildturtok** [comment]
The idea would be to have a file containing multiple named profiles for different use cases, basically what you've implemented just with multiple definitions at once that can be selected by a flag:

```
[zsv]
fs ;
prepipe zcat

[report]
j2m
skip-comments

```

```
mlr -Preport stats1 -amean,min,max,var -f requiredTime,numberOfResults queries.json
mlr -Pzsv uniq -f id people.csv.gz
```

this can be accomplished easily with your implementation by creating separate files `.mlrrc.json` and setting the env variable

**Comment by johnkerl** [comment]
Ooh I like this!!!! It would be backward-compatible with the `.mlrrc` logic as-is so this is worth thinking about. :)

**Comment by johnkerl** [comment]
@awildturtok I created https://github.com/johnkerl/miller/issues/358 to track the sections bit.

Thanks so much for this feature request! :)
