### ISSUE TITLE
Expression does not evaluate to boolean: got T_NULL

### ISSUE THREAD

**Issue by dubreuia** [johnkerl/miller#34]
Here's a minimal csv test file (named "miller_test.csv"):

    "header1","header2"
    "value1","value2"

I'm trying to filter on empty header1 column with:

    mlr --csv filter '$header1 != ""' miller_test.csv

And I get:

    Expression does not evaluate to boolean: got T_NULL.
    *** Error in `mlr': munmap_chunk(): invalid pointer: 0x000000000042915d ***
    Aborted (core dumped)

I have a fresh master from 5 minutes ago, freshly compiled, on gnome ubuntu 15.04.

**Comment by johnkerl** [comment]
Part of this is double-quoting: https://github.com/johnkerl/miller/issues/4

For that reason, `header1` is named `"header1"` and isn't appearing. So the second issue (after double-quoting) is filter on non-present fields, which violates Miller's fundamental heterogeneity-tolerance feature (http://johnkerl.org/miller/doc/record-heterogeneity.html).

**Comment by johnkerl** [comment]
Second issue fixed on commit https://github.com/johnkerl/miller/commit/624841f237225720406b8b24571b8d58399bd38e

First is underway ;)

Thanks for the bug report!!

**Comment by dubreuia** [comment]
No problem, thanks for developing miller!
