### ISSUE TITLE
Change header treating mode

### ISSUE THREAD

**Issue by Anth0nyME** [johnkerl/miller#345]
Helo!

Is it possible for mlr to switch Header treating?
I have a csv file without traditional headers at 1st row but the 1st column contain header for every row.

Please assist if possible...

Example:

id,000000N02020781
name,v3700v2
location,local

I need to get json like this:

[
  {
    "id": "000000N02020781",
    "name": "v3700v2",
    "location": "local"
  }
]

**Comment by aborruso** [comment]
If your input is only

```
id,000000N02020781
name,v3700v2
location,local
```

You can use [XTAB format](http://johnkerl.org/miller/doc/file-formats.html#XTAB:_Vertical_tabular) and run

```
mlr --x2j  --ips ,  --jvstack --jlistwrap cat input.txt
```

**Comment by Anth0nyME** [comment]
> 
> 
> If your input is only
> 
> ```
> id,000000N02020781
> name,v3700v2
> location,local
> ```
> 
> You can use [XTAB format](http://johnkerl.org/miller/doc/file-formats.html#XTAB:_Vertical_tabular) and run
> 
> ```
> mlr --x2j  --ips ,  --jvstack --jlistwrap cat input.txt
> ```

GREAT!

You absolutelly right!
Many thanks!!

Result:

[
{
  "id": 000000E020206941,
  "name": "v3700v2",
  "location": "local"
}
]
