### ISSUE TITLE
[NFR] Support for JSON Lines file format

### ISSUE THREAD

**Issue by calebeaires** [johnkerl/miller#346]
Hi, I didn't find at the documentation some option to Json LINE as describe here [JsonLines.org](http://jsonlines.org/ ). Is there some page I am missing?

**Comment by aborruso** [comment]
Hi @calebeaires ,
 JsonLines is in some way the default input & output json format.

If you have in example this CSV 

```
a,b
1,2
5,6
```

and run ``mlr --c2j cat input.csv`, you will have

```
{ "a": 1, "b": 2 }
{ "a": 5, "b": 6 }
```

And if you run on this jsonl `mlr --j2c cat input.jsonl`, you will have again

```
a,b
1,2
5,6
```

**Comment by calebeaires** [comment]
Hey @aborruso, thanks for the quick answer. I am looking to something like this

```json
["Name", "Session", "Score", "Completed"]
["Gilbert", "2013", 24, true]
["Alexa", "2013", 29, true]
["May", "2012B", 14, false]
["Deloise", "2012A", 19, true] 
```

**Comment by aborruso** [comment]
Do you need to create it as output starting from CSV or to read it as input?

**Comment by calebeaires** [comment]
Start from csv, convert/output to JSON Line. The reason: If the header stays on top, and  each sub-sequence of rows does not have its props, we will have a smaller file. 

I will use it to import data to [Clickhouse](https://clickhouse.tech/docs/en/interfaces/formats/) database. This database works very well with this type of data (Json line)

**Comment by aborruso** [comment]
Hi @calebeaires I do not know if there is a mlr way to create your kind of jsonl.

If you use [jq](https://stedolan.github.io/jq/) and miller, starting from this CSV

```
a,b
1,2
5,6
```

and running `mlr --c2j cat input01.csv | jq -c 'to_entries|map_values(.value)'`, you will have

```
[1,2]
[5,6]
```

But probably there is a better way to do it

**Comment by aborruso** [comment]
@calebeaires is it ok for you?

**Comment by johnkerl** [comment]
Miller doesn't do JSON Lines but it would be pretty easy to add I think! :)

**Comment by calebeaires** [comment]
Not quite the same, but Almost there:

Given a simple CSV Tab-separated, here is the result.

Command
`mlr --c2j cat campanha.csv | jq -c 'to_entries|map_values(.value)'`

Result
```json
["SnRGk9Ot\t24\tcaseiro\t55761\tcasado\tcaro\tcorrida\t78024\tnao"]
["d9vUhHIf\t63\tcaseiro\t35659\tsolteiro\tpratico\tcorrida\t88907\tsim"]
```

Whe have to simple problems:

1. Entire line quoted
2. \t written on the line, not transformed to CSV separator

**Comment by aborruso** [comment]
If it's a TSV, you must set it.


Or in this way

mlr --t2j cat campanha.csv

or

mlr --c2j --ifs "\t" cat campanha.csv

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il dom 5 lug 2020, 20:37 Calebe Aires <notifications@github.com> ha scritto:

**Comment by calebeaires** [comment]
Now it is ok

Command 
```shell
mlr --c2j --ifs "\t" cat campanha.csv | jq -c 'to_entries|map_values(.value)'
```

Result
```json
["9duykBWv",28,"saudavel",75554,"casado","caro","corrida",143843,"sim"]
["8r1lKAxK",22,"ativista",50052,"solteiro","pratico","academia",72659,"nao"]
["TzGNeEpz",22,"ativista",41102,"casado","pratico","futebol",137502,"nao"]
["0FtmvbGX",28,"saudavel",15873,"solteiro","pratico","futebol",50645,"nao"]
["Jx9miDCJ",30,"ativista",19249,"casado","pratico","corrida",53486,"nao"]
["VZLFeVc1",15,"saudavel",80056,"casado","caro","academia",113897,"nao"]
```

**Comment by johnkerl** [comment]
This is being addressed as discussed at https://github.com/johnkerl/miller/discussions/755 (which is a discussion, not an issue ... but the work is being done regardless ... sorry for the confusion!) :)

**Comment by johnkerl** [comment]
Do note that for
https://github.com/johnkerl/miller/issues/346#issuecomment-653772590

> If the header stays on top, and each sub-sequence of rows does not have its props, we will have a smaller file.

this is an example use of JSON Lines, not a requirement of JSON Lines. For Miller 6, JSON Lines will be JSON but with no outermost `[...]`, and all records one per line. This will fulfill the spec at https://jsonlines.org.
