### ISSUE TITLE
Replace YYYYMMDD as unix time

### ISSUE THREAD

**Issue by Anth0nyME** [johnkerl/miller#348]
Hello!

I have a multistring output (from query) in csv format:

id,name,state,trial_expiration_date
0,easy_tier,trial_available,20201007
1,flashcopy_upgrade,inactive,
2,remote_mirroring,trial_available,20201007

This csv i placed to system variable $object_array.

I need to **replace** string 20201007 (YYYYMMDD) to unix time. If i try to do it with only one string from this array (and omits header), string look as expected.

`echo "0,easy_tier,trial_available,20201007" | mlr --csvlite --implicit-csv-header --headerless-csv-output put -S '$4 = strptime($4,"%Y%m%d")'`

Output (right): `0,easy_tier,trial_available,1602028800.000000`

But if i try to do replace globally, in all strings of this array, i got wrong result (nothing changes)

`echo "$object_array" | mlr --csvlite put -S '$4 = strptime($4,"%Y%m%d")'`

Current output (**wrong**): 

id,name,state,trial_expiration_date
0,easy_tier,trial_available,20201007
1,flashcopy_upgrade,inactive,
2,remote_mirroring,trial_available,20201007

Expected output:

id,name,state,trial_expiration_date
0,easy_tier,trial_available,1602028800.000000
1,flashcopy_upgrade,inactive,
2,remote_mirroring,trial_available,1602028800.000000

Can anybody help me with this conversion or just point me to my mistake?
Many thanks for any assist!

**Comment by aborruso** [comment]
Hi,
if you use `--implicit-csv-header` your file is

```
1,2,3,4
id,name,state,trial_expiration_date
0,easy_tier,trial_available,20201007
1,flashcopy_upgrade,inactive,
2,remote_mirroring,trial_available,20201007
```

and then you will apply `strptime` to field `$4`, and then you will apply `strptime` to value "trial_expiration_date", that is no more an header but a value.

If you run

```
mlr --csv put -S '$trial_expiration_date = strptime($trial_expiration_date, "%Y%m%d")' ./input.csv
```

you will have

```
id,name,state,trial_expiration_date
0,easy_tier,trial_available,1602028800.000000
1,flashcopy_upgrade,inactive,
2,remote_mirroring,trial_available,1602028800.000000
```

**Comment by Anth0nyME** [comment]
> 
> 
> Hi,
> if you use `--implicit-csv-header` your file is
> 
> ```
> 1,2,3,4
> id,name,state,trial_expiration_date
> 0,easy_tier,trial_available,20201007
> 1,flashcopy_upgrade,inactive,
> 2,remote_mirroring,trial_available,20201007
> ```
> 
> and then you will apply `strptime` to field `$4`, and then you will apply `strptime` to value "trial_expiration_date", that is no more an header but a value.
> 
> If you run
> 
> ```
> mlr --csv put -S '$trial_expiration_date = strptime($trial_expiration_date, "%Y%m%d")' ./input.csv
> ```
> 
> you will have
> 
> ```
> id,name,state,trial_expiration_date
> 0,easy_tier,trial_available,1602028800.000000
> 1,flashcopy_upgrade,inactive,
> 2,remote_mirroring,trial_available,1602028800.000000
> ```

Andrea, many thanks!
You right as always!

**Comment by aborruso** [comment]
If it's ok for you, you could close the issue
