### ISSUE TITLE
Question: add primary key column to poor structured CSV

### ISSUE THREAD

**Issue by Anth0nyME** [johnkerl/miller#349]
Hello!

I have a simple csv data without any unique id:

**stat_name,stat_current,stat_peak,stat_peak_time**
compression_cpu_pc,0,0,200716115738
cpu_pc,1,1,200716115738
fc_mb,0,0,200716115738
fc_io,10,29,200716115513
etc...

Question: how can i add an additional column with header "id" and unique primary keys for every row, from first record to last? Placement (order) of rows is constant, so no re-ordering needed.

What i need to get:

**id**,stat_name,stat_current,stat_peak,stat_peak_time
**0**,compression_cpu_pc,0,0,200716115738
**1**,cpu_pc,1,1,200716115738
**2**,fc_mb,0,0,200716115738
**3**,fc_io,10,29,200716115513
etc...

Thank you for any support! =)

**Comment by aborruso** [comment]
Hi @Anth0nyME you can use simply cat

```
mlr --csv cat -n then rename n,id input.csv
```

**Comment by Anth0nyME** [comment]
> 
> 
> Hi @Anth0nyME you can use simply cat
> 
> ```
> mlr --csv cat -n then rename n,id input.csv
> ```

Brilliant! As always!
Many thank you, Andrea!

**Comment by johnkerl** [comment]
@Anth0nyME @aborruso even fewer keystrokes: `mlr --csv cat -N id input.csv`
