### ISSUE TITLE
DSL: how to apply math to gsub regex output?

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#351]
Hi,
if I run

```
echo "a=14°20" | mlr put '$out=sub($a,"^([0-9]+)°([0-9]+)$","\1\2")'
```

I have `a=14°20,out=1420`

Is there a way to apply math to the two regex output groups? I would like to apply simple math as `firstGroup + secondGroup/60`. 

I could create two new temp fields and then do the math, but probably there is a smarter way.

Thank you

**Comment by johnkerl** [comment]
@aborruso how about this?

```
echo "a=14°20" | mlr put '$a =~"^([0-9]+)°([0-9]+)$" {$product = float("\1")*float("\2")}'
```

**Comment by aborruso** [comment]
So easy, thank you very much

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/pull/958
