### ISSUE TITLE
[NFR] Steps shift_lead and shift_lag

### ISSUE THREAD

**Issue by derekmahar** [johnkerl/miller#355]
Please add steps `shift_lead` and `shift_lag` to the [`step`](http://johnkerl.org/miller/doc/reference-verbs.html#step) verb.  Step `mlr step -a shift_lead` would include values in fields from the _next_ record while `mlr step -a shift_lag`, equivalent to the existing command `mlr step -a shift`, would include values in fields from the _previous_ record.  These two shift steps would correspond to the [SQL window functions LAG and LEAD](https://mode.com/sql-tutorial/sql-window-functions/#lag-and-lead).

**Comment by johnkerl** [comment]
This will most likely be done in the [Go port](https://github.com/johnkerl/miller/issues/372) rather than in the current (C) implementationl

**Comment by johnkerl** [comment]
@derekmahar sorry for the very long delay :^/

https://github.com/johnkerl/miller/pull/893
