### ISSUE TITLE
Infinity incorrectly encoded to string

### ISSUE THREAD

**Issue by tanguilp** [johnkerl/miller#357]
When converting from CSV, the "INFINITY" string (all caps), which is a brand, is converted to:

```
%{"brand": INFINITY}
```

and not the correct:

```
%{"brand": "INFINITY"}
```

I suspect a problem with handling of numbers.

**Comment by johnkerl** [comment]
Yes, this is for infinity as well as NaN (not a number). Standard math libraries will scan these as numbers unless one makes sure to bypass that. I knew about this for `Inf` but didn't realize the (clearly a string!!) `INFINITY` was also getting through. :(

**Comment by johnkerl** [comment]
This is addressed in Miller 6 -- https://johnkerl.org/miller6/reference-main-data-types/#type-inference-for-literal-and-record-data

**Comment by johnkerl** [comment]
For tracking I prefer to leave these open until the Go port is released. (Since that is non-trivial and non-immediate
