### ISSUE TITLE
segfault with bad syntax

### ISSUE THREAD

**Issue by jungle-boogie** [johnkerl/miller#36]
Hello,

`mlr --csvex uniq -g ST -c then sort -f -nr count banklist.csv| most` resulted in a core dump.

    zsh: segmentation fault (core dumped)  mlr --csvex uniq -g ST -c then sort -f -nr count banklist.csv | 
    zsh: done                              most

I'm certain this is a result of my bad syntax, but I don't think the core dump is the expected outcome.

This is the file I used: http://catalog.data.gov/dataset/fdic-failed-bank-list

Would you like the core dump file?

Thanks!

**Comment by johnkerl** [comment]
absolutely should not segfault. I can recreate the cote file; they don't transport so well across systems.

**Comment by johnkerl** [comment]
There is a syntax issue: `sort -f columna -nr columnb`. If I do `sort -nr count` then it's fine:
```
$ mlr --csvex uniq -g ST -c then sort -nr count ~/Downloads/banklist.csv 
ST,count
GA,91
FL,75
IL,66
CA,41
MN,23
WA,18
AZ,16
MO,16
...
```

What you have above is sorting lexically ascending on the column named `-nr`, then `count` is a filename. Then it segfaults (flat-out bug there) on the no-such-file.

So the segfault per se needs fixing; it should exit with `mlr: Couldn't open "count" for read` and not continue. Also, `sort` (and other subcommands as well) should probably error out in cases like `-f -nr`.

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/commit/cdb94dd17951e142446f0d7230aaea163d6bdc75 fixes the segfault. Now:
```
$ mlr --csvex uniq -g ST -c then sort -f -nr count banklist.csv
mlr: Couldn't open "count" for read.
count: No such file or directory
```

**Comment by johnkerl** [comment]
The `sort -f -nr` issue ... more wishlist. Marked in `c/todo.txt` for now.

Thank you for the report!!

**Comment by jungle-boogie** [comment]
Hello @johnkerl,

Nice work! I confirm your resolution worked!

:+1: 

Thanks,
jb!
