### ISSUE TITLE
Unlicensed code in draft Go port

### ISSUE THREAD

**Issue by skitt** [johnkerl/miller#367]
Hi John,

As far as I can tell https://github.com/johnkerl/miller/tree/master/go/src/localdeps/ordered doesn’t have a license; there’s [an issue open upstream asking for one](https://gitlab.com/c0b/go-ordered-json/-/issues/2), but it hasn’t had any reaction in two years.

Unfortunately without a license, this code will end up having to be stripped from the Miller packages in some distributions at least. That’s not a problem now, but it will be when the Go port becomes the primary implementation...

Regards,

Stephen

**Comment by johnkerl** [comment]
Sigh. Thanks @skitt , good catch .......

**Comment by johnkerl** [comment]
Fortunately the C version has an ordered-map implementation which I can adapt, and integrate directly with the JSON tokenizer API.

**Comment by johnkerl** [comment]
The dependency is removed as of https://github.com/johnkerl/miller/commit/4a48e9ce1fb67183bf697fabe0622fefc95922eb. Also, Miller records / values now have end-to-end JSON decode/encode support directly in Miller and the code is now quite elegant, so all is well. :)

Thanks again @skitt for the heads-up!! :D
