### ISSUE TITLE
Double quoted field at end of file

### ISSUE THREAD

**Issue by stn-ptr** [johnkerl/miller#368]
Using this input file (note: there is no CRLF at the end)
```
a,b
"text, text","more text"
```
I'm getting a parsing error:
```
$ mlr --csv cat doublequote.csv
mlr: unmatched double quote at line 1.
```

According to the RFC this should be valid CSV.

**Comment by aborruso** [comment]
hi @stn-ptr I'm using Miller v5.9.0 in Linux, and I have no error.

It was an old bug https://github.com/johnkerl/miller/issues/251

**Comment by stn-ptr** [comment]
I'm using Miller 5.4.0 in WSL Debian. I'll try to get the newest verion installed.

**Comment by stn-ptr** [comment]
It works with Miller v5.9.1. Thanks for the hint :)
