### ISSUE TITLE
"-n" and count verb

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#370]
Hi,
everytime I use `count -n` I have an error.

```
Usage: mlr count [options]
Prints number of records, optionally grouped by distinct values for specified field names.

Options:
-g {a,b,c}    Field names for distinct count.
-n            Show only the number of distinct values. Not compatible with -u.
-o {name}     Field name for output count. Default "count".
```

Moreover in the docs you have `Show only the number of distinct values. Not compatible with -u.`, but `-u` it's not a `count` option.

Thank you

**Comment by johnkerl** [comment]
Thanks @aborruso ! It turns out `mlr count` accepts `-n` at the command line but I never actually implemented the feature. :(

**Comment by johnkerl** [comment]
Done on https://github.com/johnkerl/miller/commit/7280d71162cc2a48b554d96ecee4341262c3c616 -- sorry about that @aborruso !! :^/

**Comment by aborruso** [comment]
Thank you @johnkerl , I will wait the next release.

Thank you  again
