### ISSUE TITLE
Golang port / Miller 6 tracking issue

### ISSUE THREAD

**Issue by johnkerl** [johnkerl/miller#372]
Split out from https://github.com/johnkerl/miller/issues/369. See also https://github.com/johnkerl/miller/blob/master/go/README.md.

Pre-release/rough-draft docs are at http://johnkerl.org/miller6.

**Things which may change:**

As noted in [go/README.md](https://github.com/johnkerl/miller/blob/master/go/README.md), I want to preserve as much user experience as possible. That said:

* `--jvstack` and `--jsonx` will still be supported as command-line flags, but JSON output will be pretty-printed (like `--jvstack`) by default.
* `--csvlite` will still be different from `--csv`, as detailed below.
* `emitf` and `emitp` were invented before I had for-loops in the DSL. If people really want to keep
 these and are using these, I can keep them; but maybe we're better off leaving them behind. Please
let me know.
* CR vs CR/LF (line-endings) will be platform-appropriate using Go's own portability -- Windows files will be written correctly on Windows, and likewise for Linux and MacOS. That said, I don't know if we need any longer to preserve CR/LF-to-CR/LF even on Linux (line endings which are non-standard for the platform) -- again, please let me know.
* `mlr put -S` and `mlr put -F` will become unnecessary since string-conversion will be done just-in
-time as suggested by @gromgit on https://github.com/johnkerl/miller/issues/151.

**Please include here any thoughts you have on the Go port.**

**Comment by aborruso** [comment]
> * `--csvlite` will no longer be different from `--csv` although `--csvlite` will still be accepted at the command line, to avoid breaking existing Miller scripts.

Many times csvlite saved my days, because often I have this kind of input data:

```
idImpianto;Gestore;Bandiera;Tipo Impianto;Nome Impianto;Indirizzo;Comune;Provincia;Latitudine;Longitudine
39241;STAZIONE ANDROMEDA DI VIVIAN LUCIANO & C. - S.N.C.;Agip Eni;Altro;stazione andromeda;c.so romita ang.via Galvani  15121;ALESSANDRIA;AL;44.901887213841604;8.619216307997704
22975;AN.GI DI ANTONIO LECCE S.A.S.;Api-Ip;Altro;Stazione di Servizio "IP" - An.Gi di Antonio Lecce;LUNGO TANARO SOLFERINO 7 15121;ALESSANDRIA;AL;44.91939743419402;8.61233416718187
27453;NEW ENERGY DI RRUSHI ERMIRA E C. S.N.C.;Agip Eni;Altro;STAZIONE DI SERVIZIO ENI NEW ENERGY SNC;VIA CASALE  28 15122;ALESSANDRIA;AL;44.9321969901607;8.58518036837404
```

The `fs` is `;`, and inside a field I have some `"`. In example `Stazione di Servizio "IP" - An.Gi di Antonio Lecce`. 

I'm able to read it via csvlite `mlr --icsvlite --ifs ";" cat input`. It might be a problem not to have it

**Comment by johnkerl** [comment]
OK cool thank you!! This is exactly what I was looking for. :)

**Comment by aborruso** [comment]
> OK cool thank you!! This is exactly what I was looking for. :)

Only a note: to give you more help, I need the GO version of miller. If there was mlr.**go**.linux.x86_64, it would be perfect.

Thank you

**Comment by johnkerl** [comment]
Yes, I can build you one for Linux or Mac quite easily ad-hoc. (If anyone needs a Windows build, let's chat on how to work together on that ... .)

That said, if you would be OK with cloning the Miller repo, `cd go`, and `./build`, it would be useful to me to see how that works for you.

Also maybe for future Miller 5 releases I can just attach a go binary as well, if that's what you mean -- ? Super-good idea! :)

**Comment by aborruso** [comment]
Hi @johnkerl ,
I have tested the latest go binary

```
echo '"hello, my dear john, thank you for Miller"' | mlrgo --c2x -N put '$regex=sub($1,"^(.+?),(.+)","\1")'
```

and I have

```
mlrgo: cannot parse DSL expression.
Parse error on token ""\1" at line 1 columnn 29.
Expected one of:
  { field_name $[ braced_field_name $[[ $[[[ full_srec oosvar_name @[ braced_oosvar_name
  full_oosvar non_sigil_name float int + - .+ .- ! ~ ( ) string_literal int_literal
  float_literal boolean_literal const_M_PI const_M_E panic [ ctx_IPS ctx_IFS
  ctx_IRS ctx_OPS ctx_OFS ctx_ORS ctx_NF ctx_NR ctx_FNR ctx_FILENAME ctx_FILENUM
  env
```

I think you know it, but if it were not so, I add it.

**Comment by aborruso** [comment]
The go port solve this.

If you have this input file

```
id,CODICE,NUM_PART,foglio,prov,cod_com
1593,579E,579E/,15,PA,A546
1594,579F,579F/,15,PA,A546
```

and use mlr 5 to run

```
<input.csv mlr --c2j cat
```

you have this wrong json output (`"CODICE": 579E` should be `"CODICE": "579E"`

```
{ "id": 1593, "CODICE": 579E, "NUM_PART": "579E/", "foglio": 15, "prov": "PA", "cod_com": "A546" }
{ "id": 1594, "CODICE": "579F", "NUM_PART": "579F/", "foglio": 15, "prov": "PA", "cod_com": "A546" }
```

Using the go version you have

```
{"id":1593,"CODICE":"579E","NUM_PART":"579E/","foglio":15,"prov":"PA","cod_com":"A546"}
{"id":1594,"CODICE":"579F","NUM_PART":"579F/","foglio":15,"prov":"PA","cod_com":"A546"}
```

Great

**Comment by johnkerl** [comment]
@aborruso thanks for testing!!! 🗡️ 

Re `Parse error on token ""\1" at line 1 columnn 29.` -- you're right, regex-captures aren't implemented yet. :^/

**Comment by amitbha** [comment]
@gromgit Thanks, I got it. `filter` judge by the final boolen state, so only output the last match in the array `K`. 
BTW, description for the work flow of `filter` not found in [document](http://johnkerl.org/miller6/reference-verbs/#filter).

I can explain the reason:
- A small quantity of data used to filter records, so it's simple and intuitive to put them in script.
- I actally want more powerful filter:  just like excel, use conditions on multi-fields.

The input file:
~~~
$ mlr --csv cat f.csv
num,name,desc
4,abc,cat
30,bd,dog
50,ce,bird
18,yyyy,human
10,ztz,rat
30,xyz,tree
~~~
My original solution is not working:
~~~
$ mlr --csv filter '
    # filter multi-fields: name and desc
    cond = [ ["a", "t"], ["z", "t"] ];
    for (c in cond) {
        $name =~ c[1] && $desc =~ c[2]
    }
' f.csv
~~~
Not working too:
~~~
$ mlr --csv filter '
    # filter multi-fields: name and desc
    cond = [ ["a", "t"], ["z", "t"] ];
    for (c in cond) {
        if ($name =~ c[1] && $desc =~ c[2]) {
           return true
        }
    }
' f.csv
~~~

Finally, I find a working solution: [DSL user-defined functions - Miller 6 Documentation](http://johnkerl.org/miller6/reference-dsl-user-defined-functions/)
~~~
$ mlr --csv filter '
    func f(n, d) {
        cond = [ ["a", "t"], ["z", "t"] ];
        for (c in cond) {
            if (n =~ c[1] && d =~ c[2]) {
               return true
            }
        }
    }
    f($name, $desc)
' f.csv
~~~

Problem solved. 😄

**Comment by gromgit** [comment]
The last row matches the second `cond` (`["z", "t"]`) in @amitbha's `for` loop.

That function definition actually collapses to:
```sh
mlr --csv filter '${name}.",".${desc} =~ "[az].*,.*t"' f.csv
```
I personally find that easier to understand that the `func`, but then I'm use to thinking in regexes.

**Comment by aborruso** [comment]
Adrian you have "&&" not "||" in your function, you have an AND condition,
than you should not have that row.

Am I wrong?

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il sab 9 ott 2021, 09:35 Adrian Ho ***@***.***> ha scritto:

**Comment by amitbha** [comment]
@gromgit  @aborruso  one-line regex is great 😀
~~~shell
$ mlr --csv filter '$name=~"[az]" && $desc=~"t"' f.csv
num,name,desc
4,abc,cat
10,ztz,rat
30,xyz,tree
~~~

`cond = [ ["a", "t"], ["z", "t"] ]`
The filter conditions above are simple ones, maybe longer and more complex in fact, for which I think array is more clean and clear than regex.
And func is more flexible.
~~~
$ mlr --csv filter '
    func filter_records() {
        cond = [ ["a", "t"], ["z", "t"] ];
        for (c in cond) {
            if ($name =~ c[1] && $desc =~ c[2]) {
               $date = system("date +%D.%T");   # do more things here
               return true
            }
        }
    }
    filter_records()
' f.csv
~~~

**Comment by gromgit** [comment]
> Adrian you have "&&" not "||" in your function, you have an AND condition, than you should not have that row. Am I wrong?

Recall the ["distributivity of AND over OR"](https://en.wikipedia.org/wiki/Boolean_algebra#Monotone_laws) Boolean algebraic identity:
```
(A && T) || (Z && T) === (A || Z) && T
```
@aborruso's `func` implements the LHS, while my filter expression implements the RHS.

**Comment by amitbha** [comment]
~~~
cond = [ ["a", "t"], ["z", "t"] ]
for (c in cond)
   if ($name =~ c[1] && $desc =~ c[2])
      return true
~~~
If any condition in array `cond` is satisfied, `true` is returned and output the record. 
So, the conditions in the array are in "OR" relationship, `["a", "t"] || ["z", "t"]`.

**Comment by johnkerl** [comment]
@amitbha @gromgit @aborruso 

* https://github.com/johnkerl/miller/pull/693 for `any/every` as well as more `mlr put/filter --help` output
* See examples at https://johnkerl.org/miller6/reference-verbs/#put and https://johnkerl.org/miller6/reference-verbs/#filter
* See also https://johnkerl.org/miller6/reference-dsl for more context

**Comment by BEFH** [comment]
Will you have a `configure` for making the new version to set install prefix? It's easy enough to manually copy stuff, but it would be nice for it to be automatic.

**Comment by johnkerl** [comment]
@BEFH indeed ...

The [base Makefile](https://github.com/johnkerl/miller/blob/main/Makefile) calls [go/Makefile](https://github.com/johnkerl/miller/blob/main/go/Makefile#L1-L2) which (for the moment as a placeholder) has `INSTALL_DIR` set to `/usr/local/bin` (and similarly for [man/Makefile](https://github.com/johnkerl/miller/blob/main/man/Makefile#L5-L6)).

That's OK on my laptop, & maybe OK for build-from-source cases, and probably OK for `brew` ... but this is definitely a problem I need to solve for general release.

Honestly, all that `./configure` business (in its full GNU-ish splendor) goes waaaaaay over my head & I got some fantastic from @0-wiz-0 on the initial (C) release way back in 2015 -- he was a true lifesaver & a hero.

For Go, I *think* (fingers crossed) all I need is a simple shell script called `./configure` which accepts `--prefix` and nothing else.

My thought is to start with `brew` and `macports`; maybe `chocolatey` after; check with @skitt on [miller.spec](https://github.com/johnkerl/miller/blob/main/miller.spec) after I do a bit of homework on how other Go tools get themselves built for Linux distros ...

**Comment by BEFH** [comment]
Sweet. It looks right now like the go port is a mix of go and C, or at least needs both go and c for compilation?

I'm trying to update the conda-forge recipe for Miller so that it works with the current v5 and will also work when v6 is released.

I did manage to compile v6 with the anaconda GCC and go toolchains, so it *should* work.

**Comment by johnkerl** [comment]
> at least needs both go and c for compilation

no, not at all ... are you getting a fresh pull from head? I (thought I) red-PR'ed the C code some days ago ...

> I'm trying to update the conda-forge recipe for Miller

so good to meet you!! :) i heard from a co-worker the other day he installs miller via conda & this was great news to me (i know little about conda) 

@BEFH do you mind sharing your conda build/config/whatever files? i'd love to learn more ...

**Comment by johnkerl** [comment]
(btw there are a couple remaining source-code mods before general release of miller 6, not just work on `./configure` and `miller.spec` ... just fyi)

**Comment by BEFH** [comment]
@johnkerl, I can share as soon as I get home. It's not actually successfully compiling the current 5x release (I opened an issue for that).

I can also identify where it requires GCC for head if that would be helpful. Is it possible it's a library you depend on instead of your own code?

**Comment by johnkerl** [comment]
>  Is it possible it's a library you depend on instead of your own code?

i hope not!! :) we'll find out ... :)

thank you!!! :)

**Comment by BEFH** [comment]
@johnkerl, here's the error if gcc is absent:

```
(base) ubuntu@touched-drum:~/miller$ make
make -C go build
make[1]: Entering directory '/home/ubuntu/miller/go'
go build
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading golang.org/x/term v0.0.0-20201210144234-2321bbc49cbf
go: downloading github.com/lestrrat-go/strftime v1.0.4
go: downloading golang.org/x/sys v0.0.0-20210326220804-49726bf1d181
go: downloading github.com/pkg/errors v0.8.1
# runtime/cgo
cgo: exec x86_64-conda-linux-gnu-cc: exec: "x86_64-conda-linux-gnu-cc": executable file not found in $PATH
make[1]: *** [Makefile:5: build] Error 2
make[1]: Leaving directory '/home/ubuntu/miller/go'
make: *** [Makefile:5: build] Error 2
```

Beforehand, I installed Miniconda, initialized it, sourced my `.bashrc`, then ran the following:

```
conda install -c conda-forge mamba
mamba install -c conda-forge go make
```

After the error, I ran `mamba install -c conda-forge gcc`, after which make ran just fine:

```
(base) ubuntu@touched-drum:~/miller$ make
make -C go build
make[1]: Entering directory '/home/ubuntu/miller/go'
go build
make[1]: Leaving directory '/home/ubuntu/miller/go'
Miller executable is: go/mlr
```

As for the conda-forge feedstock, here is the branch I am working on: https://github.com/BEFH/miller-feedstock

**Comment by johnkerl** [comment]
ok from `go mod graph` it looks like `gocc` (which miller uses for parser-generator) uses `x/tools` which uses `cgo` ... TIL :)

**Comment by johnkerl** [comment]
re https://github.com/BEFH/miller-feedstock/blob/master/recipe/meta.yaml we should be able to remove the `flex` dependency ... miller <= 5 used `flex` + `lemon` for lexing/parsing respectively; for miller 6 the `gocc` go package does both

**Comment by BEFH** [comment]
`{{ compiler('cxx') }}` is also probably unnecessary. I'm still hoping that we can get this running for both the C version and the go version in the unlikely event that legacy code requires an old version. But I might end up just having to support go. IDK if you noticed, but build.sh currently detects whether there's a `config` file and does different things one way or the other.

**Comment by johnkerl** [comment]
> i'm still hoping that we can get this running for both the C version and the go version

i'm not sure what that would even mean given https://github.com/johnkerl/miller/pull/731 -- if you need mods in the now-gone C code, could you use a branch off `main`? (or a fork of the miller repo maybe ... ?)

**Comment by BEFH** [comment]
I don't need any mods. I just have a bit of a concern that there may be slight (reasonable) differences between v5 and v6 that might break legacy scripts using miller. Should I not worry?

**Comment by johnkerl** [comment]
there are absolutely slight / reasonable differences between miller 5 & 6 :) -- https://miller.readthedocs.io/en/latest/new-in-miller-6/#changes-from-miller-5 and i may uncover a few more.

i'm quite happy to have you being careful of breaking legacy scripts.

my only concern was if you need mods to the C code (which is gone) -- there are slight/reasonable differences between old & new, and i'm hoping to leave the old "frozen in time" and not update the old.

so we're good here -- it sounds like any mods you need will be in your feedstock etc.

**Comment by johnkerl** [comment]
> Will you have a configure for making the new version to set install prefix? It's easy enough to manually copy stuff, but it would be nice for it to be automatic.

@BEFH as of https://github.com/johnkerl/miller/pull/741 I have the rudimentary-but-hopefully-sufficient `./configure --prefix /foo/bar` I mentioned above at https://github.com/johnkerl/miller/issues/372#issuecomment-964625839

Note this is `configure` and not `config` though.

**Comment by BEFH** [comment]
config was a brain fart on my part from using too much Snakemake. I've fixed it locally.

**Comment by johnkerl** [comment]
all good, thanks @BEFH !! :D

**Comment by skitt** [comment]
I’m not a Go packaging expert (yet), but I’ll look into it ;-). Ignoring distribution packages, it would be nice IMO if the project could be structured in such a way that

    go install github.com/johnkerl/miller

does the right thing. See https://github.com/golang-standards/project-layout also (but ignore the `/cmd` part since there’s only one command to install).

**Comment by johnkerl** [comment]
nice, thanks @skitt ! :)

**Comment by johnkerl** [comment]
@skitt most of the recent items on this thread are conda-related ... for distros I think the main points are:

* https://github.com/johnkerl/miller/blob/main/configure
* https://github.com/johnkerl/miller/blob/main/Makefile
* https://github.com/johnkerl/miller/blob/main/miller.spec

Your advice about https://github.com/golang-standards/project-layout is great -- I think it'll be orthogonal to the `configure`/`make`/`miller.spec` setup. I.e. when I re-arrange the Go-source structure I'll make sure to adapt the `configure`/`make`/`miller.spec` setup so it still works.

**Comment by BEFH** [comment]
@johnkerl, I've made a [pull request](https://github.com/johnkerl/miller/pull/744) to make the configure syntax more standard.

**Comment by skitt** [comment]
> @skitt most of the recent items on this thread are conda-related ... for distros I _think_ the main points are:
> 
>     * https://github.com/johnkerl/miller/blob/main/configure
>     * https://github.com/johnkerl/miller/blob/main/Makefile
>     * https://github.com/johnkerl/miller/blob/main/miller.spec

I agree — IMO the project itself should “just work” in idiomatic Go style (`go install` / `go get` with properly-defined modules), and `configure`/`Makefile` etc. apply on top of that to provide whatever distributions typically expect.

Given that Go is highly opinionated, and one can expect `go build`, `go test` etc. to “just work”, it may even be that `configure` and `Makefile` don’t end up being all that useful, except for making sure the documentation is installed (since Go doesn’t handle that).

> Your advice about https://github.com/golang-standards/project-layout is great -- I think it'll be orthogonal to the `configure`/`make`/`miller.spec` setup. I.e. when I re-arrange the Go-source structure I'll make sure to adapt the `configure`/`make`/`miller.spec` setup so it still works.

Yes, that’s what I was hoping for ;-).

**Comment by johnkerl** [comment]
@skitt one critical issue (I also ran into this some months ago):

* The project is Miller and the executable name is `mlr`. Which goes back years (to the beginning) and I should not break people's expectations
* Using `module github.com/johnkerl/miller` in `go.mod` then `go build` produces an executable named `miller` not `mlr` -- this is a hard stop for me :(
  * One idea is I have `module mlr` (as now) -- not great since it breaks the Go-is-highly-opinionated expectation (I think)
  * Another is to use `module github.com/johnkerl/miller` but insist that people type `go build mlr.go` instead of `go build` -- which I think will be error-prone
  * A third is to have some rename-rule in a makefile renaming `miller` to `mlr` -- also error-prone, and would require people to step outside of `go build`
  * A fourth is rename the repo _entirely_ to `github.com/johnkerl/mlr` -- seems like an intimidatingly big step
 
A priori I don't know how to solve this puzzle :( ... but will do some research ...

**Comment by skitt** [comment]
Ah, the `/cmd` layout might come in handy after all — `go install github.com/johnkerl/miller/cmd/mlr` assuming the appropriate directory layout. I haven’t tried `go build` with that.

**Comment by amitbha** [comment]
`stats1` not support positional field name?

```bash
$ cat 1.txt
2
4
4
0
4
5
3
$ mlr --n2p filter '$[[[1]]] > 0' then stats1 -a mode -f '$[[1]]' 1.txt
```
No output.

**Comment by aborruso** [comment]
hi @amitbha , if you use NIDX, for miller you have Index-numbered fields.

Then you can run simply

```
mlr --n2p filter '$1 > 0' then stats1 -a mode -f 1 1.txt
```

to have

```
1_mode
4
```

> `stats1` not support positional field name?

`stats1` does not support it. Only using DSL, than in `filter` and `put`.

**Comment by amitbha** [comment]
@aborruso Thanks.
I think if there are some warnings for these cases, will be more friendly for beginners. 😃

**Comment by johnkerl** [comment]
All known release-blocking issues are resolved. Fresh binaries are at https://github.com/johnkerl/miller/releases/tag/v6.0.0-beta. I hope to make the 6.0.0 release very soon, barring any feedback.

**Comment by BEFH** [comment]
Do you want me to test conda for this, or do you want me to just monitor things when you make the official release. Additionally, I could make a pull request to integrate a github workflow that tests the build every time you create a tag. Assuming the unit tests are still run during the build process, it should be fairly painless.

**Comment by johnkerl** [comment]
@BEFH I'd love it if you could try Conda first! :)

There is one more release-blocker -- https://github.com/johnkerl/miller/issues/827 -- you can try a Conda test before that's resolved, if you like; I won't make the official release though until it's resolved.

**Comment by BEFH** [comment]
@johnkerl, sure. Do you also want me to add an automated test on either tag, push or pull?

**Comment by johnkerl** [comment]
@BEFH sure -- I don't see why not, anyhow ... 🙏

**Comment by skitt** [comment]
I’ve got the missing Go dependencies queued up in Debian, and I’ll be checking an updated package of Miller 6 over the next few days. I haven’t looked at the situation in Fedora, one thing at a time ;-).

**Comment by BEFH** [comment]
I've identified (and fixed) a couple of issues with the build process on Linux. I'm confident those issues are fixed, but now there's some issue with the conda build environment that's resulting in the error `$GOPATH/go.mod exists but should not`, both on Mac and Linux. I will try to debug this, but I am stumped for tonight.

Do you want me to just initiate a pull request for the fixed issues, or should I submit a bug first?

btw, Anaconda also doesn't like version numbers with dashes in them, so the current beta tag did not work with building.

**Comment by johnkerl** [comment]
> Do you want me to just initiate a pull request for the fixed issues, or should I submit a bug first?

@BEFH a PR is fine, thanks! :)

> as long as this is OK:

those are OK but the bulk of the tests are from `regression_test.go` (`go test -v regression_test.go`) which produces quite a bit more output ...

**Comment by johnkerl** [comment]
Current blockers for release:

* https://github.com/johnkerl/miller/issues/827 -- needs documentation
* https://github.com/johnkerl/miller/discussions/755 -- needs coding and documentation

**Comment by BEFH** [comment]
@johnkerl, it looks like you patched the sed issue, but not the copy issue in the makefile. The sed issue is that `-I` works on macOS (maybe) but not on other platforms. if you replace `-I .prefix-backup` with `-i.prefix-backup`, it should work. Sed doesn't like the capital I or the space. Should I make that change now when I fix the Makefile, or nah?

**Comment by johnkerl** [comment]
@BEFH yes please! :D

**Comment by johnkerl** [comment]
But what I thought I changed was to not use `sed -I` at all, but rather, just `sed ... foo > foo.tmp` and `mv foo.tmp foo`

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/blob/main/configure#L42

unless we're talking about two different things ...

**Comment by BEFH** [comment]
Yeah, I saw that you made that change, which was not in the beta release. Just stating that I came up with an alternate way that did sed in-place and worked on multiple systems. If you prefer the new way, I can leave it be.

**Comment by johnkerl** [comment]
Ahhhhhh, OK thanks @BEFH !

Ah yes, the beta release ... is a bit dated now. I've added new binaries several times now but the `.tar.gz` there is a now-outdated snapshot.

Let's use current `HEAD`; and/or I can tag a new `6.0.0.gamma` if that helps. And if there are bugs in `HEAD` let's fix them. 

I'm reluctant to tag a `6.0.0` juuuust yet b/c lots of distros auto-trigger from production releases & I'm not confident yet we're ready to unleash that. (a) due to the two blockers above; (b) even without those, I wouldn't want to trigger a bunch of builds on different distros all encountering first-time issues.

**Comment by BEFH** [comment]
@johnkerl 6.0.0.rc1 is also compatible with Anaconda, so that would be great. I just [pulled](https://github.com/johnkerl/miller/pull/839) the changes to the Makefile

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/releases/tag/v6.0.0.rc1 just tagged.

P.S. there's a workflow fail at https://github.com/johnkerl/miller/runs/4749880724?check_suite_focus=true but this is a first-ever run for a brand-new release hook -- I can debug that, but, please don't let that side issue stop you. :)

**Comment by BEFH** [comment]
lol, it doesn't like the release version. maybe i.j.kfoo would work? This is comical. I'm going to check this shortly. Dealing with internet issues right now.

**Comment by BEFH** [comment]
@johnkerl, can you please accept my pull request? The link is here: https://github.com/johnkerl/miller/pull/839


The build works with Anaconda now, but the install does not. What happens is it installs in the following way (this is a view of the Anaconda tarball with `less`):

```
-rw-rw-r-- 1000/1000        25 2022-01-09 00:15 info/files
-rw-rw-r-- 1000/1000        58 2022-01-09 00:15 info/hash_input.json
-rw-rw-r-- 1000/1000       291 2022-01-09 00:15 info/index.json
-rw-rw-r-- 1000/1000       420 2022-01-09 00:15 info/paths.json
-rw-rw-r-- 1000/1000      3474 2022-01-09 00:15 info/about.json
-rw-rw-r-- 1000/1000         0 2022-01-09 00:15 info/git
-rwxrwxr-x 1000/1000  35836273 2022-01-09 00:15 bin
-rw-r--r-- 1000/1000       936 2022-01-08 23:37 info/recipe/meta.yaml.template
-rw-rw-r-- 1000/1000    145699 2022-01-09 00:15 share/man/man1/mlr.1
-rw-rw-r-- 1000/1000      1482 2022-01-08 20:47 info/licenses/LICENSE.txt
-rw-rw-r-- 1000/1000        34 2022-01-09 00:15 info/test/run_test.sh
-rw-r--r-- 1000/1000        69 2022-01-08 23:38 info/recipe/build.sh
-rw-rw-r-- 1000/1000       458 2022-01-09 00:15 info/recipe/conda_build_config.yaml
-rw-rw-r-- 1000/1000      1885 2022-01-09 00:15 info/recipe/meta.yaml
```

As you can see, since there is no pre-existing `bin` directory, it copies mlr to a file named "bin". Everything else seems to work great on both MacOS and Ubuntu.

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/pull/850 will be the commit tagged `6.0.0`.

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/releases/tag/v6.0.0

**Comment by gromgit** [comment]
Homebrew bump in progress: https://github.com/Homebrew/homebrew-core/pull/92811

**Comment by BEFH** [comment]
Having segfault issues on Linux and I have no idea why.

https://github.com/johnkerl/miller/discussions/851#discussioncomment-1937412

**Comment by johnkerl** [comment]
Note https://github.com/Homebrew/homebrew-core/pull/92811

**Comment by grawlinson** [comment]
Awesome, I've just uploaded this to Arch Linux's repositories.

Thanks to all for the hard work in porting this fantastic utility to Go.

**Comment by johnkerl** [comment]
A while back, I rando-found on the web a site called 'repology' -- the new[README-versions.md](https://github.com/johnkerl/miller/blob/main/README-versions.md) includes a repology badge listing current versions for various distros. Currently Arch Linux, Brew, and MacPorts as showing up with `6.0.0` (as expected).

**Comment by johnkerl** [comment]
Miller 6 is released; the Go code is the only code, C code having been red-PR'ed out some time ago; distros are updating according to their own schedules at https://github.com/johnkerl/miller/blob/main/README-versions.md.

At this point the Go port / Miller 6 _is_ Miller.

This transitional/tracking issue no longer needs to remain open; subsequent issues should be opened individually.
