### ISSUE TITLE
converting string to int fails on '08'

### ISSUE THREAD

**Issue by jganong** [johnkerl/miller#374]
Here is a small example:

$ (echo a ; echo 07;echo 08; echo 09) | mlr --csv put '$a=int(string($a))'
a
7
(error)
(error)
$

Here is my work-around:

$ (echo a ; echo 07;echo 08; echo 09) | mlr --csv put '$a=int(float(string($a)))'
a
7
8
9
$

you might ask: why do i use int(string()) when int() would work OK?
in the mini-example that is true enough,
but in my actual program, $a is a string because it comes from a split:

@MonthDay=splitnvx($date,"/");
@month=int(float(@MonthDay[1]));

**Comment by aborruso** [comment]
Hi,
if you run `(echo a ; echo 07;echo 08; echo 09) |  mlr --csv put '$b=string($a)'` you have

```
a,b
07,7
08,8.000000
09,9.000000
```

And for this reason the workaround you use, it's ok.

If your goal is to remove the start `0` (one or more), you could write `(echo a ; echo 07;echo 08; echo 09) | mlr --csv put -S '$a=sub($a,"^0+","")'` to have

```
a
7
8
9
```

If you need to extract month number from a date field, you can run something like

```echo "a=25/12/2020" | mlr --ocsv put -S '$month = strftime(strptime($a, "%d/%m/%Y"),"%m")'``` 

to have

```
a,month
25/12/2020,12
```

**Comment by jganong** [comment]
thanks for getting back to me.

i am processing huge huge timeseries (every second for a year) where it
would be too expensive to run strftime() on each line.
the workaround works fine, i just wanted you to know it is surprising to a
user that '07' works but '08' does not.

**Comment by johnkerl** [comment]
Hi @jganong ! Octal is counter-intuitive for many folks. We should have an option to suppress octal-inference for people who never want it ...

**Comment by johnkerl** [comment]
(BTW `011` will be decimal 9, which I imagine will also be surprising ...)

**Comment by johnkerl** [comment]
A few PRs were involved; most recently https://github.com/johnkerl/miller/pull/788

After some discussion, the decision was that octal numbers should be opt-in via `-O`. For example:

```
$ (echo a ; echo 07;echo 08; echo 09) | mlr -O --csv put '$a=int($a)'
a
07
8
9
```

Please let me know if we need to re-open this -- thanks!

**Comment by jganong** [comment]
thanks for all your effort, i am still enjoying mlr.

**Comment by aborruso** [comment]
> After some discussion, the decision was that octal numbers should be opt-in via `-O`. For example:

Really great. Right now Miller is among the few software that does not do pointless direct inferencing of octal numbers, very useful

**Comment by johnkerl** [comment]
There is the precedent of Perl! :)
