### ISSUE TITLE
`--c2p -N` vs `--c2t -N`

### ISSUE THREAD

**Issue by agguser** [johnkerl/miller#384]
Why are their outputs (except separators) different? One has header, the other not. E.g.
```
$ echo "10,a\n20,b" | mlr --c2p -N cat 
1  2
10 a
20 b

$ echo "10,a\n20,b" | mlr --c2t -N cat
10      a
20      b
```

**Comment by johnkerl** [comment]
Thanks @agguser!

The pretty-print format isn't really CSV (although CSV-ish) and the pretty-print writer simply is failing to check the `--headerless-csv-output` flag the way the CSV writer does.
