### ISSUE TITLE
delimiters in verb reshape

### ISSUE THREAD

**Issue by nunonog** [johnkerl/miller#385]
Hi,
perhaps I am missing something obvious, but I cannot get the reshape verb to work properly. 
The example in the website works well only having spaces as delimiters
For example:

Input file long.txt:
>
field,value,count
11_1018,G,5268
11_1018,C,31
11_1018,C,4
<

does not work -> output is the same. 

If I replace all the commas (or tabs) by spaces it works fine:
>
mlr --pprint reshape -s value,count long.txt

field      G  C  C
11_1018 5268 31 4
<

Is this as expected?

Thanks

**Comment by aborruso** [comment]
Hi @nunonog you must set the input separator or the file format, if you do not use the default.

Then for a CSV you can run

```
mlr --icsv --opprint reshape -s value,count input.txt
```

or more briefly

```
mlr --c2p reshape -s value,count input.txt
```

**Comment by nunonog** [comment]
Hi @aborruso 
thanks, so I was missing something obvious ... :) So here the default is space delimiter

**Comment by aborruso** [comment]
If it's ok for you, please close the issue
