### ISSUE TITLE
Wishlist: DSL sort function

### ISSUE THREAD

**Issue by johnkerl** [johnkerl/miller#389]
_Originally posted by @torbiak in https://github.com/johnkerl/miller/issues/77#issuecomment-321900473_

I'm trying to reorder the columns of a histogram based on their sums so I can easily plot the top N series using a graphing package like gnuplot by using the leftmost N columns.

Eg, from this:

```
bin,a,b,c
0,1,3,2
```

To this:

```
bin,b,c,a
0,3,2,1
```

In a general purpose language I'd do something like a Schwartzian transform to get the order of the columns and then emit the binned data according to that order. The best I've come up with using miller is using command substitution and doing another pass to figure out the order and give it to the reorder verb:

```
echo -e 'a=1,b=3\na=2,b=4' >data
order=$(mlr --from data \
    stats1 -a sum --fx '' then \
    rename -r '(.*)_sum,\1' then \
    put -q 'for (k, v in $*) { emit {"col": k, "sum": v} }' then \
    sort -nr sum then \
    put -q '@order[$col] = 1; end { print joink(@order, ",") }')
mlr --from data reorder -f "$order"
```

Is there a better way? Am I missing something? I notice there's no sort function in the `put` DSL, which makes sense since there isn't a list datatype and sorting map keys seems really hacky. I guess I'm asking for a nicer way to reorder columns based on their aggregates, if it doesn't already exist and could fit within miller's design constraints.

**Comment by johnkerl** [comment]
@torbiak I'm working on this now for Miller 6! :)

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/pull/667

**Comment by torbiak** [comment]
Nice. I tested it out, working from your examples in sorting.md, and came up with this solution to the original problem of selecting fields with the top sum:
```
$ mlr put -q '
func cmp_sum_rev(ak, av, bk, bv) {
    return @sum[bk] <=> @sum[ak];
}

begin {
    @records = {};
    @sum = {};
}

@records[NR] = $*;

for (k, v in $*) {
    @sum[k] += v;
}

end {
    for (_, record in @records) {
        var sorted = sortmf(record, "cmp_sum_rev");
        emit sorted;
    }
}
' <<EOF
a=1,b=3,c=0
a=2,b=4,c=1
EOF
# b=3,a=1,c=0
# b=4,a=2,c=1
```

**Comment by johnkerl** [comment]
For tracking I prefer to leave these open until the Go port is released. (Since that is non-trivial and non-immediate
