### ISSUE TITLE
Wishlist: bash completion script for mlr

### ISSUE THREAD

**Issue by johnkerl** [johnkerl/miller#391]
It would be great if `mlr` had a Bash completion script.

_Originally posted by @elyscape in https://github.com/johnkerl/miller/issues/77#issuecomment-308247402_

**Comment by m040601** [comment]
Yeap, I think this should be on the top priorities, for such a command line heavy and loaded with flags tool like miller

I see there a file  "/c/todo.txt" :

> non-airable:
> ? bash completion script ?

**Comment by johnkerl** [comment]
@m040601 LOL I wrote that once before a business trip, there some things I felt like I could do on the flight and others I'd need to wait until landing. I meant "non-airable" for myself to refer to the latter. :)

**Comment by johnkerl** [comment]
Duplicate of #1128
