### ISSUE TITLE
Confusingly similar GitHub tags named v5.9.1, v.5.9.1, and 5.9.1

### ISSUE THREAD

**Issue by sjackman** [johnkerl/miller#393]
Tag `v5.9.1` https://github.com/johnkerl/miller/releases/tag/v5.9.1
Tag `5.9.1` exists https://github.com/johnkerl/miller/releases/tag/5.9.1
Tag `v.5.9.1` exists https://github.com/johnkerl/miller/releases/tag/v.5.9.1

Previous releases were named `vX.Y.Z`

**Comment by johnkerl** [comment]
Thanks -- two of these were typos. I didn't realize they were causing problems; I'll get rid of them ...

**Comment by johnkerl** [comment]
Done -- thanks! :)

**Comment by sjackman** [comment]
Two pointed to one Git SHA-1, and one of them pointed to a different Git SHA-1, which is why I noticed.
