### ISSUE TITLE
Unexpected behaviour when parsing JSON float

### ISSUE THREAD

**Issue by sjackman** [johnkerl/miller#394]
```console
$ docker run -it --rm homebrew/brew
$ brew install miller
$ mlr format-values <<<x=1.26126e-3
x=0.001261
$ mlr --json cat <<<'{"x": 1.26126e-3}'
{ "x": "1.26126e-3??x" }
$ mlr --ijson --odkvp cat <<<'{"x": 1.26126e-3}'
x=1.26126e-3J?u
```
I cannot reproduce this unexpected behaviour on macOS.

**Comment by johnkerl** [comment]
Weird. Definite  buffer overrun in the (not at all new) C JSON parser.

Fixed on https://github.com/johnkerl/miller/commit/510a122c6deb19263037bd6bfe8067adc7426616 regardless ...... :^/

**Comment by sjackman** [comment]
Thanks for the quick fix, John!
