### ISSUE TITLE
documentation about file convertions

### ISSUE THREAD

**Issue by OrionRandD** [johnkerl/miller#396]
Hi,
Where is the documentation about converting from a format to another?
Say: excel docs to cvs?
Thx

**Comment by aborruso** [comment]
Hi you have the file formats section of the documentation https://miller.readthedocs.io/en/latest/file-formats.html

Excel is not a Miller format

**Comment by OrionRandD** [comment]
Nope. My question is:
Is it possible do convert from excel to a miller file format?

**Comment by aborruso** [comment]
@OrionRandD [here](https://miller.readthedocs.io/en/latest/file-formats.html) you have the formats the Miller is able to read (in example CSV and TSV).

Use as excel output format one of these.

**Comment by OrionRandD** [comment]
give me a miller command line example here, then.
I cannot find any in miller documentation.
Like-so:

mlr -o  file.cvs  file.xls

**Comment by aborruso** [comment]
> Is it possible do convert from excel to a miller file format?

Yes, open excel and save as CSV

![image](https://user-images.githubusercontent.com/30607/100459466-ce22a680-30c5-11eb-8788-6e98839a26fb.png)


Then you can use Miller on it. If you have in example this CSV 

```
a,b
1,11
5,6
18,9
```

and you want in example the max value of b field, you can run

```
mlr --csv stats1 -a max -f b input.csv
```

and have

```
b_max
9
```

Once again, xls is not a Miller input format or output format

**Comment by aborruso** [comment]
> Where is the documentation about converting from a format to another?

The base I/O documentation is this https://miller.readthedocs.io/en/latest/reference.html#i-o-options

Some examples, starting from this CSV input file

```
a,b
1,11
5,6
18,9
```

## from csv to json

```
mlr --icsv --ojson cat ./input.csv >./output.json
```

or more simply

```
mlr --c2j cat ./input.csv >./output.json
```

## from csv to tsv

```
mlr --icsv --otsv cat ./input.csv >./output.tsv
```

or more simply

```
mlr --c2t cat ./input.csv >./output.tsv
```

## from csv to pretty print

```
mlr --icsv --opprint cat ./input.csv >./output.txt
```

or more simply

```
mlr --c2p cat ./input.csv >./output.txt
```

**Comment by OrionRandD** [comment]
All right!
I thought that miller itself had a built-in option to convert from xls to
cvs...
I use linux and it is very easy to do so...
https://linoxide.com/linux-how-to/methods-convert-xlsx-format-files-csv-linux-cli/

**Comment by OrionRandD** [comment]
thx a lot,
anyways
:)

**Comment by aborruso** [comment]
You are welcome :)

If it's ok for you, please close the issue
