### ISSUE TITLE
Look at "thinning" for high-time-density datasets

### ISSUE THREAD

**Issue by johnkerl** [johnkerl/miller#402]
Originally posted by @seamusdemora in https://github.com/johnkerl/miller/issues/212#issuecomment-754687472

**Comment by seamusdemora** [comment]
@johnkerl : I'm guessing you got busy, but not to worry as I did get some help with a solution in `awk`. I'm a _1 of 10_ in `awk`, but a _0 of 10_ in `mlr`.   :)

**Comment by johnkerl** [comment]
@seamusdemora sorry for the delay!

**Comment by johnkerl** [comment]
For handy reference here's a copy of your comment from https://github.com/johnkerl/miller/issues/212#issuecomment-754687472

----

This is a [screen shot of the oscilloscope trace](https://imgur.com/a/oBx0I1N) with some notes that might help. 

Here's approx 20 data points straddling the "Trigger" point. The delta-time increment between points is 0.2nsec, so you're looking at about 4nsec in real time: 

```
TIME,VOLTAGE
-2.0096E-09,1.6789E+00
-1.8096E-09,1.8063E+00
-1.6096E-09,1.7831E+00
-1.4096E-09,1.7242E+00
-1.2096E-09,1.8521E+00
-1.0096E-09,1.8279E+00
-8.096E-10,1.7995E+00
-6.096E-10,1.8953E+00
-4.096E-10,1.9074E+00
-2.096E-10,1.9353E+00
-9.6E-12,1.9979E+00
1.904E-10,2.1501E+00
3.904E-10,2.1827E+00
5.904E-10,2.1106E+00
7.904E-10,2.2311E+00
9.904E-10,2.2569E+00
1.1904E-09,2.3006E+00
1.3904E-09,2.3270E+00
1.5904E-09,2.2948E+00 
```

My idea is similar to yours I think - a "threshold-based" approach, but it's not random. I believe one way to do this is a "look ahead average": Calculate an average voltage value of the next "n" data points (n ~ 40). If this average differs from the previous data point sufficiently, then it becomes the next data point. If it does not, there is no new data point, and proceed to calculate the average of the next 40 data points. Something like: 

```
Vavg = (SUM Vi where i=1,40) ÷ n=40

if ABS(Vavg - Vref) ≥ τ 
then
   add new data point at time = midpoint of the n samples, voltage = Vavg
  update the "reference" voltage to Vavg
else
   no new data point & calculate Vavg of the next 20 data points
fi
```

Hope this makes some sense.

**Comment by johnkerl** [comment]
There was a sliding-window sum here:

https://github.com/johnkerl/miller/blob/master/go/reg-test/input/window.mlr

which came out of https://github.com/johnkerl/miller/issues/362

**Comment by johnkerl** [comment]
That was nicely parameterized with multiple field names etc but simplifying it down we have this:

```
$ cat seamus.mlr
begin {
  # Use 40 for https://github.com/johnkerl/miller/issues/402
  @window_size = 3;
  @input_field_name = "VOLTAGE";
  @output_field_name = "VOLTAGE_avg";

  for (i = 0; i < @window_size; i+=1) {
    @window[i] = 0;
  }
  # dump;
}

# Slide the window
for (i = 1; i < @window_size; i+=1) {
  @window[i-1] = @window[i];
}
# Update the window with new data
@window[@window_size - 1] = $[@input_field_name];

# Compute the average
sum = 0.0;
for (i = 0; i < @window_size; i+=1) {
  sum += @window[i];
}
denominator = @window_size;
if (NR < @window_size) {
    denominator = NR
}
$[@output_field_name] = sum / denominator;
```

```
 cat seamus.csv
TIME,VOLTAGE
-2.0096E-09,1.6789E+00
-1.8096E-09,1.8063E+00
-1.6096E-09,1.7831E+00
-1.4096E-09,1.7242E+00
-1.2096E-09,1.8521E+00
-1.0096E-09,1.8279E+00
-8.096E-10,1.7995E+00
-6.096E-10,1.8953E+00
-4.096E-10,1.9074E+00
-2.096E-10,1.9353E+00
-9.6E-12,1.9979E+00
1.904E-10,2.1501E+00
3.904E-10,2.1827E+00
5.904E-10,2.1106E+00
7.904E-10,2.2311E+00
9.904E-10,2.2569E+00
1.1904E-09,2.3006E+00
1.3904E-09,2.3270E+00
1.5904E-09,2.2948E+00
```

```
$ mlr --icsv --opprint --from seamus.csv put -f seamus.mlr
TIME        VOLTAGE    VOLTAGE_avg
-2.0096E-09 1.6789E+00 1.678900
-1.8096E-09 1.8063E+00 1.742600
-1.6096E-09 1.7831E+00 1.756100
-1.4096E-09 1.7242E+00 1.771200
-1.2096E-09 1.8521E+00 1.786467
-1.0096E-09 1.8279E+00 1.801400
-8.096E-10  1.7995E+00 1.826500
-6.096E-10  1.8953E+00 1.840900
-4.096E-10  1.9074E+00 1.867400
-2.096E-10  1.9353E+00 1.912667
-9.6E-12    1.9979E+00 1.946867
1.904E-10   2.1501E+00 2.027767
3.904E-10   2.1827E+00 2.110233
5.904E-10   2.1106E+00 2.147800
7.904E-10   2.2311E+00 2.174800
9.904E-10   2.2569E+00 2.199533
1.1904E-09  2.3006E+00 2.262867
1.3904E-09  2.3270E+00 2.294833
1.5904E-09  2.2948E+00 2.307467
```

**Comment by johnkerl** [comment]
Then (I think)

```
$ ../c/mlr --icsv --opprint --from seamus.csv \
  put -f seamus.mlr \
  then step -a delta -f VOLTAGE_avg
TIME        VOLTAGE    VOLTAGE_avg VOLTAGE_avg_delta
-2.0096E-09 1.6789E+00 1.678900    0
-1.8096E-09 1.8063E+00 1.742600    0.063700
-1.6096E-09 1.7831E+00 1.756100    0.013500
-1.4096E-09 1.7242E+00 1.771200    0.015100
-1.2096E-09 1.8521E+00 1.786467    0.015267
-1.0096E-09 1.8279E+00 1.801400    0.014933
-8.096E-10  1.7995E+00 1.826500    0.025100
-6.096E-10  1.8953E+00 1.840900    0.014400
-4.096E-10  1.9074E+00 1.867400    0.026500
-2.096E-10  1.9353E+00 1.912667    0.045267
-9.6E-12    1.9979E+00 1.946867    0.034200
1.904E-10   2.1501E+00 2.027767    0.080900
3.904E-10   2.1827E+00 2.110233    0.082466
5.904E-10   2.1106E+00 2.147800    0.037567
7.904E-10   2.2311E+00 2.174800    0.027000
9.904E-10   2.2569E+00 2.199533    0.024733
1.1904E-09  2.3006E+00 2.262867    0.063334
1.3904E-09  2.3270E+00 2.294833    0.031966
1.5904E-09  2.2948E+00 2.307467    0.012634
```

**Comment by johnkerl** [comment]
Then (I think)

```
$ mlr --icsv --opprint --from seamus.csv \
  put -f seamus.mlr \
  then step -a delta -f VOLTAGE_avg \
  then filter 'abs($VOLTAGE_avg_delta) > 0.03'
TIME        VOLTAGE    VOLTAGE_avg VOLTAGE_avg_delta
-1.8096E-09 1.8063E+00 1.742600    0.063700
-2.096E-10  1.9353E+00 1.912667    0.045267
-9.6E-12    1.9979E+00 1.946867    0.034200
1.904E-10   2.1501E+00 2.027767    0.080900
3.904E-10   2.1827E+00 2.110233    0.082466
5.904E-10   2.1106E+00 2.147800    0.037567
1.1904E-09  2.3006E+00 2.262867    0.063334
1.3904E-09  2.3270E+00 2.294833    0.031966
```

where I'm using tau = 0.03 here for example

**Comment by seamusdemora** [comment]
@johnkerl 👍  I'm sorry I've been slow to follow up on this - it looks promising. I've been distracted by the usual things :), but plan on spending some more time on this in the coming week. I'll follow up then.

**Comment by seamusdemora** [comment]
I'd first like to say thanks for all the effort you've put into helping me. In this post, I wanted to add a couple of things that I may have failed to mention, or that have fallen through the cracks. If you're not exhausted by then, perhaps we can continue.

1. Fairly large data sets are involved. The [waveform shown here](https://imgur.com/a/oBx0I1N) is 10M data points, approx 275MB in size. You can get your very own copy from [this file on my G-Drive.](https://drive.google.com/file/d/14TgyNHGOWcfiwsI2c3uICQXNFt6SBPWj/view?usp=sharing) 
2. I need to represent this as a much smaller file. Ideally, "much smaller" would be on the order of 50 data points! This level of "thinning" might be considered [offensive to Nyquist](https://en.wikibooks.org/wiki/Analog_and_Digital_Conversion/Nyquist_Sampling_Rate#:~:text=The%20nyquist%20sampling%20rate%20is,or%20the%20signal%20might%20alias.), but since it is known to be electromechanical contact bounce added to a binary-valued signal, and I know from the problem domain that the higher frequencies are irrelevant, this will suit my purposes well enough. 

Which brings me to the results here. I wonder if I'm doing something very dumb, because when I run the script on my macOS 10.15 w/ `mlr --version = Miller 5.10.0`, I don't get the same output as you. For example: 

```zsh
% mlr --icsv --opprint --from CB07-Small.csv put -f seamus.mlr
-2.0096E-09 1.6789E+00 VOLTAGE_avg
-1.8096E-09 1.8063E+00 0.000000
-1.6096E-09 1.7831E+00 0.000000
-1.4096E-09 1.7242E+00 0.000000
-1.2096E-09 1.8521E+00 0.000000
-1.0096E-09 1.8279E+00 0.000000
-8.096E-10  1.7995E+00 0.000000
-6.096E-10  1.8953E+00 0.000000
-4.096E-10  1.9074E+00 0.000000
-2.096E-10  1.9353E+00 0.000000
-9.6E-12    1.9979E+00 0.000000
1.904E-10   2.1501E+00 0.000000
3.904E-10   2.1827E+00 0.000000
5.904E-10   2.1106E+00 0.000000
7.904E-10   2.2311E+00 0.000000
9.904E-10   2.2569E+00 0.000000
1.1904E-09  2.3006E+00 0.000000
1.3904E-09  2.3270E+00 0.000000
1.5904E-09  2.2948E+00 0.000000
1.7904E-09  2.4338E+00 0.000000
```

I'm sure this is a minor error, but looking beyond that, it seems clear that `tau` will need to be much greater than `0.03` to get the kind of size reduction I need.

**Comment by johnkerl** [comment]
Closing as stale ... please let me know if there's something to be gained by re-opening here ...
