### ISSUE TITLE
Feature request: drop empty fields in JSON output

### ISSUE THREAD

**Issue by nichtich** [johnkerl/miller#410]
Please add an option to omit empty strings in JSON output. For example

~~~csv
a,b
1,
~~~

converted with `mlr --c2j cat` results in

~~~json
{ "a": 1, "b": "" }
~~~

instead of

~~~json
{ "a": 1 }
~~~

The latter could be forced with a command line option such as `--json-no-empty-keys`. Useful to reduce output with a lot of empty fields.

Note that it's possible to postprocess JSON with `jq 'with_entries(select(.value!=""))'` but this requires jq and is hard to remember.

**Comment by johnkerl** [comment]
Hi @nichtich ! I think the `remove-empty-columns` verb is what you want:

```
$ cat foo.csv
a,b
1,

$ mlr --c2j cat foo.csv
{ "a": 1, "b": "" }

$ mlr --c2j remove-empty-columns foo.csv
{ "a": 1 }
```

**Comment by nichtich** [comment]
Thanks a lot!

**Comment by johnkerl** [comment]
@nichtich P.S. the `columns` in `remove-empty-columns` was, in hindsight, a misnomer ... :(
