### ISSUE TITLE
NR is stale after apply remove-empty-columns

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#421]
Hi,
if I have this file

```
1,2,
3,4,
```

and run

```
mlr --csv --implicit-csv-header remove-empty-columns then put 'NR == 1 {$a="test"}' then unsparsify input.csv
```

I have

```
1,2
1,2
3,4
```

and not

```
1,2,a
1,2,test
3,4
```

I'm using Miller v5.10.0

**Comment by johnkerl** [comment]
It's not the `put` per se that's failing -- it's that the `NR==1` is not true.

```
$ mlr  put '$nr=NR' input.csv
1=1,2=2,3=,nr=1
1=3,2=4,3=,nr=2

$ mlr cat then put '$nr=NR' input.csv
1=1,2=2,3=,nr=1
1=3,2=4,3=,nr=2

$ mlr remove-empty-columns then put '$nr=NR' input.csv
1=1,2=2,nr=2
1=3,2=4,nr=2
```

So a couple things:

* This is definitely a bug
* This already works correctly in Miller 6
* As a workaround you can do

```
$ mlr put '$nr=NR' then remove-empty-columns then put '$nr == 1 {$a = "test"}'  input.csv
1=1,2=2,nr=1,a=test
1=3,2=4,nr=2
```

**Comment by johnkerl** [comment]
... unfortunately the workaround and the offer of Miller 6 is all I can offer on this one. The non-copying of "context" (`NR`, `NF`, `FILENAME`, etc.) requires a bit of a refactor and Miller 6 is precisely that refactor (among many other things). :(

**Comment by aborruso** [comment]
Hi @johnkerl thank you very much. Miller 6 will be really great!

**Comment by aborruso** [comment]
@johnkerl I have installed Miller v5.10.1, and if I run

```
mlr --csv --implicit-csv-header remove-empty-columns then put 'NR == 1 {$a="test"}' then unsparsify
```

I have again 

```
1,2
1,2
3,4
```

Thank you

**Comment by johnkerl** [comment]
@aborruso correct, this bug is only fix in the Go code which will be released as Miller 6.

For 5.x you can use the workaround above.

Sorry, I know this is confusing. :(

**Comment by aborruso** [comment]
Ok thank you John.

I have written here because you have written about this issue in the 5.10.1 release note.

Thank you again

**Comment by johnkerl** [comment]
Oops thanks -- will fix :(
