### ISSUE TITLE
basic DSL question: how to use list of values (array) to filter records?

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#422]
Hi,
I have this input file:

```
fielda,fieldb
a,2
a,3
b,4
c,7
ca,9
d,10
```

If I want the records in which `fielda=="b" || fielda=="c"` I  can run:

```
mlr --csv filter -S '$fielda=~"(^b$|^c$)"'  input.csv
```

or

```
mlr --csv filter -S '$fielda=="b" || $fielda=="c"'  input.csv
```

Imagine I have a long list of values, to use as filter values:

```
list="a,b,c,t,y,h,i,o,z"
```

Is there some DSL function that allows to use this list as filter input?

**Comment by johnkerl** [comment]
There is not but there could be! :)

**Comment by johnkerl** [comment]
@aborruso I'm closing this out for https://github.com/johnkerl/miller/pull/693; please let me know if this is a mistaken and we can re-open. Thanks!!! :)

**Comment by aborruso** [comment]
Thank you very much!!!

**Comment by aborruso** [comment]
Hi @johnkerl ,
is it possible to use `any` in filter verb, to have all CSV records that have the string "hello" in any fields of the CSV input?

I'm sure yes, but I'm not able to write it.

Thank you

**Comment by aborruso** [comment]
It's `grep` verb, I'm stupid :)
