### ISSUE TITLE
Segfault with --tsv --implicit-csv-header

### ISSUE THREAD

**Issue by ethack** [johnkerl/miller#427]
I'm getting a segmentation fault with the following:

```
$ mlr --version                                                
Miller 5.10.0

$ mlr --tsv --skip-comments --implicit-csv-header head conn.log
1	2	3	4	5	6	7	8	9	10	11	12	13	14	15	16	17	18	19	20	21	22
zsh: segmentation fault (core dumped)  mlr --tsv --skip-comments --implicit-csv-header head conn.log

$ mlr --tsv --skip-comments --implicit-csv-header head minimal.log
1	2	3	4	5	6	7	8	9	10	11	12	13	14	15	16	17	18	19	20	21
1520834388.461595	C0YMZ64KZWq62C9OOk	10.55.100.111	55593	165.227.88.15	443	tcp	http	0.163560	216	399	SF	T	F	0	ShADadfF	5	428	6651	-
zsh: segmentation fault (core dumped)  mlr --tsv --skip-comments --implicit-csv-header head minimal.log
```

- [conn.log](https://github.com/johnkerl/miller/files/6026809/conn.log) - First lines in the original log I was working with.
- [minimal.log](https://github.com/johnkerl/miller/files/6026810/minimal.log) - Minimal case where I could reproduce the issue. It  seems like Miller isn't liking the `#types` line.

I've tested this in the following Ubuntu docker containers. Each time I installed miller with `apt install miller`.
* 20.04 - miller 5.6.2 - no segfault
* 20.10 - miller 5.9.0 - segfault
* 21.04 - miller 5.10.0 - segfault

**Comment by ethack** [comment]
Somehow the conn.log I was working with had some tabs missing. This should be the properly formatted one, and it produces the same segfault behavior in miller.
[conn2.log](https://github.com/johnkerl/miller/files/6026880/conn2.log)

**Comment by aborruso** [comment]
@ethack I have the same error.

If you use `unsparsify` verb, you solve it

```
mlr --tsv --skip-comments --implicit-csv-header unsparsify then remove-empty-columns conn.log
```

**Comment by aborruso** [comment]
The problem seems related to `--skip-comments`. 

In the comments you have 22 columns, in the content instead you have 21. It seems that mlr when try to apply `--implicit-csv-header` does not skip comment lines, and than it has 2 set of data with a different number of columns. Then you must apply `unsparsify ` to normalize it.

**Comment by aborruso** [comment]
@ethack another way is to use as input `nidx` format which has less stringent structure checks.

Using your `conn2.log` file in example it's

```
mlr --n2t --skip-comments --implicit-csv-header --ifs "\t"  cat conn2.log
```

| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 1520834388.461595 | C0YMZ64KZWq62C9OOk | 10.55.100.111 | 55593 | 165.227.88.15 | 443 | tcp | http | 0.163560 | 216 | 399 | SF | T | F | 0 | ShADadfF | 5 | 428 | 6 | 651 | - |
| 1520834392.650820 | C1xhad1Fktqem2kEtf | 10.55.100.111 | 55594 | 165.227.88.15 | 443 | tcp | http | 0.140458 | 216 | 399 | SF | T | F | 0 | ShADadfF | 5 | 428 | 5 | 611 | - |
| 1520834326.270889 | CVEg6r1eYmVCUiJMYi | 10.55.100.103 | 49192 | 23.194.159.133 | 443 | tcp | ssl | 70.237071 | 467 | 3853 | SF | T | F | 0 | ShADadfF | 13 | 1011 | 13 | 4397 | - |
| 1520834396.811154 | CDjyuD4SfvCXi4Z8Wa | 10.55.100.111 | 55595 | 165.227.88.15 | 443 | tcp | http | 0.160119 | 221 | 399 | SF | T | F | 0 | ShADadfF | 5 | 433 | 6 | 651 | - |
| 1520834338.268368 | CScyo64lGl1LtckAt6 | 10.55.100.106 | 50668 | 34.235.219.218 | 443 | tcp | ssl | 60.130891 | 453 | 5439 | SF | T | F | 0 | ShADadfF | 11 | 905 | 13 | 5971 | - |
| 1520834337.876090 | CDiScb4yRqRh6Mpzs5 | 10.55.100.100 | 59848 | 35.166.112.36 | 443 | tcp | ssl | 60.181390 | 456 | 3500 | SF | T | F | 0 | ShADadfF | 11 | 908 | 13 | 4032 | - |
| 1520834339.043453 | CfL17627OivmP94uyd | 10.55.100.107 | 49243 | 72.21.81.200 | 443 | tcp | ssl | 60.643256 | 462 | 9412 | SF | T | F | 0 | ShADadfF | 14 | 1034 | 18 | 10144 | - |
| 1520834338.268371 | CLMXqN3TkifFYNsWQi | 10.55.100.106 | 50669 | 34.235.219.218 | 443 | tcp | ssl | 62.297292 | 2650 | 43351 | SF | T | F | 0 | ShADadfF | 23 | 3582 | 43 | 45083 | - |
| 1520834402.003647 | CqeV6a2Y1ix3wb7KIb | 10.55.100.111 | 55597 | 165.227.88.15 | 443 | tcp | http | 0.168280 | 221 | 399 | SF | T | F | 0 | ShADadfF | 5 | 433 | 6 | 651 | - |
| 1520834341.495624 | CQijgv4ilPD6kSscE | 10.55.100.108 | 62582 | 69.187.26.87 | 443 | tcp | ssl | 61.290352 | 2694 | 4271 | RSTR | T | F | 0 | ShADadfr | 12 | 3186 | 11 | 4723 | - |

**Comment by ethack** [comment]
Thanks for the workarounds @aborruso. I just learned a lot from the examples you gave! 

As an aside: the [help text](https://miller.readthedocs.io/en/latest/reference.html#on-line-help) implies  `--implicit-csv-header` only works with CSV.
```
Relevant to CSV/CSV-lite input only:
  --implicit-csv-header Use 1,2,3,... as field labels, rather than from line 1
                     of input files. Tip: combine with "label" to recreate
                     missing headers.
```
It also says the TSV options are just keystroke savers for a special case of CSV so it made sense to me that it would work with TSV as well. But I didn't realize it could apply to `nidx` as well. Would it make sense to change this help text somehow?

I think you're right about the columns. I hadn't been able to reproduce the issue with any of the other commented lines so I thought it was specific to the `#types` line. But now I see that the `#fields` line reproduces the issue as well and it was because of the missing tabs in my original file that I missed it before. It seems that if the commented line has fewer columns than the data it doesn't give an error. But when it has more columns than the data then it segfaults.

I found a workaround for my use case that lets me use the headers existing in the file. I had to use a crazy `sed` command to remove the `#fields\t` from the header line. This works well for me as I was planning to add the headers back in with `label` anyway.

```
mlr --prepipe "sed '/^#fields\t/s/^#fields\t//'" --itsv --omd --skip-comments cat conn2.log
```

| ts | uid | id.orig_h | id.orig_p | id.resp_h | id.resp_p | proto | service | duration | orig_bytes | resp_bytes | conn_state | local_orig | local_resp | missed_bytes | history | orig_pkts | orig_ip_bytes | resp_pkts | resp_ip_bytes | tunnel_parents |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 1520834388.461595 | C0YMZ64KZWq62C9OOk | 10.55.100.111 | 55593 | 165.227.88.15 | 443 | tcp | http | 0.163560 | 216 | 399 | SF | T | F | 0 | ShADadfF | 5 | 428 | 6 | 651 | - |
| 1520834392.650820 | C1xhad1Fktqem2kEtf | 10.55.100.111 | 55594 | 165.227.88.15 | 443 | tcp | http | 0.140458 | 216 | 399 | SF | T | F | 0 | ShADadfF | 5 | 428 | 5 | 611 | - |
| 1520834326.270889 | CVEg6r1eYmVCUiJMYi | 10.55.100.103 | 49192 | 23.194.159.133 | 443 | tcp | ssl | 70.237071 | 467 | 3853 | SF | T | F | 0 | ShADadfF | 13 | 1011 | 13 | 4397 | - |
| 1520834396.811154 | CDjyuD4SfvCXi4Z8Wa | 10.55.100.111 | 55595 | 165.227.88.15 | 443 | tcp | http | 0.160119 | 221 | 399 | SF | T | F | 0 | ShADadfF | 5 | 433 | 6 | 651 | - |
| 1520834338.268368 | CScyo64lGl1LtckAt6 | 10.55.100.106 | 50668 | 34.235.219.218 | 443 | tcp | ssl | 60.130891 | 453 | 5439 | SF | T | F | 0 | ShADadfF | 11 | 905 | 13 | 5971 | - |
| 1520834337.876090 | CDiScb4yRqRh6Mpzs5 | 10.55.100.100 | 59848 | 35.166.112.36 | 443 | tcp | ssl | 60.181390 | 456 | 3500 | SF | T | F | 0 | ShADadfF | 11 | 908 | 13 | 4032 | - |
| 1520834339.043453 | CfL17627OivmP94uyd | 10.55.100.107 | 49243 | 72.21.81.200 | 443 | tcp | ssl | 60.643256 | 462 | 9412 | SF | T | F | 0 | ShADadfF | 14 | 1034 | 18 | 10144 | - |
| 1520834338.268371 | CLMXqN3TkifFYNsWQi | 10.55.100.106 | 50669 | 34.235.219.218 | 443 | tcp | ssl | 62.297292 | 2650 | 43351 | SF | T | F | 0 | ShADadfF | 23 | 3582 | 43 | 45083 | - |
| 1520834402.003647 | CqeV6a2Y1ix3wb7KIb | 10.55.100.111 | 55597 | 165.227.88.15 | 443 | tcp | http | 0.168280 | 221 | 399 | SF | T | F | 0 | ShADadfF | 5 | 433 | 6 | 651 | - |
| 1520834341.495624 | CQijgv4ilPD6kSscE | 10.55.100.108 | 62582 | 69.187.26.87 | 443 | tcp | ssl | 61.290352 | 2694 | 4271 | RSTR | T | F | 0 | ShADadfr | 12 | 3186 | 11 | 4723 | - |

**Comment by aborruso** [comment]
Is your goal to use the field names  you have in the comment line?

The implicit option has another meaning: it associates progressive int
numbers to the field names.

Il mar 23 feb 2021, 18:51 ethack <notifications@github.com> ha scritto:

**Comment by johnkerl** [comment]
Thanks @aborruso !! Any segv is a bug, I will take a look soon

**Comment by johnkerl** [comment]
Lots of things here:

* `--implicit-csv-header` works for TSV too; TSV is just for CSV but with tab instead of comma. This is a documentation opportunity
* NIDX instead of `--implicit-csv-header` is just two different ways to give tab-delimited values 1-up integer keys. Two different (overlapping) ways to solve a similar problem. They invoke different codepaths; hence the existence of a workaround.
* The SEGV itself is flat-out a bug.

Please don't close this issue even after the SEGV fix is up; I'll split out several to-do's from it. :)

**Comment by johnkerl** [comment]
Also note: `minimal.log` the SEGV is happening on the empty line after the data line. (Which is a bug, just to clarify.) Same bug, just being surfaced for a slightly different reason.

**Comment by johnkerl** [comment]
Fix on https://github.com/johnkerl/miller/pull/428

**Comment by aborruso** [comment]
@ethack I'm adding another way to do it, using simply sed and grep

```
<./conn2.log sed -r 's/#fields\t//' | grep -v '^#' >./out.tsv
```
