### ISSUE TITLE
Quoting and TSV output

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#438]
Hi,
if I run

```
echo 'field=lorem "ipsum" sit,foo=moo' | mlr --otsv cat
```

I have

```
field   foo
"lorem ""ipsum"" sit"   moo
```

But I have a TSV output why I have the double quoting escaping?

Thank you

**Comment by johnkerl** [comment]
Ahhh that's RFC-4180 being applied without my checking for `OFS==","` :(

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/issues/922 now duplicates this, and has more context.
