### ISSUE TITLE
Dead links to flins.csv data file on the website

### ISSUE THREAD

**Issue by zx-fulvio** [johnkerl/miller#445]
Hello @johnkerl . I've noticed a few dead links on the documentation website

https://github.com/johnkerl/miller/blob/master/docs/data-examples.rst.in#L7
https://github.com/johnkerl/miller/ster/docs/data-examples.rst#L10

In the files above there's a link to a `flins.csv` file which does not seem to exist anywhere in the repo.

**Comment by johnkerl** [comment]
Hi @zx-fulvio and **very** sorry for the delay, I completely misfiled this. :(

The data file is https://github.com/johnkerl/miller/blob/main/docs/data/flins.csv

https://github.com/johnkerl/miller/commit/947d93b017e227d9147061ddfe69ad40e7ec360a is intended to fix this but I'm waiting for the change to propagate through the readthedocs webhook (https://github.com/johnkerl/miller/settings/hooks)

**Comment by johnkerl** [comment]
Closing -- please reopen with comment if I'm mistaken! :)

**Comment by trantor** [comment]
Thanks @johnkerl . Did the go port todo change end up in the commit by mistake?

**Comment by johnkerl** [comment]
I'm always editing the `go/todo.txt`, pretty much every commit :)
