### ISSUE TITLE
5.10.+: manpage missing from distfile

### ISSUE THREAD

**Issue by kloczek** [johnkerl/miller#451]
Looks like 5.10.1 no longer install milter(1) man page.

**Comment by johnkerl** [comment]
@kloczek can you clarify where you expect to see this, what URL or command-line invocation is not working as expected?

**Comment by johnkerl** [comment]
(I'm not sure what to fix)

**Comment by kloczek** [comment]
Look on Makefile.am files. None of those files have 'man_MANS` variable(s) declarations.
In 5.9.1 was docs/Makefile.am file which now is not used (look on AC_CONFIG_FILES::AC_CONFIG_FILES() and on Makefile.am::SUBDIRS).. This is causing that none of the actions in `docs/` during `all` and `install` targets are done.

**Comment by kloczek** [comment]
I'm not sure what to ad more because I don't know what was behind removing docs/Makefile from configure.ac::AC_CONFIG_FILES::AC_CONFIG_FILES.

**Comment by johnkerl** [comment]
Ahhh I see. This is because of the move to https://miller.readthedocs.io/en/latest/ from https://github.com/johnkerl/miller/issues/375

Let me look into how we can get both of these working.

Thanks for letting me know! :)

**Comment by johnkerl** [comment]
@kloczek I don't know if this helps as a workaround but for my laptop what I do is

```
export MANPATH=${MANPATH}:$HOME/man
```

in my shell rc file, and in the `miller/docs` directory,

```
make installhome
```

**Comment by kloczek** [comment]
You welcome :P 
Good that you identifird whehere that was introduced.
Please let me know when you will have commited change or at least PR because in few seconds I would be able to test that fix :)

**Comment by johnkerl** [comment]
wow, you're fast! :)

**Comment by johnkerl** [comment]
@kloczek https://github.com/johnkerl/miller/pull/452 but I still need to make a 5.10.2

**Comment by kloczek** [comment]
OK looks like that patch fixes the issue :)

**Comment by johnkerl** [comment]
5.10.2 is released -- thank you !!!! :)

**Comment by kloczek** [comment]
Just tested new version build and all looks good.

Thank you :)
Closing
