### ISSUE TITLE
Feature request: fill-down --all

### ISSUE THREAD

**Issue by johnkerl** [johnkerl/miller#459]
Originally posted by @aborruso in https://github.com/johnkerl/miller/discussions/457#discussioncomment-538399

**Comment by aborruso** [comment]
Today I have thought again to it 🙃

**Comment by johnkerl** [comment]
@aborruso  https://github.com/johnkerl/miller/pull/509

**Comment by aborruso** [comment]
@johnkerl you are a kind of magic, thank you
