### ISSUE TITLE
Is it possible to insert/add csv column in between other columns? Or reorder columns?

### ISSUE THREAD

**Issue by EnilPajic** [johnkerl/miller#492]
Hello.

Thank you for `mlr`, it is a great and usefull tool.

Is there an option to insert a (computed) column in between of other columns.
For example, given the input file:
```
a,b,c,d
test01,test02,test03,test04
test05,test06,test07,test08
test09,test10,test11,test12
```
I want to achieve something like this (e.g. insert `x` column between `b` and `c`):
```
a,b,x,c,d
test01,test02,NEW,test03,test04
test05,test06,NEW,test07,test08
test09,test10,NEW,test11,test12
```

I know, we can use `put '$x="NEW"'`, but that will put column `x` on the end. I read about `reorder`, but it can place columns on the start or end, not in the middle, AFAIK.

(Context: I'm transforming 35 column csv bank report which will be imported in db (out of my controll), so column order matters. Using `Miller 5.9.1`)

**Comment by aborruso** [comment]
You can use put and then reorder verb:

https://miller.readthedocs.io/en/latest/reference-verbs.html#reorder

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il mar 13 apr 2021, 13:39 EnilPajic ***@***.***> ha scritto:

**Comment by EnilPajic** [comment]
Than you for quick response. Still, I don't know how to reorder columns to put them in the middle, not end or beginning?
From the docs (you linked):

```
-e           Put specified field names at record end: default is to put
             them at record start.
```

So, how to achieve to "reorder" last column (created using 'put') in the middle, e.g. "after column 'b'")

**Comment by aborruso** [comment]
@EnilPajic you have `-f {a,b,c}  Field names to reorder`.

Then you can write `reorder a,b,x,c,d` and you have x after column `b`.

**Comment by EnilPajic** [comment]
I was avoiding this because (as stated in my original post) my csv has 35 columns (some with looong names). I was hoping that there is some `mlr` feature I missed in the docs, that can "insert" column, without hard-coding 35 long column names. 

I'll figure something...

Thank you very much for your response!

**Comment by johnkerl** [comment]
Hi @EnilPajic -- how about a `reorder -a b x,y,z` (for put `x,y,z` after `b`)?

**Comment by EnilPajic** [comment]
Hi. 
That would be great! Something similar crossed my mind (I just didn't know that my idea has any chance to become part of mlr), with two options:
*  `-a <X> <columns>`, put `<column(s)>` **after** column `<X>` 
*  `-b <X> <columns>`, put `<column(s)>` **before** column `<X>` (usefull if we don't know or don't care about column names before our `<X>`

But this needs to enable us to specify only column(s) we want to reorder, so in my beforementioned case
```
a,b,x,c,d
test01,test02,NEW,test03,test04
test05,test06,NEW,test07,test08
test09,test10,NEW,test11,test12
```
The ideal command would be `mlr reorder -a b x` (or `mlr reorder -b c x`), but not the command that specifies other columns of csv (like [aborruso suggested in this comment](https://github.com/johnkerl/miller/issues/492#issuecomment-818687576)), or with the new `-a` switch,  e.g. `mlr reorder -a b x,c,d`

**Comment by johnkerl** [comment]
@EnilPajic this has been implemented in https://github.com/johnkerl/miller/pull/510

**Comment by EnilPajic** [comment]
@johnkerl thank you very much for implementing this in a such short time. Have a nice day sir!
