### ISSUE TITLE
variable eol set but not used.

### ISSUE THREAD

**Issue by Lompik** [johnkerl/miller#5]
In the files: 

    input/lrec_reader_mmap_csv.c
    input/lrec_reader_mmap_dkvp.c
    input/lrec_reader_mmap_nidx.c
    input/lrec_reader_mmap_xtab.c

the eol variable is defined but not used. It is just a compiler warning but with the option `-Werror` (specifically `[-Werror=unused-but-set-variable] `) it wont compile until cleared on Linux/Arch.

git version :  7aead02c71a76fb281273563e7e65d3be018bf52

**Comment by vapniks** [comment]
yep, me too

**Comment by johnkerl** [comment]
Closed on https://github.com/johnkerl/miller/pull/7 -- thanks!
