### ISSUE TITLE
Feed mlr's output to bash' set -- $VARIABLE inside a for loop

### ISSUE THREAD

**Issue by NikosAlexandris** [johnkerl/miller#538]
How can I do the following without using `tr` in-between?
```
for PIXEL in $(mlr --csv --headerless-csv-output --from pixels.csv most-frequent -f x,y -b) ;do
    PIXEL=$(echo $PIXEL|tr ',' ' ')
    set -- $PIXEL
    mlr --csv filter '$x == '$1' && $y == '$2'' \
    then group-like pixels.csv > pixel_x${1}_y${2}.csv
done
```

Trying with the following, the `set --` part won't work correctly. 
```
for PIXEL in $(mlr --csv --headerless-csv-output --ofs space --rs 'lf' --from pixels.csv most-frequent -f x,y -b) ;do
    set -- $PIXEL
    echo $1 $2
done
```

Each `x` and `y` gets outputted in its own line. I am trying to double quote `$PIXEL` so as to _protect_ the _line_, but I can't make it work.

**Comment by johnkerl** [comment]
Hi @NikosAlexandris -- what I would do is

```
mlr --icsv --onidx --from pixels.csv most-frequent -f x,y -b \
| while read x y; do
    mlr --csv filter '$x == '$x' && $y == '$y'' \
      then group-like pixels.csv > pixel_x${x}_y${y}.csv
  done
```

**Comment by NikosAlexandris** [comment]
> Hi @NikosAlexandris -- what I would do is
> 
> ```
> mlr --icsv --onidx --from pixels.csv most-frequent -f x,y -b \
> | while read x y; do
>     mlr --csv filter '$x == '$x' && $y == '$y'' \
>       then group-like pixels.csv > pixel_x${x}_y${y}.csv
>   done
> ```

Thank you so much John! Looks simpler and it helps me advance my bash skills too :-)
