### ISSUE TITLE
Make a --prepipe variant for shell commands not handling "<"

### ISSUE THREAD

**Issue by johnkerl** [johnkerl/miller#544]
@aborruso what Miller does with `mlr --prepipe somecommand file.dat` is to `popen` from the process `somecommand < file.dat` -- note the `<`. And it turns out `unzip -qc piemonte.zip` works while `unzip -qc < piemonte.zip` does not.

This makes `unzip -qc` different from most other commands like `gunzip` which are happy with `<`.

In fact this is an important distinction to preserve since `gunzip foo.gz` isn't the same as `gunzip < foo.gz` -- the latter leaves `foo.gz in place; the former removes it and replaces it with the decompressed `foo`.

What we need is a `--prepipe-no-less-than` or something.

_Originally posted by @johnkerl in https://github.com/johnkerl/miller/discussions/539#discussioncomment-802454_

**Comment by aborruso** [comment]
it works great

Thank you
