### ISSUE TITLE
[docs] Request: Please include the example files (csv, etc) in the generated html output

### ISSUE THREAD

**Issue by m040601** [johnkerl/miller#560]
First of all thank you for your amazing work on this severely underrated tool, and it's excelent documentation.

In the generated with sphinx  **online** official guide, https://miller.readthedocs.io/en/latest/ you have lots of ilustrative examples of running commands like:

 $ mlr ...some_command... **data**/some_example.csv

or 

 $ mlr ...some_command ...**multi_join**/some_example.csv

and the corresponding generated output in  html **available online**.

But that "test data" itself, that is all those tiny files themselves, located in folders such as "data", "ngrams"
    $ tree -d  -L 2 docs

```
docs
├── coverart
├── data
├── multi-join
├── ngrams
├── pix
├── polyglot-dkvp-io
├── programs
└── _static

```

 are not available "raw" in the generated doc.
You cant click online where it says "data/some_example.csv" and peek at the plain "some_example.csv" in the browser.

I want to have all those "english-words.txt", "colored-shapes.dkvp", csv, json files used as examples in the doc, also. So that I can play with them offline.

I know that miller has a very man page and my distribution (Arch Linux) of course includes it includes it. But in a tool like this, where you need guided help and examples to master it nothing beats having that html guide with lots of example and test.csv files. And not just reading it, but testing it yourself.

I just hate having to be online and back and forth from my command line, to a browser window, to read the html and test the examples. And needing internet for that. I would rather much prefer to be offline and use a text browser for that. 

And. I would also like to try it for myself, running those examples, and doing small variations. So as to reproduce the examples cited. Of course I could just clone the miller repo, and have that entire "docs" available on my disk. But since browsing html is generated, some times I want to actually click a link to those example files to see them raw.

I just did a quick test

`wget --mirror https://miller.readthedocs.io/en/latest/`

`    $ du -ch ./miller.readthedocs.io`

```
836K    ./miller.readthedocs.io/en/latest/_images
760K    ./miller.readthedocs.io/en/latest/_sources
180K    ./miller.readthedocs.io/en/latest/_static
3.0M    ./miller.readthedocs.io/en/latest
3.0M    ./miller.readthedocs.io/en
3.0M    ./miller.readthedocs.io
3.0M    .
3.0M    total
```

Super  just 3 MEGA.

`tree -L 3  miller.readthedocs.io/`

gives

```
miller.readthedocs.io/
├── en
│   └── latest
│       ├── 10min.html
│       ├── build.html
│       ├── community.html

....

│       ├── search.html
│       ├── _sources
│       ├── sql-examples.html
│       ├── _static
│       └── why.html
├── index.html
└── robots.txt

```

So I guess it's just a matter of making sure sphinx copies all those folders like
"data" "multi-join", "ngrams"

Just like it copies "_static" containing all the css files.

Thanks in advance.

**Comment by johnkerl** [comment]
Thanks @m040601 and you are spot-on!!!

Pre-Sphinx it worked exactly as you suggest, with `./data` etc working nicely. In the move to Sphinx I lost this & didn't track it carefully enough.

Either I'll methodically hyperlink to the GitHub repo itself (https://github.com/johnkerl/miller/tree/main/docs/data/) or I'll find a way to copy the `data` directory to the Sphinx `_build` as part of the Sphinx webhook.

**Comment by johnkerl** [comment]
As for option 2 ... sadly, the Sphinx `html_extra_path = ['data/']` copies everything from `docs/data/*` to `_build/html/*` (losing the `data` subdirectory). :(

I'll try option 1 now.

**Comment by johnkerl** [comment]
(Re option 2 it's easy enough to modify https://github.com/johnkerl/miller/blob/main/docs/Makefile to have some `cp -a` ... but readthedocs doesn't use the `Makefile`; it goes straight to `conf.py`.)

**Comment by johnkerl** [comment]
Update: option 2 is alive, looks like I am able to hack around the issue on https://github.com/johnkerl/miller/pull/562

**Comment by johnkerl** [comment]
https://miller.readthedocs.io/en/latest/data/a.csv for example

I'll also work on making more of these filenames link-clickable in the docs, as a next step

Thanks @m040601  for the suggestion!! :D

**Comment by m040601** [comment]
Wonderfull !

> Thanks @m040601 for the suggestion!! :D

No, thank you, for your amazing commitment and support.
A big UNIX salute !!!

PS:

> At the moment I'm working on Miller 6, which is the Go port,

Can't wait to start crunching csv files and playing "data science" on my tiny Raspberry Pi Zero ... :D
