### ISSUE TITLE
Something strange using stats1 and -s

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#561]
Hi,
I have this input

```
key,value1
1,3
2,7
```

If I  run  `mlr --csv stats1 -a max -f value1 -s then sort -f value1_max input.csv` I have empty result.

No problem if I run `mlr --csv stats1 -a max -f value1 -s input.csv | mlr --csv sort -f value1_max`.

Is it normal?

**Comment by johnkerl** [comment]
Hi @aborruso -- for the C implementation (Miller 5) this is now fixed by https://github.com/johnkerl/miller/pull/564

For the Go port (Miller 6) it's not a bug there.

Thanks for letting me know about this! :D

**Comment by aborruso** [comment]
@johnkerl I'm sure it works. Thank you very much
I will test it using the next release
