### ISSUE TITLE
-jlistwrap adds ] when no data

### ISSUE THREAD

**Issue by ocervell** [johnkerl/miller#567]
Seems like miller `--jlistwrap` doesn't work properly when there is no data:

```
mlr --icsv --ojson --jlistwrap filter \$status==\"FAILURE\" then cut -f item report.csv
```

```
]
```

Excepted output:  `[]` (making most sense when we parse this output with `jq` or similar tools).

**Comment by aborruso** [comment]
True `echo "a=12" | mlr --ojson --jlistwrap filter '$a==3'`, you have `]`.

The right output is the one you have using `echo "a=12\na=6" | mlr --ojson  filter '$a==18' | jq -s`

**Comment by johnkerl** [comment]
@ocervell you are correct, this is a bug -- fixed in a recent commit but not yet in a tagged release. Looking for the commit ...

**Comment by johnkerl** [comment]
@ocervell I am mistaken, and am thinking of something else. Fixing now -- thanks! P.S. this is a very old bug. :(

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/pull/569

@ocervell this will go out in the next release (and it's about time for one ...) -- let me know if you're OK pulling from head or if a release would be useful.

**Comment by ocervell** [comment]
Thanks for the quick turnaround !
