### ISSUE TITLE
failed build with gcc

### ISSUE THREAD

**Issue by jungle-boogie** [johnkerl/miller#57]
Hello,

For the first time in a few days, I tried to build `mlr` from source after fetching new bits with `git pull` but this is a result of the build with `make`:
https://gist.github.com/jungle-boogie/b333580be350c4063e87

     make[1]: Leaving directory '/home/sean/bin/miller/c/dsls'
     gcc -std=gnu99 -I. -Wall -Werror -O3 *.c cli/*.c lib/*.c containers/*.c stream/*.c input/*.c mapping/*.c     output/*.c ./dsls/put_dsl_parse.o    ./dsls/put_dsl_lexer.o    ./dsls/put_dsl_wrapper.o     ./dsls/filter_dsl_parse.o ./dsls/filter_dsl_lexer.o ./dsls/filter_dsl_wrapper.o -lm -o mlr
     mapping/mlr_val.c: In function ‘s_i_sec2hms_func’:
     mapping/mlr_val.c:319:12: error: variable ‘sign’ set but not used [-Werror=unused-but-set-variable]
      long long sign = 1LL;
             ^
     mapping/mlr_val.c: In function ‘s_f_fsec2hms_func’:
     mapping/mlr_val.c:336:12: error: variable ‘sign’ set but not used [-Werror=unused-but-set-variable]
       long long sign = 1LL;
            ^
     cc1: all warnings being treated as errors
    Makefile:75: recipe for target 'mlr' failed
    make: *** [mlr] Error 1

**Comment by SikhNerd** [comment]
I brought this up here as well: https://github.com/johnkerl/miller/pull/55#issuecomment-136243967

This was introduced as part of the dhms work, I suspect will be cleared up by @johnkerl shortly as he uses the sign variable for the next iteration.

**Comment by jungle-boogie** [comment]
Hi @SikhNerd,

Thanks for the update and cross linking. Apologies for also not carefully reviewing open cases.

Thanks,
Sean

**Comment by johnkerl** [comment]
for sure this was introduced onhttps://github.com/johnkerl/miller/issues/35

i'll fix this 1st thing this evening.

but also i need to crank up the warning levels for my compiler. this issue wasn't an error for me but was for you and was for travis.

**Comment by johnkerl** [comment]
fixed in https://github.com/johnkerl/miller/commit/3e7e94cb70b8f910e6ad0f4a4a42d016beda94e8 -- thank you for the report!! :)

**Comment by jungle-boogie** [comment]
:+1:
