### ISSUE TITLE
cut verb -f option should support double quoted fields

### ISSUE THREAD

**Issue by mrdvt92** [johnkerl/miller#581]
The cut -f option should allow fields name to be double quoted.

got two empty lines
```
$ echo -e "a,b\n1,2" | mlr --csv cut -f '"a"'


```

expect
```
$ echo -e "a,b\n1,2" | mlr --csv cut -f 'a'
a
1
```

Quoted fields in the -f option just do not work so there is no backwards compatibility issue
```
$ echo -e '"a","b"\n1,2' | mlr --csv cut -f '"a"'



```

There are many files where the header is double quoted like this.  Unfortunately, RFC-4180 is not clear on double quoted headers.

```
$ cat template.csv
"a","b","c"
"foo","bar",42
```

In order to use this file header with the cut verb the double quotes must be removed.  So, a workaround is to remove the double quotes before feeding into mlr.

```
$ echo -e "a,b,c,d\n1,2,3,4" | mlr --csv cut -f "`head -n 1 template.csv | tr -d '"'`"
a,b,c
1,2,3
```

But, I expect this to work in the future

```
$ echo -e "a,b,c,d\n1,2,3,4" | mlr --csv cut -f "`head -n 1 template.csv`"
```

**Comment by aborruso** [comment]
What about to use regex?

```
echo -e '"a","ba","c"\n1,2,3' | mlr --csv cut -r -f '"^a$","^c$"'
```

```
a,c
1,3
```

**Comment by johnkerl** [comment]
Thanks @mrdvt92 !

**Comment by johnkerl** [comment]
@mrdvt92 Quotes are intended to "disappear" for CSV -- a field `"a"` is named `a` -- I think we should go with the recommended use of `tr` and/or `sed` in

```
echo -e "a,b,c,d\n1,2,3,4" | mlr --csv cut -f $(head -n 1 template.csv | sed 's/"//g' )
```
