### ISSUE TITLE
Memory requirements when merging large files via cat, unsparsify and sort

### ISSUE THREAD

**Issue by NikosAlexandris** [johnkerl/miller#587]
I have a series of relatively large files:
```
-rw-r--r-- 1 nik nik  2.8G Jun 29 22:15 landsat8_reflectances_temperature_2019-01-07.csv
-rw-r--r-- 1 nik nik 1008M Jun 29 22:19 landsat8_reflectances_temperature_2019-01-23.csv
-rw-r--r-- 1 nik nik  2.8G Jun 29 22:30 landsat8_reflectances_temperature_2019-02-08.csv
-rw-r--r-- 1 nik nik  2.8G Jun 29 22:41 landsat8_reflectances_temperature_2019-02-24.csv
-rw-r--r-- 1 nik nik  2.4G Jun 29 22:50 landsat8_reflectances_temperature_2019-03-12.csv
-rw-r--r-- 1 nik nik  2.8G Jun 29 23:01 landsat8_reflectances_temperature_2019-03-28.csv
-rw-r--r-- 1 nik nik  2.8G Jun 29 23:11 landsat8_reflectances_temperature_2019-04-13.csv
-rw-r--r-- 1 nik nik  2.7G Jun 29 23:22 landsat8_reflectances_temperature_2019-04-29.csv
-rw-r--r-- 1 nik nik  2.8G Jun 29 23:33 landsat8_reflectances_temperature_2019-05-15.csv
-rw-r--r-- 1 nik nik  2.8G Jun 29 23:44 landsat8_reflectances_temperature_2019-05-31.csv
-rw-r--r-- 1 nik nik  650M Jun 29 23:47 landsat8_reflectances_temperature_2019-06-16.csv
-rw-r--r-- 1 nik nik  2.8G Jun 29 23:58 landsat8_reflectances_temperature_2019-07-02.csv
-rw-r--r-- 1 nik nik  2.7G Jun 30 00:08 landsat8_reflectances_temperature_2019-07-18.csv
-rw-r--r-- 1 nik nik  2.8G Jun 30 00:19 landsat8_reflectances_temperature_2019-08-03.csv
-rw-r--r-- 1 nik nik  1.7G Jun 30 00:26 landsat8_reflectances_temperature_2019-08-19.csv
-rw-r--r-- 1 nik nik  2.8G Jun 30 00:37 landsat8_reflectances_temperature_2019-09-04.csv
-rw-r--r-- 1 nik nik  115M Jun 30 00:37 landsat8_reflectances_temperature_2019-09-20.csv
-rw-r--r-- 1 nik nik  721M Jun 30 00:40 landsat8_reflectances_temperature_2019-10-06.csv
-rw-r--r-- 1 nik nik  3.3K Jun 30 00:41 landsat8_reflectances_temperature_2019-11-07.csv
-rw-r--r-- 1 nik nik  1.4G Jun 30 00:46 landsat8_reflectances_temperature_2019-11-23.csv
-rw-r--r-- 1 nik nik  406M Jun 30 00:48 landsat8_reflectances_temperature_2019-12-09.csv
-rw-r--r-- 1 nik nik  2.4G Jun 30 00:57 landsat8_reflectances_temperature_2019-12-25.csv
```

I am attempting to merge them via
```
mlr --csv cat then unsparsify --fill-with "NA" then sort -f $doy,$time landsat8_reflectances_temperature_2019-??-??.csv > landsat8_reflectances_temperature_time_series_2019.csv
```

but the process seems to consume all of my workstation's 250/252GB RAM and even the swap space, then slows-down the system :D and finally seems to end up unssuccessfully (I let it ran till it got killed)!

I found no useful reference searching for `memory` that would relate to my current task.

**Comment by johnkerl** [comment]
@NikosAlexandris `unsparsify` is non-streaming, meaning, it has to keep all rows in memory before producing any.

If you know the full list of field names in advance then @sjackman 's nice feature `mlr unsparsify -f` is handy -- this is streaming and should be more memory-friendly.

However, `sort` is also non-streaming (needs all rows in memory before doing the sort) and that's not really fixable as `unsparsify` is ... . Unix/Linux `sort` does out-of-core sorting for large files, and out-of-core has never been implemented by Miller (but could conceivably be someday ...).

The Miller docs & on-line help make scattered (and brief) references to "streaming" and "non-streaming" but there's no central location -- I'll make a separate page on memory utilization, primarily around streaming & non-streaming verbs.

**Comment by NikosAlexandris** [comment]
> The Miller docs & on-line help make scattered (and brief) references to "streaming" and "non-streaming" but there's no central location -- I'll make a separate page on memory utilization, primarily around streaming & non-streaming verbs.

Thank you John. Makes sense to me now. Just flashing ideas... a table with two columns would be a nice overview (?).

| verb | non-streaming| streaming |
|-------|--------------------|---------------|
| sort | X | |
| other | | X |

or simpler

| streaming | non-streaming |
|---------------|--------------------|
| verba, verb | sort, verbc |

**Comment by johnkerl** [comment]
Hi @NikosAlexandris --

It turns out it's a little more subtle than just 'streaming vs non-streaming' -- waiting for end of input, vs being memory-unfriendly, aren't always the same.

Can you please take a look at https://johnkerl.org/miller6/streaming-and-memory and tell me what you think ?

**Comment by NikosAlexandris** [comment]
@johnkerl where is the source of https://johnkerl.org/miller6/streaming-and-memory? Sorry, I can't trace it 😞.

**Comment by NikosAlexandris** [comment]
> @NikosAlexandris sorry it's on a branch, not merged yet
> https://github.com/johnkerl/miller/blob/doc6-proofreads-3/docs6/docs/streaming-and-memory.md.in

Here what I came up with while _compressing_ stuff: https://gist.github.com/NikosAlexandris/416564ed560b3ae917d8fe9323070196

**Comment by johnkerl** [comment]
@NikosAlexandris this is nice, much more compact! :)

**Comment by NikosAlexandris** [comment]
> @NikosAlexandris this is nice, much more compact! :)

Can be on top as an overview, or elsewhere. I am not suggesting replacing the full texts.

**Comment by NikosAlexandris** [comment]
> Here what I came up with while _compressing_ stuff: https://gist.github.com/NikosAlexandris/416564ed560b3ae917d8fe9323070196

The table header or single terms (e.g. Memory and Friendly-Unfriendly, etc.) deserve perhaps some re-wording. But ok. it's a draft.

**Comment by NikosAlexandris** [comment]
@johnkerl verbs != statements in Miller's DSL, right?

**Comment by johnkerl** [comment]
@NikosAlexandris correct & I should clarify with an example like the following:

By "statements" I mean `$z = $x + $y` will be done 10,000 times if you have an input file with 10,000 records.

**Comment by NikosAlexandris** [comment]
> @NikosAlexandris correct & I should clarify with an example like the following:
> 
> By "statements" I mean `$z = $x + $y` will be done 10,000 times if you have an input file with 10,000 records.

Well, the example is already there. My need for verification only.-
