### ISSUE TITLE
filter/put don't work with fields that contain spaces

### ISSUE THREAD

**Issue by eveith** [johnkerl/miller#59]
I've got a CSV file where the column headers contain spaces. For example:

```
 Datetime; Mean Real Power (MW); Mean Reactive Power (MVA)
```

I'd like to filter column 2 and use the `stats1` verb on it (some cells in column 2 don't have values). But I cannot construct a filter expression to name this second column, i.e., `$'Mean Real Power (MW)'` or variances of it don't work. 

Or perhaps I'm just missing something?

**Comment by johnkerl** [comment]
At the moment, RS/FS are ignored for RFC-compliant CSV:

https://github.com/johnkerl/miller/issues/50
https://github.com/johnkerl/miller/releases/tag/v2.0.0

And for non-compliant CSV (`--csvlite`), `RS` & `FS` are single-char only whereas it looks like you'd want `FS` to be `; `.

This isn't great and my current effort is on this.

**Comment by eveith** [comment]
I see. 

Given the FS is a single char, can I refer to the fields if they contain spaces with `--csvlite`? E.g.:

     Some Field;Some Other Field;Yet Another Field

**Comment by jungle-boogie** [comment]
If it's only the column header with spaces, you could make it one word or use `-` or `_` until there's something more concrete.

**Comment by eveith** [comment]
Sadly, its not just the column header, but fields contain spaces as well, thus a simple `sed -e 's/ /_/g'` won't help me. Sigh, I guess I need to edit the file using Perl instead. Perhaps its worth to  associate this issue with the general "RFC-compliant CSV" issue?

**Comment by johnkerl** [comment]
RS/FS apply equally to header and data lines, no problem there.

The RFC says FS is comma and RS is CRLF, with double-quote support -- which is rather inflexible. The task here is to allow non-standard delimiters, while retaining double-quote support and reasonable performance.

**Comment by johnkerl** [comment]
I'll dup this issue this evening. Thanks for helping me to understand your use case!! :)

**Comment by johnkerl** [comment]
& yes, re you "I see" entry, for `--csvlite` you can do `--fs ';'` or `--fs semicolon`.

**Comment by johnkerl** [comment]
duping to https://github.com/johnkerl/miller/issues/50

**Comment by meonkeys** [comment]
> If it's only the column header with spaces, you could make it one word or use `-` or `_` until there's something more concrete.

Please clarify: if a column header has a space, can it be used in a filter expression (as in the original question)? I'm gathering the answer is "don't use spaces in column headers", I just want to be sure. @eveith asked if something like `$'Mean Real Power (MW)'` could be made to work. I'm not proposing or asking for a change, just trying to understand current miller behavior and usage. I can name columns without spaces and that is my current workaround.

**Comment by johnkerl** [comment]
@meonkeys sorry -- the syntax is `${...}`

```
$ cat foo.csv
id,Mean Real Power (MW)
1,3400
2,5600
```

```
$ mlr --c2j put '${Mean Real Power (GW)} = ${Mean Real Power (MW)} / 1000' foo.csv
{
  "id": 1,
  "Mean Real Power (MW)": 3400,
  "Mean Real Power (GW)": 3.4
}
{
  "id": 2,
  "Mean Real Power (MW)": 5600,
  "Mean Real Power (GW)": 5.6
}
```

**Comment by johnkerl** [comment]
@meonkeys how is https://miller.readthedocs.io/en/latest/10min/#handling-field-names-with-spaces ?

**Comment by meonkeys** [comment]
LGTM!

Also, did you just fix the documentation? I recall trying to read it the other day and the formatting was broken. Looks awesome now.

**Comment by johnkerl** [comment]
Thanks @meonkeys !

Lots & lots of doc updates these days as Miller 6 release approaches :)
