### ISSUE TITLE
OSX Build

### ISSUE THREAD

**Issue by sammcj** [johnkerl/miller#6]
I have built miller for OSX against 10.11 (BETA 6) - The binary should 'just work' and can be placed in your path somewhere.

Might be a tide-over until it's available in homebrew.

```
samm-mbp ~/git/miller/c % file mlr
mlr: Mach-O 64-bit executable x86_64

samm-mbp ~/git/miller/c % md5 mlr
MD5 (mlr) = d4199111ec0cb33365a9fc5a0dd185d6

samm-mbp ~/git/miller/c % md5 mlr.zip
MD5 (mlr.zip) = e2e8fd016ad07279ff771d06e84a27d4
```

Release download: https://github.com/sammcj/miller/releases/tag/v0.1

**Comment by johnkerl** [comment]
Thank you! I'll implement tagging soon. I've built Miller in self-CI mode (run all tests before each commit, and frequently in between) since the beginning. What's new since the release announcement on Saturday is people building Miller on multiple platforms (more than my particular two).

**Comment by johnkerl** [comment]
Linked to from http://johnkerl.org/miller/doc/build.html -- thank again!!

**Comment by johnkerl** [comment]
After things stabilize platform-wise (good info flowing in since the release announcement) I'll cut a tag at https://github.com/johnkerl/miller.
