### ISSUE TITLE
malloc(32) failed.

### ISSUE THREAD

**Issue by EnilPajic** [johnkerl/miller#604]
Hello!

I'm trying to count number of rows in CSV file. CSV is `\r\n` (CRLF) row-delimited, using `;` as field separator.
File is 105MB in size, and has 361854 rows (+1 header row).

```shell
ls -l file.csv
-rw-r--r-- 1 root root 109649791 Jul 13 14:59 file.csv

ls -lh file.csv 
-rw-r--r-- 1 root root 105M Jul 13 14:59 file.csv

awk 'BEGIN { RS = "\r\n" } END { print NR }' file.csv
361855
```

System has 32GB of RAM, currently available 19GB and free 1.1GB:

```shell
free -h
              total        used        free      shared  buff/cache   available
Mem:            31G         10G        1.1G        953M         19G         19G
Swap:          3.9G        776M        3.1G
```

But, when I try to simply print number of rows in CSV using `mlr`, it fails (exit code 1) with  error `malloc(32) failed.`:

```
mlr --icsv --irs crlf --ifs ";" count file.csv 
malloc(32) failed.
```

File is just 105MB, and `mlr` docs say it uses streaming whenever it can (and counting total number of rows seems like operation that does not require `mlr` to load it into memory).

I'm using `5.9.1` version of `mlr`, but same thing happens with `5.10.2-dev` (manually compiled).
```shell
mlr --version
Miller 5.9.1

mlr-5.10.2 --version
Miller v5.10.2-dev

```

I'm using Centos 7.

Note: I'm aware that I can use something else for counting number of rows (like I did with `awk` above), but this is just simplified case that is raising "malloc(N) failed" error. In reallity, I'm using `filter`, `put`, etc. with `then`s (and getting the same error).

Using `/usr/bin/time -v` command, it seems that peak RAM usage is over 1GB for `mlr`, despite file being 10 times smaller (and `count` operation is probably streamed anyway).

```shell
/usr/bin/time -v mlr --icsv --irs crlf --ifs ";" count file.csv 
malloc(40) failed.
Command exited with non-zero status 1
	Command being timed: "mlr --icsv --irs crlf --ifs ; count file.csv"
	User time (seconds): 2.25
	System time (seconds): 0.70
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:02.96
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 1033052 <----- (1033 MB) <-------
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 258310
	Voluntary context switches: 1
	Involuntary context switches: 12
	Swaps: 0
	File system inputs: 0
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
```

What could it be or what I'm doing wrong? Is there workaround for this (except by freeing memory)? (I tried both `--no-mmap` and `--mmap` options; same results).

**Comment by aborruso** [comment]
Hi, if you run the same command only for 100 rows do you have the same error?

```
<input.csv head -n +100 | mlr --icsv --irs crlf --ifs ";" count 
```

**Comment by EnilPajic** [comment]
Hi @aborruso, no, with only 100 rows everything works fine (also with smaller files, e.g. 50k rows instead of 360k):

```shell
<file.csv  head -n 100 | mlr --icsv --irs crlf --ifs ";" count 
count=99

#50k
<file.csv head -n 50000 | mlr --icsv --irs crlf --ifs ";" count
count=49999
```

**Comment by johnkerl** [comment]
@EnilPajic sorry I didn't see this sooner! This is definitely a bug.

I'm away this week but will respond in about a week.

**Comment by johnkerl** [comment]
@EnilPajic this is fixed by https://github.com/johnkerl/miller/commit/86f31f2f9b4f3f097e949f9f9de7658fa6c713a0

**Comment by EnilPajic** [comment]
@johnkerl thank you. I'll test it in the next week, but probably it'll work as expected!

Enil
