### ISSUE TITLE
cat: group by field value seems not work

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#611]
Hi,
If I run `echo 'a=10,b=hello\na=10,b=world' | mlr --omd cat -n -g a` I have

| n | a | b |
| --- | --- | --- |
| 1 | 10 | hello |
| 2 | 10 | world |

and not

| n | a | b |
| --- | --- | --- |
| 1 | 10 | hello |
| 1 | 10 | world |

The output is not grouped by `a` field. 

How to use the `-g` option?

Thank you

**Comment by johnkerl** [comment]
@aborruso for `mlr cat` the group-by means all rows with the same `a` values are adjacent (which they are). The `n` is the record-counter within each group of records having the same `a` value.

**Comment by johnkerl** [comment]
(Phrased differently, I don't see the bug here ...)

**Comment by aborruso** [comment]
> The `n` is the record-counter within each group of records having the same `a` value.

If I run `echo 'a=10,b=hello\na=10,b=world' | mlr --omd cat -n -g a`, I have two records with the same `a` values, but 2 different `n` values, not the same record counter.

**Comment by johnkerl** [comment]
> @aborruso for mlr cat the group-by means all rows with the same a values are adjacent

Correction, `mlr cat -g` doesn't make grouped records adjacent; `mlr group-by` does.

The idea of `mlr cat -n` is there is a 1-up record counter incrementing across records. The idea of `mlr cat -n -g ...` is that records having common `-g` field(s) have their own separate counter.

So if the input data are like this:

```
$ mlr --icsv --opprint cat example.csv
color  shape    flag  index quantity rate
yellow triangle true  11    43.6498  9.8870
red    square   true  15    79.2778  0.0130
red    circle   true  16    13.8103  2.9010
red    square   false 48    77.5542  7.4670
purple triangle false 51    81.2290  8.5910
red    square   false 64    77.1991  9.5310
purple triangle false 65    80.1405  5.8240
yellow circle   true  73    63.9785  4.2370
yellow circle   true  87    63.5058  8.3350
purple square   false 91    72.3735  8.2430
```

then ungrouped `cat -n` does this:

```
$ mlr --icsv --opprint cat -n example.csv
n  color  shape    flag  index quantity rate
1  yellow triangle true  11    43.6498  9.8870
2  red    square   true  15    79.2778  0.0130
3  red    circle   true  16    13.8103  2.9010
4  red    square   false 48    77.5542  7.4670
5  purple triangle false 51    81.2290  8.5910
6  red    square   false 64    77.1991  9.5310
7  purple triangle false 65    80.1405  5.8240
8  yellow circle   true  73    63.9785  4.2370
9  yellow circle   true  87    63.5058  8.3350
10 purple square   false 91    72.3735  8.2430
```

while grouped `cat -n` does this:

```
$ mlr --icsv --opprint cat -n -g color example.csv
n color  shape    flag  index quantity rate
1 yellow triangle true  11    43.6498  9.8870
1 red    square   true  15    79.2778  0.0130
2 red    circle   true  16    13.8103  2.9010
3 red    square   false 48    77.5542  7.4670
1 purple triangle false 51    81.2290  8.5910
4 red    square   false 64    77.1991  9.5310
2 purple triangle false 65    80.1405  5.8240
2 yellow circle   true  73    63.9785  4.2370
3 yellow circle   true  87    63.5058  8.3350
3 purple square   false 91    72.3735  8.2430
```

The output records are in the same order as in the input. Here the `n` is `1,2,3` for the 1st,2nd,3rd records which have `color=yellow`; `n` is `1,2,3,4` for the 1st,2nd,3rd,4th records which have `color=red`; `n` is `1,2,3` for the 1st,2nd,3rd records which have `color=purple`.

**Comment by aborruso** [comment]
Thank you I wrote a wrong issue, and maybe you already explained it to me. Excuse me
