### ISSUE TITLE
Use CC in Makefiles so Travis gcc/clang variants will use gcc/clang, respectively

### ISSUE THREAD

**Issue by johnkerl** [johnkerl/miller#63]
At present, both the `gcc` and `clang` builds at https://travis-ci.org/johnkerl/miller are actually using `gcc` since that's how Miller's makefiles are written.

**Comment by jungle-boogie** [comment]
I support this! It means I won't need to specify clang with each build via `make -e CCOMP=clang`.

:+1:

**Comment by johnkerl** [comment]
Right. I wrote `make -e CCOMP=clang` not knowing any better, but then I took a look at the Travis logs & realized how the rest of the world does it. :^/

**Comment by johnkerl** [comment]
Fixed by https://github.com/johnkerl/miller/commit/610c2dc8d5d64afd903cf1f58024747a148d643a
