### ISSUE TITLE
It should recognize higher version of aclocal

### ISSUE THREAD

**Issue by gnusupport** [johnkerl/miller#630]
```
$ make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/data1/protected/Programming/git/miller/autotools/missing aclocal-1.15 
/home/data1/protected/Programming/git/miller/autotools/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [Makefile:373: aclocal.m4] Error 127
~/Programming/git/miller
$ aclocal-1
bash: aclocal-1: command not found
~/Programming/git/miller
$ aclocal-1.16 
~/Programming/git/miller
$ 
```

**Comment by johnkerl** [comment]
Thanks @gnusupport -- sorry about the confusion. I'm not sure I ever got the "right" thing to do set up. :(

What I settled on (and what I recommend) is in https://miller.readthedocs.io/en/latest/build.html -- namely, first `autoreconf -fiv`. See also https://github.com/johnkerl/miller/issues/131.

I know this isn't standard open-source behavior on Miller's part -- people are accustomed to doing `./configure && make && make install`.

That said, I'm porting Miller from C to Go (https://github.com/johnkerl/miller/blob/main/go/README.md) and I'm sure this will all go away soon ........

**Comment by johnkerl** [comment]
@gnusupport Miller 6 will be released very soon & this issue will go away with it.

Thanks for reporting this! :)
