### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by jungle-boogie** [johnkerl/miller#64]
Hello,

     ./test/../mlr put $z=min($x, $y) ./test/input/minmax.dkvp
      x=1,y=2,z=1.000000
      x=1,y=,z=1.000000
      x=,y=,z=
    *** Error code 1

    Stop.
    make: stopped in /usr/home/sean/bin/miller/c

Full log here:
https://gist.github.com/jungle-boogie/5fe0b5f064a64dcb6dca

I've even removed miller git clone in hopes it was something specific with my clone, but it continues to occur.

**Comment by johnkerl** [comment]
I'll check it out. passing travis ...

**Comment by johnkerl** [comment]
Due to https://github.com/johnkerl/miller/issues/63 the Travis build isn't really using clang. But, I used clang on my OSX machine & could not reproduce the problem.

**Comment by johnkerl** [comment]
What's your platform?

**Comment by jungle-boogie** [comment]
This is on freebsd 10.2 stable. It could be my system but it was building fine very recently.

**Comment by johnkerl** [comment]
As of https://github.com/johnkerl/miller/issues/63 I have a clang build on Travis, which is an improvement.

I did a bit of a refactor while iterating on the CSV-performance stuff. Most mods the last few days have been only affecting new files which aren't yet externally visible; I've just incrementally added UTs. However, one commit was a bit cross-cutting as it modified an internal API. This was https://github.com/johnkerl/miller/commit/5dfe53056cbd9762416c973a96bc1d3cd2014ba9.

Any chance you can build with that commit, and the one before it?

(As a side note, I notice from your pastebin that `sec2gmt` is failing regression, but not causing a process exit; then the process exit after that in the `minmax` case. So there appear to be multiple issues going on.)

**Comment by jungle-boogie** [comment]
Hi,

Build 5dfe530 is worse: https://gist.github.com/jungle-boogie/19a9b0011bc38611a450

Thanks,
jb

**Comment by jungle-boogie** [comment]
Here's build    54ea039b034ff0874f386b54d5327c1de780b7fb https://gist.github.com/jungle-boogie/45a3904889144e4217f9

I think I am doing the revert/checkout thing correctly with git.

**Comment by johnkerl** [comment]
Something really weird with the `fatal error: 'lib/mlrutil.h' file not found`. Not sure the revert/checkout thing is correct.

**Comment by jungle-boogie** [comment]
okay, it must be some tiny change on my system that I originally reported the problem on as another machine builds just fine.

It appears there's a few delicate pieces with mlr.

**Comment by johnkerl** [comment]
happy to learn more about those delicate pieces! can you tell me more about the differences between the two systems?

**Comment by jungle-boogie** [comment]
Hi @johnkerl,

> can you tell me more about the differences between the two systems?

Just before I updated millier on the problem system, I updated some packages/applications. I'll have to figure out the list of updated packages and their libraries.
