### ISSUE TITLE
"$quanity" typo across the documentation

### ISSUE THREAD

**Issue by trantor** [johnkerl/miller#641]
Hey @johnkerl I've noticed this typo both in the current live docs and in the ones for Miller 6.
I haven't gone through the code to submit a PR because maybe it's quicker for you to fix it.

Just to let you know.
See you

**Comment by johnkerl** [comment]
Fixed for Miller 5 in https://github.com/johnkerl/miller/commit/14dd5592e7f88dee939559254c81480b8bb210ca; for Miller 6 in my current dev branch.

Grazie @trantor !! :)
