### ISSUE TITLE
Go-port stats1 missing output values

### ISSUE THREAD

**Issue by NikosAlexandris** [johnkerl/miller#653]
With inputs
```bash
➜  wc -l input*
  139972 input.csv
      11 input_head.csv
  139983 total
```
which look like
```bash
➜  mlr.go head -n 1 input.csv
1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26
6,2,2019-01-07,0.003527499968186021,0.01252000033855438,0.03669250011444092,0.03256750106811523,0.3152124881744385,0.1147375032305717,0.05822499841451645,0.812712,0.498767,0.500091,0.466275,-0.515387,-0.466275,0.688167,0.326733,0.984499990940094,10.81735610961914,0.961899995803833,0.9621999859809875,1.289999961853027,72.41999816894531,2.019999980926514,0.0836972
```
the following tests using 3 different Miller's
```
➜  mlr.go --version
Miller v6.0.0-dev

➜  mlr.linux.x86_64 --version
Miller v5.10.2

➜  mlr --version
Miller 5.3.0-dev
```
show a bug in the Go-port:

```bash
➜  mlr.go stats1 -a min,mean,max -f 11 input.csv
11_min,11_mean,11_max
-0.290906,,

➜  mlr.linux.x86_64 stats1 -a min,mean,max -f 11 input.csv
11_min,11_mean,11_max
-0.290906,0.357404,0.972221

➜  mlr stats1 -a min,mean,max -f 11 input.csv
11_min=-0.290906,11_mean=0.357480,11_max=11.000000
```

This does not happen with `input_head.csv` however
```bash
➜  mlr.go stats1 -a min,mean,max -f 11 input_head.csv
11_min,11_mean,11_max
0.664512,0.7986057999999999,0.870342
```

or if the requested field is one in the "beginning"
```bash
➜  mlr.go stats1 -a min,mean,max -f 4 input.csv
4_min,4_mean,4_max
-0.1928499937057495,0.05736697802950242,0.5068874955177307

➜  mlr.linux.x86_64 stats1 -a min,mean,max -f 4 input.csv
4_min,4_mean,4_max
-0.192850,0.057367,0.506887

➜  mlr stats1 -a min,mean,max -f 4 input.csv
4_min=-0.192850,4_mean=0.057395,4_max=4.000000
```

I only have
```bash
➜  cat /home/nik/.mlrrc
csv
```

ps- It seems Miller 5.3.0-dev takes into account the field name in which case it's a number (in the examples 11 or 4).

**Comment by johnkerl** [comment]
Hi @NikosAlexandris -- as far as I can tell the difference is in how `stats1` handles empty fields.

```
$ cat abc.csv
a,b,c
1,2,3
4,,
```

```
$ mlrc --csv stats1 -a sum -f a,b abc.csv
a_sum,b_sum
5,2

$ mlr --csv stats1 -a sum -f a,b abc.csv
a_sum,b_sum
5,
```

```
$ mlrc --version
Miller v5.10.2-dev
$ mlr --version
Miller v6.0.0-dev
```

**Comment by johnkerl** [comment]
Thank you @NikosAlexandris ! :)

**Comment by NikosAlexandris** [comment]
> Hi @NikosAlexandris -- as far as I can tell the difference is in how `stats1` handles empty fields.
> 
> ```
> $ cat abc.csv
> a,b,c
> 1,2,3
> 4,,
> ```
> 
> ```
> $ mlrc --csv stats1 -a sum -f a,b abc.csv
> a_sum,b_sum
> 5,2
> 
> $ mlr --csv stats1 -a sum -f a,b abc.csv
> a_sum,b_sum
> 5,
> ```
> 
> ```
> $ mlrc --version
> Miller v5.10.2-dev
> 
> $ mlr --version
> Miller v6.0.0-dev
> ```
> 
> ```
> $ echo 'x=3,y=' | mlrc put '$z=$x+$y'
> x=3,y=,z=
> 
> $ echo 'x=3,y=' | mlr put '$z=$x+$y'
> x=3,y=,z=
> ```
> 
> So both have the general rule "int plus empty string is empty string" -- but Miller 5 has a special case inside `stats1` which Miller 6 lacks:
> 
> https://github.com/johnkerl/miller/blob/main/c/mapping/mapper_stats1.c#L562-L565
> 
> This should be quick to fix (unless it causes a complication somewhere else).

I just confirmed that the `input.csv` file contains empty fields. Closing this issue and hopping for Mi6 to do the same trick as his predecessor :-)
