### ISSUE TITLE
Miller 6: something strange with regex

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#684]
Hi,
I have this CSV

```
1,2
UTM,
Y,X
2769254.392,728323.36
2779036.337,748997.019
2775781.614,752813.833
2772356.603,747497.487
2767208.788,742530.091
2763395.255,736766.372
2763799.272,731225.956
2763188.826,729889.362
```

Why do I have empty result running `mlrgo --csv filter -S '$1=~"^[0-9]+.+$"' input.csv` (I want all records in which `1` starts with a number)?

Moreover I have what I want running `mlrgo --csv filter -x -S '$1=~".+"' tmp.csv`

```
1,2
2769254.392,728323.36
2779036.337,748997.019
2775781.614,752813.833
2772356.603,747497.487
2767208.788,742530.091
2763395.255,736766.372
2763799.272,731225.956
2763188.826,729889.362
```

The last filter should give all the records, not only those that start with a number.

Am I wrong?

**Comment by johnkerl** [comment]
So the fix here will be to auto-cast to strings for operands of `=~` and `!=~`

**Comment by johnkerl** [comment]
Also (this needs documentation) `-S` and `-F` don't do anything in Miller 6, and can't.

In Miller 5 and below, all record values were strings up until the last moment in `put`,`filter`, `stats1`, etc.

In Miller 6, type-inference is done in the record-reader so ints/floats are already ints/floats when `put`/`filter`/`stats1`/ et al. get them.

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/pull/687

**Comment by aborruso** [comment]
> So the fix here will be to auto-cast to strings for operands of `=~` and `!=~`

People have Batman, I have you :D
