### ISSUE TITLE
[NFR] an easier way to print a string based on a format and field values

### ISSUE THREAD

**Issue by trantor** [johnkerl/miller#689]
Often enough I find myself using CSV fields to output strings/text using a template, à la printf.
This can be done with `put` + `print` with concatenation of strings and `$field` references, but it's rather cumbersome.

Something similar to what https://github.com/archiecobbs/csvprintf does would be much more convenient.

**Comment by johnkerl** [comment]
@trantor this is a great idea -- I get a bit tired of dotting too :)

A couple options:

* Just string interpolation, like `print "the {} of {} and {} is {}", "sum", x, y, x+y`
* Full-blown format-strings with length, left/right alignment, etc etc. as you've shown above

Even the first one would be an improvement, and would be very quick to code up.

The second one would take a bit longer to code up but would be do-able.

An alternate of the first version, with smooth transition to the second one, would be to support a type-agnostic `%v` (like Go does), so even the simple case would be `print "the %v of %v and %v is %v", "sum", x, y, x+y`. Then, moving from the quick/easy first version to the longer/harder second version would simply involve supporting more and more `%` formatters.

**Comment by johnkerl** [comment]
@trantor I realized the last option isn't great, as it requires a DSL re-parse for the innards of `#{...}`.

https://github.com/johnkerl/miller/pull/869 is a simple adaptation of Python's `"...".format(...)` method. This is wonderful simple; however it leaves the printf-style formatting to the caller ...

**Comment by johnkerl** [comment]
@trantor closing this issue -- please re-open if you'd like to go further with this -- thanks for raising it! :)
