### ISSUE TITLE
Treat fields which are potentially octal numbers as strings

### ISSUE THREAD

**Issue by spmundi** [johnkerl/miller#710]
If I have a file with fields which are decimal numbers (eg  csv with 1,11) and I concatenate those fields (s=$field.$fieldb) then on output I see 111. OK. But when the input is intended to be a string with a leading zero (eg 01,011) then on output I see 19
(explanation: 011 is treated as octal 9. Concatenating "1" with "9" gives "19")
How can I work around this? ie. I need a command line option to say that these are strings (it does not of course work to convert them to strings in dsl -- is it  even possible? -- because the conversion to octal has already occurred.

**Comment by johnkerl** [comment]
@spmundi closing ... please let me know if any concerns are unaddressed & we can re-open -- thank you! :)
