### ISSUE TITLE
JSON negative numbers as input

### ISSUE THREAD

**Issue by ChCyrill** [johnkerl/miller#714]
mlr produces random characters for unquoted negative numbers from json input.

### To reproduce
Command:
`echo '{ "a" : -15 }' | mlr --ijson --ocsv cat`
produces (each time result after '-15' is different):
```
a
-15µ
```

### Environment:
- Arch Linux
- mlr 5.10.2

**Comment by ChCyrill** [comment]
I've tried to find a problem on my side, but unsuccessfully. Also tried to build latest version from git 'directly'. 
I don't have any ideas why it can work differently. 

### Experiments

Using script below I found that:
1. It works with float/double values. Issue is reproducible only on integers.
2. Issue isn't reproducible on very big integers (probably they are interpreted as double internally).
```
./mlr --ijson --ocsv cat <<JS
{ "a": -1 }
{ "a": -1000000000 }
{ "a": -10000000000 }
JS

echo '#### Working'
./mlr --ijson --ocsv cat <<JS
{ "a": 1 }
{ "a": -1.0 }
{ "a": -1000000000000 }
{ "a": -10000000000000 }
JS
```

Result:
```
a
-1ºX]
-1000000000X]
-10000000000]
#### Working
a
1
-1.0
-1000000000000
-10000000000000
```

### Fix

I applied the same change as was made for doubles: johnkerl/miller@510a122 to integers:

case JSON_INTEGER:
  if (! (pvalue->u.integer.sval = (json_char *) json_alloc
	     (pstate, (pvalue->u.integer.length + **5**) * sizeof (json_char), 1)) )
  {

And this fixed my problem. But I don't know what I did :)

**Comment by aborruso** [comment]
I know, I'm not very useful for your purpose, but I confirm that I have the right output using the stable release (Miller v5.10.2):

```
a
-1
-1000000000
-10000000000
```

**Comment by johnkerl** [comment]
Oh my @ChCyrill ... very sorry about this! Doubly sad I didn't realize https://github.com/johnkerl/miller/commit/510a122 applies to ints as well :(

Thank you for finding this & finding the fix as well!! :) I'll push this to head right now.

**Comment by johnkerl** [comment]
FIxed on https://github.com/johnkerl/miller/commit/9dae6b84c083aea66d49d8f133bdac5d25dd5d34

> And this fixed my problem. But I don't know what I did :)

@ChCyrill this was a buffer overrun & the fix you found makes the buffer longer

Thanks again! :)
