### ISSUE TITLE
Regex or equivalent?

### ISSUE THREAD

**Issue by gregfr** [johnkerl/miller#72]
Is there are way to use regex or equivalent with Millier?

**Comment by johnkerl** [comment]
There is currently no regex support anywhere. There are lots of places it *could* go ............ can you tell me more about your use case(s)?

**Comment by johnkerl** [comment]
#1 on my list would be `mlr filter $fieldname =~ /regex/`

**Comment by johnkerl** [comment]
Another would be in pair/field/record separators but for my personal use cases this isn't important

**Comment by johnkerl** [comment]
Two others which come to mind:
* `mlr having-fields` with regex match.
* The `sub` function, of course.

**Comment by johnkerl** [comment]
(Side note: there's no `gsub` but there should be.)

**Comment by gregfr** [comment]
Thanks for the multiple answers :)
My use case is parsing zfs output, which have names like "root@postfix", I'd like to list names with something like:
```mlr filter $fieldname == "root*"```
your example is even better:
```mlr filter $fieldname =~ /root.+/```

The next step would be to extract a part:
```mlr filter $fieldname =~ /root(.+)/```
with a new column $1 added.

**Comment by johnkerl** [comment]
OK, great. I've thought for some time this would be a good idea -- but in my personal use-cases it never rose an important enough level to do "today". Your request is enough to convince me it's worth bumping up a bit. :D

**Comment by gregfr** [comment]
Great :D thanks! :+1:

**Comment by johnkerl** [comment]
As of the last few commits ending with https://github.com/johnkerl/miller/commit/6b6234b28e40222d4ce68fc1f7c3e394cefb1e72 there is now support for regexes in `mlr filter`.

You can do `mlr filter --help` for a few simple examples.

Next is support inside `mlr sub`, and a new `mlr gsub`.

Third is `mlr having-fields` which will be straightforward.

Supporting regexes for separators is a mess I don't want to start unless someone really needs it -- due to technical reasons involving peek-ahead, buffering, and memory management. (In particular, regexed IRS makes it impossible to get input a line at a time since there's no bound on what a line-terminating substring is.)

**Comment by johnkerl** [comment]
I'll include this in a 2.3.0 feature release, coming up soon. Regexes alone (in `filter`, `sub`/`gsub`, and `having-fields`) are worthy of a release.

**Comment by johnkerl** [comment]
I went with double-quotes rather than slashes for regexes, e.g. `"^a.*b$"` rather than `/a.*b/`.

**Comment by gregfr** [comment]
Sweet :-D

**Comment by johnkerl** [comment]
`mlr having-fields` now with regex support. `sub`/`gsub` are next, in two steps: first without, then with, captures of the form `\1 \2`. Then lastly all three need a case-insensitive flag. I should be able to do most/all the above this weekend.

**Comment by johnkerl** [comment]
P.S. I think I'll use slashes rather than double-quotes ... it's a bit of a standard, and also looks nice with the case-insensitive flag e.g. `/a.*b/i`.

**Comment by johnkerl** [comment]
Correction: still double-quotes, not slashes. Case-insensitive with `"a.*b"i`.

**Comment by johnkerl** [comment]
Please see http://johnkerl.org/miller/doc/reference.html#Regular_expressions for current status. All the essential pieces are there. The remaining two items are `gsub` (there's currently only `sub`), which is a rather glaring omission, and capture groups. The latter with `\1` etc. of the form `sub($field, "(.*):(.*)\.sometext", "\1@\2")`.

**Comment by johnkerl** [comment]
Note from https://github.com/johnkerl/miller/issues/37:

It will be nice to say something like `mlr put '$*bytes = $*_in_bytes + $*_out_bytes'`
or `mlr cut -x -f '*_in_*,*_out_*'`

**Comment by severach** [comment]
For my use case every file I get has a field name that changes. I'd like to be able to `cut -f 'Name,address,Date_[0-9].*'`

**Comment by johnkerl** [comment]
@severach `mlr cut -r` will do this for you:

```
$ mlr --csvlite cat reg_test/input/date*.csv
Name,Date_201505,Extraneous
Alice,2015-05-14,foo
Bob,2015-05-11,bar
Chuck,2015-05-28,quux
Denise,2015-05-02,meep

Name,Date_201506,Extraneous
Alice,2015-06-23,cafe
Denise,2015-06-17,feed
Chuck,2015-06-19,beef
Bob,2015-06-19,d00d
```

```
$ mlr --csvlite cut -r -f '^Name$,^Date_[0-9].*$' reg_test/input/date*.csv
Name,Date_201505
Alice,2015-05-14
Bob,2015-05-11
Chuck,2015-05-28
Denise,2015-05-02

Name,Date_201506
Alice,2015-06-23
Denise,2015-06-17
Chuck,2015-06-19
Bob,2015-06-19
```

```
$ mlr --icsvlite --opprint cut -r -f '^Name$,^Date_[0-9].*$' reg_test/input/date*.csv
Name   Date_201505
Alice  2015-05-14
Bob    2015-05-11
Chuck  2015-05-28
Denise 2015-05-02

Name   Date_201506
Alice  2015-06-23
Denise 2015-06-17
Chuck  2015-06-19
Bob    2015-06-19
```

This isn't in a release yet (regex support will go into a 2.3.0, real soon now) but you can build from head as at http://johnkerl.org/miller/doc/build.html.

**Comment by johnkerl** [comment]
http://johnkerl.org/miller/doc/reference.html#Regular_expressions

http://johnkerl.org/miller/doc/reference.html#cut

http://johnkerl.org/miller/doc/reference.html#rename

Please let me know what you think.

P.S. @Komosa's `mlr cut -x -r -f '_in_,_out_$'` is implemented. Conceptually I really like his `mlr put '$*bytes = $*_in_bytes + $*_out_bytes'` but matching up the distinct values for the `$*`'s is, I think, an ill-posed problem.

**Comment by johnkerl** [comment]
After this it will be time to cut a 2.3.0 release.

**Comment by aaronwolen** [comment]
This is awesome! :+1:

**Comment by Komosa** [comment]
Sounds great :+1: 

The idea of `put` extension is only loosly realated to `cut` one - I think we can rethink it to be easier (to understand, to use, and to implement). :)

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/releases/tag/v2.3.0 has been released. If there are further issues/requests/clarifications for regexes in Miller, please open a new issue -- thanks!
