### ISSUE TITLE
clean-whitespace verb breaks --quote-original option?

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#734]
Hi,
I have this horrible CSV [file](https://github.com/johnkerl/miller/files/7490095/test_02.csv).

If I run this command on it

```
 mlr --csv --rs crlf --fs ";" --quote-original clean-whitespace test_02.csv >test_02_mlr5.csv
```

in the output I do not have the original quotes of the body of the CSV (in the image below, the input on the left, and the output on the right).

Moreover if I open the output with a spreadsheet, it is not correctly read.

Thank you

![image](https://user-images.githubusercontent.com/30607/140603293-7d261434-78d6-4670-97fc-418e7737e614.png)

**Comment by aborruso** [comment]
Using a CSV GUI reader I have wrong number of rows (also in LibreOffice calc).

I know, this is an horrible CSV file. But if I open the input, I have no problem to open it using a spreadsheet.

![image](https://user-images.githubusercontent.com/30607/140603457-db222735-b3d0-4f71-b5af-12c30f1b7669.png)

**Comment by johnkerl** [comment]
@aborruso can you please attach the `test02.csv`?

**Comment by aborruso** [comment]
> @aborruso can you please attach the `test_02.csv`?

You have it in my message :)

![image](https://user-images.githubusercontent.com/30607/140617501-e2846d73-0db2-49f0-b640-fd6213f2ad94.png)

**Comment by johnkerl** [comment]
oops sorry! :)

**Comment by johnkerl** [comment]
Hmm @aborruso a few things:

* I can't reproduce an error ... can you tell me more about _if I open the output with a spreadsheet, it is not correctly read_ ? Sorry if I'm missing something obvious but I can't tell what's wrong
* For Miller 6 `--quote-original` becomes a no-op; the Go CSV library doesn't give access to original quoting
* Are you seeing the problematic behavior using Miller 5 or 6? I think it's from Miller 5 if I understand correctly ... Miller 6 is nearing release & the old C code is no longer existent in the repo as of https://github.com/johnkerl/miller/pull/731 ... if this is indeed a bug report against Miller 5 let's close it out unless the problem also exists in Miller 6 ...

**Comment by aborruso** [comment]
Hi @johnkerl ,
I have a lot of scripts and all my working computers based on Miller 5; for this reason I still have to use the stable version.

I have some problem with the output of:

```
 mlr --csv --rs crlf --fs ";" --quote-original clean-whitespace test_02.csv >test_02_mlr5.csv
```

If I open the input file using LibreOffice, it opens it properly:

![image](https://user-images.githubusercontent.com/30607/140699212-d4f5c09c-be42-46f8-8976-c38892e07357.png)

If I open the output of the previous command, I have in example misinterpretation of the number of lines, I have one more row, with a misinterpretation of the carriage return:

![image](https://user-images.githubusercontent.com/30607/140699264-1acf3ead-e22e-4e3c-9bb6-f985df8a6f0e.png)


If I use Miller 6, running `mlr --csv --rs crlf --fs ";" cat test_02.csv >test_02_mlr6.csv`, LibreOffice has no problem:

![image](https://user-images.githubusercontent.com/30607/140699563-9a59dd35-67fe-4b69-bd73-2133caa221b7.png)

**Comment by johnkerl** [comment]
BTW @aborruso when I said _if this is indeed a bug report against Miller 5 let's close it out unless the problem also exists in Miller 6 ..._ I didn't mean let's close this -- I meant to have said, let's look for a repro using Miller 6 since only the Go code exists now. I'll try to reproduce what you've shown me.

Thanks!

**Comment by johnkerl** [comment]
... unless @aborruso you're saying the problem is no longer reproducible in Miller 6 in which case let's close ...

**Comment by aborruso** [comment]
> ... unless @aborruso you're saying the problem is no longer reproducible in Miller 6 in which case let's close ...

I had closed the issue for this reason. Sorry if I did something wrong.

Thank you very much
