### ISSUE TITLE
Strange behavior after using fill-empty verb

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#736]
Hi,
I have this input file:

```
a,b,c
1,m,3
2,m,5
2,f,7
3,m,6
3,f,9
4,f,2
4,f,8
```

If I run 

```
mlrgo --csv stats1 -a sum -f c -g a,b then reshape -s b,c_sum then unsparsify then fill-empty -v 0 then put '$t=$m+$f' input.csv
```

I have

| a | m | f | t |
| --- | --- | --- | --- |
| 1 | 3 | 0 | (error) |
| 2 | 5 | 7 | 12 |
| 3 | 6 | 9 | 15 |
| 4 | 0 | 10 | (error) |

But it's strange because if I remove the put verb, I have

| a | m | f |
| --- | --- | --- |
| 1 | 3 | 0 |
| 2 | 5 | 7 |
| 3 | 6 | 9 |
| 4 | 0 | 10 |

Why is it impossible to sum `$m` and `$f`?

I'm using Miller 6.

Thank you

**Comment by johnkerl** [comment]
For these situations I like to use `typeof` (in fact I think I invented `typeof` _in order to_ debug these things) ... :D 

```
$ mlr --c2p stats1 -a sum -f c -g a,b then reshape -s b,c_sum then unsparsify then fill-empty -v 0 then put '$tm=typeof($m); $tf=typeof($f)' input.csv
a m f  tm     tf
1 3 0  int    string
2 5 7  int    int
3 6 9  int    int
4 0 10 string int
```

Now the question becomes, why are`m` and `f` sometimes string-valued?

Well, it turns out `fill-empty` only writes strings. It should probably use type-inference (unless you ask it not to using a `-S` flag, say).

**Comment by johnkerl** [comment]
As of https://github.com/johnkerl/miller/pull/738 now we get by default what you expected:

```
$ mlr --csv stats1 -a sum -f c -g a,b then reshape -s b,c_sum then unsparsify then fill-empty -v 0 then put '$t=$m+$f' input.csv
a,m,f,t
1,3,0,3
2,5,7,12
3,6,9,15
4,0,10,10
```

and we get what you didn't expect only when we ask for it with `-S`:

```
$ mlr --csv stats1 -a sum -f c -g a,b then reshape -s b,c_sum then unsparsify then fill-empty -Sv 0 then put '$t=$m+$f' input.csv
a,m,f,t
1,3,0,(error)
2,5,7,12
3,6,9,15
4,0,10,(error)
```

**Comment by johnkerl** [comment]
@aborruso I think this solves it so I'll go ahead & close this out but if I missed something please reopen -- thank you!!! :D

**Comment by aborruso** [comment]
Really great and useful, thank you!
