### ISSUE TITLE
Problem with fields type inferencing and -O option

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#756]
Hi,
I have this input

```
data,stato,codice_regione
1,ITA,08
2,ITA,08
3,ITA,08
```

If I run `<input_d.csv mlr -O --c2j --no-jvstack cat`, I have

```json
{"data": 1, "stato": "ITA", "codice_regione": 08}
{"data": 2, "stato": "ITA", "codice_regione": 08}
{"data": 3, "stato": "ITA", "codice_regione": 08}
```

Using `-O` option , shouldn't I have `codice_regione` as a string  ( `"codice_regione": "08"`)?

Thank you

**Comment by johnkerl** [comment]
@aborruso we have

```
$ (echo x=07; echo x=08) | mlr -O put '$t = typeof($x)'
x=07,t=string
x=08,t=float
```

which indeed does not feel right. :(

**Comment by aborruso** [comment]
Ok @johnkerl I'm messing with octal numbers.

The question: is there a way to obtain this output (`data` as number and `codice_regione` as string)

```
{"data":1,"stato":"ITA","codice_regione":"08"}
{"data":2,"stato":"ITA","codice_regione":"08"}
{"data":3,"stato":"ITA","codice_regione":"08"}
```

and not

```
{"data":1,"stato":"ITA","codice_regione":8}
{"data":2,"stato":"ITA","codice_regione":8}
{"data":3,"stato":"ITA","codice_regione":8}
```

If I use `-S`, everything becomes text, also `data`.

Couldn't you add a special flag, which applies the string type to fields that match `^[0-9]{2}[0.9]*$`?

Thanks and if I write nonsense, please close the issue

**Comment by johnkerl** [comment]
> Couldn't you add a special flag

This is what `mlr -O` should be doing -- and will do. Sorry for the delay, but this is precisely how `-O` should be functioning. :)

**Comment by aborruso** [comment]
> This is what `mlr -O` should be doing -- and will do. Sorry for the delay, but this is precisely how `-O` should be functioning. :)

Please @johnkerl could you make a test, using this CSV input?

```
data,stato,codice_regione
1,ITA,08
2,ITA,08
3,ITA,08
```

As I wrote you above, if I run `mlr --c2j -O cat input.csv` I have 

```json
{
  "data": 1,
  "stato": "ITA",
  "codice_regione": 08
}
{
  "data": 2,
  "stato": "ITA",
  "codice_regione": 08
}
{
  "data": 3,
  "stato": "ITA",
  "codice_regione": 08
}
```

Am I wrong or it seems that it is not working?

**Comment by johnkerl** [comment]
@aborruso you are entirely right, and I will make it a test.

**Comment by johnkerl** [comment]
(The only reason for the delay is I'm prioritizing some performance-tuning at present -- but I will return to this important issue and close it out before the Miller 6 release.)

**Comment by johnkerl** [comment]
@aborruso fixed in https://github.com/johnkerl/miller/pull/766

```
$ <input_d.csv mlr -O --c2j --no-jvstack cat
{"data": 1, "stato": "ITA", "codice_regione": "08"}
{"data": 2, "stato": "ITA", "codice_regione": "08"}
{"data": 3, "stato": "ITA", "codice_regione": "08"}
```

**Comment by aborruso** [comment]
Thank you @johnkerl my csv now works.

What about the "0.01" output here?

```
echo "a=0.01,b=01\na=2,b=02" | mlrgo -O --ojson --no-jvstack cat

{"a": "0.01", "b": "01"}
{"a": 2, "b": "02"}
```

I think it should be simply `"a": 0.01`.

Thank you

**Comment by johnkerl** [comment]
Wow @aborruso my apologies. It's taking me several tries to get this right; thank you for staying on this.

https://github.com/johnkerl/miller/pull/767

**Comment by aborruso** [comment]
> Wow @aborruso my apologies. It's taking me several tries to get this right; thank you for staying on this.

I stay on this because a l never have data with octal numbers, and I have everyday country codes, city codes, than here in Italy often are in this kind of form `0[0-9]+`.

**Comment by aborruso** [comment]
> I stay on this because a l never have data with octal numbers, and I have everyday country codes, city codes, than here in Italy often are in this kind of form `0[0-9]+`.

I in fact I would like the option in reverse 🤣: `-O` when you want manage that kind of fields as octal numbers and by default strings.

**Comment by johnkerl** [comment]
Hmm ... @aborruso that's probably a good idea. I had not thought of it that way. 🤔 

This would actually be a backward incompatibility with Miller 5, but, the reason for a major version-bump such as 5 to 6 is to introduce backward-incompatibilities.

**Comment by johnkerl** [comment]
@aborruso what really seals it for me is that `003` is _not_ valid JSON ... combined with the fact that leading-0 octal notation is really quite dated, better-off-left-in-previous-decades syntax at this point in time.

```
$ echo '{"x":3}' | mlr --j2x cat
x 3
$ echo '{"x":03}' | mlr --j2x cat
mlr :  invalid character '3' after object key:value pair
```

Leading-0 octal notation is not valid JSON. Note however that `jq` does tolerate it:

```
$ echo '{"x":3}' | jq .
{
  "x": 3
}
$ echo '{"x":03}' | jq .
{
  "x": 3
}
```

So in conclusion I think we should do what you say. Namely:

* Leading-zero ints should be treated as strings unless `mlr -O` in which case they will be parsed as octal
* Without `mlr -O`: `x=0377` results in `$x` being `"0377"`
* With `mlr -O`: `x=0377` in goes to `x=0377` on output (format-preserving) but `$y=$x+1` gives `y=256`

**Comment by aborruso** [comment]
> So in conclusion I think we should do what you say. Namely:

I'm very happy and a little proud of it. I like your proposal.

Do I must close the issue?

**Comment by johnkerl** [comment]
@aborruso let's leave it open until I merge the code change.

**Comment by johnkerl** [comment]
@aborruso https://github.com/johnkerl/miller/pull/788 -- sorry about the long delay! :)

**Comment by aborruso** [comment]
hi @johnkerl , if I run

```
(echo x=07; echo x=08) | mlrgo -O put '$t = typeof($x)'
```

I have 

```
x=07,t=int
x=08,t=int
```

Is it ok? I'm thinking about [this](https://github.com/johnkerl/miller/pull/788).

**Comment by aborruso** [comment]
@johnkerl I don't want to rush you, just add a reminder about this. A thousand thanks

**Comment by aborruso** [comment]
@johnkerl  Periodically, I remind you of this.
Excuse me if I do, but it seems important to me.

A thousand thanks

**Comment by aborruso** [comment]
I think I can close this.

All seems to work
