### ISSUE TITLE
Build mlr 6.0

### ISSUE THREAD

**Issue by spmundi** [johnkerl/miller#768]
Not sure whether this is a bug, or my imperfect understanding
of how to build 6.0
Miller now seems to be coded in go. Is that right?
There still seems to be a configure script.
When I run it I get an immediate error:
**sed: illegal option -- I**
If instead I just invoke **make**
I get
**go build github.com/johnkerl/miller/cmd/mlr**
then nothing else happens.

I don't find any version of sed which has a -I option (ie not GNU sed).

Could someone enlighten me?

Thanks

**Comment by johnkerl** [comment]
@spmundi my apologies! I do have a `sed -I` (macos & ubuntu) but this is clearly not portable. I'll modify it to not need `-I`.

as for _then nothing else happens_ -- go compiles are _very_ fast. can you check `ls -lrt` and see if `mlr` is there?

also, what's your OS?

**Comment by johnkerl** [comment]
also i'll update https://miller.readthedocs.io/en/latest/build/ with what we find out here

**Comment by johnkerl** [comment]
P.S.

>  There still seems to be a configure script.

Yes, this is only for install path -- some packaging tools need this.

**Comment by johnkerl** [comment]
@spmundi thanks for the feedback -- https://github.com/johnkerl/miller/pull/773 incorporates discussion on this issue so far :)

**Comment by johnkerl** [comment]
@spmundi closing this out in light of above doc-mods, unless there are unresolveds -- please feel free to re-open if I've missed something! :)
