### ISSUE TITLE
RFC 4180  and double quotes

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#780]
Hi,
in RFC 4180 we have

>If double-quotes are used to enclose fields, then a double-quote
>appearing inside a field must be escaped by preceding it with
>another double quote.  For example:
>
>       "aaa","b""bb","ccc"

I have this CSV input, in which double-quotes are NOT used to enclose fields:

```
a|b|c
Lorem|UNIONE COMUNI" MADONIE"|Ipsum
```

If I run `mlr --ifs "|" --csv cat input.csv` I have

```
mlr: syntax error: unwrapped double quote at line 1.
```

Is it correct to have this error? Is it not RFC 4180 compatible?
No problem if it stays that way, it's just to know if I understand correctly.

Thank you

**Comment by johnkerl** [comment]
> Is it not RFC 4180 compatible?

Correct

This is one of several reasons for CSV-lite format.

Also, this has always been this way (since RFC-4180 CSV in Miller 2 anyway)

```
$ mlr5 --icsv --ojson cat input.csv
mlr5: syntax error: unwrapped double quote at line 1.

$ mlr5 --icsvlite --ojson cat input.csv
{ "a|b|c": "Lorem|UNIONE COMUNI\" MADONIE\"|Ipsum" }

$ mlr --icsv --ojson cat input.csv
mlr :  parse error on line 2, column 20: bare " in non-quoted-field

$ mlr --icsvlite --ojson cat input.csv
{
  "a|b|c": "Lorem|UNIONE COMUNI\" MADONIE\"|Ipsum"
}
```

**Comment by johnkerl** [comment]
@aborruso I think this is resolved -- ? If not please re-open & we can go from there -- thanks! :)

**Comment by aborruso** [comment]
@ilovefreesw the problem I think is in your input file. You have spaces outside the double quotes.

If you remove these spaces, you have no error (here the [diff](https://gist.github.com/aborruso/1c3a1a57880ecc1735cde67ebc92bad2/revisions))

```
"LatD","LatM","LatS","NS","LonD","LonM","LonS","EW","City","State"
   41,    5,   59,"N",     80,   39,    0,"W","Youngstown", OH
   42,   52,   48,"N",     97,   23,   23,"W","Yankton", SD
   46,   35,   59,"N",    120,   30,   36,"W","Yakima", WA
   42,   16,   12,"N",     71,   48,    0,"W","Worcester", MA
   43,   37,   48,"N",     89,   46,   11,"W","Wisconsin Dells", WI
```

**Comment by ilovefreesw** [comment]
@aborruso Yes, you are right. I just downloaded this sample file from here: https://people.sc.fsu.edu/~jburkardt/data/csv/csv.html

Thanks.

**Comment by johnkerl** [comment]
@aborruso @ilovefreesw It's correct for Miller to not handle these _as long as_ it's being RFC-compliant (although perhaps the error message could be more clear.)

The more general issue though is that all sorts of CSV are non-compliant -- including this download from https://people.sc.fsu.edu/~jburkardt/data/csv/csv.html -- and a direction I have not taken (yet, anyway) with Miller is having it manage more and more variants of non-compliant CSV ...

Miller's strict adherence to RFC4180 makes it less useful for various kinds of less-clean CSVs out there in the world ... :^/

**Comment by aborruso** [comment]
> Miller's strict adherence to RFC4180 makes it less useful for various kinds of less-clean CSVs out there in the world ... :^/

I think it's very important the Miller strict adherence to RFC4180. For me it's a great tool to inspect and correct weird data

**Comment by johnkerl** [comment]
> For me it's a great tool to inspect and correct weird data

Absolutely agree, and that was the intent. Glad to hear it works for you too. See also https://github.com/johnkerl/miller/issues/4 which had some really, really great discussion -- and I was guided by the advice there in making [Miller 2.0.0](https://github.com/johnkerl/miller/releases/tag/v2.0.0) which was devoted to RFC-compliant CSV.

However ... sometimes I think that while the _default_ should definitely still be RFC-compliant, having some off-by-default, opt-in mode to detect -- and fix! -- non-compliant CSV might also be of value ...

**Comment by aborruso** [comment]
> However ... sometimes I think that while the _default_ should definitely still be RFC-compliant, having some off-by-default, opt-in mode to detect -- and fix! -- non-compliant CSV might also be of value ...

I agree. 

Another tool I love to check CSV, is the CLI of the frictionless project: https://framework.frictionlessdata.io/docs/tutorials/working-with-cli/
