### ISSUE TITLE
How to filter by value of JSON nested field?

### ISSUE THREAD

**Issue by dandrei** [johnkerl/miller#782]
Hello, let's say the user has data that looks like this:
    
    {id: 1, name: {first: "John", last: "McClane"}}

How could they use `mlr` to filter by one of the nested fields, e.g. by first name?

What I tried so far:

    mlr --json filter '$name.$first == "John"'
    mlr --json filter '$name.first == "John"'
    mlr --json filter '$name->$first == "John"'
    mlr --json filter '$name->first == "John"'
    mlr --json filter '$name["first"] == "John"'

I'm sure there's something obvious I'm missing, but I couldn't track it down. Thanks!

**Comment by aborruso** [comment]
In example if you have

```
{"id": 1, "name": {"first": "John", "last": "McClane"}}
{"id": 2, "name": {"first": "Marc", "last": "McClane"}}
```

you can run `mlrgo --json filter '$name.first=="Marc"' input.json` to have

```json
{
  "id": 2,
  "name": {
    "first": "Marc",
    "last": "McClane"
  }
}
```

**Comment by johnkerl** [comment]
@aborruso @dandrei 

```
$ cat input.json
{"id": 1, "name": {"first": "John", "last": "McClane"}}
{"id": 2, "name": {"first": "Fred", "last}": "Flintstone"}}
```

```
$ mlr --json filter '$name.first == "John"' input.json
{
  "id": 1,
  "name": {
    "first": "John",
    "last": "McClane"
  }
}
```

```
$ mlr --json filter '$name["first"] == "John"' input.json
{
  "id": 1,
  "name": {
    "first": "John",
    "last": "McClane"
  }
}
```

So (as of Miller 6) you can use `$name.first` in addition to `$name["first"]`.

Also note the keys need to be strings like `"id":1`,  not `id: 1` -- JS tools may produce the latter (e.g. on `console.log`) but we need string (double-quoted) keys to have valid JSON.

**Comment by johnkerl** [comment]
@dandrei I think this is resolved -- please let me know if I'm mistaken and we can re-open -- thanks!!
