### ISSUE TITLE
How to reference field names by index

### ISSUE THREAD

**Issue by chris-herring** [johnkerl/miller#785]
I have a csv that has duplicate column names. It doesn't appear Miller handles that so can I work around this by referencing column names by index? 

e.g.
instead of 
`.\mlr --csv cut -o -f City,Address test.csv`
something like:
`.\mlr --csv cut -o -f 3,1 test.csv`

**Comment by johnkerl** [comment]
> I have a csv that has duplicate column names

@chris-herring it seems like lots of people have such files -- in hindsight Miller should probably have supported this sooner.

This is tracked in https://github.com/johnkerl/miller/issues/225.

And, @aborruso 's notes about using `-N` etc are (I hope) useful workarounds in the meantime.

**Comment by chris-herring** [comment]
@aborruso  Thanks, that works for me,.

@johnkerl it can be hard to cover everything. I also tried xsv which handles duplicate columns like this `xsv select City,City[1] input.csv` however they dont appear to handle commas in the header.

**Comment by johnkerl** [comment]
No worries @chris-herring ! :)

And https://github.com/johnkerl/miller/issues/225 isn't back-burnered -- this has come up often enough recently that I think I'll do it quite soon.

Thank you! :)

**Comment by johnkerl** [comment]
@chris-herring https://github.com/johnkerl/miller/pull/794

**Comment by chris-herring** [comment]
Awesome, nice work.
