### ISSUE TITLE
configure uses "sed -I"

### ISSUE THREAD

**Issue by Andy1978** [johnkerl/miller#796]
Cset e2b6ec2391 introduced the usage of the parameter "-I" (it's a big i) for sed which looks like a BSD extension which is available for example on MacOSX and FreeBSD but not on GNU/Linux.

**Comment by johnkerl** [comment]
Thanks @Andy1978 !! Someone else pointed this out recently & I was sure I had fixed it; must have lost the fix on a bad merge. Let me take a look & put the fix back in.

**Comment by johnkerl** [comment]
Derp; must have been an uncommitted mod on a Linux host. Anyway thanks for the reminder!! :)

https://github.com/johnkerl/miller/pull/800 is merged :)
