### ISSUE TITLE
test fails with miller 6.0 with guix

### ISSUE THREAD

**Issue by vapniks** [johnkerl/miller#798]
I tried building the latest miller (c43a7109d16cdbe24d682d3fa0172c6b4e01d877) on Ubuntu 18.04 with go version 1.17 (installed with guix), and when I run `make check` I get:
```
...
NUMBER OF CASES            PASSED 1886
NUMBER OF CASES            FAILED 2403
NUMBER OF CASE-DIRECTORIES PASSED 49
NUMBER OF CASE-DIRECTORIES FAILED 195

FAIL overall
    regression_test.go:70: 
--- FAIL: TestRegression (41.89s)
FAIL
FAIL	command-line-arguments	41.892s
FAIL
Makefile:42: recipe for target 'regression-test' failed
make: *** [regression-test] Error 1
```
(the full output is 1753 lines, which I could send you if you want)

**Comment by johnkerl** [comment]
Thanks @vapniks -- please do send it! Or at least the first few hundred lines -- I imagine there is some common cause for all these failures on your system. (They run on every commit so something must be strange here.)

**Comment by vapniks** [comment]
I've attached the output to this email




On Saturday, December 25, 2021, 04:48:46 AM GMT, John Kerl ***@***.***> wrote: 







Thanks @vapniks -- please do send it! Or at least the first few hundred lines -- I imagine there is some common cause for all these failures on your system. (They run on every commit so something must be strange here.)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by johnkerl** [comment]
Sorry @vapniks but I don't see any email in my inbox, nor my spam folder; & I don't see any attachment here in GitHub Issues ...

**Comment by johnkerl** [comment]
Also, most useful output would be from `mlr regtest -s 100`

**Comment by vapniks** [comment]
OK, I thought sending the attachment in a reply to the github notification email would work, but obviously it didn't. Here's a link to a gist of the output from `mlr regtest -s 100` https://gist.github.com/vapniks/77b22cb68566820ce310bc81ef46c9b3

**Comment by johnkerl** [comment]
Hi @vapniks -- I was able to reproduce the same behavior by making a `.mlrrc` file with `--csv` in it.

https://github.com/johnkerl/miller/pull/808 is better handling for existence of `.mlrrc` files -- already I was doing unset of `$MLRRC` in the parent process before forking the unit-under-test process. But there's another step I should have taken which https://github.com/johnkerl/miller/pull/808 takes.

**Comment by johnkerl** [comment]
Closing based on feedback in https://github.com/johnkerl/miller/pull/808
