### ISSUE TITLE
build error (Ubuntu 15.04)

### ISSUE THREAD

**Issue by nichtich** [johnkerl/miller#8]
Using gcc 4.9.2 I get a build error with the current code (7aead02 2015-08-16):

~~~
$ make
make -C c top
make[1]: Entering directory '/home/voj/proj/miller/c'
ctags -R .
make -C dsls put_dsl_parse.o
make[2]: Entering directory '/home/voj/proj/miller/c/dsls'
make[2]: 'put_dsl_parse.o' is up to date.
make[2]: Leaving directory '/home/voj/proj/miller/c/dsls'
make -C dsls put_dsl_lexer.o
make[2]: Entering directory '/home/voj/proj/miller/c/dsls'
flex --prefix=put_dsl_lexer_ --outfile=put_dsl_lexer.c --header-file=put_dsl_lexer.h put_dsl_lexer.l
gcc -I.. -O3 -c -std=gnu99 put_dsl_lexer.c
make[2]: Leaving directory '/home/voj/proj/miller/c/dsls'
make -C dsls put_dsl_wrapper.o
make[2]: Entering directory '/home/voj/proj/miller/c/dsls'
gcc -Wall -I.. -O3 -c -std=gnu99 put_dsl_wrapper.c
put_dsl_wrapper.c: In function ‘put_dsl_parse_inner’:
put_dsl_wrapper.c:24:3: warning: implicit declaration of function ‘put_dsl_lemon_parser_parse_token’ [-Wimplicit-function-declaration]
   parse_code = put_dsl_lemon_parser_parse_token(pvparser, lex_code, plexed_node, pasts);
   ^
~~~

I'd enable continuous builds, e.g. at travis-ci to ensure that each commit at least compiles at a given environment. Right now I don't now if it's the error results from the commit or the build environment.

**Comment by johnkerl** [comment]
I should tell you:  I use manual CI (see also http://johnkerl.org/miller/doc/build.html) -- all unit/regression tests run on each build. So the error isn't from the commit -- I wouldn't have pushed it. (Travis-ci is a great idea which I'll pursue -- it'll automate what I'm already doing manually. This is tracked in https://github.com/johnkerl/miller/issues/15.)

**Comment by johnkerl** [comment]
The Miller code per se, I crank up the warning level. The Lemon code, including the autogen stuff, doesn't compile as cleanly. Looks like a missing prototype; I'll check it out.

**Comment by johnkerl** [comment]
Turns out I get a warning there too (I use -Werror in my own code, but not in the stuff in `dsls/` which is mostly Lemon or its autogens). It's just not fatal for me. Is it for you?

Entirely cleaning up Lemon compile warnings is on my back-burner to-do list. For now, I don't want fatal-on-warnings in the `dsls/` directory.

**Comment by johnkerl** [comment]
Sounds like it's resolved, but, please feel free to re-open if I'm mistaken. Thanks for the report!
