### ISSUE TITLE
emit statement not working as expected in mlr 6.0

### ISSUE THREAD

**Issue by vapniks** [johnkerl/miller#827]
This works fine with miller 5.3.0:
```
mlr -n put 'end {@in={"a":1}; emit @in["a"]}'
```
but gives the following error with the latest miller 6.0.0-rc (0b712981022c1413165082ff403917b286c168a7):
```
mlr: cannot parse DSL expression.
Parse error on token "[" at line 1 columnn 27.
Please check for missing semicolon.
Expected one of:
  ; } ,
```

**Comment by johnkerl** [comment]
Hi @vapniks --

Bit of a story here.

`emit` goes way back early on in Miller, even before there were control structures like `for` loops. I put (in hindsight) too much syntactic complexity into `emit`, which wouldn't have been necessary if there had been other things like `for` loops.

The grammar is more complex in Miller 6, and I'm using a different parser-generator, without shift-reduce-conflict hacks in my use of it (I hope I'm not over-jargoning). Allowing `emit` of indexed things is no longer possible in the grammar without either introducing shift-reduce conflicts (i.e. a parser-generator cannot be built for the grammar), or perhaps introducing new `emit` syntax.

What I think is the best (or perhaps least-bad) course is to more clearly document at
https://miller.readthedocs.io/en/latest/reference-dsl-output-statements/#emit1-and-emitemitpemitf
that we can't emit indexed oosvars now, and to document a suggested replacement of the form

```
$ mlr -n put 'end {@in={"a":1}; @ina = @in["a"]; emit @ina}'
ina=1
```

at https://miller.readthedocs.io/en/latest/new-in-miller-6/

What do you think?

**Comment by johnkerl** [comment]
@vapniks updated advice:

```
$ mlr5 -n put 'end {@in={"a":1}; emit @in["a"]}'
in=1

$ mlr -n put 'end {@in={"a":1}; emit1 {"in":@in["a"]}}'
in=1
```

**Comment by johnkerl** [comment]
@vapniks

* https://github.com/johnkerl/miller/pull/849
* https://miller.readthedocs.io/en/latest/new-in-miller-6/#emit-statements
* https://miller.readthedocs.io/en/latest/reference-dsl-output-statements/#emit1-and-emitemitpemitf

**Comment by vapniks** [comment]
Yes, sounds OK to me. However the example you give for mlr5 also works with mlr 6:
```
$ mlr -n put 'end {@in={"a":1}; emit {"in":@in["a"]}}'
in
1
```
Maybe also include this example which works with mlr5 but not mlr 6:
```
$ mlr -n put 'end {@input={"a":1}; emit @input["a"]}' 
mlr: cannot parse DSL expression.
Parse error on token "[" at line 1 columnn 27.
Please check for missing semicolon.
Expected one of:
  ; } ,
```

Btw, there's a typo in the above output: it should be "column" not "columnn". 
I also noticed a couple of minor typos in the documentation:
about half way down this page: https://miller.readthedocs.io/en/latest/cpu/ the `rename` bullet point should be `put`, and in the notes at the bottom of this page https://miller.readthedocs.io/en/latest/new-in-miller-6/#emit-statements it should be "did better than Miller 6 but only on Linux" rather than "did better than Miller 5 but only on Linux".

**Comment by johnkerl** [comment]
Sorry @vapniks I wasn't clear

```
mlr -n put 'end {@in={"a":1}; emit @in["a"]}' 
```

This works in Miller 5 but not Miller 6, and it won't. I'll make it clear that this syntax is no longer supported.

```
$ mlr -n put 'end {@in={"a":1}; emit {"in":@in["a"]}}'
```

Yes, this works in Miller 5 & 6. I'll make it clear that this is the suggested workaround for the previous.

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/pull/858

Thanks again @vapniks ! :)
