### ISSUE TITLE
Create null fields on join

### ISSUE THREAD

**Issue by spmundi** [johnkerl/miller#840]
I am using mlr 5.10.2 under cygwin on windows10 64 bit..

I want to **join** two **.csv** files, using a left join (**--ul** option), and if the join field(s) is(are) absent from the joinee.
eg   **mlr --csv join --ul -j keyfield -f leftfile rightfile**
I want the fields in the resultant homogeneous **.csv** to be **null** (ie two consecutive commas for all missing fields).
I cannot find a way to do this. Instead I get an output **.csv** with multiple sections, each section have different numbers of fields depending on which fields in the joinee were missing. I thought **--ragged** addressed this issue, but it does not.

Is this a feature, bug, or am I doing something wrong?

PS. How do I mark this issue as a queestion? or is only the administrator allowed this option?

**Comment by johnkerl** [comment]
Re join per se: looking, thanks! :)

Re marking as question: as far as I know issues are issues & marking as question would work at https://github.com/johnkerl/miller/discussions -- if I'm missing some configs for issues per se I'd love to fix them but I'm not aware of any such ...

**Comment by johnkerl** [comment]
Oh wait you mean labels!!! [headdesk].

Yikes, yes, let me look & see if I have to do something to let you apply tags.

Thanks for letting me know!! :)

**Comment by johnkerl** [comment]
... oh, nuts, this isn't great :(

https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels

> Anyone with write access to a repository can create a label.

> Anyone with triage access to a repository can apply and dismiss labels.

This is unfortunate -- I would want anyone to be able to apply a label to their own issues but GitHub has apparently designed labels as a repo-management feature not a repo-contribuion feature. :(

FWIW, I'm happy to apply labels though -- no problem at all. Small consolation perhaps ... :^/

**Comment by aborruso** [comment]
> eg **mlr --csv join --ul -j keyfield -f leftfile rightfile**
> I want the fields in the resultant homogeneous **.csv** to be **null** (ie two consecutive commas for all missing fields).
> I cannot find a way to do this. Instead I get an output **.csv** with multiple sections, each section have different numbers of fields depending on which fields in the joinee were missing. I thought **--ragged** addressed this issue, but it does not.

For the [Record-heterogeneity](https://miller.readthedocs.io/en/latest/record-heterogeneity/), you must add `unsparsify` verb:

```
mlr --csv join --ul -j keyfield -f leftfile then unsparsify rightfile
```

Here more details https://miller.readthedocs.io/en/latest/questions-about-joins/#how-to-rectangularize-after-joins-with-unpaired

**Comment by johnkerl** [comment]
@spmundi @aborruso closing this -- @aborruso 's `unsparsify` is indeed a solution, I believe, and https://github.com/johnkerl/miller/issues/275 tracks the idea of making this the default behavior for CSV files.

**Comment by aborruso** [comment]
> I believe, and #275 tracks the idea of making this the default behavior for CSV files

Yes, in my opinion is not only an idea: a CSV not "unsparsified" is not a CSV. 
For this reason it should be the default or perhaps the only way for a CSV. 

Thank you
