### ISSUE TITLE
Does it work the "-o" flag in top verb?

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#861]
I have the below CSV. If run 

```
mlr --csv --implicit-csv-header top -f 5 -a -o "test" -F -n 2 -g 1 input.tsv
```

I do not have any output related to `-o` flag. I probably didn't understand what it is for.

Thank you

```
1,861265,C,A,0.071
1,861265,C,A,0.148
1,861265,C,G,0.001
1,861265,C,G,0.108
1,861265,C,T,0
1,861265,C,T,0.216
2,193456,G,A,0.006
2,193456,G,A,0.094
2,193456,G,C,0.011
2,193456,G,C,0.152
2,193456,G,T,0.003
2,193456,G,T,0.056
```

**Comment by johnkerl** [comment]
Hi @aborruso -- 

There is no extra output field with `-a`.

```
$ mlr --csv --implicit-csv-header top -a -f 5 -o "test" -F -n 2 -g 1 input.tsv
1,2,3,4,5
1,861265,C,T,0.216
1,861265,C,A,0.148
2,193456,G,C,0.152
2,193456,G,A,0.094

$ mlr --csv --implicit-csv-header top -f 5 -F -n 2 -g 1 input.tsv
1,top_idx,5_top
1,1,0.216
1,2,0.148
2,1,0.152
2,2,0.094

$ mlr --csv --implicit-csv-header top -f 5 -o "test" -F -n 2 -g 1 input.tsv
1,test,5_top
1,1,0.216
1,2,0.148
2,1,0.152
2,2,0.094
```

I'll update the online help & docs for `mlr top` -- thank you! :)

**Comment by aborruso** [comment]
> There is no extra output field with `-a`.

Ok, thank you. 

`-o` is to set "Field name for output indices". What is this index? How does Miller calculate it?

**Comment by aborruso** [comment]
> `-o` is to set "Field name for output indices". What is this index? How does Miller calculate it?

I think I understand, I'm dumb: it's the numeric index within the group

**Comment by johnkerl** [comment]
@aborruso :) -- you know Miller well and the on-line help confused you -- so it _definitely_ needs to be clearer :)

**Comment by johnkerl** [comment]
@aborruso what do you think of https://github.com/johnkerl/miller/pull/875 and in particular https://miller.readthedocs.io/en/latest/reference-verbs#top (be sure to reload the page) ?

**Comment by aborruso** [comment]
> @aborruso what do you think of #875 and in particular https://miller.readthedocs.io/en/latest/reference-verbs#top (be sure to reload the page) ?

It's ok, thank you very much
