### ISSUE TITLE
test_peek_file_reader fails on a number of platforms

### ISSUE THREAD

**Issue by skitt** [johnkerl/miller#87]
See https://buildd.debian.org/status/package.php?p=miller for details; the test fails at line 23 in test_peek_file_reader.c

    mu_assert_lf(pfr_peek_char(pfr) == EOF);

If you need help figuring out what's different feel free to ask!

**Comment by johnkerl** [comment]
Thanks!! :)

**Comment by johnkerl** [comment]
This is fantastic -- this gets Miller building on far more platforms than I've ever had access to.

My guess is this is a simple sign-extension issue, but, what's the mechanism for iterating here?

**Comment by johnkerl** [comment]
Looks like you're building from my latest release; will you temporarily pull from head, or ... ?

**Comment by skitt** [comment]
I have access to "porterboxes" for each architecture, so I can test candidate fixes manually there. (You _might_ be able to get access too, see https://dsa.debian.org/doc/guest-account/ for details.) You could also get access to an ARM64 box via https://gcc.gnu.org/wiki/CompileFarm to test fixes directly.

We generally don't use the full buildd network to iterate on fixes ;-).

**Comment by skitt** [comment]
Control: forwarded -1 https://github.com/johnkerl/miller/issues/87

Hi Edmund,

On Fri, 20 Nov 2015 10:51:26 +0000, Edmund Grimley Evans
<edmund.grimley.evans@gmail.com> wrote:
> It failed to build on many architectures:
> 
> http://buildd.debian.org/status/package.php?p=miller&suite=sid
> 
> In some cases the error was:
> 
> FAIL: test_peek_file_reader
> 
> I noticed this line of code in there:
> 
>         mu_assert_lf(pfr_peek_char(pfr) == EOF);
> 
> But pfr_peek_char is declared to return char. If you want that and
> other functions to return EOF as a special value then they must be
> declared to return int, like getchar or fgetc, which "reads the next
> character from stream and returns it as an unsigned char cast to an
> int, or EOF on end of file or error".
> 
> EOF is negative. On some architectures plain char is unsigned.

Thanks for the investigation, I'm forwarding this to the corresponding
upstream issue.

Regards,

Stephen

**Comment by skitt** [comment]
(The previous message is from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=805621).

**Comment by johnkerl** [comment]
OK this is fixed in the latest Miller release: https://github.com/johnkerl/miller/tree/v3.0.1

I'm confident that this code change (https://github.com/johnkerl/miller/commit/353a903646799f2eef373b401cbb604a4b86e9fb) fixes the reported issue, but I'm not 100% sure there won't be additional issues -- this being the first time Miller has been compiled on all these platforms.

I can create a guest-account application, but, at this point I think the quickest way to resolve the current issue is to test Miller 3.0.1 on a porterbox. If there are no additional issues, and the EOF-sign issue was isolated, we should be quickly good to go. If there are others, though, I can deep-dive before troubling you further.

@skitt will that work for you?

**Comment by skitt** [comment]
Thanks for this, that change should indeed fix the issue mentioned in the analysis of https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=805621. There are other issues though, the builds are failing with 3.0.1 too (https://buildd.debian.org/status/package.php?p=miller has the details).

I don't mind running ad-hoc code on a porterbox to figure this out; feel free to send me code to test!

**Comment by skitt** [comment]
Actually test_peek_file_reader is OK on all platforms now, it's test_byte_readers which is failing now. So this bug is fixed, thanks!

**Comment by johnkerl** [comment]
OK thank you.

https://github.com/johnkerl/miller/commit/353a903646799f2eef373b401cbb604a4b86e9fb was indeed over-eager. https://github.com/johnkerl/miller/commit/2db68cc29915e46b7b50c648191c440c3a67c9c7 keeps the change only where it's needed.

**Comment by egrimley** [comment]
In https://github.com/johnkerl/miller/blob/master/c/input/lrec_reader_csv.c#L202 you have:

if (pfr_peek_char(pfr) == (char)EOF)

Are you sure that you'll never want to distinguish '\xff' from EOF in this context?

(I wonder if there are a lot of programs that incorrectly sometimes treat '\xff' as EOF.)

**Comment by johnkerl** [comment]
Actually yes I am sure. UTF-8 explicitly disallows 0xff. Thanks for checking!!
