### ISSUE TITLE
Implement "natural" sort order in Miller verb & DSL function

### ISSUE THREAD

**Issue by johnkerl** [johnkerl/miller#874]
_From https://github.com/johnkerl/miller/discussions/872#discussioncomment-1979566 :_

@aborruso if I understand correctly there are two separate questions here.

# First issue

The first is how to sort within a field -- https://miller.readthedocs.io/en/latest/sorting/#custom-sorting-of-arrays-within-records is indeed the right place -- perhaps it could be more clear. The examples there I showed were multi-line, but you could also do this on one line like this:

```
$ cat input.csv
a,b
1,"1,12B,12,12A,3"
2,"1,2,10,1A"
```

```
$ mlr --csv --from input.csv put '$b=joinv(sort(splita($b, ",")),",")'
a,b
1,"1,3,12,12A,12B"
2,"1,2,10,1A"
```

That is, I think, much simpler than `nest` with `explode` and `implode`. Note that this uses Miller's default sorting rule which is (among other things) numbers before strings. https://miller.readthedocs.io/en/latest/sorting/#custom-sorting-of-arrays-within-records could be more clear about this rule.

# Second issue

The second issue is how to specify the rule by which Miller does its sorting. To be honest, I'm embarrassed to admit that this is the first I've heard of "natural sort order" -- I had to google it just now. Miller absolutely does not (yet) do this. However, now that I know about it, I like it very much and it should be Miller's default. It looks like there are good resources for this & it should be pretty quick to code up.

Thanks for teaching me about this! :)

**Comment by aborruso** [comment]
> _From [#872 (comment)](https://github.com/johnkerl/miller/discussions/872#discussioncomment-1979566) :_
> 
> @aborruso if I understand correctly there are two separate questions here.
> 
> # First issue
> The first is how to sort within a field -- https://miller.readthedocs.io/en/latest/sorting/#custom-sorting-of-arrays-within-records is indeed the right place -- perhaps it could be more clear. The examples there I showed were multi-line, but you could also do this on one line like this:
> 
> ```
> $ cat input.csv
> a,b
> 1,"1,12B,12,12A,3"
> 2,"1,2,10,1A"
> ```
> 
> ```
> $ mlr --csv --from input.csv put '$b=joinv(sort(splita($b, ",")),",")'
> a,b
> 1,"1,3,12,12A,12B"
> 2,"1,2,10,1A"
> ```
> 
> That is, I think, much simpler than `nest` with `explode` and `implode`. Note that this uses Miller's default sorting rule which is (among other things) numbers before strings. https://miller.readthedocs.io/en/latest/sorting/#custom-sorting-of-arrays-within-records could be more clear about this rule.

It's much simpler than `nest` with `explode` and `implode`, but I do in this way to be able to sort differently numbers and text: first I explode, then split in two columns numbers and text, then I apply the sorting and then I implode it again.
Because I do not want this order `1,2,10,1A`, but this one `1,1A,2,10` (`1A` must be the second).

> 
> # Second issue
> The second issue is how to specify the rule by which Miller does its sorting. To be honest, I'm embarrassed to admit that this is the first I've heard of "natural sort order" -- I had to google it just now. Miller absolutely does not (yet) do this. However, now that I know about it, I like it very much and it should be Miller's default. It looks like there are good resources for this & it should be pretty quick to code up.
> 
> Thanks for teaching me about this! :)

I'm adding two useful URLs:

- https://www.gnu.org/software/coreutils/manual/coreutils.html#Version-sort-ordering (search "natural sort");
- a great python module and a cli to run natural sorting https://natsort.readthedocs.io/en/master/index.html

Thank you

**Comment by johnkerl** [comment]
@aborruso https://github.com/johnkerl/miller/pull/932

**Comment by aborruso** [comment]
@johnkerl you are a wonderful person and this project is a precious pearl

Thank you very much

**Comment by aborruso** [comment]
The next will be a great release
