### ISSUE TITLE
Not outputing csv headers

### ISSUE THREAD

**Issue by gregfr** [johnkerl/miller#88]
When outputing csv, is it possible not to ouput headers?

thanks in advance

**Comment by johnkerl** [comment]
ah -- yes; obvious counterpart to headerless input. i should have already thought of this. ;)

this will be easy to implement.

**Comment by gregfr** [comment]
great! my goal with this feature is to be able to use mlr to fetch a single value and get it back into a shell variable, like this:
data=`cat data.csv | mlr <using regex>`

**Comment by johnkerl** [comment]
cool. as a side note:
```
$ echo 'x=1,y=2' | mlr --ofs newline cat
x=1
y=2

$ eval $(echo 'x=1,y=2' | mlr --ofs newline cat)

$ echo $x
1

$ echo $y
2
```

maybe not quite what you want here, but a useful technique nonetheless for exporting data to the shell.

**Comment by gregfr** [comment]
Yes I found the "eval" trick, very useful to fetch several variables, but I used ofs=';'. Worth mentioning in the docs.
It's amazing what mlr can do!

**Comment by johnkerl** [comment]
Thanks!

**Comment by gregfr** [comment]
wow that's customer service! :bowtie:
