### ISSUE TITLE
mlr executing iterated script?

### ISSUE THREAD

**Issue by gregfr** [johnkerl/miller#89]
I was wondering if I can use mlr as a "master loop" to run a script for each line of an input file?

it probably can be done with writing to a socket, but I'm looking for a simpler way...

**Comment by gregfr** [comment]
I did it with:

    xargs -L1

seems to be working.

**Comment by johnkerl** [comment]
excellent!

**Comment by gregfr** [comment]
yeah :+1: I love it :-D
