### ISSUE TITLE
Catalog/uniformize some format strings between C & Go versions

### ISSUE THREAD

**Issue by johnkerl** [johnkerl/miller#890]
In the C implementation (Miller 5 and below) `fmtnum` and `strptime` used the C library -- the same thing you see with `man 3 printf` etc. In the Go implementation (Miller 6 and above) they use Go libraries -- `fmtnum` using whatever Go's `fmt.Sprintf` supports, and `strptime` using https://github.com/johnkerl/miller/tree/main/internal/pkg/pbnjay-strptime which is a fork of the original (which I've modified a little and can modify more).

In both C and Go I happily/glibly thought _Hey cool there's this library I can use and gosh they thought of ever so many things!_ -- and I never made a catalog of all possible syntaxes. It all seemed like more choices than I would ever want or need. Which isn't entirely wrong, but, as you're both seeing, there's a regression when the catalog-of-all-supported-options changes from C to Go, _and_ when one of the things in the old catalog (`%i` or `%T`) doesn't exist in the new one. :(

(Aside: `%!i(string=3)` is simply what the Go `fmt.Sprintf` does with format-strings it can't handle.)

What we can do here:

* For `%i`, since `man 3 printf` says `%i` is the same as `%d`, have Miller do a search-and-replace before calling `fmt.Sprintf`.
* For `%T`, I've forked `pbnjay/strptime` already & could probably tweak it to get `%T` working
* Bigger picture: we should have a catalog of all supported formats for both functions -- even if it's just a hyperlink to Go docs somewhere.

_Originally posted by @johnkerl in https://github.com/johnkerl/miller/discussions/882#discussioncomment-2007112_

**Comment by Poshi** [comment]
Maybe this is just a documentation issue: the help for `fmtnum` says: `Convert int/float/bool to string using printf-style format string`.
Traditionally, printf-style refers to the `printf` in the C library. Even the shell command of the same name.
If you are relying in Go formatting abilities, explicitly state that and add a link to the Go documentation with the formats. Current documentation is ambiguous and leads naturally to the wrong (C) library.

**Comment by derekmahar** [comment]
Note these [examples](https://github.com/johnkerl/miller/discussions/882#discussioncomment-2008868) of how [Miller 6 `strptime`](https://johnkerl.org/miller-docs-by-release/6.0.0/reference-dsl-builtin-functions/index.html#strptime) parses formats `%Z`, `%z`, and `%f` that [pbnjay `strptime`](https://github.com/pbnjay/strptime) implements and describes.

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/discussions/882 now tracks all these issues -- closing this issue as a duplicate.
