### ISSUE TITLE
Regression tests fail on all platforms apart from amd64 and riscv64

### ISSUE THREAD

**Issue by skitt** [johnkerl/miller#896]
See https://buildd.debian.org/status/package.php?p=miller&suite=experimental — I’ll upload a new build soon which adds `-S` to get details.

**Comment by skitt** [comment]
On ARM64, floating-point operations give slightly different results:

```
./test/cases/verb-stats1/0003/cmd: stdout does not match expected test/cases/verb-stats1/0003/expout
--- /tmp/mlr-temp1496765362	2022-01-26 13:39:04.274407774 +0000
+++ /tmp/mlr-temp3815279547	2022-01-26 13:39:04.274407774 +0000
@@ -2,8 +2,8 @@
 i_meaneb 0.9574271077563381
 i_stddev 3.0276503540974917
 x_mean   0.45362938403357633
-x_meaneb 0.06815674979352654
-x_stddev 0.21553056726175476
+x_meaneb 0.06815674979352651
+x_stddev 0.2155305672617547
 y_mean   0.5944542421994383
 y_meaneb 0.09696764352210957
-y_stddev 0.3066386128691382
+y_stddev 0.3066386128691381
```

**Comment by johnkerl** [comment]
@skitt thank you!!!

For ARM64 -- I can modify the test data a bit to not be so sensitive.

For 32-bit platforms -- TBH this is a wake-up call for me. I've taken sort of a cavalier '32-bit systems are yesterday' approach and this is not good. For the moment I can comment out the offending cases but doing overflow correctly will take a bit of a refactor. (Context: Go has `int32` and `int64` which are what they say regardless of processor architecture; also `int` which is 32 bits on 32-bit systems and 64 bits on 64-bit systems. My specific cavalierness has been to use `int` a bit overmuch within Miller -- that needs to change.)

**Comment by skitt** [comment]
Yes, see https://github.com/johnkerl/miller/pull/902 for 32-bit systems ;-).

**Comment by johnkerl** [comment]
@skitt that was fast!!!!! :D

**Comment by skitt** [comment]
> @skitt that was fast!!!!! :D

I’d figured out that `Mlrval` was at the centre of it all a few days ago, so when I saw the 32-bit failures I knew what to change — and once I did that, build and test errors told me what else needed to be fixed! So I’m not sure I’ve caught everything, but at least `mlr` still builds, the tests still pass, and the number of regression test failures has dropped significantly on 386 (there are 3 left, not related to overflow as far as I can tell).

**Comment by johnkerl** [comment]
@skitt indeed! So, you are still amazing, I don't take that back -- but indeed the Go compiler's very strict type-checking does indeed make this kind of thing quicker to do confidently and correctly. :D

**Comment by johnkerl** [comment]
@skitt I'm seeing things like

```
./test/cases/verb-stats2/0010/cmd: stdout does not match expected test/cases/verb-stats2/0010/expout
--- /tmp/mlr-temp3804231892	2022-03-16 15:32:10.840703080 +0000
+++ /tmp/mlr-temp3582423180	2022-03-16 15:32:10.840703080 +0000
@@ -1,8 +1,8 @@
 a       pan
-x_y_cov 0.01759507626713419
+x_y_cov 0.01759507626713434
 
 a       eks
-x_y_cov 0.03464062871146781
+x_y_cov 0.034640628711467815
```

so Go's formatted output is not as platform independent as I'd hoped.

I'll add some use of `--ofmt` to help.

**Comment by johnkerl** [comment]
@skitt I have https://github.com/johnkerl/miller/pull/988 which I can commit to HEAD but I don't know how you'd like to deal with this with respect to 6.1.0 -- I can make a 6.1.1 maybe?

**Comment by skitt** [comment]
> @skitt I have #988 which I can commit to HEAD but I don't know how you'd like to deal with this with respect to 6.1.0 -- I can make a 6.1.1 maybe?

I’ll just add the patch to the Debian package for now, to see if the tests pass everywhere! No need for a release yet...

**Comment by skitt** [comment]
Right, that does seem like a change worth making available to users ;-).

The tests now pass everywhere: https://buildd.debian.org/status/package.php?p=miller&suite=experimental — I’ve uploaded 6.1.0 with the `OFMT` fix to Debian proper, with the same results https://buildd.debian.org/status/package.php?p=miller. So I’ll close this, thanks for fixing it!

**Comment by johnkerl** [comment]
thanks @skitt !! :D
