### ISSUE TITLE
examples in regularizing ragged csv section need small change

### ISSUE THREAD

**Issue by jganong** [johnkerl/miller#897]
in the documention section about Regularizing Ragged CSV
the code examples have  "--fs comma" before "--nidx",
but this does not work, apparently --nidx resets the FS and all the lines have NF == 1.
instead if you put "--nidx"  followed by "--fs comma" it appears to work fine.

i am using mlr 6.0.0 on arch linux

(base) [jeg@lanternfish tom]$ echo 'eprint IFS' | mlr repl --fs x  --nidx

(base) [jeg@lanternfish tom]$ echo 'eprint IFS' | mlr repl  --nidx --fs x
x

thanks

**Comment by johnkerl** [comment]
Thank you @jganong !!

In case the documentation was fine; you surfaced a bug which is fixed on https://github.com/johnkerl/miller/pull/912
