### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [johnkerl/miller#9]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/johnkerl/miller/blob/a1d117d3b299bbf27309f157b0a8c90fea7ac066/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
* [CMake](http://cmake.org/ "CMake build system")
* [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction "GNU build system")

**Comment by johnkerl** [comment]
This is a really great idea. The current is definitely simple and quick for a dev box; since the release announcement with more people building on more platforms, it'll quickly become essential. For configuring install dir, if nothing else.

**Comment by johnkerl** [comment]
If you've used cmake or autotools before (I have not) and have any sage advice, bring it on! :)

**Comment by elfring** [comment]
* Does [a tool like "autoscan"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
* How do you think about to support more development environments by [the reuse of build system generators](http://www.cmake.org/cmake/help/v3.3/manual/cmake-generators.7.html#cmake-generators "Selection for build tool generators")?

**Comment by johnkerl** [comment]
Marking as wishlist for now, just relative to other things more pressing -- namely, RFC-CSV and packaging. In the medium term, though, this will be a should-do rather than a wishlist item.

**Comment by 0-wiz-0** [comment]
I've started an autoconf/automake based build structure in https://github.com/0-wiz-0/miller
mlr itself builds; I haven't tested it.
There is still lots of stuff to do:
tests
doc/
custom targets
distribution

To try it out:
install autoconf, automake, libtool
checkout my fork https://github.com/0-wiz-0/miller
autoreconf -fiv
./configure
make

**Comment by elfring** [comment]
>checkout my fork

* I suggest to add [the call of the macro "AC_CONFIG_AUX_DIR"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Input.html#index-AC_005fCONFIG_005fAUX_005fDIR-58 "Storage for auxiliary build tools") to [your configuration script](https://github.com/0-wiz-0/miller/blob/f498a75b09b6f9aa578fb09d938a29de4cff5b87/configure.ac#L1 "Autotools support") so that auxiliary build tools will be stored in a dedicated directory.
* Do further parameters make sense for [the call of the macro "AM_INIT_AUTOMAKE"](https://www.gnu.org/software/automake/manual/html_node/Public-Macros.html "Description for AM_INIT_AUTOMAKE")?

**Comment by 0-wiz-0** [comment]
elfring, thanks for the suggestions. I did add an AC_CONFIG_AUX_DIR call.
I also read all automake options but didn't find any I would add to the AM_INIT_AUTOMAKE call.
Let me know if I overlooked anything.

**Comment by elfring** [comment]
>Let me know if I overlooked anything.

* How do you think about the reuse of [parameters like "--foreign" and "-Wall"]( "Automake options")?
* Would you like to drop [the call of the obsolescent macro "AM_PROG_CC_C_O"](https://github.com/0-wiz-0/miller/blob/36080d7a9d557efc248b986bcbbf88399e23661a/configure.ac#L13 "Autoconf script")?

**Comment by 0-wiz-0** [comment]
foreign is in the top level Makefile.am; there's no point in adding it to AM_INIT_AUTOMAKE, since it doesn't do anything in the other Makefiles.
Wall is only interesting for people developing the Makefile.ams. You can add it from the command line. Again, there is no point in other Makefiles than the top-level one.
I've removed the AM_PROG_CC_C_O, thanks for pointing out it's on the way out!

**Comment by elfring** [comment]
>…; there's no point in adding it to …

I guess that there is a trade-off involved. How many settings should be moved from [the file "Makefile.am"](https://github.com/0-wiz-0/miller/blob/f498a75b09b6f9aa578fb09d938a29de4cff5b87/Makefile.am#L1 "Automake settings") to [the primary script "configure.ac"](https://github.com/0-wiz-0/miller/blob/811e6c8a64d39675e85b866edc3e19cb74a9d826/configure.ac#L1 "Build specification")?

**Comment by johnkerl** [comment]
Nice!

**Comment by johnkerl** [comment]
This is cool. There's no push request yet but this is something to work with. I'm currently doing what I consider higher-pri work on file formats & read performance. But, this is important. Some of the feedback I've found off Github (by searching for it) is that my failure to provide a standard `./configure && make` experience out of the box was off-putting for some.

**Comment by johnkerl** [comment]
... by which I mean, if someone else finishes the last bits, great, else I will. So we'll get there either way.

**Comment by 0-wiz-0** [comment]
I've worked on it some more.
All the unit tests are now run with 'make check'.
'make distcheck' succeeds, i.e. 'make dist' generates tarballs that can be extracted, configured, built, and finish 'make check' successfully.
The man page is now installed (but only generated on the system generating the tarball, so not everyone needs to have asciidoc installed).

Can you please take a closer look and recommend which files should be distributed that currently aren't?
In particular, in doc (but consider that not everyone should have to install poki).
but also for data (but see https://github.com/johnkerl/miller/issues/61).

I know that there is one more test, test/run, that should be added.

One issue I found is that the lemon executable needs its input files in ".". Perhaps it can be extended to support being called with an input file in ${srcdir} while being in ${objdir}, i.e. being called with "lemon ../../c/dsls/inputfile"?

**Comment by 0-wiz-0** [comment]
I've worked on test/run a bit. I have the problem that this script has paths in the expected output. Can you please modify it so it doesn't, e.g. by calling basename on executable and input(s) (just for the debugging outptu)?
Otherwise out-of-src-tree builds will never run tests successfully, and 'make distcheck' uses these for testing.
Except for that it seems easy to add this script as well, I've done it locally but not pushed yet (because of -- see above).

**Comment by johnkerl** [comment]
Out-of-dir builds, very good idea in any case.

OK I think I'll fork your fork ... get it where I want it to be ... then make you a pull request. Then you can make me a pull request to master -- sound OK?

**Comment by elfring** [comment]
>I think I'll fork your fork …

Are you aware of [better Git development techniques](https://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows "Distributed workflows with Git?")?

**Comment by johnkerl** [comment]
Apparently not :^/.  I'll take a read.

**Comment by elfring** [comment]
@0-wiz-0, @johnkerl: How do you think about to improve the software development collaboration by [the reuse of topic branches](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging "Basic branching and merging")?

**Comment by johnkerl** [comment]
sure, forks and branches are morally the same, either will work. whatever's easiest. 99% of the time i prefer unbranched iteration in master, but here either forks or branches will be called for since the changes could temporarily  break master.

**Comment by elfring** [comment]
I find that [a topic branch](http://stackoverflow.com/questions/284514/what-is-a-git-topic-branch "What is a git topic branch?") should usually get an other name than "master".
To which branch would you like to contribute the next updates here?

**Comment by jungle-boogie** [comment]
Hi @johnkerl, yes, develop on trunk/master!

http://www.tedunangst.com/flak/post/branchless-development

**Comment by johnkerl** [comment]
All -- thanks for the software-engineering discussion. Over my career, on the whole I've become a strong advocate for developing in master almost all the time, with frequent merges. This is good for small projects; it's a make-or-break for large projects/companies. That said, every once in a while a short-lived branch is useful -- and the implementation details don't matter too much -- which is the case here since autoconfigure testing will break master, and/or just confuse people, until it's complete.

**Comment by johnkerl** [comment]
Pushed out-of-directory `test/run` to https://github.com/0-wiz-0/miller. Ran as:
* `./test/run`
* `cd ../; ./c/test/run`
* `cd; ~/tmp/wiz/miller/c/test/run`

**Comment by 0-wiz-0** [comment]
Thanks!
But isn't that only half the solution? When I run this from "c/build" with "../test/run", I have the following diff in my source tree afterwards:

````
-mlr having-fields --at-least a,b,i,x,y /Users/kerl/tmp/wiz/miller/c/test/input/abixy
+mlr having-fields --at-least a,b,i,x,y ../test/input/abixy
````
In other words, the path to the input files also needs sanitizing, I think.

**Comment by johnkerl** [comment]
That case was included in the diff, using "diff -I '^mlr '" in test/run. It
works for me from all sorts of directories, on OSX. I'll investigate more,
late this evening.

On Thu, Sep 10, 2015 at 9:33 AM, Thomas Klausner <notifications@github.com>
wrote:

> Thanks!
> But isn't that only half the solution? When I run this from "c/build" with
> "../test/run", I have the following diff in my source tree afterwards:
>
> -mlr having-fields --at-least a,b,i,x,y /Users/kerl/tmp/wiz/miller/c/test/input/abixy
> +mlr having-fields --at-least a,b,i,x,y ../test/input/abixy
>
> In other words, the path to the input files also needs sanitizing, I think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/johnkerl/miller/issues/9#issuecomment-139235750>.
>



-- 
John Kerl
kerl.john.r@gmail.com
http://johnkerl.org
https://github.com/johnkerl <http://johnkerl.github.com>

**Comment by 0-wiz-0** [comment]
Ah, I had overlooked that. Thanks.
I have two issues:
1. When run in-tree, it overwrites c/test/output/out

2. When run out-of-tree during 'make distcheck' the source tree is read-only, which makes 'run' fail with:
````
mkdir: ../../../../c/test/output: Permission denied
````

**Comment by johnkerl** [comment]
ok. `test/output/out` should not be checked into source control; it should
be created by `test/run`. this was my oversight. i'll take a look at `make
distcheck`.

thank you!!!! :)

On Thu, Sep 10, 2015 at 10:17 AM, Thomas Klausner <notifications@github.com>
wrote:

> Ah, I had overlooked that. Thanks.
> I have two issues:
> 1. When run in-tree, it overwrites c/test/output/out
>
>    1. When run out-of-tree during 'make distcheck' the source tree is
>    read-only, which makes 'run' fail with:
>
> mkdir: ../../../../c/test/output: Permission denied
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/johnkerl/miller/issues/9#issuecomment-139248318>.
>



-- 
John Kerl
kerl.john.r@gmail.com
http://johnkerl.org
https://github.com/johnkerl <http://johnkerl.github.com>

**Comment by johnkerl** [comment]
Wiz, thanks very much for your ongoing expert help!! I'm new to autoconf, so just to be sure I know the steps:

* `autoreconf -fiv`
* Then the resulting `./configure` gets checked into source control so not all end-users need to have autoconf, automake, and libtool installed
* `./configure` run by end-user
* Interesting dev targets are `make`, `make check`, and `make distcheck` -- ?
* Interesting end-user targets are `make` and `make install` -- ?
* Are there important other make targets and if so where in the workflow do they belong?

**Comment by johnkerl** [comment]
I'll be reading through automake.pdf on today's flight as well.

**Comment by johnkerl** [comment]
Another test case for myself is VPATH build with read-only source tree

**Comment by 0-wiz-0** [comment]
The steps are good, and you mentioned all the main targets.
There is a tags target as well, I think.
You can give debugging etc. flags on the configure command line like this:
````
./configure CFLAGS="-g -O0"
````

The configure script itself is usually not checked in. If you did, you would have to check in many more files as well (all Makefile.in and the support scripts like libtool, config.guess...).
autoconf is more aimed at a distfile workflow: someone with autotools creates a distfile (make distcheck) which contains all the necessary files. The user of a distfile does not need autotools or libtool installed.
Hope this helps. Feel free to ask more!

**Comment by 0-wiz-0** [comment]
Oh, and you probably are interested in the "--disable-shared" configure argument -- that should give you a static executable without dependencies, that you can easily copy to other machines.

**Comment by johnkerl** [comment]
ALso the `pdm` and `fdm` executables in `c/dsls` -- I should turn these into unit-test code, or abandon them.

**Comment by johnkerl** [comment]
The merge is in. To do:
* Have the Travis build go through autoconfig
* User-level docs
* Clearly delineate in the docs what needs to be done at package-build time vs. at package-install time
* Try to reduce the number of dependencies for package install: manpage/mlrdoc/etc. should be artifacts at that point in time with no need for xmllint, poki, etc.

Thank you @0-wiz-0 !!!! :D

**Comment by johnkerl** [comment]
This is complete with docs at http://johnkerl.org/miller/doc/build.html.

If there are any subsequent build errors, feel free to open a new issue as always. And thanks again @0-wiz-0. :)
