### ISSUE TITLE
test_byte_readers fails on a number of platforms in version 3.0.1

### ISSUE THREAD

**Issue by skitt** [johnkerl/miller#90]
This test used to work, but now fails; see https://buildd.debian.org/status/package.php?p=miller for logs. I'll check where exactly it's failing.

**Comment by johnkerl** [comment]
OK, continuing conversation from https://github.com/johnkerl/miller/issues/87 ... since you don't mind running ad-hoc code to test, that will probably be fastest. As soon as we get a good cross-platform build I'll tag a new release. Thank you!!

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/commit/353a903646799f2eef373b401cbb604a4b86e9fb was indeed over-eager. https://github.com/johnkerl/miller/commit/2db68cc29915e46b7b50c648191c440c3a67c9c7 keeps the change only where it's needed.

**Comment by skitt** [comment]
https://github.com/johnkerl/miller/commit/2db68cc29915e46b7b50c648191c440c3a67c9c7 seems to fix this, at least it works on arm64. There's another failure later on, here's the full log:
[miller.txt](https://github.com/johnkerl/miller/files/46413/miller.txt)

**Comment by johnkerl** [comment]
Linear regression on data against itself should give slope 1 & intercept 0 ... but due to different floating-point implementations the latter could be +0.0 or -0.0. It was silly of me to have ever depended on that. Diff coming up. :)

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/commit/0c14e77538b8192704a0b4ad35bbbd6e9291a713

**Comment by johnkerl** [comment]
@skitt thanks for your help ... please let me know if there's anything else I can do here.

**Comment by skitt** [comment]
Hi John, sorry for the silence there, I was rather busy this week. I've just checked current git master on an arm64 box and all the tests pass, so it should be good to go! Thanks for fixing everything.

**Comment by johnkerl** [comment]
Thank you!!! :)

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/releases/tag/v3.1.0
