### ISSUE TITLE
Documentation of operators

### ISSUE THREAD

**Issue by Poshi** [johnkerl/miller#907]
In help page `reference-dsl-builtin-functions`, there are a few imprecisions regarding the operators.

`./  (class=arithmetic #args=2) Integer division; not pythonic.`: it is not clear for someone who doesn't know Python how this division works. Maybe rounding towards positive? Towards zero? Better to say what it does rather than what it does not.

`/  (class=arithmetic #args=2) Division. Integer / integer is floating-point.`: wrong, int/int is not floating point, but the simpler type that can hold the result. `4/3` is floating point. `4/2` is integer.

`???  (class=boolean #args=2) Absent-coalesce operator. $a ?? 1 evaluates to 1 if $a isn't defined in the current record, or has empty value.`: the example uses only two interrogation signs, should be three.

**Comment by johnkerl** [comment]
Thanks @Poshi !! :)

**Comment by johnkerl** [comment]
@all-contributors please add @Poshi for documentation

**Comment by Poshi** [comment]
:-) Thanks!
