### ISSUE TITLE
reg_test fails on i386

### ISSUE THREAD

**Issue by skitt** [johnkerl/miller#91]
I didn't think to rebuild on i386 yesterday; it turns out reg_test fails there (and only there). Here's the log: [test-suite.txt](https://github.com/johnkerl/miller/files/53170/test-suite.txt)

**Comment by johnkerl** [comment]
awesome, thanks. good news is my i386 buildbox is back -- i'd thought it dead but it turned out the battery contacts just needed cleaning. :)

**Comment by johnkerl** [comment]
p.s. i can repro this on my i386 box.

**Comment by johnkerl** [comment]
ok this passes on my i386 buildbox, as well as osx & x86-64:
https://github.com/johnkerl/miller/releases/tag/v3.1.1

**Comment by skitt** [comment]
Fantastic, thank you very much, this is looking pretty good now (https://buildd.debian.org/status/package.php?p=miller shows amd64, arm64, i386, powerpc, ppc64el, s390x, alpha and x32 OK now, the other architectures are still waiting for a build machine).

**Comment by johnkerl** [comment]
Thank you! :)

**Comment by johnkerl** [comment]
@skitt I have a rather embarrassing bugfix release: https://github.com/johnkerl/miller/releases/tag/v3.1.2 .  What would be the best way to get this to you?

**Comment by skitt** [comment]
You just did ;-). (The updated package is on its way to the Debian archive.) Generally speaking, when you tag a release I get notified that the Debian package is out-of-date within a few days. If you have a really urgent update (e.g. for a security issue or a data-eating bug), ping miller@packages.debian.org which will automatically be forwarded to the package maintainer, whoever that happens to be.

**Comment by johnkerl** [comment]
Thank you!
