### ISSUE TITLE
Miller 6: problem using strptime

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#914]
Hi,
running Miller 5

```
echo 'a=363 2021' | mlr --ojson put '$d=strftime(strptime($a, "%j %Y"),"%Y-%m-%d")'
```

I have `{ "a": "363 2021", "d": "2021-12-29" }`

If I use Miller 6, I have wrong output date: `{"a": "363 2021", "d": "2021-01-01"}`.

Is it normal? Am I doing some error?

Thank you

**Comment by johnkerl** [comment]
@aborruso `%j` isn't listed at https://github.com/pbnjay/strptime -- let's see though what can be done about this. (I've forked https://github.com/pbnjay/strptime for Miller mods & perhaps it will be easy enough to add another mod there.)

**Comment by johnkerl** [comment]
Also, separately from that, whatever format strings are accepted by Miller's `strptime` need to be better documented in Miller docs.

**Comment by johnkerl** [comment]
Also, the `pbnjay/strptime` library has an `ignoreUnsupported` flag internally which I have been passing as `true` and shoul not -- if you use a flag which isn't supported, you should be notified clearly.

**Comment by johnkerl** [comment]
@aborruso thanks to #930:

```
$ echo 'a=363 2021' | ./mlr --ojson put '$d=strftime(strptime($a, "%j %Y"),"%Y-%m-%d")'
[
{
  "a": "363 2021",
  "d": "2021-12-29"
}
]
```

The `strftime` and `strptime` DSL functions still need a write-up with a table of supported format strings.
