### ISSUE TITLE
How to reset blocks in REPL?

### ISSUE THREAD

**Issue by vapniks** [johnkerl/miller#918]
Is there any way to reset the begin, main & end blocks in the REPL so I don't have to restart every time I want to make a change?

**Comment by johnkerl** [comment]
@vapniks if I recall correctly I thought of the same thing but I was worried about over-engineering the REPL & thought I'd wait if anyone besides me wanted this :D 

This doesn't exist but it will be very quick to implement :)

**Comment by vapniks** [comment]
I think it would be a very worthwhile improvement.

**Comment by johnkerl** [comment]
@vapniks agreed! ::)

**Comment by vapniks** [comment]
Would be nice if you could also reset begin, main & end blocks independently, e.g. by passing an arg to :rb

**Comment by johnkerl** [comment]
@vapniks was thinking same, glad to hear demand for it :D

**Comment by johnkerl** [comment]
@vapniks https://github.com/johnkerl/miller/pull/924

**Comment by vapniks** [comment]
Excellent! but I noticed a type on line 832 of the commit, it should be "clears out end blocks" not "clears out begin blocks".

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/commit/41235c1e81385dd01dcc71f36d44e09ecc19a65e -- thanks @vapniks ! :D

**Comment by johnkerl** [comment]
@all-contributors please add @Poshi for ideas

**Comment by johnkerl** [comment]
@all-contributors please add @Poshi for documentation
