### ISSUE TITLE
Combining csv headers when cat from json

### ISSUE THREAD

**Issue by asakura42** [johnkerl/miller#919]
Some jsons have various elements in various arrays.
like

```json
{
"one": "true",
"two": "false"
},
{
"one": "false",
"three": "true"
}
```

But when I do `mlr --ijson --ocsv cat` it outputs:

```
one,two
true, false

one,three
false,true
```

How to combine headers to get smth like

```
one,two,three
true,false,
false,,true
```

**Comment by johnkerl** [comment]
@asakura42 check out https://miller.readthedocs.io/en/latest/reference-verbs/index.html#unsparsify

```
$ cat 123.json
[
{
"one": "true",
"two": "false"
},
{
"one": "false",
"three": "true"
}
]
```

```
$ mlr --j2c unsparsify 123.json
one,two,three
true,false,
false,,true
```

**Comment by johnkerl** [comment]
More generally, `mlr ..... then unsparsify` if you have something non-trivial in place of `cat`.

**Comment by asakura42** [comment]
Thank you.
