### ISSUE TITLE
'containers/free_flags.h' file not found

### ISSUE THREAD

**Issue by jungle-boogie** [johnkerl/miller#93]
Hello,

Brand new `git clone https://github.com/johnkerl/miller` results in the following errors when using
`make -f Makefile.no-autoconfig CC=clang` in the `miller/c` directory on x64 bit:

% make -f Makefile.no-autoconfig CC=clang
make -C dsls -f Makefile.no-autoconfig put_dsl_parse.o
clang -o lemon lemon.c
./lemon put_dsl_parse.y
mv put_dsl_parse.c put_dsl_parse.c.tmp
sed  -e 's/ParseTrace/put_dsl_ParseTrace/g'  -e 's/ParseTokenName/put_dsl_ParseTokenName/g'  -e 's/lemon_parser_alloc/put_dsl_lemon_parser_alloc/g'  -e
's/lemon_parser_free/put_dsl_lemon_parser_free/g'  -e 's/lemon_parser_parse_token/put_dsl_lemon_parser_parse_token/g'  -e 's/yy_destructor/put_dsl_yy_destructor/g'  put_dsl_parse.c.tmp > put_dsl_parse.c
rm -f put_dsl_parse.c.tmp
clang -I.. -O3 -c -std=gnu99 put_dsl_parse.c
make -C dsls -f Makefile.no-autoconfig put_dsl_lexer.o
flex --prefix=put_dsl_lexer_ --outfile=put_dsl_lexer.c --header-file=put_dsl_lexer.h put_dsl_lexer.l
clang -I.. -O3 -c -std=gnu99 put_dsl_lexer.c
make -C dsls -f Makefile.no-autoconfig put_dsl_wrapper.o
clang -Wall -I.. -O3 -c -std=gnu99 put_dsl_wrapper.c
make -C dsls -f Makefile.no-autoconfig filter_dsl_parse.o
./lemon filter_dsl_parse.y
mv filter_dsl_parse.c filter_dsl_parse.c.tmp
sed  -e 's/ParseTrace/filter_dsl_ParseTrace/g'  -e 's/ParseTokenName/filter_dsl_ParseTokenName/g'  -e 's/lemon_parser_alloc/filter_dsl_lemon_parser_alloc/g'  -e 's/lemon_parser_free/filter_dsl_lemon_parser_free/g'  -e 's/lemon_parser_parse_token/filter_dsl_lemon_parser_parse_token/g'  -e 's/yy_destructor/filter_dsl_yy_destructor/g'  filter_dsl_parse.c.tmp > filter_dsl_parse.c
rm -f filter_dsl_parse.c.tmp
clang -I.. -O3 -c -std=gnu99 filter_dsl_parse.c
make -C dsls -f Makefile.no-autoconfig filter_dsl_lexer.o
flex --prefix=filter_dsl_lexer_ --outfile=filter_dsl_lexer.c --header-file=filter_dsl_lexer.h filter_dsl_lexer.l
clang -I.. -O3 -c -std=gnu99 filter_dsl_lexer.c
make -C dsls -f Makefile.no-autoconfig filter_dsl_wrapper.o
clang -Wall -I.. -O3 -c -std=gnu99 filter_dsl_wrapper.c
clang -std=gnu99 -I. -I.. -Wall -Werror -O3 *.c  cli/*.c  lib/*.c  containers/*.c  stream/*.c  input/*.c  mapping/*.c  output/*.c ./dsls/put_dsl_parse.o  ./dsls/put_dsl_lexer.o  ./dsls/put_dsl_wrapper.o ./dsls/filter_dsl_parse.o  ./dsls/filter_dsl_lexer.o  ./dsls/filter_dsl_wrapper.o -lm -o mlr
In file included from mlrmain.c:5:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from cli/argparse.c:3:
In file included from ./cli/argparse.h:7:
./containers/slls.h:9:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from cli/mlrcli.c:7:
./containers/slls.h:9:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from lib/mlr_globals.c:2:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from lib/mlr_test_util.c:5:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from lib/mlrmath.c:6:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from lib/mlrutil.c:7:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from lib/string_builder.c:5:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from containers/header_keeper.c:3:
In file included from ./containers/header_keeper.h:9:
./containers/slls.h:9:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from containers/join_bucket_keeper.c:4:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from containers/lhmsi.c:22:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from containers/lhmslv.c:20:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from containers/lhmss.c:22:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from containers/lhmsv.c:23:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from containers/lrec.c:7:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from containers/mixutil.c:1:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from containers/mlrval.c:6:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from containers/rslls.c:4:
./containers/rslls.h:19:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from containers/slls.c:4:
./containers/slls.h:9:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from containers/top_keeper.c:4:
In file included from ./containers/top_keeper.h:8:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from stream/stream.c:6:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from input/file_reader_mmap.c:9:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from input/file_reader_stdio.c:9:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from input/lrec_reader_csv.c:4:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from input/lrec_reader_in_memory.c:5:
In file included from ./input/lrec_readers.h:4:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from input/lrec_reader_mmap_csv.c:4:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from input/lrec_reader_mmap_csvlite.c:3:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from input/lrec_reader_mmap_dkvp.c:3:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from input/lrec_reader_mmap_nidx.c:4:
In file included from ./input/lrec_readers.h:4:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from input/lrec_reader_mmap_xtab.c:5:
In file included from ./input/lrec_readers.h:4:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from input/lrec_reader_stdio_csvlite.c:3:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from input/lrec_reader_stdio_dkvp.c:3:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from input/lrec_reader_stdio_nidx.c:5:
In file included from ./input/lrec_readers.h:4:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from input/lrec_reader_stdio_xtab.c:6:
In file included from ./input/lrec_readers.h:4:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from input/lrec_readers.c:2:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from input/mmap_byte_reader.c:7:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from input/peek_file_reader.c:3:
In file included from ./input/peek_file_reader.h:7:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from input/stdio_byte_reader.c:4:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/lrec_evaluators.c:5:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_bar.c:3:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_cat.c:1:
In file included from ./cli/argparse.h:7:
./containers/slls.h:9:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_check.c:1:
In file included from ./mapping/mappers.h:4:
./containers/slls.h:9:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_cut.c:2:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_decimate.c:7:
In file included from ./containers/lhmslv.h:19:
./containers/slls.h:9:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_filter.c:2:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_grep.c:2:
In file included from ./cli/argparse.h:7:
./containers/slls.h:9:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_group_like.c:6:
./containers/slls.h:9:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_having_fields.c:2:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_head.c:7:
In file included from ./containers/lhmslv.h:19:
./containers/slls.h:9:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_histogram.c:6:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_join.c:1:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_label.c:2:
./containers/slls.h:9:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_put.c:1:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_regularize.c:2:
In file included from ./containers/lhmslv.h:19:
./containers/slls.h:9:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_rename.c:5:
In file included from ./mapping/mappers.h:4:
./containers/slls.h:9:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_reorder.c:2:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_sample.c:8:
./containers/slls.h:9:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_sec2gmt.c:2:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_sort.c:6:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_stats1.c:6:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_stats2.c:6:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_step.c:6:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_tac.c:4:
In file included from ./mapping/mappers.h:4:
./containers/slls.h:9:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_tail.c:7:
./containers/slls.h:9:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_top.c:7:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from mapping/mapper_uniq.c:7:
In file included from ./containers/lhmslv.h:19:
./containers/slls.h:9:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from output/lrec_writer_csv.c:4:
In file included from ./lib/mlr_globals.h:3:
In file included from ./cli/mlrcli.h:9:
In file included from ./input/lrec_reader.h:6:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from output/lrec_writer_csvlite.c:2:
In file included from ./containers/mixutil.h:7:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from output/lrec_writer_dkvp.c:3:
In file included from ./output/lrec_writers.h:3:
In file included from ./output/lrec_writer.h:5:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from output/lrec_writer_nidx.c:3:
In file included from ./output/lrec_writers.h:3:
In file included from ./output/lrec_writer.h:5:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from output/lrec_writer_pprint.c:5:
./containers/slls.h:9:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
In file included from output/lrec_writer_xtab.c:4:
In file included from ./output/lrec_writers.h:3:
In file included from ./output/lrec_writer.h:5:
./containers/lrec.h:46:10: fatal error: 'containers/free_flags.h' file not found
#include "containers/free_flags.h"
         ^
1 error generated.
*** Error code 1

Stop.
make: stopped in /usr/home/sean/bin/miller/c

**Comment by johnkerl** [comment]
Thank you; also flagged by travis.

https://github.com/johnkerl/miller/commit/fbba5d258fb0c1ddcbab3dc1fb9785555932fc97

**Comment by jungle-boogie** [comment]
:100:
