### ISSUE TITLE
[mlr 6] Regression: requires valid JSON input ;)

### ISSUE THREAD

**Issue by schragge** [johnkerl/miller#947]
This is not an error, but probably should be mentioned in documentation. The JSON parser in Miller 6 got stricter.  mlr5 would happily parse invalid JSON input with end-commas like this:
```json
{
"Name": "__NAME__",
"name": "XYZ-string",
"description": "whatever desc",
}
```
See [here](https://www.linuxquestions.org/questions/programming-9/%5Bbash%5D%5Bsed%5D-replace-string-after-fixed-string-character-4175674064).

**Comment by johnkerl** [comment]
@schragge oh no! I had forgotten that Miller 5 even allowed this non-standardness. Thanks for letting me know!!!

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/commit/fbfac891d668a6a9c33135de49d1deb8c7e36353

**Comment by johnkerl** [comment]
@all-contributors please add @schragge  for documentation
