### ISSUE TITLE
commit breaks freeBSD build

### ISSUE THREAD

**Issue by jungle-boogie** [johnkerl/miller#95]
Hello,

Unfortunately, it looks like there's a commit that breaks the build on freebsd.
I don't know how your build system didn't warn you about the failure.

Commit in question:
06234f88663bc3de40be6cc77aa560df6adcf018

The commit just before this builds successfully:
6c5be3a6a0b5b6fcc4b2111fcf266a1230e1f0ed

**Comment by jungle-boogie** [comment]
And yes, I've tried your repo from head and it fails to build.

**Comment by johnkerl** [comment]
Can you please output which shows what's broken? Compile failure? Test failure? Etc. Please include a full paste.

**Comment by johnkerl** [comment]
P.S. re build system, I don't know either:
https://travis-ci.org/johnkerl/miller/builds

**Comment by johnkerl** [comment]
Can you try to pull from head again?

My normal workflow is to use no-autoconfig build locally, and rely on Travis for both autoconfig and no-autoconfig builds. The most recent commit, https://github.com/johnkerl/miller/commit/75f1ad3c716157cd5348ddb2c3b57eac6989e8ab, fixes an error on local autoconfig builds. But it has nothing to do with the commit you highlighted above (https://github.com/johnkerl/miller/commit/06234f88663bc3de40be6cc77aa560df6adcf018).

**Comment by jungle-boogie** [comment]
Hello,

Full build log here: https://clbin.com/Dxabe

**Comment by johnkerl** [comment]
I cannot reproduce this, but, https://github.com/johnkerl/miller/commit/457e62406acfe10df4f53c41a80942b233b36736 (latest head) has some defensive coding which should either resolve or illuminate the problem.

**Comment by johnkerl** [comment]
I checked & Travis has no BSD support and won't anytime soon.

**Comment by jungle-boogie** [comment]
Hi @johnkerl,

Your latest commit fixed the problem!

As a plus, this also corrected a (unreported) build problem on openBSD as well!

Thanks for your rapid correction to this problem.

**Comment by johnkerl** [comment]
Sweet. Thanks for the heads-up.
