### ISSUE TITLE
What happened to `merge-fields`?

### ISSUE THREAD

**Issue by oschrenk** [johnkerl/miller#97]
It is listed in the reference under [merge-fields](http://johnkerl.org/miller/doc/reference.html#merge-fields) 
but is not included in the application:

```
brew info miller | head -1
miller: stable 3.2.2 (bottled), HEAD

mlr --version
Miller 3.2.2

mlr --list-all-verbs
 bar cat check count-distinct cut decimate filter grep group-by group-like
 having-fields head histogram join label put regularize rename reorder sample
 sec2gmt sort stats1 stats2 step tac tail top uniq
```

**Comment by johnkerl** [comment]
it's new since the last release (3.2.2). it'll appear when i make a 3.3.2. which i can do sooner than later if it's useful to you.

**Comment by johnkerl** [comment]
BTW, head docs at http://johnkerl.org/miller/doc/index.html match head code at https://github.com/johnkerl/miller. Release-specific docs at http://johnkerl.org/miller/doc/release-docs.html match release-specific code at https://github.com/johnkerl/miller/tags.

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/releases/tag/v3.3.2

**Comment by johnkerl** [comment]
I'll do the pull request tomorrow evening.

**Comment by oschrenk** [comment]
I was actually just proposing the tool to somebody else's problem, found merge-fields in the docs, wasn't aware of existence of release docs and was wondering why it didn't work.

Thanks for cutting new release!

**Comment by johnkerl** [comment]
https://github.com/Homebrew/homebrew/pull/47996

**Comment by johnkerl** [comment]
https://github.com/Homebrew/homebrew/pull/47996 is closed.
