### ISSUE TITLE
Streamable JSON parsing

### ISSUE THREAD

**Issue by johnkerl** [johnkerl/miller#99]
The JSON parser does not return until all input is parsed: in particular this means that, unlike for other file formats, Miller does not (at present) handle JSON files in `tail -f` contexts.

A possible solution is to clone the parser (which currently operates on pointers) to take a `FILE *` and `fgetc` until end of item, then return that.

Note that for tabular JSON data wrapped in outer list -- e.g.

```
[
  {"a":1,"b":2},
  {"a":3,"b":4}
]
```

there is no helping; nothing can be done until the final right-brace is read. But for tabular JSON data of the form

```
  {"a":1,"b":2},
  {"a":3,"b":4} 
```

it should be possible to return after each right brace is read.

**Comment by mrhmouse** [comment]
Would it be feasible to replace [udp/json-parser](https://github.com/udp/json-parser) with a SAX-like solution? Something like [yajl](http://lloyd.github.io/yajl/), maybe?

This would mean that tabular JSON data wrapped in an outer list (like your example) could be processed in a streaming manner. It's a much larger change than your suggested solution, though.

**Comment by johnkerl** [comment]
Wow, this is cool!!! Will definitely check it out.

**Comment by johnkerl** [comment]
This is already working in the Go port (https://github.com/johnkerl/miller/issues/372)

**Comment by johnkerl** [comment]
Fixed in Miller 6.
