### ISSUE TITLE
A strange repeated heading output

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#995]
Hi,
I have a bad CSV. I worked on to make it usable.
Doing it I have discovered a strange behavior.

It has this heading "idImpianto;Gestore;Bandiera;Tipo Impianto;Nome Impianto;Indirizzo;Comune;Provincia;Latitudine;Longitudine" line.

If I run

```
curl -kL "https://www.mise.gov.it/images/exportCSV/anagrafica_impianti_attivi.csv" | tail -n +2 | mlr --ragged --csvlite --fs ";" clean-whitespace | grep -i 'idimp' | wc -l
```

I have 67 time the heading and it has no sense.
It probably depends on the many errors it has inside, but I point it out because there could also be a bug.

Using mlr 5 I have the heading only one time.

Thank you

**Comment by johnkerl** [comment]
@aborruso looks like https://github.com/johnkerl/miller/issues/275 -- ? If I add `then unsparsify` to your command then I only get one `idImpianto;...` line ...

**Comment by aborruso** [comment]
O yes, you are right, sorry for the stupid issue.

Thank you
