### ISSUE TITLE
DSL error message for failure in bool expression lacks line and column numbers

### ISSUE THREAD

**Issue by pjfarleyiii** [johnkerl/miller#996]
When a conditional expression is mis-coded or fails for some reason, you get the following error:

```
C:\Users\MyUser\testdir>mlr --csv put -f mlrbug-bool.mlr mlrtest.csv
mlr: conditional expression did not evaluate to boolean.
```

Note that there is no way to tell at which line or column the failed expression happened.  You have to guess that it was something you recently entered into the script.

Test file mlrtest.csv:

[mlrtest.csv](https://github.com/johnkerl/miller/files/8311861/mlrtest.csv)

Test DSL script mlrbug-bool.mlr as a .txt file since drag-n-drop won't accept .mlr files:

[mlrbug-bool.txt](https://github.com/johnkerl/miller/files/8311863/mlrbug-bool.txt)

Note in the test script that the "while" condition uses undefined variable names which causes the failure.

Peter

**Comment by johnkerl** [comment]
Thanks @pjfarleyiii ! For parse errors we get line/column from the GOCC parser. For runtime errors (no parse fail) -- I need to find a way to attach each successfully parsed DSL statement to line-number info from GOCC.

**Comment by johnkerl** [comment]
@pjfarleyiii this will work! :)

https://github.com/johnkerl/miller/blob/main/internal/pkg/parsing/token/token.go#L25-L30

```
$ cat foo.mlr
$color_shape = $color.shape;

if (NR == 5) {
  if (0) {
    $color = "aqua";
  }
}
```

```
$ mlr --csv --from docs/src/example.csv put -f foo.mlr
mlr: conditional expression did not evaluate to boolean at DSL expression line 4 column 7.
```

This isn't checked in but it will be.

This pattern which I applied to the if-condition spot, needs to be applied to while-condition, etc.

**Comment by pjfarleyiii** [comment]
Thanks for the quick action.  I will proceed with my little project as I did get past this particular error, and await your eventual integration of this helpful feature into a release..
